### ISSUE TITLE
Use this repo for weekly notes etc?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#1]
Hey @willingc - I saw that we'd had an action item come out of  https://github.com/jupyterhub/jupyterhub/issues/1543#issuecomment-347593392 to create a repository where we can have various team interactions etc. I created this so we can get a start on that, what do you think? FWIW, I think something like this is useful as I just lost 15 minutes trying to find the link to the weekly sync doc :-)

**Comment by willingc** [comment]
I'm fine with the repo. I would like to rename it to team-compass to better convey that this is to guide the project vs. merely improving the team.

**Comment by choldgraf** [comment]
That's a good point. Feel free to rename (or make any other modifications) or I will when I get back to my computer

**Comment by willingc** [comment]
Thanks @choldgraf 👍
