### ISSUE TITLE
Sending email from the binder team email address

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#102]
Is it possible for us to reply from the binder team email address?

In this case someone emailed the binder team and I think we should reply to them from the team address.

**Comment by choldgraf** [comment]
The address is for use with google groups, so I'm not sure whether or not that can send outgoing mail, or is only used for incoming mail :-/

**Comment by jzf2101** [comment]
I don't have access to this email fwiw

**Comment by choldgraf** [comment]
how about "getting emails from the binder-team googlegroup address" is one of the responsibilities of red team members? (re: #42 )

**Comment by betatim** [comment]
> how about "getting emails from the binder-team googlegroup address" is one of the responsibilities of red team members?

I think we should make it a priv ("receiving team account email") and a responsibility ("acting on team emails").

To add a new person to the team visit https://groups.google.com/forum/#!managemembers/binder-team/invite and send them an invite.
