### ISSUE TITLE
Trademark request from 9 January 2019

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#103]
We received a request to state if we think we comply with a companies trademark policy or not.

I am unsure if we can post the email and company name here or not so not posting it at the moment. It would make discussing it much easier though. If you have not received a copy of this email/can't access the binder team email inbox this is a reason that we give you access (in a new thread).

---

I would propose we reply to the request stating that we received it and that they can expect a follow up in 2 business days.

I think we should then forward this to the lawyer that Jupyter has access to via Numfocus and ask for advice.

**Comment by jzf2101** [comment]
I haven't gotten this email

**Comment by betatim** [comment]
After talking about it I also prefer your suggestion Min.

I also did some reading about Iceweasel ~ Firefox and the history in Debian about that. Seems like this situation is similar except we can obtain permission and don't have to create the Iceweasel equivalent of this project.

**Comment by betatim** [comment]
@jzf2101 I invited you to the group with (by visiting https://groups.google.com/forum/#!managemembers/binder-team/invite) two of your email addresses, maybe only accept one of the invites on your preferred account.
