### ISSUE TITLE
February 2019 Meeting

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#104]
Hello everyone, 

The February meeting will be held on the third Thursday of the month. 

That's **Thursday, February 21, 2019** at 6pm Zurich time (or your [timezone](http://arewemeetingyet.com/Zurich/2019-02-21/18:00/Jupyterhub%2FBinder%20team%20meeting)).

* You can find the agenda [here](https://hackmd.io/_uy9uaa7RheemwDD-bLehQ?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

I look forward to seeing you then!

**Comment by Zsailer** [comment]
Hey y'all,

Reminder that we have our monthly team meeting one week from today. See the details above.

Also, don't forget to add your agenda items 24 hours in advance, so we can organize the meeting before the call starts. Thanks!

I look forward to seeing everyone there!

**Comment by betatim** [comment]
Updated the top comment to mention the recording.

**Comment by choldgraf** [comment]
Another note - there's a section at the top of the agenda for shout-outs, recent happenings, and otherwise positive things to say. Feel free to fill it in :-)

**Comment by betatim** [comment]
Question: how do we deal with people who do not want to appear in a public recording (by voice or image) but want to participate in the meeting?

Can we move the related agenda item to the start of the meeting and only hit the record button once that is over (and they can excuse themselves from the meeting)?

**Comment by choldgraf** [comment]
How about:

1. We make it clear before the meeting that the video will be recorded
2. We suggest that if people don't wish to be recorded as a part of the meeting, they turn off their video screens and mute their microphones. During the meeting, we give a 10 seconds heads up that we're about to press "record".
3. We mention that people who've turned off screen + microphone can still ask questions via the chat box. And if they'd prefer not to do that, we'd love to see them as issues.

What do you think?

**Comment by betatim** [comment]
I think muting your camera is a good solution to "please don't record my face". However if you face mute and voice mute I think it becomes very hard to actively take part in the meeting or lead the discussion for an agenda item.

There are many reasons why someone might object to being recorded, from personal preference all the way to security worries or mundane things like "It would cause very awkward/difficult situations for me if I was recognised participating in this". Several conferences I've been to hand out different colours of lanyards to signal "no pictures please" to allow people to show their preference and as far as I can tell it works well.

I don't think this should be controversial as in previous meetings there has frequently been a "off the record section" that wasn't recorded or reflected in the notes. So we don't have to achieve the "this is a perfect record of how the meeting went" recording.

**Comment by choldgraf** [comment]
we could ask that anyone who wishes to discuss an "off the record" agenda item put a little note next to that item in the agenda, and then this gets covered after the video cuts out?

**Comment by willingc** [comment]
> Question: how do we deal with people who do not want to appear in a public recording (by voice or image) but want to participate in the meeting?

## Someone who wants to participate without voice and image

- Create a meeting comments etherpad/hackmd where all have permission to write during the meeting
- Better still, a discourse thread devoted to meeting comments.

## Someone who wishes to discuss completely off the record

- Set up a separate meeting with the team
- If discussed while the video is off (i.e. closed session) then a common council approach is to report back with a summary or no action in the open session and minutes.

**Comment by choldgraf** [comment]
Those both seem good to me. Since we already use a hackmd for the meeting agenda (that I believe everyone has access to edit by default) we could add an open section there for questions, comments, etc from the community (I have found that letting people ask questions asynchonously is a good way to get feedback from folks that would otherwise not speak up anyway).

Since you mention Discourse, I wonder if one way to approach this would be to create a Discourse thread for each team meeting. We'll use the hackmd in the same way that we have before, and we'll use the Discourse thread for comments, questions, etc. When the meeting is over, rather than committing all the markdown to the team-compass repository, we paste it into the top-level Discourse thread. Maybe this would make the team meetings, notes, etc easier to find for others in the community who may not be checking the `team-compass` repo as much.

**Comment by betatim** [comment]
I think the point that is missed in the above: people aren't objecting to participating with voice and/or image. They object to a recording of them being published on the internet. In particular because once it has been published it can never be unpublished again.

**Comment by willingc** [comment]
Ahh...thanks for clarifying @betatim. 

[Enabling recording notification](https://support.zoom.us/hc/en-us/articles/360000486746-Recording-Notifications) is probably a good idea. This would help the person who wishes not to be recorded forever to not speak while the recording is in progress. Should they wish to speak (assuming it will not be disruptive to the recording flow), they could request by Zoom's chat to pause the recording.

Alternatively, we don't record the meetings, and simply post a summary of the meeting notes. If there is a demo, we could opt in to recording that.

**Comment by lheagy** [comment]
If there is any concerns for tomorrow, we could also hold off on recording this time around and first chat about it at the meeting and make sure that we have consensus and a plan for how people can interact if they wish not to be recorded or wish to bring up discussion items that they don't want recorded. We certainly don't want to surprise anyone with this.

**Comment by betatim** [comment]
Thanks for the thoughts and compromises! For tomorrow we decided that I'll talk about the work as we had to make a decision yesterday morning and it was unclear what this discussion would conclude and people had to sort out their agendas in advance.

I think having a note on the agenda that says something about how to mark your agenda item as "please don't record" as well as a note saying "if you prefer not to be recorded please turn off your camera" would solve most issues.

**Comment by Zsailer** [comment]
Thanks to everyone who attended our meeting! 

I loved the conversations about how we can highlight contributions from community members/contributors (especially contributions that aren't necessarily git commits) and strive to be more actively inclusive. Thank you to everyone for great insight! 

If you weren't there, check out our agenda notes that will be posted on our team-compass docs page soon! (No recording today. My fault for not getting the credentials to record it this time. We'll try it next month!). 

**These calls are open to everyone, so please join us next time!** 😃
