### ISSUE TITLE
Remove or fix community statistics badge

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#109]
If I click the community statistics badge in the README, it pulls up the cauldron page with no data. Do we still want this? If so, let's troubleshoot; if not, let's remove.

**Comment by choldgraf** [comment]
I'm +1 on removing this until we figure out a more reliable / stable solution for displaying community activity. I like cauldron in theory but it seems to behave in unpredictable ways :-/

**Comment by choldgraf** [comment]
I believe that this badge is gone now!
