### ISSUE TITLE
March in-person team meeting

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#110]
Should we collect topics and other things we want to tackle during the in-person team meeting in March?

**This is a space to collect any and all possible agenda items. Please start a new thread if you want to discuss any of them directly/now so we can use this as a place for collecting things. Thank you 🙇‍♂️**

I think it would be good to plan ahead a bit on what we would like to cover when we are all in one room (minus those who can't travel). My expectation would be that there isn't so much business that we fill all the hours of the week. By having a bit of a plan those who want to use the time to float around and see what other parts of Jupyter are up to can do that in the gaps.

I'd start with using this issue (or a hackmd?) as a dumping ground for now. Anything goes. You never know what interesting things people come up with. If/when we have too many things we can start sorting/grouping them.

A dump of Tim's wish list:
* Binder team and friends dinner, either self made (facilities?) or go to a restaurant. I'd be happy to wrangle this.
* https://medium.muz.li/a-super-simple-exercise-for-solving-almost-any-product-design-challenge-f9e6c0019d7d I want to try this out to find out if it is just hype or actually useful. This is a bit meta.
* Binder-end-of-year-thoughts https://discourse.jupyter.org/t/end-of-year-thoughts-from-the-rust-community/295/7?u=betatim and discussed at the january team meeting. Either prep this or start evaluating (depends on when we launch this)
* What is the theme for Binder in 2019?? For me 2018 had a theme tune of https://www.youtube.com/watch?v=I_izvAbhExY (stayin' alive)
* grant writing, we owe several people several draft grants to finance Binder further, we should work on this

**Comment by choldgraf** [comment]
A few ideas from me:

* discuss the current communications setup (github/gitter/discourse/listservs/etc) and decide if we want to plan on changing that up at all in the near future
* Discuss w/ the broader jupyter community if we'd like to use Discourse for more than just JupyterHub
* I'd love to self-make some dinner :-)
* Similar to @betatim 's request I'd love to do a [Mission Vision Values](https://www.gsb.stanford.edu/alumni/volunteering/act/service-areas/mission-vision-values-facilitation) exercise for Binder, this could help scope out the organization and give us an idea for how it fits in with the broader open source landscape

also just a note re: grants, I'd really like to make progress on grants for Binder *before* the dev meeting...we don't have that much time!

**Comment by choldgraf** [comment]
ping @jupyterhub/binder-team to make sure folks know about this thread :-)

**Comment by consideRatio** [comment]
Where is the meeting?

**Comment by betatim** [comment]
It'll be in Washington DC. I'm not sure how the list of initial invites was created as it is officially the Jupyter team meeting (and I feel a little like Binder is a guest there?). If you want to come I'll find out how we make that happen.

**Comment by minrk** [comment]
I won't be attending, on account of parental leave expected to start in the vicinity March 12.

**Comment by betatim** [comment]
* take a picture of the team for talks and the like (figure out a way to photoshop those not present into the picture or take one where we can add people)

**Comment by choldgraf** [comment]
* Create an "official" stance on Binder terminology. @lheagy rightly pointed out that this is still a bit confusing (in https://github.com/jupyterhub/binder/pull/144) and I think there'd be value in having a group of us talk it through and posting something definitive on the web

**Comment by willingc** [comment]
> * Create an "official" stance on Binder terminology. @lheagy rightly pointed out that this is still a bit confusing (in [jupyterhub/binder#144](https://github.com/jupyterhub/binder/pull/144), example here: [jupyterhub/binder#144 (comment)](https://github.com/jupyterhub/binder/pull/144#discussion_r252513699)) and I think there'd be value in having a group of us talk it through and posting something definitive on the web

Agreed. We had something that we discussed early on. I can't remember if it was an issue or email. Would be good to standardize more.

**Comment by choldgraf** [comment]
btw, here is a totally not scientific and poorly-thought-through question I asked twitter about this:

https://twitter.com/choldgraf/status/1091014562839638016

Maybe as a lead-up to the dev meeting, we can brainstorm a more well-thought out question and ask folks to give their thoughts in a Discourse topic?

**Comment by betatim** [comment]
* a question we should tackle: can we call ourselves an open project if there are team meetings that require an (de facto and/or de jure) invite? Do we need a meeting that is limited in some way (location, size, ...) or could we as a team cope with an open invite situation in terms of logistics/planning/funding? If we are a sub-project of Jupyter and tag along to a JUpyter team meeting, what does that mean? I think this is a pretty tough question to answer because there are many things to consdier so if we want to discuss this before the meeting we should start a new thread (please). Otherwise let's tackle it in March.

**Comment by betatim** [comment]
* why is the repo2docker or Binder team not growing?

**Comment by betatim** [comment]
* what is the current structure of the various documentation pages, what other ways of organising it are there? I frequently feel lost trying to find things. Either because I am not sure which documentation page to go to and/or because from the hostname I can't tell if I am looking at the docs for mybinder.org, BinderHub or repo2docker (or yet another docs page). One idea: have a common paragraph on all of them that says "BinderHub docs are where you find XXX click here. repo2docker docs are where you find XXX click here. mybinder.org docs are where you find XXX click here." that lets you navigate to the right place from any of the docs.

**Comment by lheagy** [comment]
I added a question about recording monthly meetings in #116. Feel free to add your thoughts on that thread and we can also discuss in DC.

**Comment by willingc** [comment]
> * why is the repo2docker or Binder team not growing?

I have some thoughts on this.

**Comment by betatim** [comment]
* https://app.netlify.com/drop Why do we not have "binder drop"? Drop your folder, we make a gist, launch your binder. We could take some time in one session and hack on this. Would be super cool!

**Comment by Zsailer** [comment]
* Define/discuss the relationship between Jupyter and Binder (mentioned by @willingc at the February team meeting).

**Comment by betatim** [comment]
I've added my favourites from this list to the shared Dropbox document.

**Comment by willingc** [comment]
I've also added some favorites of mine to the Dropbox document. I think @betatim did a good job capturing.

**Comment by leportella** [comment]
* I may be wrong or off the grid here, but it seems to me that we have several binder discussions to be made and few related to jupyter and jupyterhub as different projects. Do you think I am right? And if yes, why so?

* Also, I just entered the jupyter org but I was not quite familiarized with Binder before the online team meeting. Could or should we discuss ways of making it more widespread? (at least in other places, such as Brazil)

* Could we discuss the start of efforts to translate documentation as well? I think it would make the projects more accessible for people of different countries with less opportunities to learn a second language.

**Comment by choldgraf** [comment]
@leportella those are great points! Thanks for jumping in :-)

I think that there will be a more general governance / community structure conversation at the team meeting as well, so hopefully that can touch on some questions like relationships between sub-projects (e.g. JupyterHub) and the broader Jupyter Project.

+1 to helping Binder become more recognized (internally and externally), and +100 to finding ways that we can engage the international community more with translation efforts

**Comment by willingc** [comment]
@leportella Did you receive an email with a link to the dropbox paper? If not, please let us know.

I also encourage you to fill out any suggested topics there too. Please feel as if you can add, comment, suggest things there. Your points are excellent. Thanks.

**Comment by choldgraf** [comment]
I added some thoughts from this list to the dropbox paper as well, I'm really looking forward to this meeting and the thoughtful discussions we'll have! These are really important topics!

**Comment by betatim** [comment]
What should we do about this thread?

My proposal would be to close this and for things we want to keep people can create new issues/threads/etc.
