### ISSUE TITLE
Shared house in DC

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#111]
This issue is about organising a shared house in DC for March 2019.

If you'd like to join post here with the dates you will be in DC for. If you'd like to wrangle this (get consensus and then book the house) please also post here saying so.

Meeting dates: March 11 - March 15 (9am to 6pm daily)
Location: George Washington University ([map](https://www.google.com/maps/place/The+George+Washington+University+School+of+Business/@38.9001069,-77.0503373,17z/data=!4m12!1m6!3m5!1s0x89b7b7b10e3c7aa5:0xda7bf41bdc27a808!2sThe+George+Washington+University!8m2!3d38.8997145!4d-77.0485992!3m4!1s0x0:0x1eae94f9504e0b9d!8m2!3d38.8987792!4d-77.0492072?hl=en))

**Comment by choldgraf** [comment]
I'll likely arrive Tuesday morning!

(also I edited your post to include the meeting dates and location)

**Comment by lheagy** [comment]
I will likely arrive Sunday afternoon / evening and stay until Friday evening.

**Comment by betatim** [comment]
Unless someone wants to step up to wrangle this I'd recommend we close this issue and jump on the hotel bandwagon that Ana posted by email. It would also save us some hassle in figuring out how many rooms we need for how many days with people arriving and leaving on different days.

**Comment by choldgraf** [comment]
I think that'll certainly reduce the complexity of this...sad not to be able to cook some dinners but I think this may be the simplest option

**Comment by Carreau** [comment]
I think I might take and AirBnb which will be closer to $200, I hope you can still come to my place to cook and/or drink.

**Comment by choldgraf** [comment]
@Carreau I had a hard time find any places near the location that weren't super expensive...how did you find a $200 place?

**Comment by Carreau** [comment]
Just go on airbnb and search... or did I set the wrong dates / location ? 
![screen shot 2019-02-06 at 10 53 00 am](https://user-images.githubusercontent.com/335567/52365952-7b15c600-29fd-11e9-9509-55beac55b914.png)

**Comment by choldgraf** [comment]
Alternatively if we'd like, there is this place:

https://www.airbnb.com/rooms/28646312?location=Washington%2C%20DC&adults=2&check_in=2019-03-11&check_out=2019-03-15&guests=1&s=AAp0bvq3

4 bedrooms, would come out to about $160 per night per person, close to the meeting spot...

**Comment by betatim** [comment]
If you book that place @choldgraf I'd be in and cancel my request for the hotel with Ana.

**Comment by lheagy** [comment]
@choldgraf: is it available for the night before as well? I plan on arriving on the Sunday. @betatim: when do you get in?

**Comment by choldgraf** [comment]
just checked and somebody booked the castle for that monday + tuesday :-(  so I think it might be best if we just tried to get studios on our own (it'll be cheaper than the hotel and hopefully one of us has a serviceable kitchen :-) )

**Comment by choldgraf** [comment]
ok, I booked a studio nearby! It has a little kitchen in it, so maybe we can cook something if folks are willing to squeeze in a bit :-)

**Comment by betatim** [comment]
I'm planning on doing the hotel option. I arrive Sunday afternoon/evening.

**Comment by consideRatio** [comment]
Wieee I'll also be joining ;D

I'm arriving Sunday 16:15 to IAD and departing Saturday 18:15 from IAD. I aim to stay at the hotel.

![image](https://user-images.githubusercontent.com/3837114/52937849-7d164800-3360-11e9-9477-eda5cc97c260.png)
