### ISSUE TITLE
Give octobox.io read access to the jupyterhub org?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#112]
[Octobox](https://octobox.io/) seems to be a nifty service for keeping track of github issues/PRs/etc across multiple projects. It is free for open-source projects and several folks I know have recommended it.

I'd like to give this a shot for some JupyterHub repos in the hopes that this makes it easier to track activity, but we need to give it read-access to the JupyterHub repositories first. Since that's an organization-wide decision, I want to run it by folks here first to see if people are OK with this.

**Comment by yuvipanda** [comment]
Let's do it!

**Comment by betatim** [comment]
I've been using octobox (my own instance not their hosted service) for about a year now and find it very useful. Does anyone know why we now need to give it access if it worked for me already?

Either way: fine by me.

**Comment by choldgraf** [comment]
I think it's done now!

**Comment by consideRatio** [comment]
@choldgraf hey just following up after thinking about jupyterhub org access for third party services in general - is it something remains in use etc? If so that's perfectly fine but I figured we should otherwise remove it.
