### ISSUE TITLE
New team member on-boarding checklist

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#113]
We now have a document that sets out what roles the team has, however we don't have a checklist for when we on-board a new team member. For example remembering to add them to the various team related email groups.

@yuvipanda @willingc @choldgraf @Zsailer @lheagy

**Comment by lheagy** [comment]
- provide an overview of areas where they can contribute? (e.g. docs, discourse / twitter, tackling issues, ...) 
- overview of pr process? (e.g. when is it appropriate to merge a pr that you have reviewed? or what to expect when a pr of yours is being reviewed)

I know these are in the various Contributing guides in the repos, but having a high-level summary that links to these could be helpful

**Comment by betatim** [comment]
* add them as collaborators on the repo2docker and BinderHub PyPI packages

**Comment by choldgraf** [comment]
* add them to the jupyterhub team google drive: https://drive.google.com/drive/folders/0B8VZ4vaOYWZ3a2dyeEp6NzBKbnM?usp=sharing

**Comment by choldgraf** [comment]
We now have [an onboarding checklist](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/adding-members.html#the-onboarding-checklist) so I'm gonna close this
