### ISSUE TITLE
Adding new team members

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#114]
What should the process be for adding a new team member? We set out in the governance docs that you have to be nominated by an existing member but nothing beyond that.

I propose the following steps for adding a new member:
* you open a new issue where you mention who you'd like to add and why you are championing them
* issue stays open for 10 working days
* if there are no objections the team member is welcomed
* you work through #113 with the new team member

**Comment by betatim** [comment]
Related to this: a [team privilege is merging PRs](https://github.com/jupyterhub/team-compass/blob/master/docs/binder_governance.rst#team-privileges). This means right now we can't have people merge PRs on repositories related to Binder unless they are also team members.

With the proposed procedure for adding a new team member there would be a mandatory 10 day wait between wanting to let someone merge work and them being able to do so. This has pros and cons :-/

---

Personally I think having to wait 10 days is not a hurdle as you are joining the team for the long run, not a short stint. Putting it the other way: I am not interested in people joining if they feel waiting ten days is too long and a reason not to join. However I also like (and have experimented unsuccessfully) with https://hintjens.gitbooks.io/social-architecture/content/chapter4.html and https://felixge.de/2013/03/11/the-pull-request-hack.html which advocate giving out merge rights more readily.

---

More important to me than getting my opinion implemented is that we set out a process that we can follow without needing to make exceptions (ever). I think for things like this it is an important signal to existing and potential team members that there is a transparent procedure that is followed instead of exceptions/favours being given to special people (ref tyranny of structurelessness).

**Comment by choldgraf** [comment]
Another thought: perhaps we can have one more team called the "green team" that are folks who have helped out in JupyterHub repositories, and who we feel comfortable giving merge rights to. The green team could be much more fluid and would be a way to signal our trust to certain individuals so that they're empowered to help out more.

**Comment by betatim** [comment]
We'd need a new colour as green is emeritus. Should we create a new thread on discussing additional categories and keep this one for "what is the process for adding someone"?

**Comment by leportella** [comment]
@betatim I like the strategy, but there is one thing that seems weird to me. Imagine that someone proposed me to be a team member in an issue, and someone puts  a lot of arguments that I should not enter the team. Although this could be very rational, it can trigger an irrational/emotional response that could be bad on the long run.

I would propose that these issues should be discussed by the team and only announced if there is an agreement.

**Comment by betatim** [comment]
That's a good point. The motivation for using this public repo is that we conduct most business here already and that it creates transparency. Transparency around the fact that people are being added (this isn't a closed club), why they are being proposed (that hopefully lets others know that it isn't so difficult) and that as a team we can be nice to each other even when there are difficult discussions.

Maybe we can find a balance between the two needs by adding a recommendation that the champion for a new member first has private conversations with the team to find out if such a proposal would be successful. As well as not asking for justifications for why team members vote one way or another.

My underlying assumption is that when someone is being proposed it will be uncontroversial because they have worked with the team for a long time and are respected by the community. This means that it seems like it would be very unlikely that we end up in the situation were someone is proposed and then rejected.

Let's ponder this a bit longer.

**Comment by choldgraf** [comment]
I'm fine with discussing matters like these in private with the team, though I'm not sure where we'd do so. There's not a forum (beyond just an email thread) to discuss things with the team only. If we made the jupyterhub github teams match the team compass teams, I think we could use the github chat feature for that.

That said, I think at the end of the process (if the person will be joining the team), we should make some kind of public statement about why they're joining.

**Comment by choldgraf** [comment]
thinking about this a bit more, I think that we could just follow the same process that RFCs follow in other organizations. Basically "anybody can create an RFC, but your luck will be better and you'll get more positive response from the community if you get buy-in and talk to team members before you do so"
