### ISSUE TITLE
Binder demo leads

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#115]
What do you think about collecting name and contact details of projects that use Binder and we could ask for demos at meetings? I started a spreadsheet:

https://docs.google.com/spreadsheets/d/1VqB-3fcfm6fWelDAa5P3yiewWLEQeHRg3t7NoKw4a1Y/edit?usp=sharing (to be moved to the team drive once I have access to it)

There is a [discussion of having a Jupyter wide community meeting](https://gitter.im/jupyter/dev-meeting-attendance?at=5c5e15f8253c2b5ea3ddca97) once a month where I think it would be great to have others demo their stuff. Not always the Binder team. One bottleneck with getting events/meetings powered by community contribs started is contacting and chasing up potential demo'ers. Having one or two every month might not sound like a lot but for that you probably have to contact 2-3x more potentials to get someone who has time and interest. Hence creating a spreadsheet to collect details and ideas.

**Comment by choldgraf** [comment]
@betatim since this is a more community-facing question, do you think we could make this a Discourse thread instead of on team compass? I think it'd be more discoverable in that venue rather than in the TC repo

**Comment by betatim** [comment]
Closing this here. I think it should be a discourse topic. I think the text would need reformulating a bit to make a good discourse topic and should ink to existing "collect awesome binder repos" threads. If someone has a spare moment to create that discourse topic I'd promote it, I won't create it myself anytime soon because #toomuchtodo :-/
