### ISSUE TITLE
stickers!! 

### ISSUE THREAD

**Issue by lheagy** [jupyterhub/team-compass#117]
I am planning to order Jupyter stickers for the team meeting in March, and @choldgraf and I were also thinking about making some for Binder. We can easily make die-cut ones from either
- [square logo](https://github.com/jupyterhub/design/blob/master/binder/logo_square.svg)
- [logo with text](https://github.com/jupyterhub/design/blob/master/binder/logo_w_text.svg)

Which would people prefer? (note that the default size for sticker mule is 51mm x 51mm) and how many should we order (they come in packs of 100)? 

Please also add your name to the dropbox paper where planning is happening if you would like a pack of Jupyter stickers

**Comment by choldgraf** [comment]
+1 on square for me! I'd love the text logo too but I think square is a good first step

**Comment by betatim** [comment]
I'd vote for square logo, die cut to actual outline. I've made good experience with https://www.stickermule.com/.

If it works out as ~$1-2 per sticker I'd be happy to put some cash in a jar to pay for this, might be more time efficient than navigating reimbursement/purchasing via the grant.

**Comment by KirstieJane** [comment]
Heya! I think we might print some stickers for our binder workshops. I'm liking the square one too 😄 

Have you had the hex conversation? Do you want square stickers or hex stickers?

I have ***no opinion***, except that we might try to send off an order tomorrow 😬 🚀

**Comment by betatim** [comment]
When we do print stickers (in all shapes and forms and tastes) we should collect the "design files" (the thing you need to submit an order) for each sticker in https://github.com/jupyterhub/design so that future generations can sticker-fy themselves.

**Comment by KirstieJane** [comment]
I've ordered some of the 50mm x 50mm square stickers from Sticker Mule! I sent them the [logo_square.svg](https://github.com/jupyterhub/design/blob/master/binder/logo_square.svg) file linked above. If they send me any other files in the proof stages I'll upload those to https://github.com/jupyterhub/design 😸

**Comment by lheagy** [comment]
Excellent! We ordered a bunch and I guess they arrived in DC today - so there will be many to go around 😄

**Comment by betatim** [comment]
@lheagy can you post the files you sent to the sticker printers for the Binder sticker in https://github.com/jupyterhub/design? Then we can close this.

**Comment by lheagy** [comment]
I used the [logo_square.svg](https://github.com/jupyterhub/design/blob/master/binder/logo_square.svg) that is in there. I can share the "reorder" on sticker mule on an email-by-email basis, but I don't know how to post it so it is generally accessible. So for now, if anyone would like access, please ping, otherwise, I am fine if we close this.

**Comment by consideRatio** [comment]
Thanks for the stickers :D Ill feel like santa in my data science team, on events like "Hack for sweden", and when speaking at universites!

**Comment by betatim** [comment]
Coolio. I thought you had to add some kind of outline or something to have it cut to the shape of the logo.

**Comment by KirstieJane** [comment]
Sticker Mule now have my contact details and sent me regular offers. There was one for “die cut stickers” last week and so I bought a small number of the cooler stickers that all y’all had in DC. It’s pretty awesome, you just upload the square file and they send you a proof with a nice white border around it an hour later ✨✨✨

Excited for them to arrive. And for the square ones to become collectibles 🤣.

**Comment by betatim** [comment]
I think we can either use this issue as reference (there are now a few mentions here on how to do it/what was done). Or write a short markdown document to be added to this repository.

**Comment by choldgraf** [comment]
closing this issue since I think it's addressed, feel free to re-open if there's something else to discuss! 🎉
