### ISSUE TITLE
missing LICENSE on binder-examples

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#118]
Most of the binder-examples repos lack a license file. This means they are implicitly all rights reserved, which we probably don't want. For examples, I typically prefer public domain (Unlicense from the GitHub license dropdown) so that there's no question about including example code in projects of any kind. Shall we add this to all examples repos?

**Comment by choldgraf** [comment]
hey all - I just went through and added a BSD-3 license to all of the binder-examples repositories that didn't have one! closing now :-)
