### ISSUE TITLE
How to highlight activity in the community more effectively?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#119]
Hey all - I am trying to think if we can take some steps to make it easier to recognize the work that folks (particularly newcomers) have done in the JupyterHub community. Stuff that makes it easier to ask questions like:

* Who has commented in the last month that has never commented in a JupyterHub repo before?
* Who are the top N committers / commenters that aren't a part of an "official" JupyterHub team?
* What is the percentage of commits from red/blue team members vs. non team members
* What are recently closed issues, PRs, etc over the last month (e.g., that can give a shout-out for in team meetings)

About a year ago I remember that we had things like "shout-outs and recognition" sections at the team-compass meetings (I believe @willingc suggested them, and had also added some initial scripts to display "recent activity" kinds of stuff in the readme?) If we had more data like this at hand, perhaps it's be easier to incorporate this kind of thing back into our team practices.

I looked into ways that we could try collecting this kind of data, and it seems like our best bets would be:

1. Write our own GitHubAPI script that pulls the data and stores it in Python
2. Use a tool like https://github.com/docathon/watchtower to make this easier (though watchtower is fairly underdeveloped)
3. Use a more fully-featured but complex tool like [grimoirelab perceval](https://github.com/chaoss/grimoirelab-perceval) or even [grimoirelab arthur](https://github.com/chaoss/grimoirelab-kingarthur) or [grimoirelab sirmordred](https://github.com/chaoss/grimoirelab-sirmordred), which do more a grafana+prometheus-style solution

Any folks interested in brainstorming on this a little bit? Either now or at the team meeting? I think this also intersects with some of the stuff that people have suggested in #110

**Comment by betatim** [comment]
I like the idea and the goal, unsure if technology is the solution.

Maybe we (as the team) can start by making a bigger effort to take note of new/interesting/awesome contributions that happen and highlight them in the team meeting. As a maintainer who is actively involved in the project one should have a feeling for who you are working with (and that they aren't part of the team). So maybe we can get started with this with a system based on a post-it on everyone's screen or what ever your favourite organisation system is?

I have moved the announcements section to the start of the agenda and we could add the shout outs into that section and over them at the start of the meeting after everyone has arrived.

**Comment by willingc** [comment]
I agree with @betatim. The technology solutions tend to perpetuate the emphasis of code contributions over others.

**Comment by choldgraf** [comment]
Thanks for highlighting this point, I agree with you both that we don't want to be driven by the tech, and we also don't want to bias ourselves towards a particular kind of contribution by only focusing on the things that are easy to collect with a script.

For me, the ideas about technical things is more about "how do I get a high-level view of what's going on across the jupyterhub projects, so that I can dig in more deeply to a specific part of the project". It's hard for me to keep track of all the repositories and what goes on inside them (I briefly turned on notifications for them all and it was way too stressful for me). I thought that a data stream of curated activity could be useful in the same way that Grafana is useful - it doesn't solve any problems, but gives you some hand-crafted data that can make it easier to solve some problems.

(This became an itch-scratcher for me this weekend (and I'm looking for excuses to play around with papermill and altair), so I generated [a little repository](https://github.com/choldgraf/jupyterhub-team-activity/tree/master/reports) that I'll use to keep track of recent activity in JupyterHub world.)

aside from the tech stuff, I'm all for trying to bring these practices back into the team meetings. I like @betatim's suggestion to add the "recent goings on, shout-outs, etc" to the top of the agenda!

**Comment by betatim** [comment]
Adding tools and automation should be our (long term) goal. What I wanted to highlight is that we should start today with a "no tools" approach instead of delaying the start because we build some tools first. This based on two assumptions:
* as maintainers we are (very) involved with some of the repositories already
* we are doing not-very-good job at this right now so improving is easy

---

For repo2docker I can (with a bit of effort) tell you who has been contributing over the last few weeks. For the z2jh chart I have no idea but I think those who help maintain that repository do know. It is part of the job of being a maintainer ... though I'd give my own efforts on this maybe a C :-/

**Comment by choldgraf** [comment]
(sorry if I made it seem like we should prioritize the tech stuff over making team changes, I didn't mean to monopolize the topic to discuss)

Do you have suggestions for team process ways to improve this? I like the idea of having a space to give "thank yous" etc on the team agenda...is there a place for this kinda thing outside of that meeting as well?

**Comment by betatim** [comment]
> Do you have suggestions for team process ways to improve this? I like the idea of having a space to give "thank yous" etc on the team agenda...is there a place for this kinda thing outside of that meeting as well?

I have no useful advice beyond standard advice for life: be polite, patient and thoughtful with others. Don't assume malice as not-knowing/misunderstanding is more likely to be the reason for people's behaviour. On a personal level I notice that I am a more pleasant human (towards others) when I am myself not stressed out and rushing around.

Maybe as a team it would help us for individual maintainers to declare which repositories they feel responsible for and hence be the one to ask about going ons in that repo. See my comment about my knowledge of going ons in repo2docker vs z2jh chart.

Taking the idea of "responsible for knowing the social dynamics in a repo" one step further: if you feel like that is you for a repo you are probably a good person to talk to for new/potential contributors. Which would suggest we list you in the README as "talk to X if you are looking for help to make your first contribution". (I like this idea and added it to the agenda as discussion topic.)

**Comment by betatim** [comment]
Maybe counting/measuring things about the community as a whole not individuals would be interesting and useful (?) feedback. Monthly active members, number of new members, average number of interactions between members along those directions?

**Comment by willingc** [comment]
@betatim's suggestion of measuring as a whole is a good one. I like the simplicity of the Django dashboard: https://dashboard.djangoproject.com/

**Comment by willingc** [comment]
I recently started using Sourcegraph for high traffic repos that interest me. Easy to self deploy on Digital Ocean. Its recent changes and contributors page are minimal but useful.

**Comment by choldgraf** [comment]
oops, just realized I dropped off on this one. sorry!

I think it's a good idea to not use "dashboardy" things to draw attention to individual contributors. The goal is to give a general idea of the project's heartbeat and not to focus on individuals.

Back to the original question, I think that for now I'm going to start using the "shout-outs" section of each month's team meeting to append little things that I notice people doing in the jupyterhub world. That seems like the easiest thing to do now.

**Comment by choldgraf** [comment]
Hey all - I'm gonna close this one for now, since I don't think there's any actionable path forward on it, but if folks would like to re-brainstorm ways to highlight activity in general, or specifics thank-yous for individuals, I'm happy to keep discussing!
