### ISSUE TITLE
Reviving the all-Jupyter team meetings + jupyterhub/binder demo

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#124]
Hey y'all, 

I wanted to point you to my discourse post, ["Reviving the all-Jupyter team meeting"](https://discourse.jupyter.org/t/reviving-the-all-jupyter-team-meetings/423), since it's relevant to the Jupyterhub/Binder team. A few of us met on Zoom earlier today and discussed how to repurpose these all-team meetings moving forward. This post summarizes our discussion (albeit, from my perspective). 

I would love to get feedback!

That said, it would be great to have one of the Jupyterhub/Binder team members give a short demonstration. Maybe we can show an example of using repo2docker and briefly describe the technologies powering that project? We just need someone willing to give a brief (~5-7 minute) demo by sharing their screen. Then, we can discuss and answer questions after the demo. 

What are your thoughts? Do we have other ideas for a brief demo?

**Comment by Zsailer** [comment]
Pinging @willingc because she was on the call today too! 😃

**Comment by choldgraf** [comment]
very cool! Thanks @Zsailer and @willingc for helping think through this stuff w/ the rest of the team. I'll take a look at the discourse post when I wake up :-)

**Comment by betatim** [comment]
Would it be "enough" to demo how to launch an existing repository on mybinder.org?

1. what is mybinder.org?
1. add `requirements.txt` to your existing repo
1. add link to README
1. directly open a notebook via specially constructed link
1. where to find more information

Then in next months meetinng we could do R, then Julia, then something yet to be defined :)

**Comment by Zsailer** [comment]
Hi all, 

A reminder that this call is happening next Tuesday. 

@betatim, I think that's a great idea for a demo. Would you like to present? Also, if anyone would like to give a brief update of things happening in the Binder world, that would be great too. 

Here's some important info for the call:
* We'll meet at 9am PST (your [timezone](http://arewemeetingyet.com/Los%20Angeles/2019-03-26/09:00/Jupyter%20Team%20Meeting)) on Zoom [here](https://calpoly.zoom.us/my/jupyter).
* The HackMD agenda is [here](https://hackmd.io/5WDMIAOjQx-SZe4_RP6wrg?both#).

Sign into the agenda if you'll be there. Also, feel free to add your topic to the agenda list!

I'll close the agenda 24 hours before the call.

**Comment by leportella** [comment]
Wait, this is not the meeting that happened yesterday? I'm confused!

**Comment by Zsailer** [comment]
@leportella No, this is broader meeting for all-Jupyter contributors (not just Jupyterhub/Binder) 😃 

The topics we'll discuss can be anything Jupyter related (i.e. Jupyterlab, core jupyter, jupyterhub, binder, nteract, etc.).  I've just posted this issue to remind Jupyterhub/Binder folks to be there!

**Comment by leportella** [comment]
Nice! I'll be there ❤️

**Comment by Zsailer** [comment]
Closing this issue since the meeting happened yesterday. If you missed the meeting, checkout out the video [here](https://calpoly.zoom.us/recording/share/aWb4ooDZsEESzF-LMNyodilb1Rc6PWsklp1R-fvrwh2wIumekTziMw?startTime=1553616201000).
