### ISSUE TITLE
March meeting madness

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#129]
#122 is a issue for topics to work on, this is an issue to get organised on social activities, logistics, etc

I will be landing late-ish Sunday afternoon at Dulles. It would be great to meet up for dinner with others who have already arrived (and then pass out with jetlag).

**Comment by choldgraf** [comment]
I'm arriving late Monday evening and will be around until Friday afternoon.

I'd love to cook dinner with people one night!

**Comment by Zsailer** [comment]
I'm arriving around 7:00pm, Sunday night at Reagan. That might be too late for dinner (especially since you'll be feeling the jetlag), but if you're still out, I can meet you somewhere.

**Comment by consideRatio** [comment]
I'm arriving to Washington, D.C. IAD 16:15 (Dulles) @betatim !
I'll be living at 9th and P street, which makes it for a perfect bike ride to the university I'm thinking, hopeful on the ability to use bikes in the city.

Wooo I'm really looking forward to meeting you again and new faces like @choldgraf and others who I have not yet met! :D :tada: :heart:

**Comment by leportella** [comment]
I'll arrive saturday night if anyone wants to meet DC on Sunday, I would love some company!

**Comment by willingc** [comment]
I arrive on Sunday night at Reagan National. I'll be staying in Arlington (10 min metro to GW) so I can see a few friends while in DC. See everyone Monday morning. Safe travels everyone.

**Comment by betatim** [comment]
Does anyone have ideas/preferences for a location for Sunday evening dinner?

**Comment by lheagy** [comment]
Hi all, I land around 4pm tomorrow at DCA - see you soon!
