### ISSUE TITLE
Review headings for all JupyterHub/Binder Gitter Channels

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#131]
Check to see
- [ ] if the headings guide users about what types of communication belong in gitter
- [ ] Mention the existence of Discourse

**Comment by betatim** [comment]
I changed the binder channel's topic to: The home of Project Binder, mybinder.org, BinderHub and repo2docker. For questions and archivable discussions https://discourse.jupyter.org/

Doesn't feel ideal and you have to hover over it to see it. Ideas on how we can shorten it?

**Comment by willingc** [comment]
Perhaps:

Ask quick dev questions about mybinder.org, BinderHub, and repo2docker. Use discourse.jupyter.org for user questions, support, and discussion.

**Comment by choldgraf** [comment]
I like the idea of keeping the gitter channels focused on developer-level questions, and using discourse for basically anything else

**Comment by betatim** [comment]
Updated it to https://github.com/jupyterhub/team-compass/issues/131#issuecomment-473595088

**Comment by choldgraf** [comment]
I just checked these, and it looks like:

* https://gitter.im/jupyterhub/jupyterhub
  - [ ] if the headings guide users about what types of communication belong in gitter
  - [ ] Mention the existence of Discourse
* https://gitter.im/jupyterhub/mybinder.org-deploy
  - [ ] if the headings guide users about what types of communication belong in gitter
  - [ ] Mention the existence of Discourse
* https://gitter.im/jupyterhub/binder
  - [ ] if the headings guide users about what types of communication belong in gitter
  - [ ] Mention the existence of Discourse

any others that we're missing?

**Comment by choldgraf** [comment]
closing this issue since I think it's addressed, feel free to re-open if there's something else to discuss! 🎉
