### ISSUE TITLE
Check if we have a "random" social channel on Discourse

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#132]
@betatim mentioned the value at our team meeting for random conversations

**Comment by choldgraf** [comment]
the closest thing that I can think of is the "community" room:

https://discourse.jupyter.org/c/community

it doesn't explicitly say random/social stuff though

**Comment by betatim** [comment]
I'd keep the random/social chat to gitter (or other chat tool). It isn't something that needs to be archived/searchable. Also I think discourse is designed to discourage short and quick exchanges between two or three people.

My comment was aimed at maintaining a place that encourages people to talk about things which are unrelated to the project/off topic/random. Talking about random things in a non-formal way is what turns y'all from faceless internet robots into humans for me :)

**Comment by choldgraf** [comment]
since we have #135 , think we can close this and touch on the "what communication goes where" question there?

**Comment by betatim** [comment]
Agreed. I am not even sure I want a random category on discourse or prefer people come to gitter for random chat and hanging out. It would keep the signal-to-noise in discourse higher (without having to filter out the random category)
