### ISSUE TITLE
Change the logo

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#133]
Right now the team compass logo isn't exactly a paragon of design quality. There was talk at the team meeting that somebody could/should design something new! Maybe one of @timkpaine's team?

**Comment by lheagy** [comment]
I think it is also a trademark question at the moment too... so we should be aware of that as new designs are suggested

**Comment by choldgraf** [comment]
(btw, if we are doing some kind of legally bad thing having that logo up there, I'm +1 on just removing it or replacing it with the jupyter logo.

**Comment by lheagy** [comment]
@choldgraf : might be worth checking with Ana, she expressed concern when we showed it at the mtg (I wasn't clear if it was a legal problem, or they just weren't a fan of the logo...)

**Comment by Zsailer** [comment]
FWIW, I liked the "compass-Jupyter" logo. 😃 It just needs a designer to give it a revamp.

**Comment by choldgraf** [comment]
with the new docs, we no longer violate the jupyter design guidelines, so I'm gonna close this :-)
