### ISSUE TITLE
April blog posts

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#134]
The start of april is a good day to post blog posts with big announcements. Does someone want to collaborate on one of the below? I've had two-point-five ideas in my head:

* Jupyter acquires chateaux open-source
* The Binder team decides to make mybinder.org paid-plan-only and that we will continue development of the tools in a private fork. In the name of sustainability.
* Binder is acquired by Google and the team will now work on colab

We might have to coordinate and navigate a (too) large group of people to get the first idea signed off (e.g. you might want to mention where the funding came from which probably needs discussion with the funder). I think my favourite is the second one (paid plan only).

**Comment by choldgraf** [comment]
I'm +1 on a fun post though -1 on anything that might spread negativity towards others on the internet. I don't want to use April 1st to throw shade at other people :-)

I like the idea of the chateauxpen source!

Another idea: in the name of sustainability, the Binder Project is pleased to announce that it is launching a paper products company with a key focus on three-ring binders.

**Comment by betatim** [comment]
I agree that we shouldn't use it to hate other people. However I don't think that "binder team decides to make a close source product now" targets anyone specifically.

**Comment by choldgraf** [comment]
(to be clear, my previous post was more about calling out a specific group/company, which I think is a tricky thing to do without creating animus...something more generic like announcing that Binder will start charging for services would be OK)

**Comment by leportella** [comment]
I like the idea of the Chateaux and the iPython with a lowe case i

**Comment by betatim** [comment]
Another idea: Jupyter and NASA are happy to announce that Jupyter notebooks are running on a rover that has been launched towards Jupiter (the fact it is a gas giant and rovers are hard on those is part of the joke).
