### ISSUE TITLE
Proposal for JupyterHub communications

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#135]
Hey all - I opened up a thread to try and nail down a specific communications plan here:

https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505

would love for people to participate and see if we can agree on something moving forward :-)

**Comment by willingc** [comment]
As an FYI, Google Groups has some changes coming in May 2019 https://support.google.com/a/answer/9191148

**Comment by choldgraf** [comment]
I'm gonna close this one as I think we have a decent-enough pattern between the github issues and the Discourse - if folks think we should "officially" codify these rules, we can re-open and I'm happy to keep chatting about it, but I'll close this for now as nothing left to complete
