### ISSUE TITLE
April Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#137]
Hello everyone, 

The April meeting will be held on the *third* Thursday of the month.

That's **Thursday, April 11th, 2019** at 6:00 UTC (or your [timezone](http://arewemeetingyet.com/UTC/2019-04-11/06:00/Jupyterhub%2FBinder%20team%20meeting)). 

Note, that's **Wednesday night, April 10th** for anyone on the west coast in the US. 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by minrk** [comment]
April 18 is a holiday here, so I might not make it to this one. Unless maybe it moves a week earlier or later?

**Comment by Zsailer** [comment]
I'm happy to move the meeting if others agree. I propose moving the meeting **up one week** to April 11th. 

Do others agree?

**Comment by Zsailer** [comment]
Do we want to consider alternating the time as well (in line with #141), since we'd already be moving the date?

**Comment by betatim** [comment]
I vote for moving it to 11 April and the early timeslot.

**Comment by betatim** [comment]
I updated the top comment to reflect that we are meeting on 11th April.

**Comment by Zsailer** [comment]
Should we shift the time too, per @clkao's suggestion?

**Comment by betatim** [comment]
I'm ok with moving the time, I made a suggestion about moving it earlier #141.

**Comment by Zsailer** [comment]
Ok, let's try out the new time! I've updated the issue above. 

We'll meet at 6:00 UTC on April 11th (that's one week from now). People in SF, this is actually Wednesday at 11pm.

**Comment by betatim** [comment]
I can host the meeting if this isn't a good time for you Zach.

**Comment by Zsailer** [comment]
@betatim thanks, Tim! Yes, let's have you host the meeting, if you're still fine with that. 

I'm still planning to be there (and record the call), but I'm living with friends in CA for the next few months. I don't want to bother them too much. I can still do all the post-meeting stuff (i.e. adding the minutes to team-compass, posting video, etc.)

**Comment by Zsailer** [comment]
Also, pinging everyone here to remind you that our monthly video call is in a couple of days! 

Add your topics to the agenda **24 hours** before the meeting: [here is the link.](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both)

I look forward to seeing y'all!

**Comment by Zsailer** [comment]
Thanks everyone for coming to last weeks meeting! If you missed it, check out the video [here](https://calpoly.zoom.us/recording/share/o5nqrIIDMPqO2VQUnBZFe76oEUhN3IgfnWJKzv3VBg2wIumekTziMw).
