### ISSUE TITLE
February 2018 video call

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#14]
Current plan is to have the next video meeting in the first week of February (tentatively at the same time).

Plans
- [x] Tim: contact M re: meeting time/date
- [x] Tim: announce meeting to team [date fixed](https://github.com/jupyterhub/team-compass/issues/14#issuecomment-356435144)
- [x] Carol: announce meeting to the larger Jupyter community via Jupyter mailing list as suggested by Brian
- [x] [link to agenda](https://hackmd.io/MYNgpgHATAZgrAIwLQAYCMwAsTNhRJAThBQGYkoATEw0gQxgkroHYg==?view)
- [x] use Cal Poly Zoom for meeting https://calpoly.zoom.us/my/jupyter

**Comment by betatim** [comment]
Update from chatting with @mpacer: Thursdays are out. Best suggestion so far, Tuesdays before (this means 8am California time...) the Jupyter Team meeting. Does the Jupyter meeting happen every week? Or could we alternate by timing things to alternate?

Let's aim for the week of February 5th. Precise day to be fixed.

**Comment by yuvipanda** [comment]
Note that I won't be able to make 8 am meetings.

**Comment by betatim** [comment]
How do we make progress on this? My only hope is that the Jupyter team meeting isn't every week so we can use one of the empty slots.

I am a bit out of ideas, we don't want to start down the route of the mega doodle poll to doodle all polls ...

If we have no ideas on how to improve the situation I propose Feb 8th, 6pm Zurich time or [in your favourite TZ](http://arewemeetingyet.com/Berlin/2018-02-08/18:00/Binder%20Team%20Meeting). Mark your calendars.

**Comment by willingc** [comment]
> If we have no ideas on how to improve the situation I propose Feb 8th, 6pm Zurich time or in your favourite TZ. Mark your calendars.

Let's go ahead with this date and time. I'll take the action item to update M after the meeting and answer any questions that might come up. M, we can chat before the meeting to see if there is info that you want me to relay/communicate to the larger group.

**Comment by choldgraf** [comment]
How about at the end of each meeting we create an issue and copy/paste the agenda we've filled in. Then we close the issue and wipe the agenda page clean so we can start fresh?

**Comment by ellisonbg** [comment]
Hi all, following this issue so I can track the meeting time. Looking forward to it!

**Comment by willingc** [comment]
> How about at the end of each meeting we create an issue and copy/paste the agenda we've filled in. Then we close the issue and wipe the agenda page clean so we can start fresh?

Yep @choldgraf. The agenda will be at the same link each time, and I'll be archiving them weekly and after the monthly meeting.

**Comment by willingc** [comment]
The next meeting is currently scheduled for:

 Feb 8th, 6pm Zurich time

**Comment by choldgraf** [comment]
Do we have a place where we should put discussion items for the next video call? E.g., things that would benefit from having a group conversation? I think the agenda here is still weekly (at least, it has opening/closing dates 09-15th of january)

**Comment by willingc** [comment]
Let's put the discussion items in the weekly agenda with [FEB] as a notation that it is for monthly call. Two benefits: one less doc to track and folks get a multi-week heads up.

**Comment by willingc** [comment]
Reflecting a bit more on @choldgraf's comment. I've gone ahead and reordered the sections in the weekly document:
- Action items placed before news, information and thanks
- Monthly agenda items can be placed in Section 1 at any time during the entire month
- Actions first should make the monthly meeting more collaborative (Information and news items, while important, can be read.)
- Document should be less cluttered for editing
- Sections and subsections numbered for easier reference

Here's the reordered document structure:

*Outline template for meetings*

## Actions

1. Help or discussion needed; Agenda Items for Monthly Meeting 
        - 1.1 Open PRs
        - 1.2 Open issues

2. Decisions needed

3. Next actions (team)


## News, Information, and Thanks

4. Team Metrics
5. Team News and Informational items
        - 5.1 Organization highlights
        - 5.2 BinderHub projects
        - 5.3 JupyterHub projects
        - 5.4 Related projects (repo2docker, nbgrader, others)

6. Thanks, Things to Celebrate, and anything else

**Comment by choldgraf** [comment]
I think this is really nice!

**Comment by yuvipanda** [comment]
Just a bump reminder that this meeting is in one week!

**Comment by choldgraf** [comment]
Hey all - just a note that this is happening on Thursday Feb 8th! I've updated the weekly report again so we have a fresh one to use for the meeting.

A couple questions:

1. Shall we just use this week's "weekly report" to hold info etc from the meeting? Or was the plan to have a separate template for this?
2. We should announce this to the listservs in case other folks want to plan around the meeting!
3. A gentle reminder to folks to fill in the weekly updates with notable goings-on in the jupyterhub world! [weekly update link](https://hackmd.io/MYNgpgHATAZgrAIwLQAYCMwAsTNhRJAThBQGYkoATEw0gQxgkroHYg==?both)

Looking forward to seeing y'all!

**Comment by betatim** [comment]
I went through the past weeks and added what I think is relevant to the agenda.

> We should announce this to the listservs in case other folks want to plan around the meeting!

Which lists did you have in mind specifically? On my list so far: binderhub-dev

**Comment by choldgraf** [comment]
@betatim thanks for sending to the `-dev` listserv! I believe that @willingc was intending to message the broader jupyter listserv too (per top-level comment)

**Comment by betatim** [comment]
I wasn't sure which mailing list exactly that would be so I skipped it for the moment. Maybe if it is a "big list" waiting till we have the video conference link ready is a good idea too.

**Comment by willingc** [comment]
Here's the link to the video conference: https://calpoly.zoom.us/my/jupyter

**Comment by betatim** [comment]
The meeting is over, closing this.
