### ISSUE TITLE
Alternating hours for monthly meetings

### ISSUE THREAD

**Issue by clkao** [jupyterhub/team-compass#141]
It seems the monthly meetings are generally 16:00 or 17:00 UTC, which is not very Asia-Pacific friendly.

Does it make sense to try alternating hours by month?  for example 16:00UTC for one month and 08:00UTC the next.

**Comment by choldgraf** [comment]
I think it's a great point @clkao - I'd be happy to alternate jupyterhub meetings to times that are more friendly for other parts of the world.

**Comment by Zsailer** [comment]
@clkao Thank you for bringing this up. I think alternating meeting times makes sense. We should do it.

**Comment by betatim** [comment]
How about 6.00UTC which would be 8am Zurich and 23.00 San Francisco?

**Comment by choldgraf** [comment]
mmm, depending on my schedule the next day I may/may not be able to make it, but I think that's fine given that we're alternating times each meeting.

I think a related question to this is: would somebody else be willing to lead these meetings if it's at 11pm California time? I think it's unfair to @Zsailer to ask him to lead a meeting just before midnight. (maybe Zach is willing/able to do it, but I don't think we should be in the habit of asking people to do things like this in general)

**Comment by Zsailer** [comment]
Thanks @choldgraf ❤️ I'm planning to attend the first meeting, and I'm happy to lead it. But I agree, we don't want to give the impression that we expect our contributors to be on call all hours of the day. 

I think this may be a great opportunity to bring a _new_ contributor into the mix? Or maybe someone who wants to get more involved? They could host the calls during these alternate times. I'll continue the meetings during the original times.

**Comment by clkao** [comment]
Thanks to everyone for taking this into consideration!  I will be able to attend 6.00UTC in April 11th. Happy to help hosting the next time (June?) when it is in such hours.

**Comment by Zsailer** [comment]
@clkao Would you be interested in moderating the call on April 11th?

**Comment by choldgraf** [comment]
Hey all - if I recall, we agreed to slightly alter the hours that we'd planned on using before (to make the meeting a bit later so that folks in Europe didn't have to wake up so early, and to just assume the Californians wouldn't be able to make it). Do folks remember what that decision was?

**Comment by betatim** [comment]
I think we decided to move the Asia+Europe meeting slot back by an hour.

**Comment by choldgraf** [comment]
So then:

A: 9am California time
B: 11:59pm California time

And just a note that this isn't updated in the documentation yet:

https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings.html

**Comment by Zsailer** [comment]
>A: 9am California time

The next call is actually scheduled for 5pm UTC, which is **10 AM** California time (darn daylight savings!).

**Comment by betatim** [comment]
I think we should fix the time in UTC. It is a bit annoying that this means it moves in local time but because (for example) the US and Europe change to daylight saving time at a different date we would end up with meeting times that are "exceptional" for 4 or 5 weeks every year. I find it easier to know my local offset from UTC than to know the current delta to some weird remote time zone I am hardly ever in.

**Comment by Zsailer** [comment]
> I think we should fix the time in UTC.

I agree. Does everyone agree to 5pm UTC?

**Comment by choldgraf** [comment]
I agree - though this is why the google calendar on that page should be up-to-date, I'm treating it as the authoritative "this is the time of the next meeting" because I know Google can handle all the various time zone changes etc much more fluidly than we can.

**Comment by betatim** [comment]
The question is which timezone should the calendar's appointment be set to?

**Comment by Zsailer** [comment]
> this is why the google calendar on that page should be up-to-date

This is mostly my fault. I had completely forgotten (and thus, neglected) the team's Google Calendar! I'm adding it to my checklist now!

I think UTC probably makes the most sense for timezone...

**Comment by choldgraf** [comment]
we now do this! so closing this issue :-) please re-open if there's still something to discus
