### ISSUE TITLE
Watching this repository

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#142]
My assumption around communication in this repository is to assume that people keep on top of it and don't reply because they don't want to cause unnecessary notifications. However there are several people who aren't watching this repository who I think are part of the binder team and hence should have an interest in keeping on top of things.

I assume you have other ways of doing this than "watching" the repository. Is this true? Can we continue to operate under the assumption that people keep on top of activity in this repository?

I don't think it is feasible to attract people's attention via mentions. In fear of missing people I would create a list of all GitHub handles once and copy&paste it into each new issue I start.

In return for expecting everyone on the team to "watch" (or equivalent) this repository please think about the fact that ~15 or more people receive a notification each time something is posted here. In a group of N people, speak 1/Nth of the time. Emoji reactions are a good way to signal agreement/disagreement/I've seen this/etc that does not trigger a notification.

If there is no consensus around the above idea, someone from the "oppose" camp needs to propose an alternative and shepherd it to adoption. (Personal note: because I like the above idea I will not be a good facilitator for alternatives as I wouldn't want them to be adopted.)

---

Mentioning all the Binder team here (sorry for being obnoxious) @jzf2101 @lheagy @choldgraf @mpacer @yuvipanda @minrk @Zsailer @consideRatio @willingc

**Comment by minrk** [comment]
I think that's a valid expectation. We should perhaps make it explicit in [team responsibilities](https://github.com/jupyterhub/team-compass/blob/master/docs/binder_governance.rst#team-responsibilities)?

**Comment by choldgraf** [comment]
I'd also be +1 on making this an expectation of being on the team.

**Comment by willingc** [comment]
I'm fine with it being an expectation to keep up to date on the issues. Personally, I don't use the watch or notification functionality since I use Octobox to keep track of the several hundred repos across multiple projects that I follow.
