### ISSUE TITLE
mybinder.org sub-domains

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#144]
What do people think about introducing a process for assigning subdomains of `mybinder.org` to other public, vanilla, tracking the mybinder.org deployment BinderHubs?

Doing this allows us to partner with other cloud providers by acknowledging their contribution of k8s cluster(s). As part of this we should probably create gcp.mybinder.org as a name for our current cluster. A concrete use case for this is OVH who are already running a public BinderHub which doesn't yet have a good public URL. We would use the below process/rules/guidelines to decide if we want to use ovh.mybinder.org to point at that cluster.

---

From my point of view I think it is Ok to start with a fairly lightweight process as we don't have many people who come knocking on our door asking for this. This means an important thing to communicate to who ever is providing the resources is that this is totally "at the discretion of the team, a sub-domain is a privilege not a right".

Conditions I'd add:
* it is a public cluster, no logins, tracking at the level of mybinder.org, no preference give to certain repos/workloads
* tracks the mybinder.org deployment -> is up to date wrt mybinder.org
* look and feel like mybinder.org, with space for a non annoying mention of who is providing the resources on the launch form and spinner page (no JS pop ups, pop unders, crypto miners, ...)
* some form of commitment to maintain this cluster "for a while". We won't do this for you if you are only here for 4 weeks.

Potential takers for sub-domains that I can think of and would be happy with:
* cloud providers
* universities
* research labs
* governments

I propose we discuss this in this issue and have a verbal discussion at the April team meeting and try and make a yes/no decision during the team meeting. Maybe by the time of the team meeting the feeling is that there are too many questions or controversy in which case we should address those instead of deciding. Decision process is to be decided but will allow team members to take part even if they can't make it to the video meeting.

**Comment by lheagy** [comment]
I would be quite excited to start testing out a process for adding subdomains and having new partners who are helping continue the growth of mybinder.org as a public service. In addition to having conditions that define what you _shouldn't_ do as a mybinder.org partner, I would suggest that in the initial announcement blog, we spend some time highlighting what you _should_ do and why OVH is a good partner. Having a few documented decision vectors that we can point to could be helpful if there is ever a scenario where there is a player who doesn't violate the conditions, but isn't inline with the spirit of mybinder.org.

**Comment by minrk** [comment]
This sounds like a great plan to me.

**Comment by betatim** [comment]
Sounds good and like there is consensus around using ovh.mybinder.org to point to a public cluster hosted on OVH infrastructure. How should we record this decision? Should we have a vote in this thread where people post a comment with yay/nay?

Lindsey, what would you add as "what you should do"? Or should we reformulate the points I gave in the positive?

I would open a new thread to draft the blog post.

**Comment by choldgraf** [comment]
@betatim perhaps we could open a PR to the team-compass docs codifying this, similar to how we worked with the roadmaps etc? Then people could tie the language on that page to the PR that created the text, and thus to the discussion around it?

**Comment by betatim** [comment]
I made a start on a document in #149

**Comment by choldgraf** [comment]
I believe we can close this since we've got #149 merged now...feel free to re-open if this needs more work!
