### ISSUE TITLE
May Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#151]
Hello everyone, 

The May meeting will be held on the *third* Thursday of the month.

That's **Thursday, May 16th, 2019** at 5pm UTC (or your [timezone](http://arewemeetingyet.com/UTC/2019-05-16/17:00/Jupyterhub%2FBinder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by Zsailer** [comment]
I'll be in Paris for the Jupyter Server workshop on May 16th-17th. I'm not sure what our schedule will be for the workshop just yet. 

I'm hoping to make this meeting, but just in case, can someone else be ready to moderate to call?

**Comment by betatim** [comment]
I will be in Scotland hiking so won't be able to join (a laptop weighs as much as essentially an infinite amount of calories so it is staying at home 🏕 ).

**Comment by Zsailer** [comment]
@betatim That's awesome! Have a great time!

**Comment by Zsailer** [comment]
🎉  Hey everyone, reminder that our meeting is one week from today! 🎉 

Start thinking about adding your agenda items. 😃 As I mentioned, I may not be able to make it, so someone else might need to lead.

**Comment by choldgraf** [comment]
Hey all - I just opened up this Discourse thread to track the meeting as well:

https://discourse.jupyter.org/t/jupyterhub-community-call-5-16/1072

If that's a helpful template, perhaps we can copypaste before subsequent meetings! I'm trying to make it a bit easier for folks to add agenda items etc.

**Comment by choldgraf** [comment]
Friendly reminder to add discussion items or shout-outs/reports to the agenda for tomorrow!
