### ISSUE TITLE
BinderHub out of beta blog post

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#152]
This thread is about coordinating a short blog post to announce that [BinderHub doesn't have the "beta" label any more](https://github.com/jupyterhub/binderhub/pull/826).

https://hackmd.io/g1-WT20hQeqbcOQp9CiSOw for writing.

In order to give us a chance to get this out of the door quickly I would limit ourselves to something like five paragraphs.

IMHO the main goal is to get across the idea that BinderHub and its related projects are now tools that are stable and reliable for every day use. This isn't an experiment but a tool you can deploy and rely on. It is used by lots of other people who aren't super fans, they use it because it solves a problem they have and using Binder reduces the number of headaches they have (not the other way around).

**Comment by betatim** [comment]
I threw together the text in the hackmd in 20minutes on the train this morning. Please do feel free to edit and extend. The sentences are short. Very short. And could do with a bit of expanding or adding transitions between them. Also, someone who is good with words ... please do your thing :)

**Comment by betatim** [comment]
Does anyone have opinions on this or plans to look/edit the post? Otherwise I'll give it another read and edit pass and then post it on the blog.

**Comment by choldgraf** [comment]
Just had a moment to take a pass on the plane - I made some edits, additions, and added a quick comment. I think that in general it's looking good! I'd love to add some more links in there (e.g. to GKE, Azure, etc), as well as to give a shout-out to google for giving us hosting at mybinder.org. I'm not so sure we need to include a lot of content about the different kinds of repositories that people have run, though it might be interesting to talk a bit about where we'd like to see the limits pushed (e.g. mention Dask+Pangeo and talk about how a cool frontier is connecting with high-performance compute like Spark etc)

Happy to iterate on this a bit this+next week (I've been off on vacay for the last week but back tomorrow)

**Comment by betatim** [comment]
I agree I wouldn't add a section on what repos are running on BinderHubs. I'd make a second blog post with cool and creative uses like https://course.spacy.io/, jupyter book and the like.

I added a sentence about who is bank rolling mybinder.org

**Comment by betatim** [comment]
I made a few more tweaks and will copy it to the medium blog in the next few hours. I'll add a note on the hackmd when I do that so people know where to edit.

**Comment by choldgraf** [comment]
this is published! https://blog.jupyter.org/binderhub-is-out-of-beta-fa2781a229d6
