### ISSUE TITLE
Discuss applying for a CZI "Essential OS for Science" grant

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#156]
CZI recently announced a call for proposals for the [essential open source for science](https://medium.com/@cziscience/essential-open-source-software-for-science-72faec2c38c1) program. This supports open source projects that are deemed "essential" for biological science. It explicitly says it doesn't need to be directly bio, but can be underlying infrastructure as well.

## Current status

- We are iterating on a "Binder fellow" position here: #165 
- Feel free to brainstorm other titles for other applications below

## Links

- [blog post](https://medium.com/@cziscience/essential-open-source-software-for-science-72faec2c38c1)
- [application page](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/)

## Important info

- They are fairly open-ended about what people will apply to do
- They explicitly mention it doesn't have to be for code - it can be for community management, documentation, project management, etc
- The amount is for 1 year, between $75,000 and $250,000, with the opportunity to re-apply.

I think that JupyterHub and/or Binder could make a *really* easy case for why we should be supported by a grant such as this. Who is interested in brainstorming and then putting together an application to make this happen? I am happy to work with y'all in doing this!

**Comment by yuvipanda** [comment]
I was confused if this was to go to individuals or an organization. From reading the RfA packet, it's targeted at organizations. 'Grants are not permitted to individuals; only to organizations.'. So if we apply, who would receive this money?

**Comment by betatim** [comment]
Couldn't Numfocus be the receiving organisation as Jupyter is a sponsored project?

What would we use the money for?

**Comment by betatim** [comment]
We could start something like the Django Fellowship ([scroll down a bit here](https://www.djangoproject.com/fundraising/))?

I think we couldn't use it for hosting costs.

**Comment by yuvipanda** [comment]
I *love* the idea of the django fellowship program equivalent!

**Comment by choldgraf** [comment]
I'm hesitant to start a new thing that will create overhead unless we also get funding to pay for somebody's time to organize / prioritize that new thing. So one thought is we could also ask for funding to hire a community advocate of some sort that would work on this kind of stuff.

In terms of "who would receive the funding" I think NumFocus would work fine.

> As an example, scikit-image used an earlier version of this CZI grant to buy-out a year of development from Juan, one of their core-devs. He's employed in Australia and they used the grant to make his employer OK with him spending most of his time on OSS stuff.

**Comment by jhamman** [comment]
I know NumFOCUS has this call on its radar already. I'd encourage you all to get in touch with them and  let them know you are considering a submission.

I'd also be happy to help brainstorm some ideas. My ideas would probably center around Jupyter/binder for large scientific analyses.

**Comment by betatim** [comment]
I'm not super attached to the idea of creating a Binder Fellow, but until there is a concrete alternative to discuss I'll keep spinning it further :)

> I'm hesitant to start a new thing that will create overhead

Agreed. A while back I saw the call for applications for the Django fellowship which had a good [description of what the expectations are](https://www.djangoproject.com/weblog/2018/dec/21/django-fellow-applicants/). This made me think "yes someone like this would help Binder and JupyterHub" in terms of facilitating contributions from the outside, keeping the machinery well greased, triaging issues, first point of contact for support questions, welcoming contributors, advocating for the project, helping others figure out why the CI is red, etc. Basically, we hire a janitor :) Someone who in their paid time works on giving assists to others so they can score a goal.

To put it very bluntly: you get paid to work on open-source but your highest priority tasks are to do all the stuff no one else wants to do but needs doing. If there is time left at the end, you can do what you please for the project.

I think every project and community needs someone like this. So this isn't a new need or position because others are currently doing all those tasks in their "spare time" (time that isn't paid to work on Binder).

Not sure how much overhead it is to admin this position. There is some work involved in soliciting applications and reviewing them. We need to create a clear job description with responsibilities and authorities before asking for applications. The contractor paperwork is a standard thing for Numfocus. We can make it part of the Binder fellows job to report about their work at the monthly meeting. What else would need doing?

What is a community advocate? In my mind it sounds like a job like Kelsey Hightower's who is a sales person. Is that also what you have in mind?

**Comment by choldgraf** [comment]
ohhh my bad, I think I mis-understood your suggestion. I thought you were saying that we should set up an ongoing fellowship program (and my first thought was "ok but who's going to raise money for, administer, etc this program"). If instead you're saying "let's use this money to hire a single person that would be the 'binder fellow'" then I think that would be great as well.

I agree it would create *some* administrative overhead but not nearly as much as I had imagined, I think we could handle somebody like this between our respective orgs.

**Comment by betatim** [comment]
I would bill it as a "trial run" or "prototype this" with the goal/promise/end goal of making this permanent if it turns out to be a useful thing, we can find funding on a repeat basis, etc. I think it is easier to sell in the grant if we aim to make it a permanent fixture instead of a one off thing. What actually happens after the test run is, of course, unknown because otherwise we wouldn't need a test run.

**Comment by choldgraf** [comment]
I like the sound of that idea!

**Comment by minrk** [comment]
This sounds like a super great plan.

**Comment by choldgraf** [comment]
OK so here are two more logistics questions

* if we asked for a fellow to help with Binder-related projects, where would this person be based? Would we be able to hire them through NumFocus? Or would they need to be based at one of our institutions?
* Does anybody immediately come to mind for this role? Do any of the core Binder team folks want this role?
  * If no, I think we have a lot of good potential people in the Discourse pages, GitHub issues, etc but it'll take a bit of a search and we should budget in that effort as well.

**Comment by betatim** [comment]
> where would this person be based? Would we be able to hire them through NumFocus? Or would they need to be based at one of our institutions?

From reading about the Django fellow: the fellow got hired as a contractor. I think that is a good idea we can/should copy. This means they can be based anywhere in the world (as long as they can generate an invoice that a US based entity can pay). I know Numfocus has paid contractors to work on nteract so that would work out as well. We don't have to deal with the admin overhead of an academic institute and their hiring policies.

We should check with the Outreachy interns how they got paid. I think they were also contractors for Outreachy, not employees of Outreachy.

For filling this role: we should open an application that people can respond to and review who applies. Before we open this call we should work on a (very) good job description with expectations, responsibilities, authority, etc. I'd start with what we can find in terms of Django fellowship and what other similar programs we can find.

Tough before all this: we need to write an application ;)

**Comment by choldgraf** [comment]
I'm happy to help the team brainstorm an application! Shall we spin that off into a separate issue?

Who is interested in making this part of their priorities for the next couple weeks? :-)
The proposal for CZI will be in mid-June I believe.

(I am happy to be one person to do so, with caveats that I have a few talks coming in the next 2 weeks that may suck away some time)

**Comment by choldgraf** [comment]
Hey all - it sounds like we have converged on at least one proposal here: The Binder (or JupyterHub) fellow. We've got an issue to discuss it here: #165 and I just opened up a template to start filling out the application here:

https://docs.google.com/document/d/1yZLJj1olp4AJOeigXHdZ6MqXYWkBceQONbIT0yWPH-E/edit?usp=sharing

**I think we have an opportunity to apply for more than one position**. This could either be as a part of this call, or we could plan to stagger them so we don't try to do too much at once. Would love thoughts from people on this one.

**Comment by betatim** [comment]
Two ideas for another position:

1. Binder evangelist. Someone whose job it is to travel the world (not just the US) to run workshops. They would have two kinds of workshop to offer: One about using Binder and getting feedback from (potential) users on what they need/like/are missing. One on contributing to Binder. They'd talks to high ups at educational and research institutions as well as companies to drum up support for "the Binder way" of sharing work as well as support for the Binder federation/project directly.

1. A UX person to help improve the user interface and experience. This isn't just a designer who produces ideas but should be weighted towards someone who can implement the ideas a designer might produce. A position with the main focus of making Binder easier, nicer, more pleasing to use. From how it looks, to how you flow through the application, to adding to the docs where people frequently stumble (after finding out where that is).

**Comment by choldgraf** [comment]
I've been thinking about this a little bit more, and I think that we should only apply for one position with CZI for now. I'm already a bit worried that we'll have challenges in oversight for this person (unless we find somebody unusually motivated) and doubling the capacity we need for oversight seems like a recipe for failure.

That doesn't mean we don't need more person-power, or that we shouldn't apply for one of the roles that @betatim suggests above (I actually think both of those would be extremely useful roles to have) just that I don't think now is the right time to do it because we are already spread quite thin.

The CZI grants will come in cycles of a few times a year, so we'll definitely have more opportunities to refine our ideas and put out new calls. What do folks think?

**Comment by betatim** [comment]
Sounds good to me. I think one position is a good way to start and gain experience.

Not sure which of the possible ideas is the best starter idea (I'd say which ever position requires the least oversight from our side is the best starter position?). I think we should also try and hire someone with experience contributing to and working with distributed teams/GitHub/open-source or find a way to predict that they'd be comfortable with such a setup.

Another thing I was wondering: should we ask for money for a in person workshop at the start and end of the grant?

ps. I promised to help, realistically reading, commenting, fixing parts is what I will manage before August starts. Writing large chunks of text from scratch is probably not going to happen :-(

**Comment by choldgraf** [comment]
Hey all, any chance that someone can take a look at this or give some general comments/edits? I can work on it a bit tomorrow but would be helpful if y’all thought we were moving in the right direction. If the general details of the position sound good, I think we should also think about the section on what support this person would have. We should make sure that we’re prepared to give this person the support they’d need to succeed in this position.

**Comment by betatim** [comment]
What do you have in mind in terms of "support"? Admin, mentoring, directing work?

I was thinking that we have had two "full time" people work on the project who were new (outreachy interns) and we can copy the support they got. Ideally we'd hire someone who has several years experience contributing to/working with open projects so we'd need even less support on that side.

I would assume the least amount of hassle on all sides is to receive the money via NF and have the person be a contractor. They send a monthly invoice, NF pays the invoice, done. For travel expenses I'd assume CZI sends a list of conditions (only US carriers, maximum daily amounts, etc) or we are free to set them ourselves (in which case -> use the standard NF rules around expenses as NF would be doing the admin so taking their rules will reduce the amount of BS involved).

I am all for giving support, but right now it is not clear to me what you have in mind which makes it hard to discuss :)

**Comment by choldgraf** [comment]
> What do you have in mind in terms of "support"? Admin, mentoring, directing work?

yep, basically mentoring and some oversight (especially at the beginning, probably would go down in need over time)

> I was thinking that we have had two "full time" people work on the project who were new (outreachy interns) and we can copy the support they got. 

I think that sounds reasonable too. Though we still needed to get a commitment of mentorship for each outreachy student ahead of time. I don't believe we have this from somebody for the CZI person. One thing we could do is ask for this grant to cover some % of one of the core devs time in order to assist with oversight of the person, that's what the scikit-learn folks are doing I believe.

> I would assume the least amount of hassle on all sides is to receive the money via NF and have the person be a contractor. 

For that it sounds good to me as well. One caveat is things like "who on the jupyterhub team is on the hook if something goes wrong with paperwork, numfocus is slow, etc. To me the minimal amount of support is "a person that can help direct the hire's work, get integrated with the community, assess the impact of this role over time, and oversee the NF/CZI/new hire relationship"

**Comment by choldgraf** [comment]
Hey all - THANK YOU to @betatim , @minrk , and @lheagy for giving their thoughts in the CZI application. A few updates:

* I spoke with Leah at NumFocus and she sent along a letter of support that we need to include in the CZI application (if we want NumFocus to be the org to run the grant through). It'd be a 15% overhead fee and they mentioned it's fine if we want to do a remote / international / etc position.
* We should determine a budget - we can ask for between $50 and $250K. I'll eyeball something and would love to hear what y'all think.

**Comment by betatim** [comment]
> budget

($100k for a 100% fellow + $30k for a 30% supervisor (if we do that) + $X for travel?) + 15% overhead? I am assuming the 100k as "base cost" and then adjusting all other numbers from it. I'd adjust the 100k based on what someone like Yuvi earns at Berkeley. We don't need to offer the same but I think as a "order of magnitude" thing that is where I'd aim. In Zurich we'd probably have to offer 120k for someone with experience. (Federal) Post docs in Swizterland make around 90k, rumour has it that the entry level salary at Google ZRH is around 120k + shares + perks + perks + perks for someone fresh out of undergrad. Not sure what the current post doc level salaries in the UK are, somewhere around GBP 35-40k??

> Posting on twitter

Do you think it is ready yet? It feels like it is still very much a draft which makes me wonder if it will be useful.

> Turing or not

I sent a DM to Kirstie but haven't heard back. Chris did you also contact her? If no I will try again.

What about the idea of working on federation? Could that be what the fellow does when they aren't supporting the community? Is it good to have two "jobs"?

**Comment by choldgraf** [comment]
re: budget, seems good to me.

re: twitter, I'm happy holding off for a bit. Andy's post was also for a draft, not the final thing.

re: federation and other features - IMO that's stuff we could (should) write another set of grants for. How about for this proposal, we include a section like "particular directions we'd like this person to help grow the project". That way we don't say "this person will build fancy new things that don't exist", but "this person will accelerate directions in which we're already heading"?

**Comment by betatim** [comment]
I agree with all the things you said.

**Comment by betatim** [comment]
This has been submitted so closing the issue.
