### ISSUE TITLE
Build a BinderHub workshop proposal EuroPython 2019

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#159]
Just before going on holiday last week I submitted a proposal for a three hour workshop at EuroPython 2019 in Basel. The topic was "Build your own BinderHub" so building on the zero2jupyterhub workshops but deploying binderhub instead.

Full text: https://hackmd.io/E0OzdBWZTuWz1BfjLivgWQ

This morning I got an email that the workshop is on the wait list/has been rejected. It isn't quite clear from the email as it doesn't have a sentence like "Your proposal has been ...." in it :-/

Where should we archive proposals like this so we can polish-reuse-resubmit them for other events?

**Comment by choldgraf** [comment]
ah that's a bummer :-/

maybe the jupyterhub team google drive? the one with all the talk materials etc in there?

**Comment by betatim** [comment]
Done!
