### ISSUE TITLE
June Team Meeting

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#160]
Hello everyone, 

The June meeting will be held on the *third* Thursday of the month.

That's **Thursday, June 20th, 2019** at 7AM UTC (or your [timezone](http://arewemeetingyet.com/UTC/2019-06-20/07:00/Jupyterhub%2FBinder%20team%20meeting)). 

* Discourse post [here](https://discourse.jupyter.org/t/jupyterhub-community-call-6-20/1167)
* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by Zsailer** [comment]
Note, this meeting is happening at our alternate meeting time.

**Comment by betatim** [comment]
*bump* this meeting is tomorrow morning Europe time.

**Comment by choldgraf** [comment]
hey folks - I won't be able to make this one since it'll be in the middle of the night, I added a couple of points in there for discussion, looking forward to hearing more about the meeting

**Comment by Zsailer** [comment]
Hey y'all, sorry for dropping the ball on this meeting. I'm moving this week, and things got a little behind on my to-do list. 

Like Chris, I'm on the west coast of the US and won't make it to this meeting. I'll make sure to post the meeting minutes in the morning. 

Thanks, everyone. Have a good time and see you next month!
