### ISSUE TITLE
mybinder.org's carbon footprint

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#162]
For various reasons I've been pondering where and how I use up resources (no prizes for guessing that flights are my personal poison). Recently chatted with someone who runs a data center in previously abandoned factory buildings using hydro.

Do we know if any of the GKE zones are powered by more or less CO2 neutral sources of power? If yes, can we afford to move?

**Comment by jhamman** [comment]
@betatim - my understanding is that Google is ahead of the curve on this one: https://cloud.google.com/sustainability/.

**Comment by betatim** [comment]
Nice! Should have googled that first :)

**Comment by consideRatio** [comment]
I'd love to dig down further on this!

@betatim have you seen [googles carbon footprint report of their datacenters](https://storage.googleapis.com/gweb-sustainability.appspot.com/pdf/24x7-carbon-free-energy-data-centers.pdf)? I really really appreciate google for not simplifying the picture way too much and instead doing a serious analysis about their data centers. While it may be tempting to say "Well we have only bought 100% renewable energy" i think it is [a too simple way out](https://www.youtube.com/watch?v=xW-VLPyxqAM).

Also!!! Check out electricitymap.org as well. While this webpage is largely based on open source software, they provide an API we could perhaps pay 50 EUR / Month for to get info about an electricity zone where our datacenter reside. Then we could write a script and make a report that would estimate our emissions very well do make similar reports like Google have done in their report.

/cc: @corradi who has founded electricitymap.org ! :heart:

**Comment by choldgraf** [comment]
I think that the conversation around energy use when running a service like mybinder.org is both interesting and important. If this will be more of an ongoing conversation, do you think we could have that conversation over in the mybinder.org discourse page? If this issue is going to result in a specific change to documentation / blog post / etc then I think it's fine keeping it here, just trying to keep the GitHub issues for "closeable" topics.

**Comment by betatim** [comment]
From browsing all the linked docs my impression is that there is nothing we can do to change the source of the energy that powers mybinder.org by moving from one GCE zone to another. This means there is nothing for us to do, we should do what Chris suggests and move this to discourse if we want to continue chatting about it.
