### ISSUE TITLE
CZI OS application: The Binder/JupyterHub Fellow

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#165]
Hey all - in #156 we discussed hiring a "Binder fellow" via an application to CZI for funding. To get the ball rolling, I started out a document to brainstorm the details around this position. If we can narrow down to something specific then I think it should be straightforward to make a pitch to CZI:

https://docs.google.com/document/d/1zN3JCdoMvCp2xZHvtwur5fuhFeD2DEu_UpmQu7k4tAs/edit#

cc @betatim who mentioned he'd be interested to help with this, though it would be **wonderful** of other folks on the team pitched in as well

**Comment by choldgraf** [comment]
Hey all - in the google doc above, @minrk suggested that we call this a "JupyterHub Fellow" rather than a "Binder fellow" with the idea that JupyterHub is a more generic project and that BinderHub/repo2docker may be too narrow for someone's full-time job.

What do folks think about that? General +1? 

I think it sounds reasonable to me, and I agree that JupyterHub often gets overlooked because the focus is on derivatives of JupyterHub (e.g. z2jh, tljh, binderhub, etc). It would be good to have somebody that spans both of those worlds. So I think I'm +1 on this.

**Comment by choldgraf** [comment]
I took a look through the CZI application, and outlined the major sections that we need to fill out in this Google Doc:

https://docs.google.com/document/d/1yZLJj1olp4AJOeigXHdZ6MqXYWkBceQONbIT0yWPH-E/edit?usp=sharing

Can we collaboratively work on this one to fill out a vision/plan for what we'd use the funding for? It's just a shell right now and I can work on it in the coming weeks, but first I have to prioritize the Binder report for Moore finalized (hopefully filling that out will help us write this one up more easily anyway).

**Comment by choldgraf** [comment]
Hey all, I took some time to fill in some of the proposal in the Google Doc linked above (and here)

https://docs.google.com/document/d/1yZLJj1olp4AJOeigXHdZ6MqXYWkBceQONbIT0yWPH-E/edit#heading=h.x107od81xw1h

Would love to know what folks think (cc @betatim who mentioned he might have time to take a look)

**Comment by choldgraf** [comment]
A question for folks: who would be interested in some kind of "PI" or "co-PI" status for this grant? AKA, who is willing to be co-responsible for the oversight and execution of the stuff we say we're gonna do here?

I am happy to be a co-I...I'm not sure if I'm allowed to be a PI or not but if I am then I'm happy to be a co-PI as well.

**Comment by minrk** [comment]
I’m happy to be co-PI if it helps, though none of the funds would be coming here so maybe that’s weird. @choldgraf has done most of the legwork here, so I think you’re a good choice. Would you be able to spend the oversight funds on yourself?

**Comment by choldgraf** [comment]
Hey all - three quick points for the team.

1. Just a reminder that **this is due August 1st at 5:00pm California time**.
2. I've added another doc for **budget** at [this link](https://docs.google.com/document/d/1QdMIOy9dt05ecR_JCwqzreG5WwZpGw_6i_6jC-4NwAY/edit#). **Can people help fill it in?**
3. I think we should beef up our statements about the impact of JupyterHub and Binder. What metrics, stories, etc can we add in there? Please add edits etc to the text!

Chris

**Comment by choldgraf** [comment]
Hey all, I am planning to post a PDF of this grant to the internet and share a link tomorrow, let me know if anybody thinks that is not a good idea for some reason

**Comment by choldgraf** [comment]
Hey all - note that **I will plan to submit this proposal tomorrow (July 30th)** (assuming that we get clarity on the sub-contracting question). Please get in your comments, edits, etc before then!

I know it's a day early, but I have learned not to _plan_ on submitting during the due date. You never know what will come up when you submit.

**Comment by betatim** [comment]
Ill read through the docs again today. Do you have a definitive list of all the docs (in the right versions) for lazy readers/making sure nothing gets missed?

**Comment by choldgraf** [comment]
@betatim I believe that the sub-sections of the main document we've been working are all that we need. I went through the CZI application and copy/pasted the headers for the sections they wanted information for

**Comment by choldgraf** [comment]
Ah I noticed there are two sections for a 200 word summary of any major projects that are associated with the proposal. I was planning to include JupyterHub and Binder as the two projects. I've added a section to the proposal with these 200 word descriptions, would love feedback on that:

https://docs.google.com/document/d/1yZLJj1olp4AJOeigXHdZ6MqXYWkBceQONbIT0yWPH-E/edit#heading=h.ofvfti9ilpr3

**Comment by choldgraf** [comment]
Ah and one final question about metrics for impact. In general there are a few questions like "how many users", "how many citations", etc. I'm trying to think of good ways to quantify and answer those questions:

## Metrics to show impact

https://docs.google.com/document/d/1yZLJj1olp4AJOeigXHdZ6MqXYWkBceQONbIT0yWPH-E/edit#heading=h.4l2svyyp8b01

**Comment by choldgraf** [comment]
Alright y'all, I think we have almost all of the information needed in place, **though please see the above-two comments for ways you can help us push this past the finish line**

I will wake up tomorrow morning and submit this at 9am California time with whatever is the current state of materials.

**Comment by minrk** [comment]
I did edits on the summaries and KPIs, and filled in some of the project metrics from GitHub, PyPI, and Docker Hub.

**Comment by choldgraf** [comment]
These edits look great! Thanks for the added stats about the repositories etc.

I think that it all looks to be in good shape to me. **Can I get some thumbs-ups that folks are +1 on submitting**? In particular @minrk @betatim and @lheagy who have made edits to the document in the last 12 hours?

**Comment by choldgraf** [comment]
Hi all - here is the final PDF that we will submit. It includes everything (the proposal is at the very end).

[proposal.pdf](https://github.com/jupyterhub/team-compass/files/3458384/download__67D8g7mrNdkP5sfSTGmKFb9MW5hHk5.pdf)

**I will submit this PDF in 30 minutes!** Speak now or forever hold your peace (at least until the next grant proposal :-) )

**Comment by betatim** [comment]
👍

**Comment by choldgraf** [comment]
application submitted!

![image](https://user-images.githubusercontent.com/1839645/62328111-15177200-b467-11e9-9810-177c05e73468.png)

thanks everybody for all of the hard work in polishing this up! I'm hopeful about this one, and if it doesn't come through we have great material that we can use to try and get funded from somewhere else!

**Comment by betatim** [comment]
Thank you for writing 99% of this and keeping your foot on the gas pedal!!

What grant to apply for next? :D

**Comment by minrk** [comment]
Thanks for taking the lead on this one! You did a great job. 


Let’s add to the agenda for the September team meeting ideas for the next round so that maybe we can get ready a little earlier in the process.
