### ISSUE TITLE
Onboarding @sgibson91

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#168]
This is an onboarding checklist for @sgibson91 . Checklist was made from synthesizing discussions we had at the team meeting and in a few issues. See #167 for a PR that adds this to our docs.

**Things the new team member needs**
- [x] A gmail account (for GKE credentials + Google team drive)
- [x] A [PyPI account](https://pypi.org) (for PyPI access)
- [x] A [Discourse account](https://discourse.jupyter.org)

**Membership**

- [x] Add them to the [binderhub google group](https://groups.google.com/forum/#!forum/binderhub-dev)
- [x] Add them to the [binderhub team in the github organization](https://github.com/orgs/jupyterhub/teams/binder-team)
- [x] Add them to the [Discourse jupyterhub group](https://discourse.jupyter.org/g/jupyterhub-team)

**Permissions**

- [x] Make sure they have permissions on the [google cloud projects](https://console.cloud.google.com/home/dashboard?project=binder-prod)
      (binder-prod, binder-staging, binder-sandbox)
- [x] Add them as collaborators on the repo2docker and BinderHub PyPI packages
- [x] Add them to the [jupyterhub team google drive](https://drive.google.com/drive/folders/0B8VZ4vaOYWZ3a2dyeEp6NzBKbnM?usp=sharing)

**Learning**

- [x] Send them [a short onboarding message](https://jupyterhub-team-compass.readthedocs.io/team/adding-members.html#an-official-onboarding-message)

**Community**

- [x] Add them to the [jupyterhub or binderhub team yaml files](https://github.com/jupyterhub/team-compass/tree/5d014f3af161e3abcf79c7adfb77620607929d77/docs/team)
- [x] Tell people in Discourse + Twitter about our awesome new community member

**Comment by consideRatio** [comment]
You are doing so much that ties it all together @choldgraf!! :heart:

**Comment by betatim** [comment]
Time to wrap this up by telling the world?

**Comment by choldgraf** [comment]
It's on my list for this week, got caught up in workshops all of last week :-)

**Comment by choldgraf** [comment]
OK, boxes are checked! Here's a welcome post in Discourse:

https://discourse.jupyter.org/t/welcoming-our-new-jupyterhub-team-member-sarah/1416

and a tweet:

https://twitter.com/choldgraf/status/1141411186077921280

y'all should say hi to Sarah :-)

**Comment by choldgraf** [comment]
gonna close this one now - thanks for everybody's feedback and comments/edits on the checklist!

**Comment by sgibson91** [comment]
I promise, one day soon I will get Twitter 😁
