### ISSUE TITLE
Review Request: BinderHub chapter in the Turing Way

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#169]
Hi all! :wave:

As you may be aware, I came into the Binder-sphere via the [Turing Way](https://github.com/alan-turing-institute/the-turing-way) project at the Alan Turing Institute. At our London book dash (which was crazy fun and attended by an _amazing_ illustrator who created images like [this](https://discourse.jupyter.org/t/hub-illustrations/1211)!), I wrote up a chapter on BinderHub, how it works and why someone may want to deploy their own. I'd be very grateful if anyone who has the time could review the chapter and verify that what I've written is appropriate.

https://github.com/alan-turing-institute/the-turing-way/pull/557

Binder itself has already been discussed in [this section](https://the-turing-way.netlify.com/reproducible_environments/reproducible_environments.html#Binder_section) of the Turing Way handbook.

Many thanks! 🎉

**Comment by choldgraf** [comment]
This is actually quite timely, as I'll use these materials for the workshop at UW next week, so I'll try and get in a review after then once I've got more familiarity with the materials. That work?

**Comment by sgibson91** [comment]
That's great, thank you!

**Comment by sgibson91** [comment]
Hey @choldgraf, do you still want to review this or shall I go ahead and merge? 🙂

**Comment by choldgraf** [comment]
heya - I can try to put some cycles into this but am slammed right now! If you're willing to hold off a bit then I can look through it later, but for now am prepping for a talk tomorrow

**Comment by sgibson91** [comment]
Np 🙂

**Comment by sgibson91** [comment]
Thank you for your feedback, the chapter is now live! https://the-turing-way.netlify.com/binderhub/binderhub.html
