### ISSUE TITLE
Binder federation blog post

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#171]
This is a dedicated thread to track the progress and to dos for the "Binder federation" blog post.

Started in https://github.com/jupyterhub/mybinder.org-deploy/issues/1021#issuecomment-501852191

Draft: https://blog.jupyter.org/announcing-the-international-federation-of-binderhubs-4f6235c1537e

**Comment by betatim** [comment]
I think the two clusters are running well so from the side we should go ahead and announce it.

* We need a world map with the two hubs drawn on
* We need another editing pass

What else do we want to get done before hitting publish?

**Comment by mael-le-gal** [comment]
For the OVH Blogpost, here is the draft that I write : 

https://hackmd.io/GusJ9SRwQuuyK02acG2ikg

@choldgraf I admit, I copied some of your figures for my introduction :) (as well as the `How does it work` part)

Don't hesitate to annotate if you want

**Comment by choldgraf** [comment]
@mael-le-gal you are welcome to copy whatever I put out there :-)

I'll take a look at your draft this week!

**Comment by mael-le-gal** [comment]
On our side we will probably publish the blog post on Friday.

**Comment by choldgraf** [comment]
My 2 cents are that I'd feel better about publishing these blog posts widely once we are sure there aren't any persistent bugs or inefficiencies in the OVH cluster. I've noticed that it hiccups a fair bit more than the GKE cluster despite having much less traffic:

week so far, successful % launches,
GKE:
![image](https://user-images.githubusercontent.com/1839645/60192544-db5da680-97ea-11e9-8226-83a8d50b1e2d.png)


OVH:
![image](https://user-images.githubusercontent.com/1839645/60192585-eb758600-97ea-11e9-8b01-dc5d4793808f.png)

How do other folks feel about this? I am itching to publicize the OVH cluster, so I can probably be persuaded to post these regardless, but I'm also a bit worried about upping the traffic or attention before we're sure the setup is rock-solid

**Comment by betatim** [comment]
I've not spent a huge amount of time investigating but my feeling is that the majority of OVH launch failures are related to docker registry trouble. This is going to be addressed in https://github.com/jupyterhub/mybinder.org-deploy/pull/1054. Let's see how that goes.

From my side 15% or more of the traffic to OVH is "a significant chunk" we've been running at this for a while and with an improved registry we should be able to up it as there is spare capacity in the terms of CPU/RAM.

From the experience of setting up the cluster on GKE I think it will take us months to get to as smooth and hands off running as we have for the GKE cluster now. Mostly because once you start fixing all the fast leaks you then only have small leaks left .. and by definition it takes a long time before you notice those :) I don't think we should wait that long.

I assume everyone is fine saying in public that this is (obviously and like all of mybinder.org) a work in progress, significant step up in complexity, successful collaboration and the first time anyone has tried this.

**Comment by choldgraf** [comment]
if we're fine mentioning these caveats (I can put them in our blog post anyway) then I'm +1 on posting

**Comment by betatim** [comment]
Fine by me. Though I think we shouldn't label them caveats because "successful collaboration" isn't a caveat it is a feature :) So I'd mention how well things are working and then use our standard "As always we are pushing this out as soon as we think it is useful, help us to scale it and make it rock solid by reporting things you notice."

**Comment by choldgraf** [comment]
Hey all - I moved the blog post to our medium account, made some edits per comments that were in there, and also added in some of the language we described above:

https://medium.com/p/4f6235c1537e/edit

I think it is close to ready to go! Shall we try to coordinate a release w/ the OVH team?

**Comment by betatim** [comment]
Let's use this thread as the single source of truth for posting or not. In particular currently no traffic is being sent to OVH because we had a problem with the new docker registry being down yesterday evening. I see three options: delay posting, diagnose&fix registry problem, switch back to old registry setup. In the last two cases we should go ahead and post today.

My order of preference would be: "diagnose&fix", "switch to old", "delay posting".

**Comment by mael-le-gal** [comment]
On our side, the blog post is going through the validation process but I ask them to synchronize with me and delay a little bit the release until we understand what happened with the registry.

**Comment by betatim** [comment]
@choldgraf I made some edits and added one question to the binder blog post on medium. Please take a look on content and how it flows.

**Comment by mael-le-gal** [comment]
I copy here what I just write on the gitter : 

The registry service is also hosted above kubernetes.
Yesterday an upgrade was done on the k8s version and this is this upgrade that was responsible for our registry pod to shutdown and restart.
We're still investigating to understand why exactly that happened.

The thing is : this is not the binder usage that cause the registry to shutdown.

**Comment by betatim** [comment]
See https://github.com/jupyterhub/mybinder.org-deploy/pull/1063. We are now at 5% traffic.

**Comment by betatim** [comment]
Should we post or wait till Monday? My feeling is that it is already 4pm in Europe so we should wait because people are leaving for the weekend.

**Comment by minrk** [comment]
Good idea to wait until Monday. If folks are happy with the post we can schedule it to auto-post on Monday so *we* can be done with it today. Lots of news on Friday gets lost. Especially with three world cup games this weekend ⚽️ 🏃‍♀ !

**Comment by choldgraf** [comment]
This all sounds good to me - @betatim feel free to update the "unique binder repo" statistic in there, and I'm +1 on publishing Monday

**Comment by betatim** [comment]
I'll take care of the scheduling. Was thinking of us people being away from our computers more than the readers being away which makes it tricky to decide anything.

Happy weekending!

**Comment by baaastijn** [comment]
Hi there, as seen together it's D-day. Done on OVH side :)
https://www.ovh.com/fr/blog/mybinder-and-ovh-partnership/ 

have a good day all

**Comment by mael-le-gal** [comment]
As said in the last part of the blog post : thanks to everyone in here for making this happen ! You rock 🎉

**Comment by betatim** [comment]
Yay! Thanks for  your hard work as well!

https://blog.jupyter.org/the-international-binder-federation-4f6235c1537e is the post on the Jupyter blog.

(Happy heat wave from Zurich)

**Comment by betatim** [comment]
The posts have been posted, closing this issue!

**Comment by choldgraf** [comment]
way to go everybody! One last piece of information, here's the link from us that y'all should retweet etc :-)

https://twitter.com/mybinderteam/status/1145667618734530560
