### ISSUE TITLE
Blog post: Zenodo integration

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#172]
Here's the beginning of a blog post to show how people can create a DOI of a repository on Zenodo and then create a Binder link that points to it:

https://hackmd.io/IZ4JjvVARNSocv0Z8L9cCw?both

It's still a WIP, so feel free to add new content, edits, etc.

**Comment by betatim** [comment]
I left a few comments and made a few edits.

I think if we can iterate once or twice on the comments I made I'd be happy for it to go out after that. Speed is our friend :)

**Comment by choldgraf** [comment]
OK, I resolved both comments, thanks for those!

I agreed on both of them - I removed the note about "verify" (I couldn't find a way to create a call-out in the Medium UI) and instead added a note that users should try to run their analyses in the built binder to make sure they work.

For the GitHub zenodo guide, I removed most of that section, and instead added a note to follow that guide because I agree it's a lot better than I can do in just a couple paragraphs :-)

**Comment by betatim** [comment]
LGTM. Let's let it stew and ripen a bit and then publish it.

**Comment by yuvipanda** [comment]
This looks great. The only suggestion I have is to suggest the UI on mybinder.org to form link rather than ask people to construct links by hand.

**Comment by betatim** [comment]
I made an edit that implements @yuvipanda's suggestion. It uses the GIF I recorded a while back.

**Comment by choldgraf** [comment]
Good suggestion!

I'm happy with where the post is right now, shall we post Friday morning California time?

**Comment by betatim** [comment]
The draft (https://medium.com/p/af68ed6648a6/edit) is empty?

**Comment by choldgraf** [comment]
oops, maybe it didn't save, putting it there now

**Comment by betatim** [comment]
Can we change the title? "Zenodo + Binder" or "When Binder met Zenodo" or "When Zenodo met Binder" or some such?

I'd move the current title to be the first sentence of whole post.

**Comment by yuvipanda** [comment]
I dig it! @choldgraf do you wanna post it friday morning or monday morning?

**Comment by betatim** [comment]
Friday morning california time.

**Comment by yuvipanda** [comment]
Is that a good time to post? It's friday evening europe time. Wouldn't monday morning california time (or monday morning europe time) be better?

**Comment by betatim** [comment]
I'd probably define California morning as Friday 3-4pm Europe time.

Not sure it matters much when you post really if you don't plan on playing the social media hype game. If it is good and interesting it will get picked up by others and if not it won't 🤷‍♂️.

**Comment by yuvipanda** [comment]
I'd suggest waiting until Monday morning california time to post unless there's a strong reason to not :) We can schedule it to post at that time too...

**Comment by betatim** [comment]
Be my guest. It would be interesting to see some data for Jupyter blog posts. Most of the traffic comes from external sources like twitter and email so who promotes it and when they promote it seems more important than when it is actually posted.

**Comment by choldgraf** [comment]
@yuvipanda the reason I was suggesting Friday morning is because:

1. I think it's better to post when readership is generally awake (so ruling out today)
2. I'm giving a talk about reproducibility and Binder tomorrow afternoon and wanted to mention this :-)

**Comment by choldgraf** [comment]
but if y'all would prefer Monday, that's fine w/ me - I can just share a copy of the draft w/ folks at the talk

**Comment by yuvipanda** [comment]
I agree on all points! However, if we can do small things that increase chances of people who aren't already in the community coming across it, we should. In this case,  it is a delay over a weekend...

I've now scheduled it to post on Monday 9AM PST. It looks good to me.

**Comment by yuvipanda** [comment]
@choldgraf ah, reason 2 is good enough for me :) I've scheduled it instead for tomorrow 9AM instead.

**Comment by betatim** [comment]
I moved it forward by a few hours so that people in Europe aren't already at home when it gets published and made a mybinderteam tweet for it (for your retweeting pleasure).

**Comment by yuvipanda** [comment]
Thanks, @betatim

**Comment by choldgraf** [comment]
now published! yay https://blog.jupyter.org/binder-with-zenodo-af68ed6648a6
