### ISSUE TITLE
Blog post: Diving into Leadership to Build Push-Button Code

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#176]
Hi all,

I've been writing up a blog post about the sprint at which I developed the deploy button. (I also like that it has become somewhat common place to prefix this with "the amazing" 😂)

https://hackmd.io/Yvql5JL7R6ukR3dfjh6Q8A?view#Diving-into-Leadership-to-Build-Push-Button-Code

I initially wrote this to go on the Turing's blog which is public, but I have no issue with cross-posting if you'd like 🙂

**Comment by betatim** [comment]
I like it!

I have no opinion on cross-posting or not. We should definitely tweet about it from @mybinderteam though :)

**Comment by sgibson91** [comment]
I will definitely share the link when we publish 🙂

**Comment by choldgraf** [comment]
this is great! thanks for the post :-)

one thought: we could try something like this for another JupyterHub tool (I've thought that a "the littlest jupyterhub" button would be pretty easy to do and quite nice). Maybe if such a button were created, we could write a post for the jupyter blog that mentions *both* of these? That way it's not quite duplicating the content but still draws attention to both tools?

**Comment by sgibson91** [comment]
@choldgraf That's a nice idea, though I guess my original hope for this post is that it would encourage more women to join in or lead hackathons by talking about how fun this particular sprint was for me

**Comment by betatim** [comment]
I like that it tells a personal story. Makes it different from "the usual" blog posts. Maybe if/when someone makes a TLJH or BinderHub on GKE button we can make a new post that talks about all of them.

I have no opinion on cross-posting the exact same post. I'd do it because I'd assume more people would end up reading it. But I'd also post at 10am European time because I don't pay attention to good times for posting things (aka Tim's social media influencer skills are low ;)).

**Comment by choldgraf** [comment]
@sgibson91 I must admin, I had not yet read the draft of your post 🤦🏻‍♂️ so I assumed it was a very "feature release" kind of post. I just took a pass through the draft and I really like how personal the story is - I was mistaken in my assumptions about what kind of post it was :-)  I'm +1 on cross-posting (actually, this reminds me a bit of some old blog posts that were run on the jupyter blog back in the day that were more about the jupyter devs themselves)

**Comment by choldgraf** [comment]
Another thought: I'd keep the title that's in the draft, rather than the one that you added to this post. The reason I thought it was a pure tech post was because of the title of this issue :-)

**Comment by choldgraf** [comment]
hey all - if I recall this was very nearly ready to go already, @sgibson91 what do you think? Does Turing has a date that they plan to post it? If so, we can try to co-ordinate with the jupyter blog?

**Comment by sgibson91** [comment]
I got a lot of feedback from the Turing group that I'm still working through (I'll update the hackmd with the most recent changes). I'm still unsure as to the process of publishing, I think it just gets posted when it's done?

**Comment by choldgraf** [comment]
@sgibson91 wanna just ping this issue once you're ready to talk about when to post on the jupyter blog then? There's no hurry from our end, let us know what works for you!

**Comment by sgibson91** [comment]
@choldgraf Will do!

**Comment by sgibson91** [comment]
Sorry this has taken so long, but this is finally ready to be posted!! :tada: I've set up a Medium account with my gmail address.

**Comment by sgibson91** [comment]
Sent the email anyway 😂

**Comment by sgibson91** [comment]
Does Markdown work on Medium?

**Comment by choldgraf** [comment]
mmmm nope :-(

But, usually if you render the markdown and then copy/paste, it works pretty well. Wanna give that a shot?

**Comment by sgibson91** [comment]
Oooh, thanks! I think its just links and things I need to tidy up

**Comment by sgibson91** [comment]
Sent!

**Comment by sgibson91** [comment]
FYI, the reason I got this ready now as I need to submit writing examples for the SSI Fellowship (#208) so it would really be beneficial for me for this to be published before the 23rd so I can submit the link with my application 😄Thanks!

**Comment by sgibson91** [comment]
Thank you @choldgraf!

**Comment by choldgraf** [comment]
Hey @sgibson91 - I took a pass through the text and cleaned up a few small things here and there.

In general I really appreciated the perspective that you bring to the post, and the vulnerability that you are willing to expose in starting out on your own leadership journey :-) 

I didn't want to change anything major because I want this piece to be in your own voice and style - it was mostly just minor wording choices etc. I left in a few comments, and also added in section headers to help organize the flow of the article a bit.

Wanna take a look and let me know what you think?

**Comment by choldgraf** [comment]
woot! let me know if you're +1 on posting the draft, and if so, a time when you'd like it posted!

**Comment by sgibson91** [comment]
I'm definitely +1 on posting. I'll be recording the presentation for SSI on the 17th so I'll be putting the rest of the application together after I get that sorted. So 17th-23rd is a good window.

**Comment by choldgraf** [comment]
ok, let's plan to revisit this issue on the 17th then?

**Comment by sgibson91** [comment]
Blog is live on the Turing website! https://www.turing.ac.uk/research/research-programmes/research-engineering/programme-articles/diving-leadership-build-push-button-code

**Comment by choldgraf** [comment]
woot! want me to post it now? I'll cross-link it to the Turing blog

**Comment by sgibson91** [comment]
That'll be great, thanks 😄

**Comment by choldgraf** [comment]
https://blog.jupyter.org/diving-into-leadership-to-build-push-button-code-df2a075c9914 there ya go! :-)

**Comment by sgibson91** [comment]
Thank you! :sparkling_heart:

**Comment by choldgraf** [comment]
thanks @sgibson91 for sharing your story!
