### ISSUE TITLE
Create a Binder GH team?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#18]
Sometimes I wanna ping all the BinderHub team members in an issue, maybe it'd be easier if we created an actual GitHub "Binder Team" to make this easier. All the members could match those listed on the `team-compass` repo. Thoughts?

**Comment by willingc** [comment]
Looks like there already is a binder team in the jupyterhub org, and you're the only member at the moment. Makes sense to add everyone. Thanks @choldgraf

**Comment by choldgraf** [comment]
I just added it this morning, then thought to open this issue before going
further :-)

**Comment by willingc** [comment]
Closing as this is now done ;-)
