### ISSUE TITLE
Some thoughts on the SRE guidelines: Upgrading k8s

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#180]
This issue is relating to the [Upgrading Kubernetes section](https://mybinder-sre.readthedocs.io/en/latest/command_snippets.html#upgrading-kubernetes) of the guidelines and is just a collection of my thoughts after performing my first upgrade of the GKE cluster 🙂 

- [x] We should include the snippet `gcloud container clusters get-credentials <CLUSTER-NAME> --zone us-central1-a` at the top of these docs so the correct `kubectl` context is merged and made current for the following snippets. (Addressed in commit [`
5fe89f8`](https://github.com/jupyterhub/mybinder.org-deploy/pull/1069/commits/5fe89f84f1bde7af28f7fa22432f7ab23fd188f5) in PR https://github.com/jupyterhub/mybinder.org-deploy/pull/1069)

- [x] I think the `gcloud` CLI structure has changed as some of the commands I ran raised an error as they required a `zone` or `region` argument. This was not difficult to figure out but would make the docs a bit more copy-pastable. (Addressed in commit [`
67e58bd`](https://github.com/jupyterhub/mybinder.org-deploy/pull/1069/commits/67e58bd2c091e4c1b1f11c1363ec8d584d0c679b) in PR https://github.com/jupyterhub/mybinder.org-deploy/pull/1069)

- [x] `old_pool=default-pool` and `new_pool=standard-4` are listed as current and incoming nodepool names (in the upgrading staging section, a similar issue is carried forward to the prod section), but we actually follow the convention of labelling the pools with the k8s version as follows: `1dot12dot8` for k8s v 1.12.8 (prefixed by `core-` or `user-` on the production cluster, but not on staging). That convention could be a bit clearer, though I know it's difficult to give a persistent suggestion for a new node pool name when we don't know in advance which version we're upgrading to.

- [x] "_To avoid new nodes being allocated in the old pool, set the autoscaling upper limit to 1 on the old pool, or disable autoscaling on the old pool. This can only be done via the cloud console at this time._"

  Some screenshots or a GIF would be nice to illustrate how to do this. (@betatim sent me some over gitter)

- [x] "_After the new nodes have had a chance to warm up (check cluster utilization and user pods metrics in grafana, around 10 minutes should be fine), we can cordon the rest of the old pool._"

  I think it would be nice to hyperlink to these grafana charts, simply because if you're concentrating on the upgrade, you may not have the remaining brain capacity to remember the layout of grafana. Also, the OVH cluster on there may add some additional confusion 🙂 (related: https://github.com/jupyterhub/team-compass/issues/182)

Generally, I think the guidelines are good and descriptive. I think filling out the prod section to be a complete list of commands like the staging section would be helpful. While this would mean repeating snippets (like the `kubectl drain` command), it would mean the operator wouldn't have to scroll back through the docs and/or terminal history in order to find the command again.

**Comment by choldgraf** [comment]
This is excellent! Thanks for sharing your thoughts - in general I'm +1 on most of the above if you wanna make a PR for the "straightforward" stuff (happy to review). We should probably discuss as a team whether we wanna change node naming standards, though your proposal seems reasonable to me I agree.

re: your points about Grafana, maybe we should have a little section with links to lots of grafana dashboards and a rough explanation of what each one is

**Comment by sgibson91** [comment]
> re: your points about Grafana, maybe we should have a little section with links to lots of grafana dashboards and a rough explanation of what each one is

+1 on this idea!

**Comment by sgibson91** [comment]
Where are these docs built from?

**Comment by betatim** [comment]
Source of the docs lives here: https://github.com/jupyterhub/mybinder.org-deploy/tree/master/docs/source

RE node pool naming: we used to pick names "at random", usually related to the function of the pool and what was being changed (e.g. `user-pool-highmem` when we switched to highmem node type). At some point I ran out of ideas and started using the function (user or core) and the GKE version as names. `dot` is spelt out because I wasn't sure if you could use `.` or not. We could roll through https://en.wikipedia.org/wiki/NATO_phonetic_alphabet which might make it easier to write the docs so they aren't always out of date and can cope with node pool replacements that aren't linked to GKE version changes.

**Comment by minrk** [comment]
All excellent points! Like @betatim said, we don't actually have a convention for node pool names other than the `core-` and `user-` prefixes. I'd rather have just 'core' and 'user' since the node v, but of course we have to have at least two names to be concurrent while we do an upgrade. But it would be super nice to not have to think about it. Maybe we should just use the date, e.g.

```bash
new_pool=users-$(date +"%Y%m%d")
```

which would result in `users-20190702` today?

Another possibly useful snippet for getting the current node pools:

```bash
> gcloud container node-pools list --cluster prod-a --project=binder-prod
NAME             MACHINE_TYPE  DISK_SIZE_GB  NODE_VERSION
user-1dot12dot8  n1-highmem-8  1000          1.12.8-gke.10
core-1dot12dot8  n1-highmem-4  250           1.12.8-gke.10
```

Or if you want to get fancy and *fully* automatic, get the current user pool:

```bash
> old_user_pool=$(gcloud container node-pools list --cluster prod-a --project=binder-prod --format json | jq -r '.[].name' | grep '^user')
> echo $old_user_pool
user-1dot12dot8
```

**Comment by sgibson91** [comment]
Thanks @minrk those look super helpful!

My current plan for the open PR is to do the first and second point, potentially the third, and then merge. Once we reach a consensus on a naming convention, I can make a PR for that. And then I was thinking of making a new issue to collect people's descriptions of their favourite grafana plots in order to address the last point.

**Comment by betatim** [comment]
I like the idea of using the date because it means one less page to open and figure stuff out :) It is super rare for us to switch node pools twice in a day so we shouldn't worry about that.

**Comment by sgibson91** [comment]
Date sounds sensible to me too. It'll also serve as a reminder of when the last upgrade was!

**Comment by betatim** [comment]
For point four:

![Kapture 2019-07-03 at 7 15 49](https://user-images.githubusercontent.com/1448859/60565229-115ad780-9d63-11e9-9a6c-3f57623d976f.gif)


A GIF showing where to change the maximum number of nodes in a node pool (they changed the UI recently!)

**Comment by sgibson91** [comment]
Thanks @betatim, I've included that and I think the PR is ready to merge

**Comment by sgibson91** [comment]
A PR addressing point 5 is available [here](https://github.com/jupyterhub/mybinder.org-deploy/pull/1074)

**Comment by sgibson91** [comment]
Sorry I kinda forgot about this issue, but Hacktoberfest is a great excuse to finish it off! https://github.com/jupyterhub/mybinder.org-deploy/pull/1184
