### ISSUE TITLE
Blog post: the henchbot!

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#184]
@henchc has a nice draft of a post to talk about our henchbot, which helps us auto-deploy updates to BinderHub/repo2docker to mybinder.org, here's a draft:

https://discourse.jupyter.org/t/draft-for-blog-post-on-mybinder-org-repo2docker-and-binderhub-upgrade-bot/1455/3

It seems to be in a nearly-ready-to-go state, so we should give some feedback and post soon!

**Comment by betatim** [comment]
Which version should we read?

And we should post it. "Henchbot has changed my life" (if you are collecting testimonials)

**Comment by henchc** [comment]
It should all be in the hackmd [link](https://hackmd.io/qC4ooA5TTn6xA2w-2OLHbA) now, I've swapped it out on the discourse too so there's just one ground truth.

**Comment by betatim** [comment]
Looks good to me, only idea is to add a screenshot of a PR the bot made

**Comment by sgibson91** [comment]
My only comment is that for someone who's using your blog post as a blueprint to building their own bot (i.e. me!), the part about generating a personal access token isn't super clear. It took me a while to realise that henchbot is a GitHub user account, not an organisation, and I should be creating the PAT from my bot's own account, not _my_ account.

Other than that, it's brilliant and I've learned how to automatically clone a repo today! 🎉

**Comment by henchc** [comment]
Thanks, everyone! I've updated the post with all the feedback :)

**Comment by betatim** [comment]
Do you have the rights to add it to blog.jupyter.org? If yes I think we should add it as a draft and then consult our social media consultants (Chris and Yuvi) about when the best time is to post ;)

**Comment by henchc** [comment]
No, I do not

**Comment by betatim** [comment]
I think we might need @choldgraf or @minrk to hook you up as an author on the blog so that you can post with your medium account. I don't seem to have enough rights to add people.

**Comment by choldgraf** [comment]
Hey all - @henchc now has a jupyter blog account, and here is the latest version of this blog post submitted to medium:

https://medium.com/p/bb5e38542059/edit

I took a pass through and made a few edits, and I'm +1 on posting this. Anybody else have objections?

What date should we shoot for?

**Comment by minrk** [comment]
Looks great! Made a couple of small edits, but hapy for this to go up any time.

**Comment by betatim** [comment]
Looks nice. I give more votes to dates that are closer than dates further in the future ;)

**Comment by choldgraf** [comment]
@henchc is this ready to go when you are? If so then I propose two times to post:

1. Tomorrow morning (2019-07-17)
2. 7000 years in the future on Thursday (9019/07/18)

If folks want to note their preferences, or a third date that is not listed, please do!

**Comment by minrk** [comment]
I vote 1!

**Comment by henchc** [comment]
I'm good with 1!

**Comment by choldgraf** [comment]
It's up! https://blog.jupyter.org/automating-mybinder-org-dependency-upgrades-in-10-steps-bb5e38542059

fire up yer twitterz :-)

**Comment by minrk** [comment]
Blog posted!
