### ISSUE TITLE
JupyterHub on Hadoop repos

### ISSUE THREAD

**Issue by jcrist** [jupyterhub/team-compass#185]
Hi all,

I was talking with @choldgraf and @willingc earlier today about the work I've done recently integrating JupyterHub with Hadoop. This work produced a few repos, which they suggested may be useful to move into the Jupyterhub org - it was suggested that I should make an issue here to discuss this. The repos in question:

- A spawner for running on YARN: https://github.com/jcrist/yarnspawner
- An authenticator for authenticating with Kerberos: https://github.com/jcrist/kerberosauthenticator
- Docs for setting up the whole thing, in the spirit of zero-to-jupyterhub-k8s: https://jcrist.github.io/jupyterhub-on-hadoop/

If y'all are interested in adding any of these into the JupyterHub organization, I'd be more than happy to move them over.

**Comment by minrk** [comment]
That would be awesome!

**Comment by choldgraf** [comment]
Agreed - this is all super cool! I am +1 on having stewardship of these projects under the jupyterhub org, they all seems like fairly common use-cases to support. I really like the documentation that you put together for the hadoop project, really great!

**Comment by willingc** [comment]
@minrk Any objection if we have time to move these over during the sprints?

**Comment by jcrist** [comment]
Hooray! @willingc if it's ok I'll find you after lunch to figure out what needs to be done to do the transfer.

**Comment by jcrist** [comment]
This didn't end up happening during the sprints - just let me know what needs to be done to do the transfer, and I'll be happy to do it.

**Comment by willingc** [comment]
@jcrist Sorry we missed each other. I've sent you an invite to be a JupyterHub org member. You should be able to transfer in the repos after accepting. The settings page for your repo should have a transfer repo section. Ping me if you have any issue.

**Comment by choldgraf** [comment]
And again, thanks @jcrist for putting together these repositories, and for offering to transfer them over to the jupyterhub org! And welcome to the jupyterhub org :-)

**Comment by jcrist** [comment]
Thanks all. I've moved over `yarnspawner` and `kerberosauthenticator`. Previously I was building docs with [doctr](https://drdoctr.github.io/) to host on github pages - since JupyterHub uses readthedocs, I'm moving things over. Looks like I lack permissions to add webhooks for these repos - I'll ping back here once I have everything working to get someone to finish the readthedocs setup.

**Comment by choldgraf** [comment]
@jcrist do you need permissions on RTD? Or GitHub? Let us know if there are bottlenecks that the JupyterHub teams can help with!

**Comment by jcrist** [comment]
Things are setup on travis and readthedocs, the only thing missing is webhooks so the docs build automatically. I'm not sure what the permission model is here - I think a github owner needs to add them, but since I set up the readthedocs integration I may need to add someone as a collaborator on readthedocs? I've only ever set readthedocs up for projects I had full permissions for, so I'm not sure what the process is.

**Comment by jcrist** [comment]
Looks like I also don't have permission to change the repo description, so the doc links are incorrect (see e.g https://github.com/jupyterhub/kerberosauthenticator still links to `jcrist.github.io`)

**Comment by jcrist** [comment]
Ok, all three repositories have been transferred over and test/documentation builds successfully in their new home. The only remaining todos:

- Get readthedocs webhooks running. This requires org ownership on the github side, not sure what it needs on the readthedocs side.
- Update github project description links, as these also require owner permissions.

**Comment by willingc** [comment]
@jcrist Can you add me and @choldgraf to the ReadtheDocs accounts that are open if any. Let me bump your privileges on the repos that you transferred. Thank you!!!!!!!!!!

**Comment by jcrist** [comment]
Sure! What are your readthedocs usernames (they don't have to correlate to github)?

**Comment by willingc** [comment]
willingc for me on RTD. Also you should now have admin privileges on all 3 repos.

**Comment by jcrist** [comment]
Thanks! Minus adding @choldgraf to RTD, I think everything is done here.

**Comment by choldgraf** [comment]
I'm choldgraf as well!

**Comment by jcrist** [comment]
Added. Thanks all, this can be closed.

**Comment by choldgraf** [comment]
@jcrist any interest in a blog post for the jupyter blog? I'd be happy to help review something. Maybe an old blog post you wrote that we can repost?

**Comment by jcrist** [comment]
Sure, I could write up something short (I didn't blog about this, so nothing to reuse). Where would I go about writing this?

**Comment by choldgraf** [comment]
What we often do is write a draft in a Hackmd (https://hackmd.io/) and open an issue where we collaborate on edits etc. Then we'll get you an account at blog.jupyter.org so you can submit a draft, you'll convert the post to Medium, and we'll post!

It doesn't need to be long, just stuff like "what are these contributions, what's their background, why are they cool, a small bit about how they work if there's something interesting there, etc.

**Comment by jcrist** [comment]
Sure, I'll try to write something up sometime next week.

**Comment by willingc** [comment]
@jcrist Totally cool to start with bullets or an outline too. As a group, we can iterate and polish as needed 👍
