### ISSUE TITLE
Onboarding @GeorgianaElena

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#189]
This is an onboarding checklist for @GeorgianaElena, adding her to the JupyterHub team. Welcome!

**Things the new team member needs**

- [x] A gmail account (for GKE credentials + Google team drive)
- [x] A [PyPI account](https://pypi.org) (for PyPI access)
- [x] A [Discourse account](https://discourse.jupyter.org)

**Membership**

- [x] Add them to the [Discourse jupyterhub group](https://discourse.jupyter.org/g/jupyterhub-team)

**Permissions**

- [x] Add them to the [jupyterhub team google drive](https://drive.google.com/drive/folders/0B8VZ4vaOYWZ3a2dyeEp6NzBKbnM?usp=sharing)

**Learning**

- [x] Send them [a short onboarding message](https://jupyterhub-team-compass.readthedocs.io/team/adding-members.html#an-official-onboarding-message)

**Community**

- [x] Add them to the [jupyterhub or binderhub team yaml files](https://github.com/jupyterhub/team-compass/tree/5d014f3af161e3abcf79c7adfb77620607929d77/docs/team)
- [ ] Tell people in Discourse + Twitter about our awesome new community member

**Comment by GeorgianaElena** [comment]
Thank you very much for adding me to the team! I am very happy and honored :heart: :confetti_ball: :heart:

**Comment by choldgraf** [comment]
Hey all, I just realized we hadn't finished up our final to-do item here :-)

I've made a formal "hello" to @GeorgianaElena on the community forum! https://discourse.jupyter.org/t/announcing-our-new-member-georgiana/2779

closing this issue now
