### ISSUE TITLE
September Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#199]
Hello everyone, 

The September meeting will be on the _third_ Thursday of the month.

That's **Thursday, September 19th, 2019** at 5PM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2019-09-19/17:00/Jupyterhub%2FBinder%20team%20meeting)). 

* Discourse post [here](https://discourse.jupyter.org/t/jupyterhub-community-call-september-2019/1913). 
* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I added two agenda items about Gesis and Turing joining the federation. We should discuss it and make a decision if possible.

**Comment by sgibson91** [comment]
Unfortunately, it's unlikely that I'll be online for this meeting as I'll be travelling back from RSE Con UK. I think a goal capacity should be in the region of 10-20% given the amount of money we have and the size of the machines compared to GKE (roughly half).

**Comment by choldgraf** [comment]
Hey all - I know this is super annoying, and I'm sorry for being AFK for the team meeting in Oslo (I was on vacation), but I just had a family issue come up and need to be traveling this Thursday at 11am (an hour after the meeting starts). I'll jump on the call for as long as I can but may have to hop off quickly if my flight starts boarding.

**Comment by betatim** [comment]
No worries about life happening! It is why we try to conduct as much of our business async/in writing.

For me it would be good to get a feeling of the general support for the two new federation candidates. Should we continue on, slow down, step on the gas? What points do we need to remember to address? I think the formal vote would be in the respective issues so that can happen "whenever".
