### ISSUE TITLE
mybinder.org subdomain: gesis.mybinder.org

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#203]
https://jupyterhub-team-compass.readthedocs.io/en/latest/binder/subdomains.html

We have https://notebooks.gesis.org/binder/ as part of the federation at 1% right now. In the long term increasing that share would be great. One step towards that is to assign a subdomain. This is the issue to ask for gesis.mybinder.org.

The issue #204 discusses adding the binderhub to the federation.

**Comment by choldgraf** [comment]
Is there a place where we can look at the launch successes for gesis? That might help us determine when to move up the amount of traffic.

Really excited about this!

**Comment by bitnik** [comment]
@choldgraf maybe this one? https://notebooks.gesis.org/grafana/d/fZWsQmnmz/pod-activity?refresh=1m&panelId=9&fullscreen&orgId=1&from=now-12h&to=now

**Comment by betatim** [comment]
Picking this up again. @bitnik can you configure a virtual host (I think this is what nginx calls it?) so that gesis.mybinder.org gets sent to https://notebooks.gesis.org/binder/ without the need of a subpath (the `/binder/` part)?

I'll try and illustrate this with a (pseudo) `nginx.conf` (because I don't know much about it :) ):
```
server {
    listen 443;
    ssl on;
    # I think this is how nginx knows that this config only applies to requests
    # a Host header of gesis.mybinder.org
    server_name gesis.mybinder.org;
    # something like this for letsencrypt??
    ssl_certificate /etc/letsencrypt/live/gesis.mybinder.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gesis.mybinder.org/privkey.pem;
    include snippets/ssl.conf;

    # just like the default gesis config
    location / {
        proxy_buffering off;
        proxy_pass http://bhub;
        include snippets/headers.conf;
        proxy_set_header X-Scheme $scheme;
    }
```

**Comment by bitnik** [comment]
Hmm my idea was different, I was planing to redirect requests from gesis.mybinder.org/* to notebooks.gesis.org/binder/*:

```
# HTTP server to redirect gesis.mybinder.org 80 traffic to SSL/HTTPS
...

# HTTPS server for gesis.mybinder.org
# Redirect everything to https://notebooks.gesis.org/binder
server {
    listen 443;
    ssl on;
    server_name gesis.mybinder.org;
    ssl_certificate /etc/letsencrypt/live/gesis.mybinder.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gesis.mybinder.org/privkey.pem;
    include snippets/ssl.conf;

    return 301 https://notebooks.gesis.org/binder$request_uri;
}
```

What do you think? If we agree, I think these are the steps we have to follow:

1. create a subdomain (gesis.mybinder.org) with A record pointing to IP 194.95.75.9 (this is the IP where our nginx lives)
2. then I have to create ssl certs and update nginx config
3. update federation config: in urls replace notebooks.gesis.org/binder with gesis.mybinder.org
4. increase weight of GESIS to 5%

**Comment by betatim** [comment]
Hadn't thought of redirects. Also sounds fine to me.

We could even make the DNS entry a CNAME for notebooks.gesis.org so that only one entry needs updating if you ever need to change IPs.

**Comment by choldgraf** [comment]
I'm happy to add a CNAME as long as we won't run into HTTPS issues and the like, I vaguely remember having problems with that before but it might not be applicable here

**Comment by bitnik** [comment]
@choldgraf can you add it? then I can test if there are any issues.

**Comment by bitnik** [comment]
How do we proceed here?

**Comment by choldgraf** [comment]
Oops - sorry I missed this one.

What is the pattern we decided on doing? In reading the last two suggestions, one was to use an A-record, and another was to use a CNAME...which one is the better option? I can do it this week once I know.

**Comment by bitnik** [comment]
I think Tim's suggestion is better. Let's try with CNAME first.

**Comment by choldgraf** [comment]
Hmmm - I think that this would only work if Binder lives in its own sub-domain, rather than in a sub-directory. @bitnik do you think that you could make `binder.gesis.org` work as well as `notebooks.gesis.org/binder`?

Let me know if anybody thinks I am not correct here! (I found https://serverfault.com/questions/47175/can-a-cname-dns-record-point-to-a-subdirectory which seems to support this idea)

**Comment by bitnik** [comment]
I think a CNAME record which points `gesis.mybinder.org` to `notebooks.gesis.org` should work (because we have an A record which points `notebooks.gesis.org` to the IP of the server). Then in nginx we will handle redirection to `notebooks.gesis.org/binder`. @betatim is this also what you thought? I am not 100% sure neither.

**Comment by manics** [comment]
I think a CNAME and an Nginx redirect to `/binder` should work, as long as you're only redirecting `GET` requests. Redirecting `POST` requests is best avoided.

**Comment by choldgraf** [comment]
OK, I've got `gesis.mybinder.org` CNAME-ing to `notebooks.gesis.org`:

https://gesis.mybinder.org/

I tried it once and got an HTTPS problem, but we'll see if this updates over time? Does it work for other folks?

**Comment by manics** [comment]
Two hostnames for the same IP (doesn't matter whether it's a CNAME or A record):

```
$ host notebooks.gesis.org
notebooks.gesis.org has address 194.95.75.9

$ host gesis.mybinder.org
gesis.mybinder.org is an alias for notebooks.gesis.org.
notebooks.gesis.org has address 194.95.75.9
```
So the server will need multiple certificates (and clients will use [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) to indicate which servername/certiticate they expect). How are the let's encrypt certs obtained?

**Comment by bitnik** [comment]
I just created certificates ~5 mins ago and now added nginx config for `gesis.mybinder.org`

**Comment by manics** [comment]
👍 
```
$ openssl s_client -connect 194.95.75.9:443 -showcerts -servername gesis.mybinder.org < /dev/null 2>/dev/null | openssl x509 -noout -text | grep 'Subject: CN'
        Subject: CN = gesis.mybinder.org

$ openssl s_client -connect 194.95.75.9:443 -showcerts -servername whatever < /dev/null 2>/dev/null | openssl x509 -noout -text | grep 'Subject: CN'
        Subject: CN = notebooks.gesis.org
```

**Comment by bitnik** [comment]
@manics Sorry, I am a bit confused.

I created new certs for gesis.mybinder.org: `certbot --nginx certonly -d gesis.mybinder.org`

Do you think that I had to update certs for `notebooks.gesis.org` and have same certs for both domains? For that I think I could try `certbot --nginx certonly -d notebooks.gesis.org -d gesis.mybinder.org`.

**Comment by bitnik** [comment]
I just saw your last comment. My previous comment can be ignored.

**Comment by bitnik** [comment]
> I think a CNAME and an Nginx redirect to /binder should work, as long as you're only redirecting GET requests. Redirecting POST requests is best avoided.

@manics did you mean sth like this?

```
    ...
    server_name gesis.mybinder.org;
    ...
    location / {
        limit_except GET {
            deny  all;
        }
        return 301 https://notebooks.gesis.org/binder$request_uri;
    }
```

**Comment by manics** [comment]
That looks fine, though my comment about `GET` only was more with reference to binderhub and/or the redirector.

See https://softwareengineering.stackexchange.com/a/99966 for more background.

**Comment by betatim** [comment]
Job done so closing this :)
