### ISSUE TITLE
Adding Gesis to the federation

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#204]
This issue is to discuss adding https://notebooks.gesis.org/binder/ to the Binder federation.

@arnim and @bitnik run that BinderHub.

The goal would be to send around 10% of the traffic there as a first goal.

#203 discusses the subdomain.

What do we need to discuss to make a decision here?

**Comment by arnim** [comment]
Thank you @betatim we would love to join ;)

**Comment by choldgraf** [comment]
I think it’s a great idea. Gesis has been in the binder community from the beginning, and I’d love them to be a part of the federation.

Let me know if I can help to move things forward here. Just getting back from vacation so I may be out of the loop a bit.

**Comment by choldgraf** [comment]
Something that I just remembered: the GESIS notebooks deployment has some UI changes from the other BinderHub deployments. It has the buttons in the top-right for "binder link / session / etc".

I could see this confusing some people, as I *think* we're operating under the idea that any BinderHub in the federation should behave like any other BinderHub, no?

So what is our policy on how much a BinderHub in the federation is allowed to differ from the others?

(that said, I do like those buttons and wonder if we could get them into BinderHub master somehow)

**Comment by arnim** [comment]
That is indeed the case. We should have a consistent UI. The quick fix is that we remove the buttons (we discussed this in the last meeting). In the long run, I think it would make sense to add such functionality to the mybinder deployment.

**Comment by betatim** [comment]
For now I am happy with the buttons. I am ideologically opposed to the "share your current instance by sharing the secret token" (despite doing it myself sometimes...). There is some prep work and a PR from @bitnik on helping to add a subset of the buttons to "any" BinderHub. So we are converging from both directions.

Should we send 5% of the traffic to Gesis as a next step?

**Comment by bitnik** [comment]
This week I will continue with PRs for buttons :)

We can already increase to 5%. But probably it is better that we first conclude subdomain issue (https://github.com/jupyterhub/team-compass/issues/203)?

**Comment by choldgraf** [comment]
I believe this is now done! We've been consistently sending traffic to GESIS and they're now listed on the federation page! https://binderhub.readthedocs.io/en/latest/federation/federation.html

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-can-i-support-mybinder-org/4692/4
