### ISSUE TITLE
mybinder.org subdomain: turing.mybinder.org

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#205]
Hi all!

The Turing's proposal for credit to host a mybinder.org cluster on Azure was accepted (https://github.com/jupyterhub/mybinder.org-deploy/issues/1124) so this issue is to request subdomains for the deployment:

* turing.mybinder.org -> binder page host
* hub.turing.mybinder.org -> JupyterHub host

The issue discussing the progress of the deployment can be found here: https://github.com/jupyterhub/mybinder.org-deploy/issues/1154

**Comment by betatim** [comment]
I support this application for a sub-domain.

Two questions:
* who has access to the account which can setup subdomains?
* @sgibson91 does the turing cluster get a (temporary) domain name from somewhere else during testing or do you need turing.mybinder.org to work from day 1?

For the second point: if you need a domain for testing I have several throw away domains where we can create an entry for testing. This might allow quicker turn around than editing turing.mybinder.org because I have a suspicion that the people who control that are in a US time zone.

**Comment by sgibson91** [comment]
> * @sgibson91 does the turing cluster get a (temporary) domain name from somewhere else during testing or do you need turing.mybinder.org to work from day 1?

I think temporary domain names will be fine for testing and then we can switch to turing.mybinder.org when we're confident. The only time I created a domain name (for Hub23), it was more to-ing and fro-ing with IT - though that's because Hub23 is on a subdomain of turing.ac.uk.

**Comment by manics** [comment]
FYI you can use http://xip.io/ to get an automatic IP based domain name for testing, e.g.
`1.2.3.4.xip.io` automatically resolves to 1.2.3.4

**Comment by sgibson91** [comment]
Thanks @manics!

**Comment by betatim** [comment]
Oh yes! Despite using xip.io and nip.io day in day out for dev work I had put them in the "for local dev only" corner of my mind :)

https://nip.io/ has a comment about "dash notation" and let's encrypt. Never used either with let's encrypt but if weird stuff happens might be worth poking around in this direction.

**Comment by sgibson91** [comment]
The Turing cluster is now running at https://testbinder.hub23.turing.ac.uk 😄

**Comment by choldgraf** [comment]
Hey all - lemme know where I should point turing.mybinder.org !

**Comment by sgibson91** [comment]
The cluster IP address is 51.105.186.97. See https://github.com/jupyterhub/mybinder.org-deploy/pull/1203#discussion_r355107989 for my question about A records. Thanks!

**Comment by sgibson91** [comment]
https://turing.mybinder.org/ now works!

**Comment by manics** [comment]
```
$ host turing.mybinder.org
turing.mybinder.org is an alias for testbinder.hub23.turing.ac.uk.
testbinder.hub23.turing.ac.uk has address 51.105.186.97
```
Seems to work, launches the image on `testhub.hub23.turing.ac.uk`.

**Comment by sgibson91** [comment]
Great! I'm just waiting on Turing IT services to set a new DNS zone record for me so that this hub doesn't share a subdomain with Hub23 and then I'll migrate the A records across.

**Comment by sgibson91** [comment]
Plan is to have turing.mybinder.org point to binder.mybinder.turing.ac.uk - however, currently having issues that certmanager won't issue a certificate for it, but will issue one for the hub.

**Comment by sgibson91** [comment]
Let's Encrypt is now issuing certificates correctly so I'm happy to move forward with this 🙂

**Comment by minrk** [comment]
turing.mybinder.org now points to binder.mybinder.turing.ac.uk

**Comment by sgibson91** [comment]
It works! Thank you!
