### ISSUE TITLE
JupyterHub / BinderHub team responsibilities

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#206]
In the [team-compass docs on adding new members](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/adding-members.html#adding-a-new-team-member), there is a reference in step 2 to [team responsibilities](https://jupyterhub-team-compass.readthedocs.io/en/latest/binder/governance.html#binder-team-responsibilities), but these are BinderHub Team specific to at least some degree.

## Action point - regarding the documentation
My current idea is that we can clarify there are multiple teams and there is a lot of technical overlap, and that we could have a common section for expectations on all of them and then clarify team specific details in additional sections or similar.

**Comment by choldgraf** [comment]
I'm all for being more explicit about the JupyterHub team, its responsibilities, etc. I think we just didn't want to bite off too much with the original BinderHub team PR. I'd be happy to iterate on a PR or discussion to come up with a specific set of responsibilities (maybe this is related to #194 as well?)

**Comment by betatim** [comment]
I'd be happy if we could maintain one section for "team responsibilities" that is shared. The main motivator would be to reduce the amount of maintenance from two sections to one section.

**Comment by consideRatio** [comment]
Closing as possibly resolved but no matter too outdated to help us be actionable
