### ISSUE TITLE
Adding @manics to the JupyterHub team

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#207]
@jupyterhub/jupyterhubteam, I want to invite @manics to be a _JupyterHub team member_!

@manics has a long history of contributions. I often find myself very appreciative of the helpful communication and insight Simon contributes with in Discourse and GitHub. Simon is great! I see a friendly voice with a lot of technical insight about the JupyterHub repos who has used these qualities to contribute for a long time, and also likes to keep doing so given the opportunity. In my mind, that meet expectations on a JupyterHub team member!

We don't have the expectations for JupyterHub team members pinned down so well yet though, so there may be need for additional work to document this as described in #206. I really wanted to submit this request to invite @manics already though as I really don't want to drop the ball on this!

---

UPDATE: I'm leave this open for 10 days according to procedure in [the team-compass documentation](https://jupyterhub-team-compass.readthedocs.io/en/latest/team/adding-members.html#adding-a-new-team-member).

**Comment by willingc** [comment]
Sounds like a great idea. Thanks @consideRatio.

**Comment by choldgraf** [comment]
Yes! I am all for it! Thanks @manics for everything you've done in the jupyterhub community already!

**Comment by yuvipanda** [comment]
I love it!

**Comment by manics** [comment]
Thanks! I'd be happy to join you, and to work (even more closely) with you all!

**Comment by minrk** [comment]
Yay, by all means!

**Comment by choldgraf** [comment]
It's been more than 10 days, let's get this ball rolling! :-)

Here's a link to the onboarding docs in case it's helpful:

https://jupyterhub-team-compass.readthedocs.io/en/latest/team/adding-members.html#the-onboarding-checklist

**Comment by willingc** [comment]
Should we divide and conquer the checklist items? If any have been completed, please check off.

Welcome aboard @manics!

**Things the new team member needs**
- [ ] A gmail account (for GKE credentials + Google team drive)
- [ ] A [PyPI account](https://pypi.org) (for PyPI access)
- [ ] A [Discourse account](https://discourse.jupyter.org)

**Membership**

- [ ] Add them to the [binderhub google group](https://groups.google.com/forum/#!forum/binderhub-dev)
- [ ] Add them to the [binderhub team in the github organization](https://github.com/orgs/jupyterhub/teams/binder-team)
- [ ] Add them to the [Discourse jupyterhub group](https://discourse.jupyter.org/g/jupyterhub-team)

**Permissions**

- [ ] Make sure they have permissions on the [google cloud projects](https://console.cloud.google.com/home/dashboard?project=binder-prod)
      (binder-prod, binder-staging, binder-sandbox)
- [ ] Add them as collaborators on the repo2docker and BinderHub PyPI packages
- [ ] Add them to the [jupyterhub team google drive](https://drive.google.com/drive/folders/0B8VZ4vaOYWZ3a2dyeEp6NzBKbnM?usp=sharing)






**Learning**

- [ ] Send them [a short onboarding message](https://jupyterhub-team-compass.readthedocs.io/team/adding-members.html#an-official-onboarding-message)

**Community**

- [ ] Add them to the [jupyterhub or binderhub team yaml files](https://github.com/jupyterhub/team-compass/tree/5d014f3af161e3abcf79c7adfb77620607929d77/docs/team)
- [ ] Tell people in Discourse + Twitter about our awesome new community member

**Comment by choldgraf** [comment]
Good idea!

@manics - could you send along info for these two pieces:

* A gmail account (for GKE credentials + Google team drive)
* A PyPI account (for PyPI access)

**Comment by manics** [comment]
Google: sent privately
Pypi: sas

**Comment by choldgraf** [comment]
Thanks! I just added @manics to the:

* GKE cloud accounts
* PyPI repositories
* Discourse team
* Google group
* Google Drive

I think just a few steps remaining!

**Comment by choldgraf** [comment]
Arg I realized we never made an announcement about @manics joining the team, consider it done :-)

https://discourse.jupyter.org/t/announcing-our-new-member-manics/2846

I'll send along a "welcome" message in the Discourse and then I think that we can close out this issue.
