### ISSUE TITLE
Software Sustainability Institute 2020 Fellowship application

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#208]
Hi all,

Applications for the [2020 Software Sustainability Fellowship programme](https://docs.google.com/forms/d/e/1FAIpQLSca092mXExTB207VFjAIJtyrZ38vu9uNtdMVwzoXIbpGsQFLg/viewform) are now open! I was going to apply and use the money/connections/collaborations to do something Binder-related, e.g. run another workshop. Any advice on putting together an application would be very much appreciated!

I have to put together a **6 minute** screencast presentation covering the following points:

1) Who I am professionally (**1min 30 sec** suggested)
2) What I do (**1min 30 sec** suggested)
3) My plans for the Fellowship (**3 mins** suggested)

Official deadline is Oct 29th but I'll be on annual leave by then, so **actual deadline is Oct 23rd**.

cc: @KirstieJane @martintoreilly

**Comment by choldgraf** [comment]
It sounds great to me! I don't know much about the application so it'd be hard for me to provide advice there, but happy to look over applicatoin materials and provide feedback if it's helpful

**Comment by betatim** [comment]
No experience with video applications really or the particular fellowship so my only input: make sure to record with a great microphone in a quiet room.

For contents: maybe a workshop towards "how to become a mybinder.org operator/contributor" is an idea to ponder. The spin would be that to make mybinder.org sustainable it needs a constant stream of new contributors/operators and this is within reach of normal people. Also it is good for individuals (new skills, new network, new friends) and it is good for science because the users can actually drive the agenda of the tool they use (unlike with a tool not owned by the community).

**Comment by sgibson91** [comment]
Thanks guys! I think the area you can help most with (beyond sanity checking), and what I think @betatim is already heading towards, is what's a sensible plan for £3000 over 18 months? Most of that fund will be eaten up by a workshop. I like this idea of onboarding people into the operator role. One route could be to run Build A BinderHub so they understand the software, and now let's turn that knowledge into a contribution. But maybe that's too intense? Another route could be for me to do a lot of smaller talks about my own onboarding story, but then that doesn't encourage a lot of follow-through and it's less interactive so I can't help facilitate contributions there and then.

**Comment by sgibson91** [comment]
Capturing a lift chat with Martin this morning:

Application isn't so much "what am I going to do with this money", more "what's my goal for the year". So if the goal is to bring more people into the community and I achieve this either through one big workshop or lots of small talks at conferences, then this totally fits the brief of the Fellowship! 🎉

**Comment by betatim** [comment]
Another idea after reading the feedback: how about using the money for travel and conference tickets? At each event you visit try and give a talk (about something interesting, maybe related to Binder but mostly interesting to get your face known by attendees) and then stick around for the sprints. At the sprints lead a sprint onboarding/contributing to the Binder ecosystem.

**Comment by sgibson91** [comment]
Great idea!

**Comment by sgibson91** [comment]
I think it would be good to name in the application a few events that I intend on applying to in order build the community, around 3 or 4. For my personal interests, I'd like to go to a PyData/PyCon event, but maybe we can think of some conferences for other languages so that we can broaden the skills of the team? Such as an R one?

**Comment by betatim** [comment]
PyData London is by far the biggest of the PyDatas in Europe (May-ish each year). PyData Amsterdam is the next biggest (I think). [PyParis](http://pyparis.org/) is nice (I went many years ago) if you want to escape the Numfocus conference circus/circuit. 

@willingc has been to a few Python events in Asia. Sounded like she had a lot of fun there.

Don't know anything about Python/data science conferences in Africa nor anyone who has been to one. There was a keynote at PyConUK about PyCon Africa so we can probably find out more via that.

Some R conferences that I've seen but never been to (nor know anyone who has been):
* http://www.user2019.fr/
* https://erum.io/ (I might actually know someone involved in organising this, at least at some point (2018??) someone asked if I wanted to apply to talk about binder)

**Comment by minrk** [comment]
reaching beyond Python would be great, since I think we are already relatively well connected in the PyData community. EuroSciPy is also a good conference where there might be more scientific users to connect to.

**Comment by willingc** [comment]
@sgibson91 Perhaps reach out to R-Ladies to see if they have a conference. PyData NY also has good crossover to R. EuroSciPy, as Min mentions would be great, as would SciPy in Asia (it was in Japan this past year). 

One interesting angle on the workshop could be: "Best practices for creating reproducible binders for Python, R, Julia" Going from I have a repo to I can run the repo on Binder. I have a Zenodo ID to Binder, etc.

**Comment by willingc** [comment]
"Best practices for creating reproducible binders for Python, R, Julia" could be created in a manner similar to DjangoGirls workshop so that others could run the workshop again.

**Comment by sgibson91** [comment]
These are all wonderful ideas, thank you!

**Comment by martintoreilly** [comment]
I think a pitch around building / expanding the binder / binderhub community is a great idea and using the money to contribute to travel to conferences is very much in line with the expectations for the use of the grant. A pitch that involved you running workshops at various conferences would be very strong a think.

From the [SSI fellowship page](https://www.software.ac.uk/programmes-and-events/fellowship-programme).

>This funding can be used for any activities that meet both the Fellow's and the Institute’s goals, such as
> - travel to workshops
> - running training events such as software carpentry, data carpentry or library carpentry, nurturing
> - contributing to communities of practice
> - any other activities that relate to computational practice or policy

The [launch video from last year](https://www.youtube.com/playlist?list=PLpX1jXuNTXGo2MYcFn68MI40Y6Kb2tWud) has 1h10m on previous fellow experiences (from the 20 min mark), which is probably worth a look.

There's also a [fellows profile page](https://www.software.ac.uk/about/fellows), but the few I checked didn't really discuss what they did with their fellowship.

**Comment by sgibson91** [comment]
So here's an outline of a presentation that I just drafted out:

- Welcome! (Title slide)
- (Brief) Introduction to myself and Fellowship topic
- Background
  - Reproducibility problems in my PhD
  - Joining the Turing as a Research Data Scientist
  - My involvement in _The Turing Way_ and joining the Binder community
- What do I care about?
  - Reproducibility! (re-use some Turing Way slides)
  - Open Source!
- What is Binder?
  - Obligatory Binder comic/Docker whale
- What have I been doing so far?
  - Workshops on Binder/BinderHub through _The Turing Way_
  - RSE Con UK 2019, RSE Worldwide panel...
- What issues are the Binder community facing?
  - The development team are very Python-centric, this makes it difficult for us to help users of other languages or develop the tool further in that space.
  - Small number of operators/people who know how to do the job (small bus factor)
- Why would someone be interested in joining the Binder community?
  - They will have a voice in shaping the roadmap of Binder (as opposed to a closed project)
  - Improve the support for their language and/or domain
  - Be a part of a welcoming and supportive community! ❤️
- How will the SSI Fellowship help me achieve this?
  - Money will primarily be used for attending/travelling to conferences
  - Identified 3 (maybe 4) conferences to attend:
    - **eRum** to attract R users;
    - **EuroSciPy** to attract scientific users;
    - **JuliaCon** to attract Julia users (provided the 2020 conference is held in UK/EU);
    - **PyCon UK** (potentially, also for my own personal interests).
  - Use talks to speak about Binder and spread the ❤️
  - Use sprint sessions to help facilitate first contributions (a la _Turing Way_ book dashes and Collaboration Cafes)
  - Use workshops to run "Reproducible Binders in Python/R/Julia"
- Thanks for listening!

This is definitely well over 6 minutes 😄

**Comment by KirstieJane** [comment]
I think its gorgeous @sgibson91! Sorry I've been so quiet on this thread. I think everything sounds amazing so far.

Its a little too long (like you said, but probably not wildly so) and I think it needs to get to the point a little faster (as in, when you say "(Brief) Introduction to myself and Fellowship topic" make sure that people could literally stop listening after that and know the problem you're trying to solve!)

I think your bullet points under "What issues are the Binder community facing?" are 💯 💯 💯 and I think you should lead with them. I also blew Beth in comms mind a couple of weeks ago by explaining that "Jupyter" stands for Julia Python and R so I think that's a great point to lead with too - too few people really get that Binder can be so broad. I also think bringing in some ye olde fortran is always kinda fun just to emphasise the point (not for more than a single bullet point.)

I'd be super happy to give some feedback on a practice run though. I think what you have here is a great start, so my suggestion would be to make the slide deck and then do a run through next week. I think I have some ok availability at the moment, and then maybe a zoom run through with Binder folks the week after?

If you're super nice to Dan - and give him a heads up now - I bet he'd help you film it.....which will just make the whole thing look super slick. Make sure to say that he doesn't have to edit it (that's what takes ages) but using his camera and lighting would be really nice 💁 🎥 🌟

**Comment by sgibson91** [comment]
Thanks @kirstie_j! Already asked Dan about this and shot him an email!

**Comment by sgibson91** [comment]
I've written a script for the presentation based on the above skeleton. I'm not super excited by it now that I've done, so please feel free to re-write as much as you like! A link to the PDF presentation is also in the Markdown doc, comments there are welcome too. Thanks everyone!

https://github.com/sgibson91/ssi-fellowship/pull/1

**Comment by sgibson91** [comment]
Just submitted the application! Thank you all for your input! 🎉

The short list will be announced 21st Nov (my first day back after holidays 😂), then there's a community call for short-listed applicants on 5th Dec, and the successful Fellows are announced on 10th Jan 2020. I'll keep you updated with my progress!

**Comment by choldgraf** [comment]
wohoo! wishing you luck Sarah :-)
