### ISSUE TITLE
@sgibson91 unavailability

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#209]
Hi all :wave:

This is just a quick note to say that I'll be unavailable and off-grid for an extended period of time for a (much needed 😂) holiday! 🌴

I will be going offline on **24th October** and back online on **21st November**.

**Comment by choldgraf** [comment]
Hooray vacation! I hope you have a great time :-)

**Comment by sgibson91** [comment]
Closing as I'm back!!

**Comment by consideRatio** [comment]
❤️ welcome back!!!

**Comment by choldgraf** [comment]
woooohoooo - I hope you tell us a bit about your trip sometime, I hope it was great!

**Comment by sgibson91** [comment]
I had a wonderful time, thank you! There's some stuff in [Kirstie's lab meeting notes](https://hackmd.io/@KirstieJane/WhitakerLabMeeting20191121) - including penguins!

**Comment by choldgraf** [comment]
omg can we have a Littlest Penguin mascot for The Littlest JupyterHub?!?!
