### ISSUE TITLE
October Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#211]
Hello everyone, 

The October meeting will be on the _third_ Thursday of the month.

That's **Thursday, October 17th, 2019** at 7AM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2019-10-17/07:00/Jupyterhub%2FBinder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I'll be there

**Comment by Zsailer** [comment]
The notes for this meeting are posted for review (#218) and should be viewable soon!
