### ISSUE TITLE
A round of GKE credits for mybinder.org (2019-2020)

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#214]
We are nearing the end-of-life for our free credits on GKE. Here's the current situation:

* We have $10,920.78 in credits remaining (of $50,000 original)
* This will run out on November 22nd of this year

This is an issue to keep track of this and make sure we don't fall off a credit cliff, or that we have a contingency plan if we do.

# Getting more credits for GKE

First off, we are trying to wrangle credit support from GKE to keep that deployment running. @fperez has been in touch with some collaborators at Google and we have some promising leads there, but nothing specific has materialized yet.

# What to do if we *don't* get more credits

Now that we have a federation of BinderHubs, the downside to losing the main GKE deployment is much smaller. If we run out of credits on the GKE deployment, a suggestion from @betatim was the following:

* Remove access to mybinder.org for the `try.jupyter.org` page and the `spacy.io` docs. This will reduce our mybinder.org load by at least half.
* See if the federation members are OK with increasing load to them (given that total traffic will be way down)

**Comment by betatim** [comment]
<img width="448" alt="Screenshot 2019-10-01 at 07 41 06" src="https://user-images.githubusercontent.com/1448859/66072738-e779a280-e555-11e9-80a0-8e0e3147bd69.png">

These are the top repos and how often they've been launched over the last 120 days. Over the same time we had a total of ~1.5million launches.

**Comment by choldgraf** [comment]
I've sent another email to our GKE friends to see if they'll get back to us - I think that if we don't hear from them by next week, we should start pursuing other options for keeping mybinder.org running.

Another option with GKE:

I've heard that the [google research credits program](https://edu.google.com/programs/credits/research/?modal_active=none) gives us a high change of being accepted. It probably wouldn't fund a full year but could still buy us some runway.

**Comment by betatim** [comment]
I added this to the team meeting agenda. Let's see what ideas we can come up with.

**Comment by arnim** [comment]
@choldgraf 

> See if the federation members are OK with increasing load to them

I think some of them will. @bitnik is currently making sure that we are on the same version jupyterhub/mybinder.org-deploy/pull/1191 ... and then I think we can go a little bit further.

**Comment by choldgraf** [comment]
Hey all - I'm happy to report that we have another year of funding for the GKE deployment from Google. Thanks Google!
