### ISSUE TITLE
Hacktoberfest labels in repos to encourage contribution?

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#215]
Hi all,

I was looking through a few issues marked "good first issue" on the BinderHub repo today. I wondered if we could take advantage of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and add a "hacktoberfest" label to such issues to encourage contributions? Thoughts?

This is an event that happens between 1st and 31st October (in any timezone) annually. So we don't have to decide for this year's event if we want a longer discussion on this.

**Comment by minrk** [comment]
I think it would be great to look through and make sure our "good first issue" labels are up-to-date for hacktoberfest, I think it's a great project.

FWIW, I've participated in hacktoberfest for some time, and set myself the goal of 4 PRs *to projects I've never contributed to before* rather than just 4 PRs, which isn't so much of a stretch since I can't be doing my job without reaching that goal.

**Comment by choldgraf** [comment]
I think it's a great idea - I'll try to do a bit of tagging in the JH repos this week as well. @sgibson91 lemme know if you wanna go through some issues tagging together as a start.

**Comment by GeorgianaElena** [comment]
I really like the idea too, @sgibson91 and I'd be happy to help :tulip:.

**Comment by sgibson91** [comment]
Awesome! Shall we take a repo each? Main ones I'm thinking of are: jupyterhub/binderhub, jupyterhub/jupyterhub,  jupyter/repo2docker, jupyterhub/zero-to-jupyterhub-k8s?

**Comment by choldgraf** [comment]
those seem like the main ones to me too! which repo would you like to tackle? I am probably more well-qualified to look at repo2docker or binderhub...I always find it difficult to know what is a "first issue" or not, since a lot of this dev-ops stack is still black magic to me 😬

**Comment by sgibson91** [comment]
I'll take binderhub on 😄

**Comment by betatim** [comment]
Do we have to list our repos somewhere or is tagging things enough?

**Comment by sgibson91** [comment]
Tagging things is fine. I figured a lot of people might be searching for hacktoberfest labels on github this month.

**Comment by GeorgianaElena** [comment]
I'll give TLJH a go :smiley_cat:

**Comment by choldgraf** [comment]
Hey yall - I see that we have "good first issues" tags in both the binderhub and repo2docker repositories, yay! @sgibson91 do you know if we also need a 'hacktoberfest' tag on those issues as well? There are some in BinderHub but I didn't see any in r2d

**Comment by sgibson91** [comment]
I think having a specific hacktoberfest label for this time of year would be good as I expect a lot of people will be searching for the hacktoberfest label. Also, there's a hacktoberfest label on http://issuehub.io/ that we may get picked up by.

**Comment by choldgraf** [comment]
Perhaps we should tweet out links to our hacktoberfest tags across these repos?

**Comment by sgibson91** [comment]
Love that idea!! You can tag them with @Hacktoberfest and use the hacktoberfest hashtag too 😄

**Comment by sgibson91** [comment]
I'm reviving this issue since this will be coming around again soon!

**Comment by sgibson91** [comment]
Hacktoberfest update: https://hacktoberfest.digitalocean.com/hacktoberfest-update
