### ISSUE TITLE
November Team Meeting 2019

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#219]
Hello everyone, 

The November meeting will be on the _third_ Thursday of the month.

That's **Thursday, November 21st, 2019** at 5PM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2019-11-21/17:00/Jupyterhub%2FBinder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)
* 🎥 🎬 we will record the meeting for those who can't make it.

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by Zsailer** [comment]
Members in the US (+participating states), be aware that there is a time change happening before our next meeting. For example, west-coasters, the meeting time is at 9AM instead of the usual 10AM

@yuvipanda, @choldgraf

**Comment by Zsailer** [comment]
> Members in the US

I forgot to ping @willingc, @lheagy, @mpacer! Sorry y'all :)

**Comment by betatim** [comment]
In Europe the time will have changed as well so make sure to click that "are we meeting yet" button to see the new local time :)

**Comment by minrk** [comment]
I’m moving to a new house on Friday, so might not be able to make it Thursday evening.

**Comment by choldgraf** [comment]
I'll miss you in the meeting @minrk, good luck w/ the move!

**Comment by betatim** [comment]
@GeorgianaElena do you have this in your calendar?
