### ISSUE TITLE
Contributor in Residence announcement blog post

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#223]
Following on from #156 and #165: we got the grant and there will be an announcement from CZI today.

@GeorgianaElena and Tim started writing a blog post to announce things from our side:
https://blog.jupyter.org/the-jupyterhub-and-binder-contributor-in-residence-56708d1e3069

It still needs some editing and an ending/wrap up. Also a lead picture would be great.

Thanks a lot to @willingc and @choldgraf who helped develop ideas and shape things for the post.

As usual, feedback is super welcome :)

**Comment by choldgraf** [comment]
Hey all - I took a pass through the blog post and made:

* Minor edits
* Added a few links to relevant material
* Added one last question at the end
* Added an image

What do y'all think?

IMO this post is nearly ready to go, I'd be +1 on planning to publish this week.

**Comment by willingc** [comment]
Looks good to me. A few missing links at the end. Thanks!

**Comment by choldgraf** [comment]
Does anybody object to me posting this on Monday morning California time? (@betatim or @GeorgianaElena in particular?)

**Comment by GeorgianaElena** [comment]
No objections from my side :+1: . Sorry for going completely offline this week and not helping more with the blog post. I had an urgent (family related) situation I had to manage :disappointed: 
Thanks a lot @willingc, @choldgraf  and @betatim for your help.

**Comment by choldgraf** [comment]
OK, this is now posted! Thanks everybody for helping write / edit / comment / etc :-)

https://blog.jupyter.org/the-jupyterhub-and-binder-contributor-in-residence-56708d1e3069

I'm excited to work on this with you all :-)
