### ISSUE TITLE
Systematization of Badges in our repos

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#224]
I have been adding badges in the README to various JupyterHub repositories, is there something we want to change about this I figured we should centralize input regarding that here in the team-compass. I also I'll document a suggested badge practice in the README once initial feedback has been accounted for.

# Example badges

## Builds
[![](https://img.shields.io/readthedocs/jupyterhub?logo=read-the-docs)](https://jupyterhub.readthedocs.org/en/latest/) [![](https://img.shields.io/travis/jupyterhub/configurable-http-proxy/master?logo=travis)](https://travis-ci.org/jupyterhub/configurable-http-proxy) [![](https://img.shields.io/docker/build/jupyterhub/configurable-http-proxy?logo=docker&label=build)](https://hub.docker.com/r/jupyterhub/configurable-http-proxy/tags) [![](https://codecov.io/gh/jupyterhub/jupyterhub/branch/master/graph/badge)](https://codecov.io/gh/jupyterhub/jupyterhub)

## Versioning
[![](https://img.shields.io/pypi/v/oauthenticator?logo=pypi)](https://pypi.python.org/pypi/oauthenticator) [![](https://img.shields.io/conda/vn/conda-forge/oauthenticator?logo=conda-forge)](https://www.npmjs.com/package/oauthenticator) [![](https://img.shields.io/npm/v/configurable-http-proxy?logo=npm)](https://www.npmjs.com/package/configurable-http-proxy)

[![Latest stable release](https://img.shields.io/badge/dynamic/json.svg?label=stable&url=https://jupyterhub.github.io/helm-chart/info.json&query=$.jupyterhub.stable&colorB=orange&logo=helm)](https://jupyterhub.github.io/helm-chart/) [![Latest pre-release](https://img.shields.io/badge/dynamic/json.svg?label=pre&url=https://jupyterhub.github.io/helm-chart/info.json&query=$.jupyterhub.pre&colorB=orange&logo=helm)](https://jupyterhub.github.io/helm-chart/) [![Latest development release](https://img.shields.io/badge/dynamic/json.svg?label=dev&url=https://jupyterhub.github.io/helm-chart/info.json&query=$.jupyterhub.latest&colorB=orange&logo=helm)](https://jupyterhub.github.io/helm-chart/)

## Social
[![GitHub](https://img.shields.io/badge/issue_tracking-github-blue?logo=github)](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues) [![Discourse](https://img.shields.io/badge/help_forum-discourse-blue?logo=discourse)](https://discourse.jupyter.org/c/jupyterhub) [![Gitter](https://img.shields.io/badge/social_chat-gitter-blue?logo=gitter)](https://gitter.im/jupyterhub/jupyterhub)

**Comment by choldgraf** [comment]
Ah this is excellent! I wonder if it's something that we could loop @GeorgianaElena onto - standardizing badges and badge practices across our repositories would be really great

**Comment by betatim** [comment]
:+1: to standardised badges! I think the only input I have is to not go overboard with badges so that we don't end up with a forest of badges through which we can't see any badges.

**Comment by consideRatio** [comment]
Closing in favor of #230
