### ISSUE TITLE
@betatim unavailable

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#234]
I will be visiting New Zealand over Christmas for about three weeks (plus travel time which is insanely long!). I am going there to do lots of multi day hiking in Fiordland. This means that for several days I need to carry everything I take on the plane, the laptop isn't coming. Nor is much electronic gear because there is no phone reception there anyway.

This means I will be unavailable from 12 December 2019 till 5 January 2020.

Merry New Year y'all!

**Comment by choldgraf** [comment]
The idea of being away from my laptop for 3 weeks is both exciting and terrifying to me :-) I hope it's a great trip!  Anything you want us to help you get finished/merged before you go?

**Comment by betatim** [comment]
I have it on good authority that the internet will still be here when I get back ;)

I am excited about helping @manics with https://github.com/jupyterhub/binderhub/issues/1007 and helping out with #235. Otherwise the top three items on my to do list are:
* don't forget to pack stuff you will need
* don't forget to pack stuff you will need
* find out how to spend 12h in Shanghai

**Comment by betatim** [comment]
Back again (and making progress on GH notifications :) )

**Comment by choldgraf** [comment]
Wooo!
