### ISSUE TITLE
Write a blog post for the GESIS cluster

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#235]
The team at GESIS (👋 @arnim and @bitnik) has done an amazing job of setting up a public BinderHub for the 3rd member of our federation. Thanks so much :-)

Now that the new cluster has been operational for some time, we should have a little write-up about them. We did something similar with OVH, so perhaps we could follow that approach. Another option is to do something similar to [our recent Contributor in Residence post](https://blog.jupyter.org/the-jupyterhub-and-binder-contributor-in-residence-56708d1e3069) and do a little Q&A.

What do folks think about this? I'm happy to help out with either writing or editing. @arnim and @bitnik what would be a valuable write-up from your perspective?

**Comment by arnim** [comment]
@bitnik and I have already been discussing this. Our current feeling was/is that we first want to get persistence going and then write do a post. There could be 3 aspects that could be of interest a) value proposition for the institute/community deploying the hup b) technical aspects of deploying on bare metal and c) combination with a binder-configurable JHub setting that is necessary for persistence.

Persistence is not too far away and @bitnik is (as far as I know) planing already a post on discourse. I think including the persistence part in a medium? post would make it more substantial, however, we can also do it earlier. 

What do you think?

**Comment by arnim** [comment]
Independent of which way we do it, it would be awesome to have also core-team members on board for the post :)

**Comment by choldgraf** [comment]
That all sounds really interesting to me - to be honest it seems worthy to have _two_ blog posts - one that is focused on GESIS and the federation (and is probably shorter), and another that talks about how to get binder-like functionality in a JupyterHub. But if you'd rather have a single post that's fine with me

**Comment by betatim** [comment]
A post on BinderHub + persistence would be amazing! Even one that announces that it exist and then followed by one with a tech dive would be great I think. This is based on the experience that ~no one I talk to even knows that BinderHub can run with auth if you want to. If we can raise awareness about that more by having two posts on the topic that would be great. Maybe one to layout use-cases or other "why is this interesting" aspects and one on the technical details and tricky aspects?

We should also do a short post announcing that GESIS is part of the federation. It hopefully would help you internally and if nothing else helps mybinder.org by telling the world that the federation is growing and "oh wow others are doing it" which might encourage other institutes to think about it/run their own hubs. I am thinking a two or three paragraph post that "only" announces the facts.

---

I am becoming more and more a fan of short posts. In particular via https://www.johndcook.com/blog/ who wrote that his shorter posts receive a lot more visits that then read other stuff on the blog (I guess a bit like you never leave wikipedia after reading just one article) and https://matthewrocklin.com/blog/work/2019/06/25/write-short-blogposts. I don't see a downside to posting a "series". and as a reader I much prefer several shorter posts instead of one long one. They tend to be structured better (and easier to write?). So I will always vote for breaking things into multiple posts :)

**Comment by arnim** [comment]
I think we have a clear votum!  I will try to put some ideas together and then share it here so that we can iterate together ;)

**Comment by choldgraf** [comment]
sounds great- @arnim looking forward to helping out and telling folks about the GESIS binderhub!

**Comment by bitnik** [comment]
I think having 3 posts as @betatim explained would be very good. And thanks a lot for  helping out :)

I will also share updates from my side here and I think that will be by the beginning of next week.

**Comment by bitnik** [comment]
Here is the technical post ["A Persistent BinderHub Deployment"](https://hackmd.io/DWAMypBJS2Odq3ASEhYTOA). We would like to post it on discourse.jupyter.org this week :)

What do you think? You can also comments or updates directly on document.

**Comment by manics** [comment]
I've made some spelling/grammar fixes

**Comment by arnim** [comment]
Currently writing the post on joining the federation at https://docs.google.com/document/d/1sTydvRDk0-fXfFMm8Yp5uB1OmfeOdn5EppFaHTwwu3A/edit?usp=sharing

**Comment by betatim** [comment]
I think it is a nice blog post! Short and to the point (which makes me super happy) :) What do you think of adding a bit more (towards the end?) about how you see a setup like this being used by people/at an institute? Something to help people imagine what all this is good for in their life. I'm thinking of people who meet this new idea for the first time while still trying to understand what JupyterHub and BinderHub are.

**Comment by arnim** [comment]
> Currently writing the post on joining the federation at https://docs.google.com/document/d/1sTydvRDk0-fXfFMm8Yp5uB1OmfeOdn5EppFaHTwwu3A/edit?usp=sharing

@choldgraf I think we have some text. I' will try to get this past communications on Monday morning. Feel free to make suggestions in the text. It would be awesome if we could get this out before Christmas.

**Comment by arnim** [comment]
@manics thank you for your comments in the doc ... all accepted ;)

**Comment by choldgraf** [comment]
I can try to take a look later today. Sorry, have been off on holiday w family

**Comment by choldgraf** [comment]
Just a few very short comments, and one question in the google doc. Let me know what you think and if you're +1 then I'll open up a draft in the Jupyter blog and we can post tomorrow

**Comment by choldgraf** [comment]
@arnim do you have an account on Medium that I can use to invite you to the Jupyter blog account? If not then can you create one and then send the username to me? Then:

* I'll invite you to the blog
* You can copy/paste the test to submit it (links etc *should* copy over fine)
* I'll approve and post

**Comment by arnim** [comment]
> @arnim do you have an account on Medium that I can use to invite you to the Jupyter blog account? 

https://medium.com/@arnim.bleier

> * I'll invite you to the blog
> * You can copy/paste the test to submit it (links etc _should_ copy over fine)
> * I'll approve and post

Perfect - however I'm still waiting for the go from communications. It should be fine but I would be happier if I got their stamp of approval :/

**Comment by choldgraf** [comment]
ah ok, sounds good. I've added you as a writer so you should be able to submit something to blog.jupyter.org now. Let me know when the communications team gives it an OK and then we can post it. I don't think it's a big deal to wait until after the 25th anyway, as many folks will be vacationing anyway.

**Comment by arnim** [comment]
@choldgraf 
> Let me know when the communications team gives it an OK and then we can post it. 

We have a go ;)
I have put up a draft on medium and included your editor's paragraph
https://medium.com/@arnim.bleier/gesis-joins-the-binder-federation-8603d878ff77

**Comment by choldgraf** [comment]
wohoo! I've published your post and also sent out this tweet! Please do share! And thanks @arnim and @bitnik for all of your hard work and help :-)

https://twitter.com/mybinderteam/status/1210508279597674497

**Comment by arnim** [comment]
Thanks to you and the binder-team for making this possible ;)

**Comment by choldgraf** [comment]
😁 Shall we close this issue?

**Comment by arnim** [comment]
I think we can close this issue
