### ISSUE TITLE
Blog post on accessing a JupyterHub from visual studio code

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/team-compass#236]
I've drafted a blog post on accessing JupyterHub from your local vscode.

https://blog.jupyter.org/connect-to-a-jupyterhub-from-visual-studio-code-ed7ed3a31bcb

I'd love to post this early next week. @choldgraf has already helped edit this and is happy with it (thanks!). I also socialized it a little on Gitter, but an issue here is definitely better!

Thoughts?

**Comment by sgibson91** [comment]
This looks really great @yuvipanda, thank you!

**Comment by betatim** [comment]
Looks good to me. Publish it!

**Comment by choldgraf** [comment]
Hey all - I added a little image for the social preview, and published it! Thanks @yuvipanda :-)

https://blog.jupyter.org/connect-to-a-jupyterhub-from-visual-studio-code-ed7ed3a31bcb?

**Comment by yuvipanda** [comment]
Awesome! Thank you all :)
