### ISSUE TITLE
Contributor in Residence project

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/team-compass#237]
Hey all! Just wanted to let everybody know that the CIR project will takeoff at the beginning of January. :rocket:

We can use this issue to store the milestones and end-goals of this project, to track the progress towards achieving them and any thoughts, ideas and questions that will appear along the way.

@betatim, @choldgraf and I have tried to draft an initial plan to be used as a reference, that we can refine together. Hopefully by the end of next year we will have a CIR model that can and will be replicated in other places. :yellow_heart: 

### 1. Deliverables and their timeline:

* **Blog posts:** :memo: 
    * **First blog post** will be at the end of the first 3 months (~ early **April**). It should cover conclusions about our initial decisions (main repositories we are trying to improve, KPIs we’re tracking), what’s working and what needs improvement and what are the goals for the next months.
         - [x] [blog post link](https://blog.jupyter.org/cir-report-i-1ca418c230cd)
   * After the first quarter there will be **blog posts every two months** covering progress towards meeting the previously set goals, setup new goals, engagement rate (using GitHub activity).
     - [ ] **June** blog post link (todo)
     - [ ] **August** blog post link (todo)
     - [ ] **October** blog post link (todo)
     - [ ] **December** blog post link (todo)
    * Last [blog post link](https://medium.com/jupyter-blog/lessons-learned-from-jupyters-contributor-in-residence-pilot-427e2b361a7b)
* **weekly progress reports** (informal style) to track KPI progress
   - [ ] todo: add link to the team-compass issue thread
* **weekly Gitter chat** to encourage and onboard new contributors
### 2. Repos to focus on: :dart: 
**Note:** will start with the top star repos and adjust the list with repos that are doing “worse” according to our KPIs
* jupyterhub
* binderhub
* zero-to-jupyterhub-k8s
* the-littlest-jupyterhub
* jupyterhub-deploy-docker
* dockerspawner
* kubespawner
* oauthenticator
* repo2docker
### 3. KPIs (will use GitHub activity to measure these): :running_woman: 
* time to first reply on issues 
* number of issues with no replies
* average time-to-close issues/prs
* weekly pull requests opened - merged
* weekly issues opened - closed
### 4. Main CIR tasks: :construction_worker_man: 
* Triage issues
* Synthesize questions/issues
* Respond questions
* Review PRs
* Fix bugs
* Document
### 5. Communication channels: :speech_balloon: 
* Gitter for quick QAs
* Use the existing monthly meetings to discuss progress and receive feedback about next month’s goals
* Jupyter blog for the blog posts
* Tim-Georgiana 1-to-1s to evaluate Georgiana’s performance

**P.S.**
* Hope people won’t mind if I’ll ping them when I’m in need. :sos: 
* Thanks a lot to @betatim and @choldgraf for helping putting together *the plan* :heart:

**Comment by minrk** [comment]
This looks like an excellent plan! To start out, perhaps we should shorten the repo list for the first period or two? That's a lot to keep track of, and it's hard to "focus" on lots of things at once! Of course, attention is always welcome anywhere, but I don't want to make @GeorgianaElena start with too much breadth.

**Comment by betatim** [comment]
I support Min's comment. Maybe three to five is a good place to start. Especially as there is no cost to adding more if you feel bored. One thing I find hard is just the shear volume of things happening in high traffic repositories.

Something else to ponder or keep at the back of our mind is #230 and the related effort to create standard building blocks that can be reused across repositories. I think the task here isn't so much to change how repos do things which are happy where they are and more spotting common patterns (and writing them down/pointing them out) as well as using them on repos that have nothing in place.

**Comment by GeorgianaElena** [comment]
The CIR is over for some time, so it only makes sense to close this issue. Thanks everyone for your support ❤️ and sorry for not doing the best job following the plan in this issue. Really loved the CIR experience and learned a lot from it! Thank you!!!
