### ISSUE TITLE
Write a blog post for Turing mybinder cluster

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#239]
I know this is early to be opening this issue and usually the announcement is made after the cluster has been operational for a couple of months "under the radar" (which is totally fine!) - but the sooner we start on this, the more time we have to coordinate with/get approval from the Turing Comms team 🙂So I recommend we start pushing on this in January.

cc: @KirstieJane

**Comment by sgibson91** [comment]
Previous announcement blogs for reference:

* https://blog.jupyter.org/the-international-binder-federation-4f6235c1537e
* https://blog.jupyter.org/gesis-joins-the-binder-federation-8603d878ff77

**Comment by sgibson91** [comment]
I've started a draft in this hackmd: https://hackmd.io/kIvIVCfNQreAiNEaeSuLYQ

**Comment by choldgraf** [comment]
cool! let us know when you'd like feedback

**Comment by sgibson91** [comment]
I've moved the blog post to this PR to The Turing Way: https://github.com/alan-turing-institute/the-turing-way/pull/820 This is mostly because Kirstie and I are expecting the Turing comms team to do a lot of editing (specifically removing stuff) and we'd like to keep the "longer read" for the jupyter blog - and git/GitHub was specifically designed to handle branching in this way!

If anyone has some thoughts to flesh out the "About Jupyter" and "About "Binder" sections, that would be really appreciated! ✨

**Comment by sgibson91** [comment]
Please review 🎉 https://github.com/alan-turing-institute/the-turing-way/pull/820

**Comment by sgibson91** [comment]
I'm going to close this now as I don't think the above will be merged
