### ISSUE TITLE
End of the year post for Binder

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#242]
Hey all - I think it would be nice to have an end-of-the-year post to celebrate all the great stuff we've done with the Binder project. It could be a way to highlight the changes we're most excited about (tech or community-focused) as well as talk about what the project has been up to and where it's going in general.

I put down a few quick thoughts in outline form here, and would love if others would chime in with their own thoughts, comments, etc:

https://hackmd.io/961ps1_wSgi7QLhvJDawug

Maybe we can iterate on that a little bit, and then write up a blog post by the end of the year?

(feel free to make *any* edits that you'd like, whether they're structural, content, removing stuff, etc)

**Comment by choldgraf** [comment]
Thanks for comments etc in the hackmd! I've put together a short blog post that covers some of the highlights that were listed there. Would love to hear any feedback, edits, comments, etc! (it is still a rough draft so please suggest changes!)

https://blog.jupyter.org/a-2019-retrospective-from-the-binder-and-project-57a449517362

What an impressive list of stuff that we've done! Especially given that we've had such limited funding, it is astonishing what an impact the Binder community has had in one year :-)

**Comment by sgibson91** [comment]
Thanks for writing this up @choldgraf, it's fantastic to see how much growth and success we've achieved over the last year! I'd say this post is good to go (once the list of new members has been filled out), unless anyone has any other comments 😊

**Comment by betatim** [comment]
I left some comments on the medium article. Nits about language. Otherwise this looks great to me. Let's publish it!

May 2020 be an equally productive and fun year!

**Comment by choldgraf** [comment]
Hey all - I went through and implemented everybody's suggestions! I think the post is ready to go on my end...should I post it? Or does somebody else want to press the button? Feel free to do so!

**Comment by betatim** [comment]
Would press publish if I could!

**Comment by choldgraf** [comment]
OK, I made a post and little tweetstorm summary! Please RT and share with others!

https://twitter.com/mybinderteam/status/1217506308468822016
