### ISSUE TITLE
Help to understand required conda-feedstock maintenance

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#245]
I made a release of oauthenticator three weeks ago, and we got [a PR arriving to conda-forge/oauthenticator-feedstock](https://github.com/conda-forge/oauthenticator-feedstock/pull/3). What is the process of merging those? Is it to write /lgtm as a listed code owner, or is it to press merge as an owner? Is this left to conda-forge maintainers? How to become a conda feedstock project code-owner?

**Comment by consideRatio** [comment]
Aha! @dhirschfield just demonstrated that what is needed is to be listed in the recipe/meta.yml file it seems: https://github.com/dhirschfeld/jupyterhub-ldapauthenticator-feedstock/commit/bacab24ce359a93e7f5fc1258937923e5b33d6d9

**Comment by choldgraf** [comment]
hmmm that's a great question re: conda-forge, I know very little about it myself. I know that sometimes the conda-forge recipes get created by the community and aren't necessarily maintained by the open source projects themselves, could that be the case here?

**Comment by betatim** [comment]
AFAIK someone who is a maintainer of the conda-forge recipe's repository merges the PR. The PR is made by a bot based on a new package appearing on PyPI.

https://conda-forge.org/docs/maintainer/updating_pkgs.html looks like a good entry point into the documentation.

**Comment by minrk** [comment]
For the most part (this applies to ~all Jupyter projects), for Python packages on conda-forge, the only thing to do for an update PR is to check if dependencies have changed and update them in meta.yaml.

To be clear, conda-forge is not meant to add burden to package maintainers or the release process. It is not necessarily the responsibility of maintainers publishing things to PyPI to *also* be in charge of landing those in conda-forge, so I would probably say that conda-forge should not be mentioned in our release process. What do others think?

**Comment by consideRatio** [comment]
> To be clear, conda-forge is not meant to add burden to package maintainers or the release process. It is not necessarily the responsibility of maintainers publishing things to PyPI to also be in charge of landing those in conda-forge, so I would probably say that conda-forge should not be mentioned in our release process. What do others think?

Oh, is this done by conda-forge maintainers?

**Comment by minrk** [comment]
> is this done by conda-forge maintainers?

It is done by *recipe* maintainers, which can be different for every recipe ($pkg-feedstock repo) and may or may not overlap with upstream package authors. For instance, I maintain several scientific computing recipes with no involvement of the authors (openmpi, mpich, etc.) but also several Jupyter recipes. The key point is that it is not the responsibility of package authors to necessarily *also* be conda-forge recipe maintainers. But individuals are certainly free to choose to do so. I don't want to force choices I happen to have made for myself (being a conda-forge maintainer) on everyone on the JupyterHub team.

**Comment by betatim** [comment]
👍  to Min's point. I am not involved in the conda-forge packaging for the few PyPI packages I maintain. When people asked if they can create the feedstock repo or if "the maintainers of the package" will do it, my answer always was "if you have time and knowledge please do it, it is a good way to help out and get involved with the project".

So I would also vote for conda-forge not officially being part of the release process.

**Comment by consideRatio** [comment]
Considered resolved!
