### ISSUE TITLE
@consideratio reduced availability until mid January

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#246]
Between 29th December and 13th January I'll be on a computer free holiday in Cape Town!

I released JupyterHub 1.1.0b1 and Z2JH 0.9.0-beta.2 tonight btw! ;)

**Comment by choldgraf** [comment]
woooo, enjoy Cape Town!

**Comment by betatim** [comment]
Southern hemisphere for the win :)

I was very sad when I arrived back home yesterday and it started being dark outside at 4.30pm instead of 9.30pm like it was in Te Anau (south island of New Zealand).

**Comment by consideRatio** [comment]
I'm back! :D

**Comment by choldgraf** [comment]
hooray!
