### ISSUE TITLE
January Team Meeting 2020

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#248]
Hello everyone, 

Reminder that we're meeting **this Thursday, January 16th, 2019** at 5PM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2020-01-16/17:00/Jupyterhub%2FBinder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I'll be there

**Comment by minrk** [comment]
I'll try, but I will be alone on childcare duty at the time, and he may not allow it.

**Comment by sgibson91** [comment]
We should just onboard him as a member, start early and all that 😂

**Comment by minrk** [comment]
Oops, misread my calendar. I’ll be there!

**Comment by Zsailer** [comment]
It was great seeing you all yesterday!
