### ISSUE TITLE
February Team Meeting 2020

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#252]
Hello everyone, 

Reminder that our next meeting is **Thursday, February 20th, 2020** at 8AM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2020-02-20/08:00/Jupyterhub%2FBinder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
Just saw a [PR on the ldapauthenticator which stalled](https://github.com/jupyterhub/ldapauthenticator/pull/103) for a long time because of lack of maintainers. https://github.com/marcusianlevine did some work on adding some CI and tests. Should we invite him to the next team meeting with the goal of eventually asking him if he is still interested in becoming a maintainer of that package?

I think it would be good to meet people a bit before asking them to become maintainers.

cc @yuvipanda

**Comment by manics** [comment]
I probably won't make this meeting

**Comment by choldgraf** [comment]
I think it's a great idea to invite them to the meeting... Can we think of other ways to invite participation other than the meetings?

**Comment by sgibson91** [comment]
I also probably won't make this meeting - 7am's a bit too early for me! 😴

**Comment by betatim** [comment]
Ouf! Didn't it used to be 9am Zurich time -> 8am London?

**Comment by sgibson91** [comment]
Yes, then the clocks went back!

**Comment by betatim** [comment]
We said we'd use UTC so I guess we are stuck with it for a bit. I've added "move by an hour" to the agenda. It isn't a super useful meeting if most people can't make it.

**Comment by betatim** [comment]
Haven't added it to the agenda yet because the linked HackMD still contains the notes from the January meeting. @Zsailer do we normally reuse or create a new HackMD for the next meeting?

**Comment by choldgraf** [comment]
@betatim I believe we re-use the same HackMD. Copy/paste the notes into a markdown file and PR it to the repository, then reset the HackMD with a blank slate (but the same URL)

**Comment by sgibson91** [comment]
On the time issue, I think it's fine to leave for now as the clocks will be going forward again next month 🤷🏻‍♀️

**Comment by Zsailer** [comment]
> do we normally reuse or create a new HackMD for the next meeting?

@betatim We reuse the same HackMD—I just cleared the agenda for February's meeting. I had already merged the January notes into our team-compass page but forgot to clear the HackMD. We're good now 😎 

Is it too late to change the time of the meeting?

I propose we push this meeting back on hour this month. Next month will be on the US/Europe swing anyways, so we're already used to meeting time switches. 😄

**Comment by sgibson91** [comment]
@Zsailer I'm happy to do that if others are 😊

**Comment by betatim** [comment]
Moving the meeting back by an hour is good for me.

**Comment by Zsailer** [comment]
Great, I've officially pushed back the meeting by one hour!

This issue, the agenda, and the Google Calendar have all been updated.

**Comment by minrk** [comment]
I can't make it this week, I have to visit prospective barnehages that morning.

**Comment by minrk** [comment]
I’ll be there! I’m bad at calendars and thought it was going to be last week.

**Comment by choldgraf** [comment]
Hey all - I sadly won't make the meeting because I just flew back from Australia this morning and I *really* hope to not be awake at midnight :-P

I threw in a few points I wanted to mention in the hackmd - nothing too major, but feel free to reach out if you wanna chat further about it!
