### ISSUE TITLE
Keeping track of what Georgiana has been up to!

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#253]
Hey all - @betatim , @GeorgianaElena and I have met a couple of times to kick-off the "Contributor in Residence" project. For those who aren't sure what that is, [check out this blog post](https://blog.jupyter.org/the-jupyterhub-and-binder-contributor-in-residence-56708d1e3069).

One thing that @GeorgianaElena asked about is whether we could keep track of the kinds of contributions she's making over time in order to see where her time is being spent.

This is an issue to brainstorm the kinds of things that we'd like to keep track of, and how to do so in an effective manner

**Comment by choldgraf** [comment]
As a quick update, I updated my github activity tracker to add a notebook that can visualize a single person's contributions over time. It generates plots like this:

Activity over time, broken down by "type" of activity

![visualization (3)](https://user-images.githubusercontent.com/1839645/73023548-9df0e400-3de0-11ea-96ca-b7b1fe4c9634.png)

Comments over time, broken down by repository

![visualization (4)](https://user-images.githubusercontent.com/1839645/73023565-a9dca600-3de0-11ea-866f-539cb33c51e9.png)

@GeorgianaElena and @betatim is this the kind of thing you had in mind? What other statistics or behavior types are worth tracking? Any other suggestions or comments?

One thing I want to flag is that there's sometimes danger in tracking a specific metric. We don't want to create a weird incentive to maximize a particular thing unless we know it's really helping the community, so that's something we should consider when deciding what KPIs to track.

**Comment by Zsailer** [comment]
At Jupyter Cal Poly, we've been using Github's project boards to track the work/progress our intern team is making. You can view our current board [here](https://github.com/orgs/jupytercalpoly/projects/1).

Our strategy this quarter has been to create a *curated* list of issues across multiple Jupyter projects that we'd like our interns to tackle. Some require code; others require discussion. 

Interns move the issues they're currently addressing into the "in progress" board, then to the "done" or "needs review" columns after they address the issue. The goal is to push stale issues forward. If they can't solve the issue themselves, they at least reach out the the issue/PR poster and add feedback to bring attention to the issue.

At the end of the quarter, we're hoping to have a full list of issues, PRs, proposals, etc. that they addressed on over the quarter. We check in weekly to see what issues they finished over the week. If they are blocked on their current issue, we can talk about it in our meeting and help them move forward. So far, it's been a nice way to track progress.

**Comment by yuvipanda** [comment]
Since she started doing stuff at 2i2c, I've taken it as my responsibility to keep [this hackmd updated](https://hackmd.io/SSQQgBCsTnCliR2uqciOuQ) so she knows how cool she is :) I don't think this is easily trackable automatically, but can be informed by our experiences & looking at GitHub activity now and then. I'd love for others to add to that hackmd too!
