### ISSUE TITLE
Team meetup/sprint in Berlin

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#254]
What are people doing around the middle of August (besides being on holiday)?

Should we try and get together for a few days (like we did in Oslo last year) but in mid August in Berlin? (Why this time and place, just a hunch). Right now I'd just try and judge interest levels, then see what we could do in terms of organising stuff.

**Comment by sgibson91** [comment]
I also have a hunch that I may be in Europe in mid-August...

**Comment by rkdarst** [comment]
I don't know if I'm invited, but I would definitely be interested.  I still haven't finished many of the things from last time, but this would be good motivation.

**Comment by sgibson91** [comment]
I vote we invite @rkdarst just so I can have more Finnish chocolate 😋

**Comment by choldgraf** [comment]
I sadly won't be able to make anything in August :-(

**Comment by arnim** [comment]
Would be interested ;)

**Comment by yuvipanda** [comment]
I WOULD ABSOLUTELY LOVE THIS, although someone would need to help me with Visas.

**Comment by minrk** [comment]
I'd love to do this. I'm going to be [in Sweden](https://medeltidsveckan.se) until probably the 6th, so if we are planning on a couple of extra days before [JupyterCon](https://blog.jupyter.org/jupytercon-2020-is-a-go-47c82b281fa8) on the 10th, I could train down straight from Stockholm, which would be perfect for me.

@yuvipanda what help can we provide?

**Comment by yuvipanda** [comment]
@minrk awesome! I'd probably need a letter of some sort inviting me to this on some sort of official looking paper from an official-ish organization. Do you know if such an org exists?

**Comment by sgibson91** [comment]
If we plan to do this over a weekend, @trallard may be able to help with a venue

**Comment by betatim** [comment]
Before JupyterCon sounds like a great idea.

Maybe Hans at EU XFEL can invite you? There were some messages on the jupyter-research mailing list about having a HPC-or-such meeting around JupyterCon. And EU XFEL is a org in Germany. The other org to contact is JupyterCon itself. Usually conference organisers take care of sending letters of invitation as they necessarily have a local legal entity and a fitting story.

**Comment by yuvipanda** [comment]
@betatim oh yeah, I think JupyterCon itself should be able to manage. I didn't realize JupyterCon was gonna be in Berlin when I first wrote the comment...

Excited to make this happen!

**Comment by yuvipanda** [comment]
Hmm, I don't understand what the words T R A V E L means, given that the only things that exist are inside this house I live in and through this screen I'm staring at. I'm starting to believe that y'all are a simulation set up to make me feel good about myself, since it's doing a pretty good job of that. Given such beliefs, I shall close this issue until there is strong evidence that things and places exist outside our immediate field of vision.
