### ISSUE TITLE
Outreachy, winter 2020-2021

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#255]
This summer is the pressing issue: sign up is due in less than a week, **February 18**.

I don't have the resources to mentor until I'm back to full time in the Fall, but we had a great experience in our first go. Is anybody available or willing to mentor this Summer? We would need an intern project and at least one or two folks responsible for handling application contributions (defining appropriate mini tasks in Issues and reviewing PRs) and then mentoring for the long project. Then we just need to find the $6,500 to support a position, which I'm sure we can do. Last time, it was preparing and reviewing mini task contributions during the application period that took the most time and effort.

I plan to mentor again when I'm back to full time in the Winter, but not the Summer.

**Comment by GeorgianaElena** [comment]
I'm very happy for the possibility of Outreachy happening again and I would love to help :heart:
I'm not sure if I'm fully qualified to mentor, but I'm willing to try if people think it's a good idea.
I can definitely help out the mentor/s with the application contributions or anything else along the way.

**Comment by choldgraf** [comment]
I don't have the bandwidth to mentor but I'm happy to help either scrounge up cash or write an application.

@GeorgianaElena perhaps you and someone could co-mentor an outreachy student to share the load?

**Comment by betatim** [comment]
I won't have time to mentor either :(

**Comment by minrk** [comment]
Raising this issue again because project submissions are due in September. Any project ideas that fit in the time frame are welcome.

Project ideas:

- jupyterhub-auth-proxy: write a thin proxy, combining work in jupyter-server-proxy and jupyterhub.services.auth to make a *standalone* proxy enabling jupyterhub auth, so that a notebook server is not required. This is essentially taking jupyter-server-proxy from a notebook server extension and making it a standalone app.

**Comment by manics** [comment]
`jupyterhub-auth-proxy` sounds similar in aim to `jhsingle-native-proxy`:
- https://discourse.jupyter.org/t/new-package-to-run-arbitrary-web-service-in-jupyterhub-jhsingle-native-proxy/3493

**Comment by minrk** [comment]
lol, that's exactly what I was thinking. need another idea, I guess!

**Comment by minrk** [comment]
Actually, on reading, I think what I want is ever so slightly different, since I was mainly thinking of using it as a *sidecar container*, assuming the proxy target is already running. That's very close, though, and should be solvable with minor modifications.

**Comment by choldgraf** [comment]
I think that we should close this, since it is way past the deadline :-/
