### ISSUE TITLE
2020 mybinder user survey aggregated results and the SSI Fellowship

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#256]
Hey all,

I'm hoping to do achieve some gospel-spreading and community growth around binder through my Software Sustainability Institute Fellowship by attending Julia, R and Python community conferences. One idea I've been thinking about with @betatim and @willingc is applying to give lightning talks at these conferences where I summarise the aggregated results of the mybinder user survey, both in general and those points specific to the identified communities. I can then present myself as a point of contact for further discussion around these topics and helping people get involved either by helping them open an issue, pointing them towards documentation, etc etc. I could then partner these lightning talks with either a table where I hand out stickers and have an open laptop for demos/GitHub-ing, or Birds of a Feather session where we plan more concrete contributions.

So I'm opening this issue so we can track my progress and do some work around aggregating the results of the survey when it closes! ✨

**Comment by betatim** [comment]
I like the idea! Should we combine several of the "one thing to improve" items together when they share a theme or should we keep things as individual suggestions? A task for the next team meeting?

---

I created #257 to track follow up items from the survey.

**Comment by sgibson91** [comment]
I think combining things to identify themes is a good idea. I'm not sure how many responses we got but it could be unwieldy to keep things individual. Yeah if people want to work on it in the next meeting, that would be cool!

**Comment by betatim** [comment]
(just stopping by to say this is a pretty excellent issue number, 256 :)

**Comment by sgibson91** [comment]
🌈
I think that's a large enough sample size for pulling out themes!

**Comment by choldgraf** [comment]
what a great data set!

**Comment by sgibson91** [comment]
@choldgraf that wasn't my intention!

**Comment by sgibson91** [comment]
FYI, my lightning talk at eRum was accepted, but it's in Milan so... we'll see? 😬

**Comment by choldgraf** [comment]
eek - well I hope you get to go! You should swing by Chambery on the way to Milan, it is a nice little town (where my wife grew up) :-)

**Comment by betatim** [comment]
I closed the user survey https://github.com/jupyterhub/mybinder.org-deploy/pull/1383

**Comment by betatim** [comment]
We got some good feedback (as well as some frustrated users commenting). The need to make it faster remains :D

**Comment by sgibson91** [comment]
Hey y'all! My colleague at the Turing @fedenanni has some experience in NLP. I thought maybe we could work on a Notebook (in Binder of course!) that would pull out themes from the free text question on the survey - then it'll be reproducible for the next survey!

**Comment by fedenanni** [comment]
Hi all! Sounds great, @sgibson91 ! We could start playing around with some clustering of key-phrases to see if there are commonalities across the messages in free text. Let me know when you have access to the data and I'd be happy to test a few things ;-)

**Comment by sgibson91** [comment]
Thanks @fedenanni!

Does anyone have/foresee any issues with me putting the responses in a GitHub repo (public or private)? If yes, I can use the Turing's Sharepoint/OneDrive to share a bit more privately with Fede.

**Comment by choldgraf** [comment]
Hmmm - there is the question of user privacy. We would need to make sure that there no possible way that responses could be identifiable in the public data. And there is also a broader question about whether we told users this was a possibility or not. @betatim was there any language like "these responses might be made public"?

**Comment by sgibson91** [comment]
Yes, exactly. I looked through the responses and the only data we collect other than the actual answers is the timestamp from when the response was submitted. But I'm also not a data privacy expert, so I'm very happy to go with our internal platform to make sure we're covered :)

**Comment by manics** [comment]
I thought the link to the results was already public?

**Comment by choldgraf** [comment]
yeah - my intuition is that it is OK, though perhaps worth parsing the dataset first to make sure there's nothing identifiable in the responses (e.g. if somebody signed the response)

**Comment by sgibson91** [comment]
I don't recall anything like that on my first sweep, but I will do another check. Thanks! :)

**Comment by sgibson91** [comment]
Feedback and PRs welcome! https://github.com/sgibson91/mybinder.org-user-survey-nlp

**Comment by betatim** [comment]
This is pretty cool!

My two take aways: "faster!!!111!" continues to be a wish and "workshops/education/teaching/examples" is what people use it for. Makes me wonder how we can include that in the Binder motto/slogan/etc which is a lot about "reproducible science/publishing" which very few people seem to be using mybinder.org for (obvious caveat emptor: ... of the population that responded to the survey)

**Comment by sgibson91** [comment]
It would be great if we could break down the "faster!!!111!" into what can be solved by contributing to us and what can't (if it hasn't been already). I suspect there's some k8s/docker pushing/pulling stuff that we are entirely dependent on upstream features for. But having that issue/slide available somewhere shows that we know it's annoying and that we're thinking about it.
