### ISSUE TITLE
where to publish nbviewer helm chart

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#261]
nbviewer now has a [helm chart](https://github.com/jupyter/nbviewer/pull/905), but it's not published anywhere. Do folks think it makes sense to publish the nbviewer chart to the existing jupyterhub/helm-charts repo along with jupyterhub and binderhub, or should we make a similar (identical), separate helm chart repository on the jupyter org?

xref https://github.com/jupyter/nbviewer/issues/907

**Comment by consideRatio** [comment]
+1 for using the current helm chart registry!

**Comment by choldgraf** [comment]
I'm fine with it. I suppose the question is whether the jupyterhub charts repo is a generic 'place for hosted infrastructure tools in the jupyter ecosystem' vs. 'place for jupyterhub-specific deployment tools'

**Comment by sgibson91** [comment]
I agree with @choldgraf, having a clear definition of what that repo's purpose is will be important for people's understanding. But it does seem like a good idea to have all the helm stuff together.

**Comment by minrk** [comment]
I'd lean slightly toward saying that this is the general Jupyter ecosystem chart repository, mainly because I suspect that most folks interested in these things (people who deploy stuff) are likely to be jupyterhub community members already. JupyterHub is "a tool for deploying jupyter" and Jupyter-related helm charts are similarly tools for deploying Jupyter things. I also don't think there are likely to be too many other Jupyter helm charts, and one of the main was that folks deploy their own nbviewer instances is as a jupyterhub service already, so it seems like a reasonable fit to me.

**Comment by yuvipanda** [comment]
I agree with @minrk. Having it all in one place helps with discovery from a user perspective too.

**Comment by betatim** [comment]
My vote is to use the same repo. My top reason after those already mentioned: feels like it will be less maintenance effort and maintenance complexity.

**Comment by yuvipanda** [comment]
I referenced this decision in https://github.com/jupyter/nbviewer/issues/907#issuecomment-778052454, so gonna close this now.
