### ISSUE TITLE
Remove myself (Zsailer) from JupyterHub/Binder teams

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#262]
Hi all! 

Acknowledging our guidelines for Team Membership, I'm planning to remove myself from the JupyterHub/Binder Teams. I'm not leaving the community, just demoting myself to create room for others 😃. 

After self-evaluating my time/priorities, I recognize I'm not actively contributing to JupyterHub or Binder at a frequency that I think warrants membership (though I plan to in the near future)—my attention is consumed by other parts of the Jupyter "orbit" (namely, Jupyter Server, Lab, and Notebook). Further, I've been slipping on my few responsibilities here already... e.g. slow to post meeting notes, announce meetings, etc. My sincere apologies for this! I should have communicated this sooner. 

I think it makes more sense to relinquish these responsibilities to someone who is more actively involved in this community. I'm happy to work with this person to get them started.

These teams are **awesome**, and it's an honor to be named next to each of you. I don't take that lightly. I appreciate each of you. Now, I look forward to being a community member that supports our amazing core team members! I'm hoping to return sometime in the near future.

Y'all—keep crushing it! You've got a super fan here. :sunglasses:

**Comment by consideRatio** [comment]
@Zsailer awww! Thanks for all your warm energy, I'm happy it remains in the Jupyter ecosystem :) Lots of love from Sweden, hope to see you soon!

**Comment by choldgraf** [comment]
we are sorry to see you go, but happy to keep seeing you on the other moons of Jupyter :-) and don't forget that you're not being removed from the team, you're just moving to the green team 😎
