### ISSUE TITLE
March Team Meeting 2020

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#264]
Hello everyone, 

Reminder that our next meeting is **Thursday, March 19th, 2020** at 5PM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2020-03-19/17:00/JupyterHub%20Binder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I'll be there.

**Comment by minrk** [comment]
Not sure yet if I'll make it this week.

**Comment by sgibson91** [comment]
I've invited Chris Woods (Bristol) to this meeting as he reached out to me to be a technical advisor on a project that aims to use BinderHub within a platform for sharing greenhouse gas data :)

**Comment by sgibson91** [comment]
> I've invited Chris Woods (Bristol) to this meeting as he reached out to me to be a technical advisor on a project that aims to use BinderHub within a platform for sharing greenhouse gas data :)

Just heard that they won't be able to attend due to the work needed to change working patterns RE Covid-19. Chris and his colleague Gareth are hoping to make the April call instead.

**Comment by choldgraf** [comment]
I should be able to make it.

Did anybody else notice that the JupyterHub team meeting is gone from the "Project Jupyter" google calendar? Am I just missing it?

**Comment by Zsailer** [comment]
@choldgraf—I still see it on the Jupyter Calendar [here](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Comment by Zsailer** [comment]
Note, the JupyterHub events are on JupyterHub's Team calender (not the Project Jupyter calendar). You'll need to show JupyterHub Team calendar on your personal Google calendar view to see these events. 

The calendar I posted in the above comment is a consolidated view of various Jupyter team calendars.

**Comment by choldgraf** [comment]
ah no I found it, it's just overlapping with 3 other meetings at the same time slot so the text got crowded out :-P

**Comment by betatim** [comment]
What do people think about having an agenda item "using or thinking about using mybinder.org for remote teaching - meet&greet"? Trying to bring together some people who are doing it or thinking about doing it. Maybe we can answer some common questions. If we want to do this we should start advertising it a bit on the internets.
