### ISSUE TITLE
reduced availability for the next week or more

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#268]
I will have reduced availability for Jupyter things for a little while because I am helping out on a project with some public health organizations here. I will definitely be using what I've learned from the team running mybinder.org!

**Comment by minrk** [comment]
OK, this has been way more than a week. Sorry for disappearing! The demands of this project were not at all what I expected and it has been completely overwhelming and I had to shut down basically everything else in my life. But things are calming down now and I should be back to JupyterHub things soon.

**Comment by betatim** [comment]
Whoop! Make sure to take some time to relax the brain as well ;) (and to satisfy my curiosity maybe we can have a "Min's big adventure" at the next team call?)

**Comment by yuvipanda** [comment]
WELCOME BACK, @minrk! <3
