### ISSUE TITLE
Merge the Binder and JupyterHub teams

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#269]
Following a discussion in our community meeting:

right now, we have two different teams listed on the teams page:

https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html

A jupyterhub team, and a binder team.

These two teams are pretty well overlapping with each other, and also have many of the same responsibilities, projects, etc.

So: **what if we merged these into a single team, and allowed team members to note if they'd like to emphasize a particular part of the project on which they work? (e.g., Binder)**. Then we'd have a single team, and we'd use the same "color" roles for it.

This would also resolve #266

**Comment by betatim** [comment]
Would reduce some admin overhead which I am (almost always) in favour of.

**Comment by choldgraf** [comment]
OK, I have 5 team +1s and no -1s. Unless anybody objects I'll make a PR to the team-compass in a PR soon

**Comment by consideRatio** [comment]
> OK, I have 5 team +1s and no -1s.

Awww the heart will remain a bit more than `+1` to me though.

I'm very much in favor :)

**Comment by choldgraf** [comment]
Cool! check out https://github.com/jupyterhub/team-compass/pull/283 for a first pass
