### ISSUE TITLE
Raising the cap for a civic data class repo

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#270]
What do you think about (temporarily) increasing the cap for a repository used to teach people about Python, data and all that?

I saw https://twitter.com/palewire/status/1242448226059354112 and thought we could help out.

I'd be happy to try this out and invest a bit of effort. It seems like this is for a good cause/something that aligns with the mission of mybinder.org. We need to be a bit careful with bumping up caps as we should make sure that "mybinder.org the resource" is available to a mixed audience and doesn't all get consumed by a few big players/power repos.

There is an issue on the repo in question https://github.com/california-civic-data-coalition/first-python-notebook-binder/issues/1

What do people think?

**Comment by sgibson91** [comment]
I'm +1 on this. I've been thinking it might be time we bump the traffic to Turing up a bit again if that helps with resourcing.

**Comment by choldgraf** [comment]
Definitely +1 from me - Ben is also a pretty great advocate of open source in the journalism world

**Comment by betatim** [comment]
Limit lowered again in https://github.com/jupyterhub/mybinder.org-deploy/pull/1400
