### ISSUE TITLE
Team Meeting April 2020

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#273]
Hello everyone, 

Reminder that our next meeting is **Thursday, April 16th, 2020** at 8AM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2020-04-16/08:00/JupyterHub%20and%20BinderHub%20Team%20Meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Google Hangouts (video conferencing) [here](https://meet.google.com/wat-vtby-cfd)

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

**Comment by betatim** [comment]
I'll be there!

**Comment by betatim** [comment]
Does anyone know what it would take to use Google hangouts or Jitsi or X for the video conferencing part? Zoom has always had a bad privacy story but over the last few days they've really worked hard to cement their position as "we give very few **** about security and privacy". I'd be happy to switch.

**Comment by sgibson91** [comment]
I unfortunately have very little experience with any other conferencing software. Discord?

**Comment by choldgraf** [comment]
Some relevant links:

article about zoom's crappiness: https://www.schneier.com/blog/archives/2020/04/security_and_pr_1.html
campaign for end-to-end-zoomcryption: https://tumblr.fightforthefuture.org/post/614318663706820608/new-campaign-calls-for-zoom-to-actually

**Comment by betatim** [comment]
Discord can do video chat? (I only learnt about it yesterday but it was for voice chat while playing a game).

Google hangouts works well for us at work with around 16 participants (we have paid G Suites if that makes a difference). It makes it harder to see everyone at the same time though :(

**Comment by betatim** [comment]
I've also used https://meet.jit.si/ which worked well (but didn't impress me as much as whereby.com did when I first used it, but that is a high bar).

**Comment by consideRatio** [comment]
I went ahead and scheduled a google hangouts link for us. I got it as part of the calendar entry i created in a new calendar i made.

- calendar: https://calendar.google.com/calendar?cid=c3VuZGVsbG9wZW5zb3VyY2Uuc2VfczdndDc4ZGlwY2dscTRlMzI4dWluOGoycmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
- google hangouts link for the calendar entry i created: meet.google.com/wat-vtby-cfd

**Comment by sgibson91** [comment]
Thank you @consideRatio! I've updated this issue and the agenda. We can see how it works out!

**Comment by consideRatio** [comment]
@jupyterhub/jupyterhubteam :heart: - meeting in 30 minutes

**Comment by sgibson91** [comment]
Hi @Zsailer @choldgraf, do either of you have access to the JupyterHub team meetings Google calendar? Would you be willing to share with some more people on the team? There was a little bit of confusion over the time for the meeting this morning :smile:

**Comment by Zsailer** [comment]
Hi @sgibson91—I've given you, @consideRatio, and @manics full access to the calendar 😎.

**Comment by sgibson91** [comment]
Thank you!
