### ISSUE TITLE
Increasing the cap for `hugobowne/COVID-19-EDA-tutorial`

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#276]
Similar to #270.

Twitter thread: https://twitter.com/hugobowne/status/1247343891264589824 and repository https://github.com/hugobowne/COVID-19-EDA-tutorial

I'd be happy to increase the limit somewhat. I don't think we can meet the demand for "thousands" but I think the experience from the MIT course shows that so far everyone has been overestimating how many concurrent users there will be.

**Comment by hugobowne** [comment]
thanks for moving this here, @betatim. I am probably over-estimating. Last time I did FB Live Coding FB reported there were 30K viewers but no idea how many were coding along (I had install instructions in repo then.

Let's say we reach the limit. Do users with active binders get to keep using them at that point?

I'd also like to flag that I'm doing this coding session as part of my work at DataCamp. DC is **not** monetizing this session in any way but I wanted to be totally transparent about that, in case it changes anything about how you would allocate resources here. An upside is that I will shamelessly plug binder (which you know I love) to everybody! Startling that DC has 920,654 followers on FB.

**Comment by betatim** [comment]
Sorry for the slow response.

If you have a session you get to keep it, new users (or people who close their tab and start a new session) see a message telling them that there are currently too many users using that particular repo.

Do you know what date and time (in UTC) you had in mind?

**Comment by betatim** [comment]
As a point of reference daily concurrent usage peaks at around 800-900 users. So having an extra 200 is probably "easy" beyond that we are in uncharted territory. I don't see why it would break, but who knows, we've not been there before :)

**Comment by choldgraf** [comment]
+1 from me - and thanks @hugobowne for reaching out about it. If you ever see one of the Binder team you can buy 'em a beer or two :-)

**Comment by hugobowne** [comment]
thanks, binder legends!
I've also got a colab NB set up, in case I max this out.

@choldgraf shame I can't buy you a beer or three at scipy this year :(

hey also, is this list up to date wrt current binder team?

https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html#binder-team

**Comment by betatim** [comment]
I've set the limit to 200 for now.

The list you linked is a good list to use.

Can you tell me *when* we should expect people to start using the repo?

Beer or best-alternative drinks are always welcome ;) (I'm telling you a business that does global coordinate drinks delivery is the next big  startup thing.) Another way to help out is to use the influence you have and/or ideas when we need to secure more funding to run the computers :)

**Comment by betatim** [comment]
I found the time in your tweet: 4pm ET or 10pm Zurich time or 9pm London time.

**Comment by hugobowne** [comment]
Thanks, yes, and I'm sorry I missed you question earlier.

**Comment by hugobowne** [comment]
> Another way to help out is to use the influence you have and/or ideas when we need to secure more funding to run the computers :)

**very** interested in helping here. Perhaps we could discuss at some point?

**Comment by betatim** [comment]
> very interested in helping here. Perhaps we could discuss at some point?
> it would be good to know the current situation and future plans.

Maybe we can make this a topic for the next team meeting: #37. Do you have time to attend that one?

Right now the high level (and long term) vision is to make it so easy (technically and politically) for an institution to host a small share of mybinder.org that we can persuade enough big research/teaching institutions to host a cluster. I think we have some work to do on the technical side but also on the social side of making contacts in enough places. So in the short and medium term we rely on receiving credits from the cloud providers we use.

**Comment by hugobowne** [comment]
Thanks for the context. It's be a pleasure to join a team meeting. That's 2am Sydney, however, and I'd be useless at that time. If you have meetings at other times, I'd happily join. Otherwise, we can chat 1on1 or even loop in @choldgraf.

**Comment by betatim** [comment]
Sorry, I linked to the wrong April team meeting (the one of 2018). The one this April (in the year 2020) is #273. It is at 8am UTC. Does that make it a more reasonable time in your part of Australia?

**Comment by betatim** [comment]
<img width="1123" alt="Screenshot 2020-04-09 at 23 04 20" src="https://user-images.githubusercontent.com/1448859/78940885-e1d9b800-7ab6-11ea-9a6c-5bc9ed35c93a.png">

looks like we got lucky ... I mean our highly scientific method for picking the limit of 200 was a good choice ;)

**Comment by hugobowne** [comment]
that's great, Tim! I'll report back soon on numbers from FB also :)

> It is at 8am UTC. Does that make it a more reasonable time in your part of Australia?

I'll be there.

**Comment by hugobowne** [comment]
this is a nonsense idea for raising funds but i just watched an old ep. of curb your enthusiasm, in which they had a celebrity auction where people bid to have lunch with celebrities: https://www.imdb.com/title/tt0551425/

the nonsense idea is to have something similar for jupyter/binder w/ pydata and adjacent celebs:

e.g. your org can bid for fernando or brian to come give a lunch'n'learn and a q&a

ofc the pydata community is huge & it's low cost for community members & for a good cause.

also be careful that curb ep is slightly nsfoss

**Comment by hugobowne** [comment]
@betatim on another note, that was so much fun let's do this again!

i'm giving a 3 hour workshop on bayesian inference at odsc east, 04/14, starting at 930am ET: https://odsc.com/speakers/bayesian-data-science-probabilistic-programming/

the repo is one you've seen before ;) https://github.com/ericmjl/bayesian-stats-modelling-tutorial

ODSC says they will cap the workshop at 500 learners. May be a lot less as I'm competing with @amueller, @chendaniely, and @ericmjl for eyeballs! (also interested in what they're doing for setup, actually?)

Slightly different, situation: ODSC is charging attendees, however I'm not being compensated. Transparency so you all can make decisions around resources.

Side note: as more & more conference trainings go online, perhaps collaborations with conferences could be a method for funding?

**Comment by betatim** [comment]
I was mostly offline doing other things as it was Easter in Europe (four day weekend and chocolate!).

What do people think of bumping up the limit for the Bayesian stats modelling tutorial? https://github.com/ericmjl/bayesian-stats-modelling-tutorial

I would discuss the fundraising ideas at the team meeting and then start an issue if we want to pursue (one of) them.

**Comment by hugobowne** [comment]
about to take off!

**Comment by hugobowne** [comment]
@betatim @choldgraf FB Live metrics of interest FYI (as of directly after; significant engagement since also)

<img width="492" alt="Screen Shot 2020-04-15 at 3 34 24 PM" src="https://user-images.githubusercontent.com/4182382/79302056-91d37900-7f2e-11ea-8cf9-cdc970f91d9d.png">
<img width="495" alt="Screen Shot 2020-04-15 at 3 34 03 PM" src="https://user-images.githubusercontent.com/4182382/79302064-94ce6980-7f2e-11ea-9cc7-662e6c720226.png">

<img width="499" alt="Screen Shot 2020-04-15 at 3 34 27 PM" src="https://user-images.githubusercontent.com/4182382/79302073-9b5ce100-7f2e-11ea-8a5d-f8a3255b71f5.png">

<img width="525" alt="Screen Shot 2020-04-15 at 3 34 31 PM" src="https://user-images.githubusercontent.com/4182382/79302081-a283ef00-7f2e-11ea-939f-e07e8df38ddf.png">

**Comment by betatim** [comment]
Nice!

I didn't get around to bumping the limit for the bayesian stats repo :( It looked like you were discussing a colab alternative in the issues of the repo. Did things work out?

See y'all on the call tomorrow.

**Comment by choldgraf** [comment]
nice - way to go @hugobowne 

Sad that I will miss the call (Asia-friendly times != California-friendly times) but hello in advance from me, Hugo :-)

**Comment by amueller** [comment]
FYI I'm having everybody run locally. It usually mostly works, some people have to update their scikit-learn. I like people leaving a workshop with an environment they can use in the future.

**Comment by choldgraf** [comment]
@amueller what I usually do is either use binder as a safety valve for people that can’t run locally, or I do the tutorial in binder and then at the end have a session on setting up your own environment

**Comment by betatim** [comment]
Can you create a forum thread to discuss pros and cons of the approach? Thank you :)
