### ISSUE TITLE
Testing the support bot

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#279]
### Your personal set up

 - OS:
 
 - Version:
 
 - Configuration:

**Comment by choldgraf** [comment]
@GeorgianaElena should this be enough to trigger the bot?

**Comment by GeorgianaElena** [comment]
Yes, should be enough, but right now the bot is only configured for 3 repos: jupyterhub, binderhub and tljh (discussion about this here: https://github.com/jupyterhub/binderhub/issues/1087).

**Comment by choldgraf** [comment]
ah - we should document that in the team compass as well, then...maybe add a line for "Currently, the bot will only check the following repositories: [list-of-repos]" so people know what to expect?

**Comment by GeorgianaElena** [comment]
Good idea. Just added a new commit to the PR: https://github.com/jupyterhub/team-compass/pull/278/commits/78edd5a44f0a165dd710ac3caf589865d4fc6377

**Comment by choldgraf** [comment]
awesome, thanks :-)
