### ISSUE TITLE
Open list of JupyterHub / Binder Write-ups

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#28]
At our last meeting we discussed keeping a running list of JupyterHub / Binder write ups. We can use this issue to keep track of these for now, until it seems like there's a better place to put this information.

@jupyterhub/binder-team @jupyterhub/jupyterhubteam can you add links to any public talks, papers, abstracts, etc that you've submitted? Links to the raw materials etc would be great too - we wanna be able to provide as much content to remix as possible.

If you add comments below I'll add to the list in the top-level comment!

# Papers

* [Post Training Evaluation with Binder](https://docs.google.com/document/d/1AUTSzkvWKj4SDu1uIHwhfo8b5DzMf_ygpmswMTTbYXI/edit?usp=sharing) cc @jzf2101 

# Talks
* [The Past Present and Future of JupyterHub, MSDSE Summit 2017](https://drive.google.com/open?id=1PTFdG1IdAmftXbRLqvOqlE38nKNTjGYgsLlaEgRwCK0)
* [Interactive, convenient, reproducible. Pick two?, Swiss Python Summit 2018](https://github.com/betatim/talk-swiss-python-summit-2018)

# Workshops and tutorials
* [Ongoing google drive with JupyterHub/Binder teaching](https://drive.google.com/open?id=0B8VZ4vaOYWZ3V2tfRVU3NlN4dW8)
* [Binder Hackathon, UC Davis, Oct 2017](https://github.com/ctb/2017-binder-workshop-notes)

# Blog posts
* [Binder 2.0, eLife](https://elifesciences.org/labs/8653a61d/introducing-binder-2-0-share-your-interactive-research-environment)
* [Binder 2.0, a tech guide, Jupyter blog](https://blog.jupyter.org/binder-2-0-a-tech-guide-2017-fd40515a3a84)

**Comment by jzf2101** [comment]
Should we put this in an RST on the binder website?

**Comment by choldgraf** [comment]
I'm +1 on this

**Comment by choldgraf** [comment]
I think we now use the Discourse for this, so I'm gonna close this issue
