### ISSUE TITLE
Advertise discourse on the mybinder.org main page?

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#281]
Hey, I've been thinking about our motion to gently encourage support questions onto discourse and thought maybe it would be a good idea to advertise this more prominently on the main mybinder.org page.

We have a line that says "join the chat, read the docs, see the code" with links to our gitter, docs page and GitHub repo respectively. While it may break the catchy flow of this sentence, could we add something like "ask for support" and link to discourse?

I think there's also a case to be made for moving this further up the page so it's easier to find (that is, not right at the bottom :smile:)

**Comment by choldgraf** [comment]
I'm +1 on that, I think the Discourse is actually in general a better place to send people than the gitter room. What do others think?

**Comment by betatim** [comment]
How about "join the discussion, read the docs, see the code"?

**Comment by sgibson91** [comment]
I like it!

**Comment by sgibson91** [comment]
I've opened up a PR https://github.com/jupyterhub/binderhub/pull/1089. It changes the wording but I'm not sure the best way to go about moving the text further up the page.
