### ISSUE TITLE
Google meet - new features and my +1 to use it during our next team meeting

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#282]
During our last JupyterHub team meeting, we evaluated google meet. A common dislike was that we could not have a tiled view of the participants. This is now fixed, and they also added noise cancellation. I wonder how that works in detail, do they use the video feed to help like here perhaps? https://www.youtube.com/watch?v=zL6ltnSKf9k

Read more about the features here:
https://cloud.google.com/blog/products/productivity-collaboration/introducing-tiled-view-and-other-top-requested-features-in-google-meet

I can also make us record it btw.

**Comment by choldgraf** [comment]
I'm in principle happy with Google Meet. My open sourcey insides prefer something like Jitsi, but Meet is definitely more of a standard than Jitsi so maybe it'll have less cognitive burden?

**Comment by sgibson91** [comment]
I'm happy to give Google Hangouts another shot :-) We tried Jitsi in REG for our coffee breaks and the audio quality was terrible. We're not sure if that was related to the number of people joining the call though.

**Comment by manics** [comment]
I thought we used Google Hangouts last time. Was it actually Google Meets?

**Comment by sgibson91** [comment]
This blog post suggests to me that they are the same in functionality but Meets supports more people (enterprise version of Hangouts) https://zapier.com/blog/google-hangouts-meet-guide/

**Comment by betatim** [comment]
We use Meets (I didn't know there was a difference :) at work. It seems some people already see the many-tiles layout and some don't So right now we have some people on calls that have the cool/useful layout and some who are still on the old one. We can't work out what the system is and think they are slowly rolling it out?

**Comment by consideRatio** [comment]
Yepp we used my sundellopensource.se google suite's Google Meet!

@sgibson91 thanks for the link untangling the meet / hangout confusion I've had!

**Comment by yuvipanda** [comment]
We currently continue to use Google Meet, right? Can this be closed now?

**Comment by sgibson91** [comment]
Yeah - thanks for the cleanup @yuvipanda!!!
