### ISSUE TITLE
Hubs Team Meeting: May 2020

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#285]
Hello everyone!

Reminder that our next meeting is **Thursday, May 21st, 2020** at 5PM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2020-05-21/17:00/Hubs%20Team%20Meeting)). 

* [Agenda - HackMD](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both)
* [Video - Google Meet](https://meet.google.com/xwg-yizm-miq)
* [Calendar - Google Calendar](https://calendar.google.com/calendar?cid=c3VuZGVsbG9wZW5zb3VyY2Uuc2VfczdndDc4ZGlwY2dscTRlMzI4dWluOGoycmdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

These calls are open to **anyone**, so please join us! We love seeing new members on the call 😄

**Comment by sgibson91** [comment]
@consideRatio Are you happy to provide another hangouts link and add it to the issue and hackmd please?

**Comment by consideRatio** [comment]
Done! Should we perhaps record this one?

**Comment by sgibson91** [comment]
Thank you! Sure, sounds good :)

**Comment by choldgraf** [comment]
Hey all - just a reminder that this is happening today! (in about 2 hours)

**Comment by minrk** [comment]
Running a bit behind, but I’ll be there!
