### ISSUE TITLE
Chris announcement (and reduced availability around August)

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#287]
Hey all - I just wanted to give you a quick heads-up and piece of news...

Claire and I are going to have a baby! :tada: :baby_chick:

Our little girl is expected in early August. I'm looking forward for her to meet you all one day :slightly_smiling_face:

I'm planning on significantly reducing my working time once she's born, for at least a couple of months (it will either be a couple of months immediately in August, or a couple of months later on around 2021 or so...we are figuring out the logistics given the uncertain working arrangements we all have these days).

Just wanted to give a heads up. Hopefully this news brings a little bit of joy to your day!

**Comment by sgibson91** [comment]
Congratulations! 💖🎉💐 Sending my best wishes!

**Comment by consideRatio** [comment]
Wow congratulations!!! :heart: :baby: :tada: Lots of love from Sweden!

**Comment by choldgraf** [comment]
Hey all - I want to announce the release of a new project that we have been working on! It is not the most functional tool yet but I'm sure it'll do great things for the world one day ;-)

After many months of hard work I am happy to share with you:

Léonie Kathleen Holdgraf (pronounced lay-oh-knee)

![image](https://user-images.githubusercontent.com/1839645/91602943-f82ac800-e920-11ea-8516-e77b63609a43.png)

Born August 19th at 4:05pm, at 8lbs 5oz

Hoping you all are well, and that this brightens your day a little bit!

**Comment by yuvipanda** [comment]
BIG BABY! <3
