### ISSUE TITLE
jupyterhub/pebble-helm-chart - OK? LICENCE?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#289]
To enable testing of HTTPS setups of Z2JH and derivative charts like, BinderHub and Pangeo, I've created a Helm chart to deploy Pebble - an ACME server like Let's Encrypt.

My plan is to have that Helm chart's code base at https://github.com/jupyterhub/pebble-helm-chart, and publish the package helm chart at https://github.com/jupyterhub/helm-chart alongside JupyterHub and BinderHub. And, to see if the [letsencrypt github org](http://github.com/letsencrypt) would like to take it over, as they have developed [Pebble](http://github.com/letsencrypt/pebble) itself.

## Questions
1. Sounds ok?
2. What LICENSE file to use?

**Comment by manics** [comment]
👍 

If we're maintaining it having it under https://jupyterhub.github.io/helm-chart/ sounds fine.
Note I've got a PR open which should ensure the new helm chart will appear, though an additional change will be needed to have it also appear as stable: https://github.com/jupyterhub/helm-chart/pull/107

If letsencrypt take it over would they still want it hosted under JupyterHub?

LICENSE: any reason not to use BSD 3-Clause License which most Jupyter repos seems to use?

**Comment by yuvipanda** [comment]
Thank you for getting this done! 

3-BSD seems appropriate...

**Comment by betatim** [comment]
Nice! 

Did you see https://github.com/jetstack/cert-manager/tree/master/devel/addon/pebble? Could we reuse that and farm some of the maintenance work out to jetstack?

**Comment by manics** [comment]
@consideRatio Can we close this? https://github.com/jupyterhub/helm-chart/pull/109

**Comment by consideRatio** [comment]
Thanks for all input about this! The Pebble helm chart is functional, documented and released.

Just a final clarification about the license, I've seen various versions of what name is put in the LICENSE file, what makes sense? I figure'd I'll switch it away from Erik Sundell to something, but what?

Here are some different files from various repos:
https://github.com/jupyterhub/kubespawner/blob/master/LICENSE
https://github.com/jupyterhub/jupyterhub-idle-culler/blob/master/COPYING.md
https://github.com/jupyterhub/traefik-proxy/blob/master/LICENSE

**Comment by minrk** [comment]
I think the kubespawner one is most correct

**Comment by consideRatio** [comment]
Thanks @minrk! Going with that!
