### ISSUE TITLE
Update the public calendar with new meeting info

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#293]
The calendar location is out of date (it points to the old calpoly link). If we're using Google Meet, we may be generating a new video link each week. I suggest we just add a link to the HackMD in the calendar, since that's persistent across meetings. So we could set the location and description to "For video links see https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both"

I tried editing this myself, but it told me that it would only be working for my own entry...maybe @Zsailer is the only one that can edit this? Or maybe I just don't have permissions?

**Comment by manics** [comment]
I've updated it (at least I think I have!)

**Comment by manics** [comment]
Also there's a `Add Google Meet video conferencing` button which might be useful?
![image](https://user-images.githubusercontent.com/1644105/82587132-88be7300-9b90-11ea-84a3-f1703cbdc135.png)

**Comment by choldgraf** [comment]
@manics looking at the invite now, could we put this link in the description rather than the "location"? That way it will be copy/clickable rather than point to Google Maps

**Comment by manics** [comment]
I've changed it only the URL is in the location- it's now clickable. Also added it to the description.

**Comment by choldgraf** [comment]
ah perfect, thanks :-)
