### ISSUE TITLE
Hubs Team Meeting: June 2020

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#297]
Hello everyone!

Reminder that our next meeting is **Thursday, June 18th, 2020 at 8AM UTC** (or your [timezone](https://arewemeetingyet.com/UTC/2020-06-18/08:00/Hubs%20Team%20Meeting)). 

* [Agenda - HackMD](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both)
* [Video - Google Meet](https://meet.google.com/was-uqcr-qkm)

These calls are open to **anyone**, so please join us! We love seeing new members on the call 😄

**Comment by sgibson91** [comment]
Hoping someone else can chair this time. I will be simultaneously in this meeting, attending e-Rum and accepting delivery of my new bed 😅

**Comment by consideRatio** [comment]
Thanks for being the chair the last time @sgibson91!!! :heart:

**Comment by choldgraf** [comment]
I probably can't chair this one as it'll be 1am for me 😬 thanks @sgibson91 for chairing last time!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-can-i-support-mybinder-org/4692/4

**Comment by betatim** [comment]
I can chair it.

**Comment by sgibson91** [comment]
Hi @consideRatio, do you mind providing a Google Meet link again? I was going to host it but I think my eRum talk now clashes with the meeting

**Comment by sgibson91** [comment]
I can probably make this meeting but 15 minutes late as that's when the Q&A panel for my session at e-Rum 2020 finishes.
