### ISSUE TITLE
A bot to welcome first time contributors

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/team-compass#298]
### Proposed change

Add a bot to welcome new contributors when they open their first issue and/or PR.
Relevant discussions about this so far:
* https://github.com/jupyterhub/team-compass/issues/288
* https://github.com/jupyterhub/.github/issues/7

The downside is that a *first time contributor* from the welcome's bot point of view is someone new to a repository and not an org. So, someone opening up first-issues across many different repositories in the same org will be welcomed each time.

But maybe a short message and a cute picture won't make the message very annoying
| [Welcome msg link](https://github.com/GeorgianaElena/test-bots/issues/1#issuecomment-640699760)             |  [Congrats msg link](https://github.com/GeorgianaElena/test-bots/pull/2#issuecomment-640703081) |
:-------------------------:|:-------------------------:
![welcome-screenshot](https://user-images.githubusercontent.com/7579677/84070943-9a4bab80-a9d5-11ea-80d4-b21b97077cdb.png) | ![congrats-screenshot](https://user-images.githubusercontent.com/7579677/84070954-9f105f80-a9d5-11ea-99e8-1be7c35db283.png)

What do you think?

**Comment by sgibson91** [comment]
This looks so cute I love it! :sunflower: Did you draw the pictures yourself?

**Comment by consideRatio** [comment]
WOW! :D YES!!!!!!!!!!!

Where does the art come from?

**Comment by GeorgianaElena** [comment]
I'm so happy you like them :heart:

>Did you draw the pictures yourself?

yes :see_no_evil: I didn't know you can have images with bots messages until I saw the welcome bot in action @ The Turing Way. They are so beautiful and warm.

**Comment by sgibson91** [comment]
@GeorgianaElena you are incredibly talented!

**Comment by betatim** [comment]
Lets do this! The drawings are super cool. Once upon a time we had the idea of showing images to people while they wait for the binder to start ... now that we have someone with drawing skills we should revive that idea :D

**Comment by sgibson91** [comment]
I found the meeting notes with the original idea. A year ago! 😱 https://github.com/jupyterhub/team-compass/blob/master/docs/monthly-meeting/2019-02-21.md
