### ISSUE TITLE
Add yourself to the teams in the README.md

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#3]
Hi all,

Please add yourselves to the README under teams. Thanks.

**Comment by jzf2101** [comment]
@Zsailer ?

**Comment by choldgraf** [comment]
I'm gonna close this, as I think the original audience interested in this issue is up there now. @Zsailer if interested you should definitely add yourself on the new team-compass "teams" page! https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html
