### ISSUE TITLE
Use PR docs previews with ReadTheDocs instead of CircleCI

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#306]
@GeorgianaElena recently told me that ReadTheDocs now does documentation previews in PRs! https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Currently, we're doing previews with a combination of CircleCI + (in some cases) a GitHub Action to show a preview link for the docs. I think it'd be much simpler if we just used the RTD documentation previews for this!

**Comment by manics** [comment]
We're already doing this repo by repo. Should we close and let it happen organically?

**Comment by choldgraf** [comment]
I thought this might be nice to document in our team practices, so opened a short PR here: https://github.com/jupyterhub/team-compass/pull/481
