### ISSUE TITLE
Summary of mybinder SciPy 2020 requests

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#310]
I thought it'd be handy to have all the [resource requests](https://github.com/jupyterhub/mybinder.org-deploy/labels/impact) for SciPy 2020 (next week!) in one place:

- [Increase limit for SciPy tutorial (Bayesian) to 300](https://github.com/jupyterhub/mybinder.org-deploy/issues/1476)
  - 9am CDT Monday 6 July
- [Increase limit for SciPy tutorial (Deep Learning) to 300](https://github.com/jupyterhub/mybinder.org-deploy/issues/1477)
  - 9am CDT Wednesday 8 July
- [Increase limit for SciPy tutorial (Xarray) to 300](https://github.com/jupyterhub/mybinder.org-deploy/issues/1479)
  - 5:45a - 11:00a PT, Thursday 6 July
- [Increase limit for SciPy tutorial (Conda) to 300](https://github.com/jupyterhub/mybinder.org-deploy/issues/1480)
  - 9 am - 1 pm CDT, 9 July
- ~[Requesting bump resources for Bayesian stats tutorial](https://github.com/jupyterhub/mybinder.org-deploy/issues/1481)~
  - ~8 am to 12 pm CDT, 6 July~
- [Increase limit for SciPy tutorial (Dask) to 300](https://github.com/jupyterhub/mybinder.org-deploy/issues/1483)
  - 9AM - 1 PM CT, Tuesday 7 July

**Comment by choldgraf** [comment]
this is a good idea - also, wow! that's a lot! I wonder if there is some kind of way that we could get a little bit of resources from Enthought to help out with this. I mean, they are paying the instructors and taking in $$ for the conference after all. Could we ask them to donate to the Jupyter NumFocus account or something?

**Comment by manics** [comment]
One person has offered to donate: https://github.com/jupyterhub/mybinder.org-deploy/issues/1480
> I am currently arranging for Enthought to donate this stipend to the Python Software Foundation. I would be happy to push some or all of this money your way if possible. Given the number of tutorials that are using mybinder.org perhaps Enthought could work something out to help push some of the donated stipend money your way.
