### ISSUE TITLE
JupyterCon 2020

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#312]
Bringing conversation over from gitter:

[JupyterCon](https://jupytercon.com) is going to be online, October 5-17 this year. We should probably coordinate some talk/tutorial proposals related to JupyterHub

Relevant dates:

- Authors submit proposals by ~July 20~ July 22, 2020
- Authors receive proposal accept/decline decision August 10-12, 2020
- Authors upload talks by September 11, 2020

so we don't have a lot of time to come up with proposals. I figure we'll talk about this at the next meeting (#308), but good to get the conversation going before then, since the due date is only a few days later.

Summarizing from gitter:

- @choldgraf and @sgibson91 expressed support, but not enough time to lead/submit themselves.
- @arnim and @bitnik have been discussing their Binder persistence project
- @betatim proposed:
  - "you know what mybinder.org is, here are five uses that you didn't know and number four will shock you"
  - talking about things like thebelab and various other ways of using mybinder.org that isn't necessarily "start a binder and get a notebook"

Doing an updated run of zero-to-jupyterhub as a tutorial is probably always a good idea. We could also switch it up and try tljh this time!

I think it might also be worth submitting a talk on the management/bot work that's been going on across the org, if the folks leading that would be interested.

**Comment by yuvipanda** [comment]
I was encouraging @GeorgianaElena to do a TLJH talk as well :)

**Comment by betatim** [comment]
Another thing to consider is taking part in the sprint. If we have the bandwidth to take on new contributors that would be a great event. I think it would be great to have more/new contributors but I am not sure we are setup well enough to handle an influx of inexperienced contributors right now. I don't know if this means that we don't want to take part or if we use it as a chance to improve our onboarding.

**Comment by rkdarst** [comment]
Once I gave a talk "JupyterHub ≠ x, ∀ x", which was based on my theory that most people don't know what JupyterHub is and isn't and how all of the components relate.  One of the key messages was that you shouldn't look at JupyterHub as a service, but an interface to resources.  Any resources that are accessed by an ssh server, there could be JupyterHub to make it more usable.  And to design your resources first, then how JupyterHub accesses them.  The target audience was a bunch of infrastructure people (and reflects my HPC/batchspawer background, not the k8s side so much).

I don't know if JupyterCon would be the target audience for this, but in my limited searching I hadn't found anything that did this.  So, this is what I can suggest (and could be probably convinced to help do it...)

**Comment by manics** [comment]
> most people don't know what JupyterHub is and isn't and how all of the components relate.

This gave me another idea: "10 (common?) misconceptions about JupyterHub".

> Any resources that are accessed by an ssh server, there could be JupyterHub to make it more usable.

Getting off-topic, but I use a configuration management system called Ansible a lot, and for fun I recently wrote [AnsibleSpawner](https://github.com/manics/jupyterhub-ansiblespawner), and Ansible can do almost anything infrastructure related 😀.

**Comment by sgibson91** [comment]
I've just had a run-through of the CFP platform if anyone has questions! 🙋🏻‍♀️

**Comment by choldgraf** [comment]
I have a question @sgibson91 are they willing to let infant children give presentations?

**Comment by manics** [comment]
> I have a question @sgibson91 are they willing to let infant children give presentations?

Only if they're accompanied by goats

**Comment by sgibson91** [comment]
> > I have a question @sgibson91 are they willing to let infant children give presentations?
> 
> Only if they're accompanied by goats

I am strongly encouraging all of this.

**Comment by yuvipanda** [comment]
I'm thinking of:

- "JupyterHub isn't just for Jupyter" - focusing on jupyter-server-proxy - voila, shiny, RStudio, Linux desktop, etc. Possibly with @ryanlovett?
- "Distributing content with nbgitpuller" - Possibly a poster, rather than a full 30minute talk. Very useful tool.
- "Zero to Continuous Deployment with JupyterHub & Hubploy" - Talk about https://github.com/yuvipanda/hubploy and how it can be used (with https://github.com/yuvipanda/hubploy-template) to setup a continuously deployed hub quickly, and why you would do it.

I am thinking I might submit more posters than talks - feels like I've been mostly working on many small things than anything big...

**Comment by minrk** [comment]
Posters are a great idea - I think there are a lot of small things that are cool and good to share in a venue like this.

**Comment by manics** [comment]
I probably won't be at the conference, but I'm happy to help with preparing talks or posters.

**Comment by rkdarst** [comment]
Last year, I said I would write a blog post "The tale of two JupyterHubs", where I describe my two hubs and how they don't just integrate, they are part of other services.  Now I'm thinking of submitting this as a proposal.

The goal is to address all of the people who don't understand what JupyterHub is: they think it's only a separate service, not something that can fit into a whole infrastructure.  That it's not a new thing to do, but is another way of accessing your existing resources.

I guess we make separate submissions, so I'll go ahead and submit.  But if you want to do more coordination, let me know.

**Comment by arnim** [comment]
A preliminary and short [proposal](https://docs.google.com/document/d/17AcnNldeKdyO-Cf-2yhH57FSZJ0ZwNo-oVsm2Z-nLKM/edit?usp=sharing) for a talk on the *"Persistent BinderHub: Democratizing access to Computational Resources in the Social Sciences"*. So fare we have not submitted ... so feedback on what we can improve or what you would like to see is always welcome ;) (cc @bitnik)

**Comment by rkdarst** [comment]
My proposal is here: https://docs.google.com/document/d/11nZpTvzbReqz62zcxAIuEsbrZouNV01xFMjuWoq_mfM/edit.  I settled on a title combining my two titles: "JupyterHub ≠ x, ∀ x: A tale of two JupyterHubs".

I'm happy for any advice or co-authors/co-presenters (however that works online...).

**Comment by minrk** [comment]
Proposals are due today!

I'll submit an overview talk about JupyterHub, what it is and what it isn't, including some "what's new" overview across the project. Given that everything needs to be wrapped up and published at the beginning of September, I can't be involved in as many things as I have in the past, and getting a three hour tutorial completely together in that timeframe would be a pretty huge effort when there's a lot else going in August as well.

Drafting [here](https://hackmd.io/vT-LPcosTSO_SXOF4WoCww). I'm happy to include copresenters, if anyone would like to do a segment focusing on z2jh, etc. I'll submit early this evening Europe-time (probably before noon in California)

**Comment by GeorgianaElena** [comment]
I've submitted a proposal for a TLJH talk, link [here](https://hackmd.io/o1osn1DTTIeyMMJyNqz9Cg).
Yuvi was very kind and helped me a lot with the content (thanks @yuvipanda :heart:). The proposal it's still editable until the deadline, so any suggestions are welcomed.

If I manage to get something decent until midnight :crossed_fingers:, I will try to submit one for a poster about the CIR experience and bots.

**Comment by minrk** [comment]
Given the CFP's emphasis on new and the fact that folks have other, more specific talks, I may cancel the general overview talk, since the more specific ones are less repetitive with prior presentations.

Instead, I think I'll shift over to a poster about the scaling limits of JupyterHub and the barriers to horizontal scaling / HA (basically, try to present [this](https://github.com/jupyterhub/jupyterhub/issues/1932#issuecomment-658031232)). @Vildeeide and I will also submit a poster about what we have found exploring repo2docker for measuring reproducibility.

**Comment by rkdarst** [comment]
I've left comments on the hackmd proposals (not sure if authors get notified or if they are easy to see... I've missed them before).

@minrk our proposals did start to seem rather similar and was wondering how they could be combined.  I really liked your latest wording and vision of the talk, and was also wondering if mine wasn't needed.  I guess it's too late to re-organize, but we can see in the preparation stage.  I'm thinking to include snipets from other people, if I can find time to prepare it so well...

**Comment by betatim** [comment]
If any of you have spare time and brain cycles at short notice: please take any or all of my suggestions/ideas and submit a talk for them if you want to. I won't be submitting anything. My silence over the last week(s) is because moving flats, all the "container packaging and shipping" followed by "deployment" at the new location (oh yes, container jokes...so funny) and admin related to that has taken over my life.

**Comment by minrk** [comment]
@rkdarst I think you should definitely proceed with your proposal, and feel free to take anything you think is useful from what I started to sketch out. I'll happily help out with editing/recommendations, but I think that's better than my overview idea, which was mostly because it's what we've done before for JupyterCon.

**Comment by choldgraf** [comment]
Hey all - I'm not planning on anything specifically jupyterhub-related, though the 2i2c founding team is submitting a talk about [2i2c](https://2i2c.org) which will involve a lot of discussion of our attempts at deploying JupyterHub at scale in the past (Berkeley/Syzygy/Pangeo). That said, I don't think it'll overlap with the ones here much - it's more about "organizational and sustainability" challenges rather than technical ones.

That said, I am happy to help review anybody talk proposal if they would like me to. Please do not hesitate to reach out to me today and I'll make some time to give it a look!

**Comment by consideRatio** [comment]
I'm happy to help with Z2Jh matters, but didn't want to take on responsibilities during the dates when JupyterCon is held due to vacation plans.

**Comment by yuvipanda** [comment]
I'm working on a jupyter-server-proxy talk (thanks to @GeorgianaElena for help!). Hope I get it done.

I was going to make a poster for nbgitpuller, but realized there is a blog post draft from almost a year ago! https://docs.google.com/document/d/1-DULS3KAm8BO2b5lZ14Tmkq46QI5c8pNRGOwqdX3LcE/edit?usp=sharing so I'll just clean it up and post it on the Jupyter blog instead.

**Comment by minrk** [comment]
I've submitted the [jupyterhub-scaling-limits poster](https://hackmd.io/2Ly6b_eRTsyIsHZHPHRrkA) and [measuring reproducibility with repo2docker poster](https://hackmd.io/UjpF5YS7QVy8hvSPL1GPrQ).

**Comment by sgibson91** [comment]
CFP has just been extended to Wednesday

**Comment by choldgraf** [comment]
lol well I guess I can reconfigure the rest of my day then

**Comment by yuvipanda** [comment]
woop woop. Now working with @Zsailer on a jupyter telemetry talk: https://hackmd.io/Xeks4-3CRLKAsPbycBOuig

**Comment by yuvipanda** [comment]
I think I'm fairly complete on a talk about jupyter-server-proxy: https://hackmd.io/rfsuyH_aRTqk9hSwMd_ZCg. Would *love* to hear comments. @GeorgianaElena has already been very helpful :)

**Comment by sgibson91** [comment]
Looks really cool @yuvipanda!

**Comment by yuvipanda** [comment]
I also wrote a proposal for 'JupyterHub from scratch' (https://hackmd.io/ZbWI3_hETqi5okwfsMyxSA). I think I'll help write up github.com/jupyterhub/jupyterhub-the-hard-way along the way, and use that for the talk (if it gets accepted)

**Comment by sgibson91** [comment]
> I also wrote a proposal for 'JupyterHub from scratch' (https://hackmd.io/ZbWI3_hETqi5okwfsMyxSA). I think I'll help write up github.com/jupyterhub/jupyterhub-the-hard-way along the way, and use that for the talk (if it gets accepted)

This sounds like something I already want to attend! Can't believe I actually haven't done this! :joy:

**Comment by rkdarst** [comment]
> I also wrote a proposal for 'JupyterHub from scratch' (https://hackmd.io/ZbWI3_hETqi5okwfsMyxSA). I think I'll help write up github.com/jupyterhub/jupyterhub-the-hard-way along the way, and use that for the talk (if it gets accepted)

I'm somewhat interested in this, too, since from what I can tell most
HPC system deployments are "the hard way" and in fact what I did
first.  Perhaps this can be a motivation to finish
jupyterhub/jupyterhub#2726 which is somewhat of a prerequisite?

**Comment by yuvipanda** [comment]
This happened, and it was pretty cool :) <3 Thanks everyone for your talks!
