### ISSUE TITLE
Move `thebelab` into this organization?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#313]
# Background

`thebelab` is a javascript tool written by @minrk that operates on "static" HTML blocks and does the following:

1. Converts them into editable code-mirror cells
2. Requests a kernel from a Jupyter server either on Binder (most common), JupyterHub, or a local jupyter server
3. Hooks up the cells so that you can run them and display the output in-line.

Check out the docs for Thebelab here: http://thebelab.readthedocs.org/

and a related project I've got that integrates it with sphinx here: https://sphinx-thebelab.readthedocs.io/en/latest/

also worth noting that it looks like `thebelab` will soon be re-named to `thebe`.

# Moving into this org

We think that Thebelab could be quite a useful tool for people to build on top of, and are wondering if the JupyterHub community is willing / interested in taking over stewardship of this repository. We've discussed this a bit here: https://github.com/minrk/thebelab/issues/214

I think it could be in-scope for JupyterHub because Thebelab uses JupyterHub / Binder infrastructure under the hood when requesting kernels. That said, I also want to recognize that the thebelab codebase is a bit different from our JupyterHub projects (it is almost entirely a javascipty/npm project).

What do folks think about this? Pros, cons?

**Comment by yuvipanda** [comment]
+1 from a governance & signalling standpoint. configurable-http-proxy is also in this org & is a pure JS project.

**Comment by betatim** [comment]
I think JupyterHub would be a good home for thebelab. Though I think there is a (very very) small number of people who currently maintain/work on thebelab. Increasing that maintainer base would be the next thing to work on, no matter where the project moves.

@joelachance do you have time and interest to maintain (haha) your level of involvement in thebelab?

**Comment by choldgraf** [comment]
> Increasing that maintainer base would be the next thing to work on, no matter where the project moves.

💯 agree - I hope it'll be easier to do this as a part of the jupyterhub org

It would be awesome to see @joelachance continue helping out!

**Comment by joelachance** [comment]
Hello! I'll admit I'm not terribly familiar with JuypterHub, but from what I can tell this seems like a great place for Thebelab. +1 for what @betatim mentioned, I also agree.

@betatim as for time, I have _some_  to offer, although it's limited. My workload fluctuates quite a bit which makes it difficult to consistently be around. And as for interest-- I won't claim this is my passion project, but absolutely like helping out where I can!

In regards to additional contributors, I've put a message out on my alumni Slack channel for recent grads to help out. I'm offering some mentorship/handholding through the process, and I think Thebelab has some simple enough issues that some eager grads might be interested in spending some time on.

Curious everyone's thoughts!

**Comment by minrk** [comment]
Summarizing some conversation during our JupyterHub meeting yesterday: there are mixed preferences from our side on whether JupyterHub or executablebooks seems like the most natural home, but I don't think there would have been an objection to bringing it here if executablebooks hadn't been available as a possible alternative (I could be wrong there, this question wasn't posed exactly). So depending on feedback at https://github.com/executablebooks/meta/issues/72, I think it makes sense to land either here or there.

**Comment by choldgraf** [comment]
FYI folks in the `executablebooks` org seem to generally be happy w/ it taking over `thebelab` (at least, it seems there is more overlap there "conceptually" w/ what Thebe does). Just keeping folks updated, and would be happy to hear anybody's thoughts over there as well: https://github.com/executablebooks/meta/issues/72

**Comment by choldgraf** [comment]
OK this got moved to `executablebooks/` last night! So I'm gonna close this one here. If anybody would like to help out with `thebe` I 💯 invite you all to help maintain and improve this tool! :-)
