### ISSUE TITLE
GitHub action feature - run job only on changes to specific paths

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#314]
Imagine that you have a repo with docs, and a python package, and a helm chart. Then perhaps you want to trigger CI jobs depending on what changed in a merged PR.

[GitHub actions has such feature](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths)! I just wanted us all to know about it so we can build better automation.

I'll try it out in https://github.com/neurohackademy/nh2020-jupyterhub where I only want to build the GitHub pages hosted documentation when the folder `book` changes which contains a jupyter-book.

**Comment by choldgraf** [comment]
ah very cool! Maybe we can start off by trying this out on a documentation build somewhere?
