### ISSUE TITLE
Proposal: Moving repo2docker Action the Jupyter Org?

### ISSUE THREAD

**Issue by hamelsmu** [jupyterhub/team-compass#315]
I have been working on a GitHub Action for the wonderful repo2docker and related binder project:

https://github.com/marketplace/actions/repo2docker-action

I think this CI tool could be really valuable for the community but does require maintenance.  It might be beneficial if the repo was part of the Jupyter org to get more visibility and attract more contributors.   

Again, my plan is to keep maintaining it, either way.   However even people filing issues and bugs would be really helpful and would allow me to make progress faster (and I think having this in the Jupyter org may help with that).   This is just a proposal, I understand that including a new project requires careful consideration.  

cc: @betatim @choldgraf @willingc

**Comment by choldgraf** [comment]
I think this is a cool idea - a lot of Binder folks use GitHub, and I've even seen patterns like the one this action enables used in the Jupyter community (I believe the JupyterLab team has a heroku bot that posts a Binder link for new PRs).

Taking a quick look at the repository, I think we could add two things:

1. Some Sphinx documentation (though maybe @hamelsmu can advise if this is not-standard in the actions world, and instead people just use the README?)
2. Some contributing documentation (either as part of Sphinx docs, or in a `CONTRIBUTING.md` file. Something that explains how everything works, how people could get up-and-running to contribute to the repo.

Maybe we can discuss this at the team meeting tomorrow?

**Comment by willingc** [comment]
Great idea. I think that having this accessible for users would be fantastic. Documentation is key and even a GIF as a how to would be fabulous. I'm supportive of moving this repo. I will likely miss the team meeting tomorrow but I think the next step would be sending a message from Chris/Tim/Hamel/me to the steering council requesting the move to the JupyterHub (my preference - I really wish that we had bit the bullet a few years ago and moved repo2docker to JHub org) or Jupyter org.

Thanks @hamelsmu and @choldgraf.

**Comment by willingc** [comment]
Oh @choldgraf whoever set up the welcome bot rocks. The image is adorable 💯

**Comment by choldgraf** [comment]
@willingc that bot was created by, and the image is proudly drawn by our very own @GeorgianaElena :-)

**Comment by hamelsmu** [comment]
@choldgraf should I come to this meeting?  

I'm happy to write docs, do you think Sphinx is appropriate given this isn't a python library and a GitHub Action with very limited interface surface area?  Perhaps I can put what is on the README in [just the docs](https://github.com/pmarsceill/just-the-docs)?

What do you think?

**Comment by sgibson91** [comment]
@hamelsmu It is an open meeting so you are more than welcome to attend :) https://github.com/jupyterhub/team-compass/issues/308

**Comment by MSeal** [comment]
Although I'm an outsider somewhat to jupyterhub development cycles, I think this is a great change and would add user trust, comfort, and visibility to using the action. e.g. I'm taking a deeper look as I think I have a nice usecase for using this and I hadn't discovered it before.

**Comment by hamelsmu** [comment]
Hi @MSeal 

> Although I'm an outsider somewhat to jupyterhub development cycles, I think this is a great change and would add user trust, comfort, and visibility to using the action

Just want to make sure I understand the suggestion, what are you referring to wrt: trust, comfort, visibility?  Are there more docs or something I can add to the repo?  Let me know!  Really appreciate your suggestions and feedback thanks so much.

**Comment by hamelsmu** [comment]
@MSeal and I am so excited about the fact that you might have a use case, please do share!  I really would love to know if there are any additional features or something I can add ❤️

**Comment by MSeal** [comment]
> EDIT: I think you mean moving this into the Juptyer org would provide more trust, comfort visibility. Sorry for being dense

Yeah that's what I meant. I don't think you were being dense -- I maybe didn't word it well.

> @MSeal and I am so excited about the fact that you might have a use case, please do share! I really would love to know if there are any additional features or something I can add :heart:

I need to find some time to play with it to see what would be useful, but I was thinking of automating a sphinx or mkdocs repo integration testing for the code example included. Specifically I was looking at generating / augmenting a sphinx doc site out of notebooks and hosting them in a way where you could live execute the code snippets on-demand without needing to launch a binder page (or for when you want a private docs page that's interactive). The GH Action would help keep the repo setup easy and provide the ability to execute those snippets with a working kernel / environment.

**Comment by hamelsmu** [comment]
> Specifically I was looking at generating / augmenting a sphinx doc site out of notebooks and hosting them in a way where you could live execute the code snippets on-demand without needing to launch a binder page (or for when you want a private docs page that's interactive). The GH Action would help keep the repo setup easy and provide the ability to execute those snippets with a working kernel / environment.

Sounds like a really fascinating project.  I didn't realize there was a way to do this!  Let me know if you run into any issues or roadblocks with this Action or with GitHub Actions in general.   Can't wait to learn more about what you end up building, will keep an eye out 👀 , please tag me on GitHub whenever you build it would love to follow along.

**Comment by choldgraf** [comment]
@MSeal I do stuff like that with a new project I've been working on called `sphinx-thebe` - you should check it out! https://sphinx-thebe.readthedocs.io/en/latest/

**Comment by MSeal** [comment]
Well I am definitely behind on keeping up with projects! I'll have to take a look at that next week as well. Thanks for pointing it out

**Comment by minrk** [comment]
We do have a [process for adoption of repos across Jupyter-governed orgs](https://jupyter.org/governance/newsubprojects.html#incorporation-of-an-existing-external-subproject) by going through a JEP. I did propose [a change](https://github.com/jupyter/governance/pull/83) to reflect the fact that teams can decide to adopt repos without going through JEPs, as has been the case for most repo adoptions in practice, but the most useful part of the doc is the [criteria for adoption](https://jupyter.org/governance/newsubprojects.html#criteria-for-official-subprojects), which includes considerations. Please feel free to propose updates to those criteria, if folks have them.

**Comment by hamelsmu** [comment]
@betatim do you think I need to fill out a JEP as @minrk has pointed to above, or another process?  Happy to do whatever is recommended

**Comment by choldgraf** [comment]
IMO I don't think this needs a JEP - the action feels well-scoped to JupyterHub and doesn't affect the other Jupyter orgs. There also seemed to be consensus amongst the JupyterHub team that this was a good idea, so I don't think we need a JEP to resolve any disagreements there. Do others agree?

That said (not blocking moving the r2d action) - I agree with @minrk that we could bring over the language from the Jupyter governance docs about "criteria for adopting a project" into our own jupyterhub team docs for more guidance 👍

**Comment by minrk** [comment]
Yup, I don't think we need a JEP since we appear to have consensus here already. Setting a few tasks like a checklist for contributing docs, license, COC, etc.

For bringing things into jupyterhub docs, we could have specific cases mentioned, like we are happy to host community-maintained Spawners, Authenticators, etc. in this org. and link to the central docs for more info.

**Comment by hamelsmu** [comment]
@choldgraf @betatim I've made you both admins on the repo to facilitate the transfer, is this all that is needed in order to move the repo?  Also, I suppose I should be added as a maintainer for the transferred repo?   Please let me know if there is something I need to do to facilitate the transfer.

**Comment by sgibson91** [comment]
Definitely not a blocker but I think the contributing guidelines and code of conduct should reference the Jupyter guidelines and CoC as well (this is something that BinderHub does, for example).

- https://jupyter.org/governance/conduct/code_of_conduct.html
- https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html

FYI, I realise the second link is broken and not very helpful in this context. I've opened [this issue](https://github.com/jupyter/jupyter.github.io/issues/377) to try and get it resolved.

**Comment by hamelsmu** [comment]
@sgibson91 I made the updates to the best of my understanding regarding what you suggested via https://github.com/machine-learning-apps/repo2docker-action/pull/35 

🎉  Really excited to have this repo be part of Jupyter 🎉

**Comment by choldgraf** [comment]
Just merged that in - anything else that we need to take care of?

**Comment by hamelsmu** [comment]
> anything else that we need to take care of?

My understanding is that it is ready to go, just waiting for an admin to push the buttons to do the transfer

**Comment by betatim** [comment]
Did you notice anything? :p Welcome to your new home: https://github.com/jupyterhub/repo2docker-action

**Comment by hamelsmu** [comment]
🥳  🎉  🎈  Wooo!  Yaay I am part of the cool kids (for the first time in my life) 🥳  🎉  🎈  

Thanks everyone

**Comment by sgibson91** [comment]
Definitely the first time I've been referred to as a cool kid! 😂
