### ISSUE TITLE
Planning how to sustain `gke.mybinder.org` for another year

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#320]
Hey all - the Google Cloud credits that have powered `gke.mybinder.org` for the last year **will run out on October 1st of this year**. We should plan how to keep this deployment (which powers most of mybinder.org usage) running for another year.

In the past we have sent lots of emails to folks that we knew in cloud companies (particularly, Google Cloud) to find someone that is willing to gift credits. We can try that again, but this time I will have an infant, and so I cannot be relied upon to be the one to do this.

Opening up this issue so that we can coordinate this effort and see if we can get another sponsorship from a cloud provider!

One extra note: we actually have ~$26,000 remaining and won't run out in October, so perhaps one step is to just ask for an extension in the credits.

**Comment by betatim** [comment]
Do you know how much we use per month at the moment? Then I could make concrete ask with the people I emailed with last year to get the credits: "we have 26k left, this would cover another X months, is it possible to extend them?"

**Comment by manics** [comment]
Turing is currently down pending a funding request: https://github.com/jupyterhub/mybinder.org-deploy/issues/1545
One of the questions there is whether to ask for an immediate renewal, or to delay until October. What effect does that have on how long the GKE credits will last?

**Comment by betatim** [comment]
I think we should renew the credits for Turing as soon as we can/have the resources to do so.

The limit of the GKE credits (as I understood it) is a date on which they expire. We aren't using them up quickly enough :(

**Comment by choldgraf** [comment]
@betatim yep that is correct - for billing data, a note to all that you can actually explore a (semi-recent) data dump of Binder billing at this repository:

https://mybinder.org/v2/gh/jupyterhub/binder-billing/master?filepath=analyze_data.ipynb

from the weekly plot it looks like we're in the ballpark of 1,500 - 2,500 a week. So something like $7,000-8,000 a month.

![image](https://user-images.githubusercontent.com/1839645/88200550-27039f00-cbfb-11ea-9851-2aacac3a892c.png)

So If we have $26K remaining and it's out in october, we may have about an extra 1.5 months or so, but actually not that much (which is good, cloud companies are happy when you use credits as-expected)

**Comment by choldgraf** [comment]
Hey all - another thought here: the CZI EOSS project is entering round 3 of proposals. I believe the deadline is August 4th. I dunno why I didn't think of this before, but I bet mybinder.org would have a good shot at being accepted for this award. I wonder what you all think about it?

We could either:

* Pitch it directly for credits for gke.mybinder.org and that's it. Maybe like $60-80K
* Include something else, like a Binder advocate, someone to help give workshops etc

What do folks think? August 4th is very soon but I am happy to work with others in putting together a proposal if we think it's a good idea.

**Comment by manics** [comment]
Launches per day for 2020 until 19 June, split by cluster, using @betatim's datasette:
https://binderlytics.herokuapp.com/binder-launches?sql=SELECT%0D%0A++strftime(%27%25Y-%25m-%25d%27%2C+`timestamp`)+as+date%2C%0D%0A++origin%2C%0D%0A++count(origin)%0D%0AFROM%0D%0A++binder%0D%0AWHERE%0D%0A++strftime(%27%25Y%27%2C+`timestamp`)+%3D+%222020%22%0D%0AGROUP+BY%0D%0A++date%2C+origin%0D%0AORDER+BY%0D%0A++date%2C+origin%0D%0A#g.mark=line&g.x_column=date&g.x_type=ordinal&g.y_column=count(origin)&g.y_type=quantitative&g.color_column=origin

![binder-datasette-launches-by-origin-2020](https://user-images.githubusercontent.com/1644105/88332249-24ea2f00-cd26-11ea-9ea7-89b2093943d4.png)

Cost per launch per cluster could be an interesting metric?

**Comment by sgibson91** [comment]
Why are `binder.mybinder.turing.ac.uk` and `turing.mybinder.org` so drastically different when it's the same cluster?

**Comment by manics** [comment]
The colours make it difficult to distinguish some of the lines.
https://binderlytics.herokuapp.com/binder-launches?sql=SELECT%0D%0A++origin%2C%0D%0A++count(origin)%0D%0AFROM%0D%0A++binder%0D%0AWHERE%0D%0A++strftime(%27%25Y%27%2C+`timestamp`)+%3D+%222020%22%0D%0AGROUP+BY%0D%0Aorigin%0D%0AORDER+BY%0D%0A++origin%0D%0A

Total counts for 2020:

origin | count(origin)
-- | --
binder.mybinder.ovh | 140
binder.mybinder.turing.ac.uk | 123
gesis.mybinder.org | 616182
gke.mybinder.org | 2235841
notebooks.gesis.org | 324632
ovh.mybinder.org | 169582
turing.mybinder.org | 208241


So maybe `binder.mybinder.turing.ac.uk` is just from testing?

**Comment by sgibson91** [comment]
Yes, that's probably right. I misread and thought the `turing.ac.uk` domain had more launches which made no sense to me! 😂 The numbers help, thank you

**Comment by choldgraf** [comment]
Also worth noting that CZI is specifically looking for a tie-in to the biomedical world:

https://twitter.com/ReaderMeter/status/1286473192123428865

so perhaps we can analyze the binder repos to show any that have the word "bio" in the repository title?

**Comment by choldgraf** [comment]
In case it helps us come up with a story here, I made a tiny meta repository that aggregates launch data for the last 7 months so it's easier to quickly grab:

https://github.com/choldgraf/binder-meta

feel free to use it to play around w/ launch statistics yourselves (or if you wish, push some changes that you think would be useful!)

Here's a simple analysis to look at launches / bio-related repositories, but I bet we can do better:

https://nbviewer.jupyter.org/github/choldgraf/binder-meta/blob/master/notebooks/analyze.ipynb

**Comment by choldgraf** [comment]
Is anybody in this thread interested in spearheading a CZI proposal? I can help write but I can't do it by myself, and also shouldn't be the PI on the grant since I'm the PI on the CIR grant (and since I'm having a baby in 1-4 weeks).

**Comment by sgibson91** [comment]
Sorry, I'm too swamped and over-worked right now 😔

**Comment by choldgraf** [comment]
Hmm - maybe we could just scope this proposal very narrowly so that it just pays for credits? That way it'd be much less overhead to run the grant itself (I guess the grant would just go to NumFocus and we'd use that to pay for `gke.mybinder.org`?

**Comment by betatim** [comment]
I think if CZI are open to the idea then we should attempt asking for credits only. I think this is about the only thing that will help keep the lights on at gke.mybinder.org in terms of grant funding. As in, getting a grant to pay somebodies time won't help with running gke.mybinder.org in a few months. It is however something to explore as a longer term solution.

**Comment by choldgraf** [comment]
OK it sounds like we are probably not going to apply for CZI funding this time around. That means that we still need to find a way to sustain `gke.mybinder.org`. I will do what I can to find funding but I can't be relied on to make this happen due to the newborn.

I think if we get to September and still don't have a plan for sustaining `gke.mybinder.org`, then this conversation should instead shift to "how to absorb 60% of binder traffic into the other federation hubs, or how to gracefully shrink the capacity of mybinder.org"

**Comment by yuvipanda** [comment]
Who was the contact from Google last time? Maybe I can poke them to see if we can extend the end date.

**Comment by choldgraf** [comment]
it was a guy that Fernando knew, I can look it up to send - maybe Fernando has kept in touch w/ him. There are some other potential leads as well. In particular a guy named Karan Bhatia in the google cloud research world

**Comment by yuvipanda** [comment]
@choldgraf a connect, especially if it is in an existing email thread, would be great!

**Comment by sgibson91** [comment]
Tania mentioned she knew some folks too and I've asked her to put us in touch :)

**Comment by choldgraf** [comment]
Sounds great - we are also starting some conversations w/ folks in the google world too 👍

**Comment by choldgraf** [comment]
Hey all - just FYI, I've put together a proposal that our Google contacts have submitted internally for more cloud credits. I'm not sure what kind of timeline to expect, or what kind of probability of success we have, but I wanted to let you all know. I've also cc'ed @yuvipanda and @fperez on the email to Google so they'll be notified if we hear back from Google while I'm on leave.

**Comment by trallard** [comment]
Hey I am back from leave so only able to update now. My contact from Google confirmed her team is actually the one that could help with this 🚀  who in the Binder team should I cc for this? Chris is on leave so any advice would be great

**Comment by sgibson91** [comment]
Hi @trallard, welcome back! I think @yuvipanda and @minrk were also involved in some email threads

**Comment by trallard** [comment]
Right @yuvi and @minrk would it be ok to cc you then in my emails with the Google folks?

**Comment by choldgraf** [comment]
Note that I believe we may have a promising direction with the GKE team that we're already in touch with. Perhaps we should let that play out first before starting another conversation in Google? Do you think it'd be useful to reach out to the folks you know @trallard just to build a relationship?

**Comment by trallard** [comment]
Sure, will send an intro email for this

**Comment by minrk** [comment]
Sorry for missing this last week. Thank you, @trallard! As @choldgraf mentioned was in the works, we have just been set up with a GCP project, so I think we are all set for this year. We are working on migrating the GKE deployments to the new project, which is owned by a Google team.

**Comment by trallard** [comment]
Fab good to hear. I will connect you with Amanda anyway, I am sure she will be a great connection to have there

**Comment by choldgraf** [comment]
Hey all - in October of last year we received a generous donation of credits for one year from a team at Google Cloud Research. Those credits are linked to @fperez's account, and in January we finalized the switch so that `gke.mybinder.org` is now pulling from those credits. Once they run out, we should be able to switch over `gke.mybinder.org` to a group account within Google Research but we need to run out the credits first.
