### ISSUE TITLE
JupyterHub social stuff

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#321]
I'm being a bit socially starved and would like to have more chat/telephone/video interactions with you! Realizing this I got to thinking about some stuff that we could do

__JupyterHub happy hour__
Just a time to align when to sit at the computer and do open source stuff with each other, where all of us login to Gitter in the JupyterHub channel or similar.

__A JupyterHub team chat space__ 
We have some gitter chat channels at the moment but they are all public, I think I'd appreciate a place where I'd be able to chat with you without public discussion/Q&A in the same channel.

__Calendars where meetings can be scheduled easily__
I learned that its possible to create calendar events that allow others to schedule a time in them. Here a [one that I welcome anyone to use to schedule a chat with me](https://calendar.google.com/calendar/selfsched?sstoken=UUdEcnN2bHdZTUExfGRlZmF1bHR8Njc3ODg2NWJjOTIzMTkxYjc5MDZlODAzN2QzYzUzZDE), then we get a video meet link automatically generated etc btw.

__Hi <person> :wave:__
I remember friendly "Hi" being said in Gitter, it makes me smile :) Me writing this is a consequence of @betatim saying Hi =D

__Demo sessions__
Perhaps we could have a demo session now and then where we informally without fuzz could show something we've been working on. I was very happy to learn about the Jupyter Book project @choldgraf and learn about yuvipanda/hubtraf and Grafana dashboards from @yuvipanda etc, and I just want more of these excellent insights! ;D

__Triage sessions__
I don't like issue triaging much but I think it would feel fun to make a voice call and do it together, helping each other out where its a bit tricky.

**Comment by sgibson91** [comment]
Hi @consideRatio 🤗

**Comment by consideRatio** [comment]
Hi @sgibson91! :D

**Comment by yuvipanda** [comment]
I would also *love* a space for chatter and conversation that was more focused on folks from non-North-American timezones. I feel a bit starved for interaction too, at UTC+0530

**Comment by minrk** [comment]
hi! 👋 

I'd love this and I also happen to be in the same timezone as @consideRatio and would be happy to have some coordinated time together. But I think we can't reasonably "all" do anything synchronous on a regular basis. I think one thing that's hard with a globally distributed team is that synchronous communication _always_ excludes people. But we still want to be connected! For example, there are no times during a normal work week that I can have synchronous communication with California. With my partial parental leave, I am trying to have a pretty strict work schedule of 9-15 CEST, which is 00-06 in CA. Not the best time over there! I have to rearrange things every time I sync with the US.

Maybe we could arrange a few slots of "office hours" that work for different combinations of folks, where people who are available at that time can make a point of connecting?

We also had [planned](https://github.com/jupyterhub/team-compass/issues/254) a JupyterHub team event colocated with JupyterCon when that was going to be at a time and place. Maybe we should still do something like that, but with more decentralized time windows?

**Comment by manics** [comment]
![giphy-1](https://user-images.githubusercontent.com/1644105/88270786-17a15600-ccce-11ea-8d0a-e2e6a0cddd03.gif)

Could do a weekly (or more frequent) coffee hour, rotating through different times?

**Comment by yuvipanda** [comment]
PANGEO has coffee meetings every other day I think https://pangeo.io/meeting-notes.html

**Comment by sgibson91** [comment]
> I'd love this and I also happen to be in the same timezone as @consideRatio and would be happy to have some coordinated time together.

I'm only 1 hour behind you so happy to join too :-)

I would be slightly wary about too frequent coffee hours. Only because I already have one daily coffee with Kirstie and co and _two_ daily coffees with my team at the Turing. I don't wanna get sick of y'all 😅 Seriously though, it's a lovely idea.

**Comment by yuvipanda** [comment]
Asynchronously, what do folks feel about a 'social' channel? Like '#random' in slack, so not focused on any one topic. Equivalent to running into people at places...

**Comment by minrk** [comment]
@yuvipanda no objection from me to a jupyterhub/#random on gitter

**Comment by yuvipanda** [comment]
I just created https://gitter.im/jupyterhub/random for off-topic, social conversations. Please follow the Jupyter Code of Conduct!

**Comment by consideRatio** [comment]
Let's mark this issue as resolved for now, the random chatroom was a great addition!
