### ISSUE TITLE
Moving repo2docker back to jupyterhub org

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#322]
Hoping to finalize https://github.com/jupyter/repo2docker/issues/232 over here.

Background:

repo2docker started on this org, but was moved to jupyter early on because it's *technically* generic to any Jupyter use case. However, from a practical standpoint, it's still primarily the Binder team that maintains it, so it probably makes the most sense to bring it back over here. As supporting evidence, the repo2docker-action just landed on this org, and not the org which currently hosts repo2docker itself (#315). This was brought up in 2018, and there was concensus that it probably should be over here, but the cost of moving was not worth it since the cost of separation was low (it still is pretty low). The main headache for moving [brought up](https://github.com/jupyter/repo2docker/issues/232#issuecomment-366650639) in that issue was renaming the docker image, but we don't actually have to do that. We can leave the docker image alone and just move the git repo. There appears to be consensus so far on that issue after suggesting we only move git and not docker.

Proposal:

- transfer jupyter/repo2docker github repo back to jupyterhub/repo2docker
- leave docker image alone as jupyter/repo2docker

Task list:

- [x] update .travis.yml config triggers for `deploy.on.repo` ([PR](https://github.com/jupyterhub/repo2docker/pull/939))
- [x] maybe update travis config, if secret values are lost after migration? Not sure if that will happen. ([PR](https://github.com/jupyterhub/repo2docker/pull/940))
- [x] checking for links to the github repo in the docs, which is also low-impact, since there will be a redirect in place already. ([PR](https://github.com/jupyterhub/repo2docker/pull/939))
- [x] update [henchbot](https://github.com/henchbot/mybinder.org-upgrades) with new repo url ([PR](https://github.com/henchbot/mybinder.org-upgrades/pull/2))

**Comment by minrk** [comment]
Seems to be well supported with no objections. I'll have a go at this next week when I'm back (8/10) unless folks chime in before then who want to keep the conversation open.

**Comment by choldgraf** [comment]
Come home repo2docker!

![](https://media.giphy.com/media/WQHAtBrMVM7eCq4BhG/giphy.gif)

**Comment by minrk** [comment]
Move appears to be finalized pending merge of https://github.com/jupyterhub/repo2docker/pull/940

**Comment by betatim** [comment]
Thanks a lot for doing this and taking care of all the (tedious) side effects/changes on the side this move needed!
