### ISSUE TITLE
Reduced availability for 7/27-8/7

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#324]
Meant to post this earlier, but I’m taking some vacation this week and next (7/27-8/7), so I might be slow to respond to things.

Current view:

![080A4504-9DBC-4B69-A271-9BCFA1CB8884](https://user-images.githubusercontent.com/151929/88538809-48f08d80-d010-11ea-8b18-b90fff60b7de.jpeg)

**Comment by sgibson91** [comment]
Very jealous. Have fun!

**Comment by minrk** [comment]
Back!

**Comment by minrk** [comment]
Didn't realize there were obligatory pictures as in #327.

@betatim your mountains look bigger than ours! But we had some pretty good lakes and waterfalls.

![IMG_0458](https://user-images.githubusercontent.com/151929/89765125-fde97680-daf5-11ea-96ca-bfbf2b931150.jpeg)

![IMG_0470](https://user-images.githubusercontent.com/151929/89765135-0346c100-daf6-11ea-90e1-795dba440f00.jpeg)

**Comment by betatim** [comment]
I thought your first pic mid holiday was what made it obligatory :D 

Nice reflection in the lake!
