### ISSUE TITLE
Reduced availability for 2020-08-04 to 2020-08-08

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#327]
I'm away hiking with a tent, the laptop didn't make the weight cut :D 

See y'all after

**Comment by sgibson91** [comment]
Have fun!

**Comment by betatim** [comment]
Back and with obligatory pictures:

![IMG_20200807_144523](https://user-images.githubusercontent.com/1448859/89764180-3daf5e80-daf4-11ea-9746-deda191d9616.jpg)
![IMG_20200808_155038](https://user-images.githubusercontent.com/1448859/89764198-456f0300-daf4-11ea-82d3-eace98eebdba.jpg)
![IMG_20200807_144533](https://user-images.githubusercontent.com/1448859/89764271-5d468700-daf4-11ea-9c79-cc4f3684af57.jpg)
