### ISSUE TITLE
BatchSpawner & Friends as part of team compass calendar etc?

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/team-compass#329]
Hi everyone,

One of the things to come out of the Jupyter Community Workshop on Science Facilities and HPC last year was a plan for [batchspawner](https://github.com/jupyterhub/batchspawner) and  [wrapspawner](https://github.com/jupyterhub/wrapspawner) (and some other package) stakeholders to meet regularly to discuss maintenance of those projects, develop processes for maintaining those packages, and getting to a new release.  We've been holding these "BatchSpawner and Friends" meetings once a month since November.

Mostly this has been myself, @mbmilligan @rkdarst @cmd-ntrf @scanon but recently there have been some newcomers.  Conversation usually branches into discussions about support from batch schedulers and sharing knowledge and experience related to deploying Jupyter at HPC centers.

With the release of BatchSpawner 1.0 it now seems like we're entering a new phase where more engagement with the JupyterHub project would be a good idea.  We're interested in getting more perspectives represented in our discussions and efforts and maybe get some more help.  There's also interest in taking advantage of experience, expertise, and infrastructure (especially for streamlining maintenance, review/release processes).

We were wondering what the best way to do that is, and it occurred to us that "surfacing" the meeting here and on Discourse would be the way to start.  Some of us make the monthly oscillating Hubs meetings, and we're happy to do that but we're also happy to start advertising our meeting through the same calendar, keep agenda/notes on hackmd, etc. to put things more in the open.  Any recommendations on how to proceed?

**Comment by choldgraf** [comment]
hmmm, I wonder if these projects could be re-branded as a working group or something? Maybe that'd be a way to start building more of a community of expertise around this?

**Comment by minrk** [comment]
Yeah, I think naturally forming groups / topics around any subset of the community makes sense. If a regular meeting sounds good to those involved, adding it to the Jupyter calendar (and making sure some participating folks have the required access) is a good idea. Other things we might want to add: tags/labels/topics for the discourse, etc.

**Comment by rcthomas** [comment]
Working group sounds like a good way to start growing things.  Are there any kinds of instructions or recommendations for developing working groups?

**Comment by betatim** [comment]
Do you want to add a short (or longer) item to the #319 team meeting agenda? A shout out would be great to direct some attention to it or a longer item to discuss mechanics around WG and the like.

**Comment by rcthomas** [comment]
I think @rkdarst will be calling in but the hour's too late for me here.  Look forward to the notes!

**Comment by manics** [comment]
@rkdarst Have you been added to the JupyterHub Team Meetings calendar? If not I should be able to add you if you give me a google account address.

**Comment by rcthomas** [comment]
Thanks for the summary @rkdarst, I picked up some of that from the notes.  The thing about drop-in deployment is true but we get a lot out of our conversations around that particular challenge.

**Comment by rkdarst** [comment]
@manics, I propose you add @rcthomas instead.  He's scheduling the current meetings, and if I was added to the loop I'm sure I would start forgetting pretty soon.

**Comment by rcthomas** [comment]
Email sent @manics

**Comment by manics** [comment]
Should  be done!

**Comment by rcthomas** [comment]
The monthly "JupyterHub HPC" meeting has been moved to the team calendar

**Comment by rcthomas** [comment]
Following onto that, we're rethinking our agenda process and we're adapting something similar to the Hubs team meeting using HackMD since that seems to work so well.  I was hoping we might be able to keep the notes somewhere (in the team compass repo as well possibly)?  Would it be possible to (re-)structure the directories a bit to account for another meeting?  Let me know what you think, thanks!

**Comment by manics** [comment]
Sounds reasonable! Do you want to start a new issue and outline your suggested changes?

**Comment by manics** [comment]
This was done!
