### ISSUE TITLE
sgibson91 unavailable: 22/08 -> 31/08

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#332]
I'm taking annual leave next week to coincide with a bank holiday in the UK. I don't have many exciting plans and I won't be completely incommunicado if there's something urgent (Twitter DM is probably best for quick response), but I do plan to mute most work things that notify my phone 🙂

**Comment by sgibson91** [comment]
I'm back! Here are some obligatory photos 😂 https://photos.app.goo.gl/CpZM2qqkyZNiMH6s5

**Comment by consideRatio** [comment]
Welcome back @sgibson91! :tada: :heart:!

**Comment by betatim** [comment]
It moves!
