### ISSUE TITLE
JupyterHub 1.2 / Z2JH 0.10.0 release coordination

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#336]
Hi all, I figured we could coordinate some releases on some projects. I would like to make a release of Z2JH and it feels nice to have dependent projects recently updated as well.

Here is a list of various projects and PRs to consider before making a release.

## Projects
- [ ] [jupyterhub](https://github.com/jupyterhub/jupyterhub) - 1.1.0 was released Jan 2020
  - [x] (?) Resolution of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1772
  - [ ] @minrk do you have ideas PRs to focus on?
- [ ] [configurable-http-proxy](https://github.com/jupyterhub/configurable-http-proxy) - 4.2.1 was released Mar 2020
  - [ ] Resolution of https://github.com/jupyterhub/configurable-http-proxy/pull/254/files
- [x] [kubespawner](https://github.com/jupyterhub/kubespawner) - 0.13.0 was released this week
- [ ] [oauthenticator](https://github.com/jupyterhub/oauthenticator) - 0.11.0 was released in Jan 2020
  - [ ] Resolution of https://github.com/jupyterhub/oauthenticator/pull/366
- [x] [ldapauthenticator](https://github.com/jupyterhub/ldapauthenticator) - 1.3.2 was released about a week ago by @manics
- [ ] [ltiauthenticator](https://github.com/jupyterhub/ltiauthenticator) - 0.4.0 was released in Dec 2019
  - @yuvipanda you have some open PRs here, would you like some PR review and release help on this project?
- [ ] [zero-to-jupyterhub-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) - 0.9.0 was released 15 April (0.9.1 is a more recent security fix)
  - [ ] Resolution of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1763
  - [ ] Resolution of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1758
  - [ ] Resolution of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1682
  - [ ] Resolution of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1669

**Comment by minrk** [comment]
I don't think there's anything we need to wait for in jupyterhub, I think we can do a docs/changelog pass and push it out. I am a bit short on time right now, but will try to have a look.

**Comment by yuvipanda** [comment]
@consideRatio me and several hundred students using JupyterHub with EdX would be very very grateful for any help in getting https://github.com/jupyterhub/ltiauthenticator/pull/16 done.

**Comment by consideRatio** [comment]
JupyterHub 1.3 + z2jh 0.11 is out :) Closing
