### ISSUE TITLE
Planning Binder user workshops

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#34]
Good news everyone: the Mozilla Science Lab grant I applied for a while back got accepted!

The grant promises to create content for and test drive it via three one day workshops on using binder. Getting people to create binders and making them aware of all the things binder can do for them. A bit like z2jh but from the perspective of a user of binderhub. Location wise the plan is to hold one at EPFL in Lausanne and one in Cambridge and one in Berlin.

To do:
* who could I persuade to help out on the days? (the grant can pay for your travel within the EU)
* setting three dates over the summer
* where to host the content? jupyterhub org? new org?

The full text of the proposal: https://hackmd.io/LTP2RpePQl-81An09C3Qww?view

**Comment by gedankenstuecke** [comment]
I will actually be traveling in 🇪🇺 a bit this summer. So that might be a fit. 😂

**Comment by betatim** [comment]
Any thoughts from anyone on where to host this? Otherwise I will create one in my user account (we can always move it later if we want to).

**Comment by minrk** [comment]
I'm happy to help with at least one of these in person, and materials/support for others. I'll be in Hamburg June 20-22, so might be able to do Berlin adjacent to that.

**Comment by betatim** [comment]
Created https://github.com/betatim/build-a-binder

Thanks for offering to help Min! Time to get organised in terms of dates and locations :)

**Comment by jzf2101** [comment]
I'm closing for now.
