### ISSUE TITLE
Have I graduated to a red team member?

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#341]
Hey 👋  I was just reading through the [team roles](https://jupyterhub-team-compass.readthedocs.io/en/latest/binder/governance.html#team-roles) and I wondered if the rest of the team would agree that I've taken on a lot of the responsibilities outlined for red team membership? 🙂

**Comment by consideRatio** [comment]
@sgibson91 I'd say you absolutely meet the criteria described in the team roles section!

> Red member. You spend a large part of your time coordinating and promoting the Binder Project as well as the service at mybinder.org. You are expected to coordinate your actions with other red members so that the project presents a coherent position towards the outside. You are expected to prepare and attend the monthly team calls.

**Comment by sgibson91** [comment]
> Thank you so much for your work, I'm really happy to be working with you in this ecosystem ❤️ 🎉

Right back at ya @consideRatio! ❤️

**Comment by betatim** [comment]
I think so. Do you want to make a PR moving your role?

**Comment by sgibson91** [comment]
Opened #342

**Comment by choldgraf** [comment]
Agreed! Thanks for all of the great work that you have done in this community @sgibson91 !

Also just a note that we don't have explicit rules about how one moves between blue/red team status. In general I believe that we just allow people to self-describe as they wish. @sgibson91 I am wonder - as a person that recently thought to themself "I wonder if I should be `<some other team designation>`?" - did you find this lack of guidelines confusing or a barrier to taking action?

**Comment by sgibson91** [comment]
> Agreed! Thanks for all of the great work that you have done in this community @sgibson91 !

🙌 

> Also just a note that we don't have explicit rules about how one moves between blue/red team status. In general I believe that once people are "team members", we allow them to self-describe as they wish. @sgibson91 I am wondering - as a person that recently thought to themself "I wonder if I should be `<some other team designation>`?" - did you find this lack of guidelines confusing or a barrier to taking action?

So I felt that just moving myself up a band was a touch presumptuous, but not so presumptuous that I couldn't open an issue and ask if the team agreed with my feeling that I was meeting that criteria. And I did have an afterthought that maybe "Do you feel you are on the correct team?" would be a question in the 6 monthly check-ins in the same way that we might ask if someone wanted to move into/out of the green team.

**Comment by minrk** [comment]
Yes absolutely! I forgot you weren't already there.

> And I did have an afterthought that maybe "Do you feel you are on the correct team?" would be a question in the 6 monthly check-ins in the same way that we might ask if someone wanted to move into/out of the green team.

I think that's perfect.

Shall we add a team check-ins to the next meeting agenda? I think there might be more team-membership shifts due.

We officially have last-check-in times in the file, maybe the periodic check-in Issues can be automatically issued by a bot?

**Comment by sgibson91** [comment]
I am +1 on bots for anything 😂
