### ISSUE TITLE
TravisCI .org -> .com migration - Action required

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#348]
Travis CI have deprecated the .org domain and now only use a .com domain. At the end of the year, all JupyterHub's TravisCI builds except for a few newly created repos TravisCI integration will stop working, and are currently getting stuck in queues of many hours.

I have concluded that it works great to just migrate to .com, at least for the zero-to-jupyterhub-k8s repo, but there is one change at least we need to make - we need to update Travis build badges in our readme files for various repos.

## References
- [Migration documentation](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)
- [Travis CI forum where many users like myself had no clue about this](https://travis-ci.community/t/builds-hang-in-queued-state/10250/6)

## Migration activated [at travis-ci.com/organizations/jupyterhub/migrate](https://travis-ci.com/organizations/jupyterhub/migrate)
This can be done in a single click for all at once, I'm +1 to pushing it, but I felt I wanted to have some agreement among more than just myself about doing it.

- [x] batchspawner
- [x] binderhub
- [x] chartpress
- [x] configurable-http-proxy
- [x] dockerspawner
- [x] firstuseauthenticator
- [x] helm-chart
- [x] hubshare
- [x] jupyterhub
- [x] jupyterlab-hub
- [x] jupyter-rsession-proxy
- [x] jupyter-server-proxy
- [x] kubespawner
- [x] ltiauthenticator
- [x] mybinder.org-deploy
- [x] nbgitpuller
- [x] oauthenticator
- [x] outreachy
- [x] sudospawner
- [x] traefik-proxy
- [x] zero-to-jupyterhub-k8s

## Readme file badges updated
The change required is examplified in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1882.

```diff
 # /com added after img.shields.io/travis
 # .org changed to .com in travis-ci.org
- [![TravisCI build status](https://img.shields.io/travis/jupyterhub/zero-to-jupyterhub-k8s/master?logo=travis)](https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s)
+ [![TravisCI build status](https://img.shields.io/travis/com/jupyterhub/zero-to-jupyterhub-k8s/master?logo=travis)](https://travis-ci.com/jupyterhub/zero-to-jupyterhub-k8s)
```

- [x] batchspawner
- [x] binderhub
- [x] chartpress
- [x] configurable-http-proxy
- [x] dockerspawner
- [x] firstuseauthenticator
- [x] helm-chart
- [x] hubshare
- [x] jupyterhub
- [x] jupyterlab-hub
- [x] jupyter-rsession-proxy
- [x] jupyter-server-proxy
- [x] kubespawner
- [x] ltiauthenticator
- [x] mybinder.org-deploy
- [x] nbgitpuller
- [x] oauthenticator
- [x] outreachy
- [x] sudospawner
- [x] traefik-proxy
- [x] zero-to-jupyterhub-k8s

I updated all repos with a .travis.yml.

**Comment by minrk** [comment]
Yeah, let's do it! I don't see any reason not to.

It probably makes sense for certain repos with heavy CI (especially lots of parallelism) to move some or all tests to GitHub Actions, which has lots more capacity and free-tier concurrency, but that's for later, I think.

**Comment by sgibson91** [comment]
+1 for GHA too. Happy to help out if/when we get to that stage!

**Comment by consideRatio** [comment]
I migrated all projects to travis-ci.com from travis-ci.org. Now everything except the build badges in README files are expected to work as they should again.

**Comment by consideRatio** [comment]
I updated all travis badges as well

**Comment by choldgraf** [comment]
amazing - thanks for catching this @consideRatio
