### ISSUE TITLE
JupyterLab user survey on mybinder.org

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#349]
The JupyterLab team wants to ru na survey of their community.

As we have used the banner on mybinder.org before to link to the "Binder user survey" the [idea to use it to link to the JupyterLab survey](https://github.com/jupyterlab/team-compass/issues/104#issuecomment-718150414) came up.

We should have a short discussion on yay/nay for doing that and if we decide yay use this issue to coordinate the change.

---

I'd be happy to run a banner that links to the survey. We should try and not leave it up for too long (months and months) without also finding a different way of acknowledging the federation cluster sponsors.

**Comment by sgibson91** [comment]
I also agree that it's fine so long as it doesn't need to be there for months and months :)

**Comment by manics** [comment]
Are we still planning to do this? The survey is live
https://github.com/jupyter/jupyter.github.io/pull/396
Does anyone know the closing date?

**Comment by choldgraf** [comment]
Here's a link that we can use for the survey that will "tag" the responses as coming from Binder:

https://www.surveymonkey.com/r/2HTNV3Y

I think they are hoping to keep it open a bit longer, we should add it!

**Comment by manics** [comment]
Unfortunately entropy and the arrow of time has caught up, the survey is now closed 😢
