### ISSUE TITLE
Update on Kubeflow

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#35]
Hi @jupyterhub/binder-team,

@yuvipanda got us started off with Kubeflow several months back. kubespawner and JupyterHub are key pieces of Kubeflow.

[Kubeflow](https://github.com/kubeflow/kubeflow) is a Kubernetes project to make deploying machine learning tools at scale easier. A bit more background is in the [README](https://github.com/kubeflow/kubeflow#kubeflow).

As an organization, Project Jupyter's open source code is a foundational piece of Kubeflow and is being recognized as such. There's a recently [merged PR](https://github.com/kubeflow/community/pull/100) that adds Jupyter to the list of organizations contributing to Kubeflow. If you wish to be listed as a contact, please submit a PR adding your email.

cc @jhamrick as FYI

**Comment by jzf2101** [comment]
Do you know what being listed as a contact generally means for Jupyter maintainers?

**Comment by willingc** [comment]
Just that we've contributed in some way to the project and that the project uses Jupyter.

**Comment by choldgraf** [comment]
@willingc just getting around to updating on old issues - thanks so much for keeping the thread alive with Kubeflow + giving updates to the team :-)

**Comment by jzf2101** [comment]
Closing since this is old - we met last month with Kubeflow and will be continuing to communicate with them. Feel free to reopen.
