### ISSUE TITLE
TravisCI is now down for us - a request for credits sent

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#351]
Hi everyone!

I've sent a request for 15k worker minutes / 150k credits a month to Travis CI, according to a suggestion from https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing, following they now limit JupyterHub org to 1k worker minutes a month. This can be put in perspective to the ~11k worker minutes we used last month.

Let's hope they approve our request, otherwise consider this a heads up that our CI system will go down in ~2 days when our credits run out.

**Comment by choldgraf** [comment]
which pieces of JupyterHub depend on travis? I know we've moved mybinder.org-deploy to github actions, where else are we exposed?

**Comment by consideRatio** [comment]
@choldgraf you can see what has been using travis ci within the JupyterHub org in this view: https://travis-ci.com/github/jupyterhub

**Comment by choldgraf** [comment]
right, I knew that 🤦 thanks for reminding me :-)

**Comment by consideRatio** [comment]
We are now out of credits with travis-ci.com :sob:

**Comment by betatim** [comment]
While we are waiting to receive credits we could move some of the CI to CircleCI or GgitHub Actions. CircleCI works Ok and I think still has a generous allocation for open-source projects. One thing that was hard to do when running some of our deployment tooling there was the lack of an equivalent for `TRAVIS_COMMIT_RANGE` which we use a bunch 9or used to use).

**Comment by minrk** [comment]
GitHub actions offers the most parallelism, which is helpful for the long/slow repos (repo2docker probably biggest)

I think the helm bootstrap work that @sgibson91 did in jupyterhub/mybinder.org-deploy can be helpful for z2jh and binderhub, which are among our heaviest

**Comment by minrk** [comment]
I think we have stopped using TRAVIS_COMMIT_RANGE. That was used for chartpress to check for changes to given paths within a PR, but chartpress now ignores that and only checks directly if the latest commit exists on a registry.

**Comment by consideRatio** [comment]
I'm strongly biased for GitHub actions over CircleCI for a CI transition in repo's where Helm charts are used so we can make use of @manics work in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1896. @manics is refactoring the k8s setup logic into a GitHub action: https://github.com/manics/action-k3s-helm/

**Comment by betatim** [comment]
Sounds like GitHub Actions has a lot of support. Lets go with that then 🎉

**Comment by sgibson91** [comment]
Happy to review and/or chip in if anyone needs a hand!

**Comment by sgibson91** [comment]
Something to be aware of if/as we switch to GitHub Actions https://bugs.chromium.org/p/project-zero/issues/detail?amp;q=&can=2&id=2070&colspec=IDTypeStatusPriorityMilestoneOwnerSummary&cells=ids

**Comment by consideRatio** [comment]
We have received no replies so I've mentally decided to focus on GitHub workflows now (it is called actions, but i think it makes more sense to say github workflows that use github actions).

**Comment by consideRatio** [comment]
Closing this issue in favor of https://github.com/jupyterhub/team-compass/issues/353. We have not yet received a response and we have got started migrating to GitHub workflows.

**Comment by consideRatio** [comment]
Yesterday 12th November I got a response from Travis who are happy to sponsor us but wanted confirmation on some points. At this point though with work put in to #353, I don't want to go back to retain .travis.yml infra as all CI systems have their quirks to adapt to and learn about.

>We offer an Open Source Subscription for free to all non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
>1. You are a project lead or regular committer (latest commit in the last month)
>2. Project must be at least 3 months old and is in active development (with regular commits and activity)
>3. Project meets the [OSD](https://opensource.org/docs/osd) specification
>4. Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
>5. Project can not provide commercial services or distribute paid versions of the software

## Question
Should we follow through with our request, and if so, do we meet criteria 4?

**Comment by choldgraf** [comment]
I'm +1 on trying to get Travis to give us credits just in case we wish to use them in the future, and to buy us time in converting the cicd, but also going forward with converting our infra to use github actions

**Comment by choldgraf** [comment]
On point 4 I'd just say that there are many companies that contribute some development to jupyter, but it's not dedicated developers and they do not sponsor jupyter financially

**Comment by consideRatio** [comment]
Update: we got 50k temporary credits but our request is still under review. I'm closing this issue now as I don't see a clear action point for us remaining regarding this.

**Comment by choldgraf** [comment]
Thanks @consideRatio for all of your hard work on this one, I really appreciate you helping to make sure the ci cd infrastructure remains functional!
