### ISSUE TITLE
Incorporating notes from other related meetings (esp HPC)

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/team-compass#352]
### Proposed change

The immediate goal is to create a home for agenda/minutes captured from the monthly HPC JupyterHub interest group meeting.  This could be done by just creating a directory in `/docs/` alongside the `monthly-meeting` maybe called `monthly-hpc-meeting` (an inspired choice eh).  We're experimenting with following a template very similar to the Hubs monthly meeting, using HackMD for the agenda and notes as well.  

In general if other "interest groups" arise and want to have their activities captured at the Team Compass maybe we should think through how those could be incorporated as they arise?  Maybe doing this will help clarify some kind of process.

### Alternative options

Putting the notes elsewhere?  I'd like to see if people thought it would be valuable to accumulate the notes we produce alongside the other sets of notes as additional resources.

### Who would use this feature?

Everyone involved in the Jupyter HPC interest group, and anyone we might be able to direct to the meeting notes from various places (discourse, documentation, etc).  Anyone else who uses Team Compass for whatever reason could see the notes and be welcomed to participate!

See also #329

**Comment by yuvipanda** [comment]
Did we start doing this?

**Comment by sgibson91** [comment]
Yes - [here](https://github.com/jupyterhub/team-compass/tree/master/docs/monthly-meeting-hpc)
