### ISSUE TITLE
Security scanning of Turing Binder URLs

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#355]
Hi folks,

The IT team at the Turing recently performed a (service non-disrupting) security scan on the mybinder.turing.ac.uk domain. Good news is that the issues found were very minor but as fixing them needs to happen upstream I thought I'd open an issue for discussion first. Also, the issues are mainly JavaScript ones and that's not my forte 😄 

Issues are:

- Framed page, susceptibility to "clickjacking"
- jQuery library version has a known vulnerability, needs to be >= 3.5 for full security coverage

I can share the reports I was sent for full info if anyone would like to see. IT are also going to run these checks monthly and let me know of anything they find. So this sounds like a good opportunity to learn if BinderHub has/develops any frontend security issues at least.

**Comment by manics** [comment]
Is this a CyberEssentials scheme 😄. I'm happy to take a look at the report. How about either
- send it to the binder-team private email group
- start a private discussion for the team https://github.com/orgs/jupyterhub/teams/binder-team and we can decide whether they need to be kept private or if they can resolved with public PRs?

**Comment by sgibson91** [comment]
It's Qualys I think? And they are all low risk so I think public is fine, we may choose not to act on them at all. Turing certainly won't mind if we don't, they figured the risk was low enough that it didn't warrant an external PEN test (I'm repeating words here without understanding them 😊 )

**Comment by rkdarst** [comment]
> - jQuery library version has a known vulnerability, needs to be >= 3.5 for full security coverage

If this is JupyterHub jquery, same happened to us and this fixed it:
https://github.com/jupyterhub/jupyterhub/pull/3174

**Comment by betatim** [comment]
Does the report link to some suggested remedies for the clickjacking problem? I think that this is something where we can configure a good default for users (prevent BinderHub UI from being shown in an iframe). But maybe there are people who host a BinderHub who want to iframe it. So if we have some links to docs/guides we could add them to the BinderHub docs in a section on "how to use your binderhub in an iframe, this could open your users up to evil things, see link-to-guide for more."

For a standard BinderHub the risks should be low, I think, as users don't have accounts but for BinderHub-with-auth I think in some worst case scenario kinda scenario users could be tricked into clicking something that will delete contents from their home directory (on the BinderHub)?! So worth fixing for sure!

**Comment by sgibson91** [comment]
I sent the reports to the google group email :)

**Comment by manics** [comment]
Thanks! Ignoring the fact it's a PDF which isn't the easiest format to parse... other than Jquery it looks like it mostly concerns headers that you'd want to set to secure a typical organisation website, though for a public resource like mybinder.org we might deliberately want them to be less restrictive. I think @betatim's suggestion of documenting how to set the headers is a good plan for JupyterHub and BinderHub, it would help solve several forum posts asking related questions. A few from a recent search:
- https://discourse.jupyter.org/t/embed-jupyterhub-in-a-desktop-app/2152
- https://discourse.jupyter.org/t/login-process-does-not-complete-with-content-security-policy/5515
- https://discourse.jupyter.org/t/issue-with-chrome-80-and-samesite-cookie-changes/3757
- https://discourse.jupyter.org/t/generic-oauthenticator-500-internal-server-error-400-oauth-state-missing-from-cookies/6520

**Comment by sgibson91** [comment]
Closing as the Turing BinderHub no longer exists
