### ISSUE TITLE
Hubs Team Meeting - December 2020

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#357]
Hello everyone!

Reminder that our next meeting is Thursday, December 17th, 2020 at 8AM UTC (or [your timezone](https://arewemeetingyet.com/UTC/2020-12-17/08:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Google Meet: https://meet.google.com/kxq-hycx-bvt

These calls are open to anyone, so please join us! We love seeing new members on the call 😄

**Comment by consideRatio** [comment]
@sgibson91 thank you so much for your work to manage these announcements and track the meeting minutes etc! :heart: I missed our last meeting as well sadly and really appreciate being able to read up a bit retrospectively. :hugs:
