### ISSUE TITLE
Team holiday leave

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#360]
Hey all, this issue will track the team's leave over the holiday season. We decided to use one issue since many people's leave will overlap.

My annual leave over the holidays will commence on **18th December 2020** and I will back on **11th January 2021**.

I hope everyone who celebrates has a relaxing and well-deserved break!

**Comment by minrk** [comment]
I was about to open an issue for me, too, but I will be off for the exact same dates!

**Comment by sgibson91** [comment]
😂😂😂 I updated the title

**Comment by choldgraf** [comment]
Shall we re-title this "team leaves over the holiday season" and ask everyone to post days they expect to be away if they wish?

**Comment by sgibson91** [comment]
Good idea- updated again!
