### ISSUE TITLE
Adding a COC to our meeting minutes template

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#361]
At the moment, we don't have a link to a Code of Conduct in our monthly meeting template which is poor practice especially since we invite public attendance. As a Jupyter project, we fall under the [Jupyter Code of Conduct](https://jupyter.org/conduct), but I also wanted to ask if there were any specific _JupyterHub_ (+ Binder) flairs we wanted to add to these guidelines that would serve our community? (It's fine if the answer is no!)

And just to note, I'm not opening this issue because I believe conduct in the meeting needs enforcement of a CoC, but because the lack of a visible CoC presently is not inclusive.

**Comment by sgibson91** [comment]
Some examples of flairs we might consider:

* Would we like to nominate a CoC committee within the team to triage such issues first and evaluate whether they need to be escalated to the Jupyter CoC/SC? Maybe folk would prefer to report to someone within the team first?
* Any wording tweaks to the guidelines to avoid ambiguity or such?

**Comment by manics** [comment]
I agree with @choldgraf , I can't think of any reason not to add a link to the standard CoC now, and if necessary make changes later.

**Comment by minrk** [comment]
Yeah, let's put a link to what we already have at the top of the agenda template now (and probably the Issue announcing the meetings as well). We can discuss in the meeting if there's any relevant video-specific addenda to write up and link to instead. But given that there are also Jupyter community calls with a similar structure, I wouldn't expect anything to be unique to us. So if there's content missing that's relevant to these public calls, I would guess it should go in an upstream location shared across Jupyter to be used in those calls as well.

**Comment by sgibson91** [comment]
I've added a link to the CoC as it stands to the live document and added it as an agenda item too

**Comment by betatim** [comment]
👍 

On adding customisations: I think we shouldn't. Instead if there is something missing we should try and get it included "upstream". I think having one uniform process is good. In particular because it takes a lot of skill and experience to deal with issues that arise around a COC and luckily(!) COC related cases are rare. This means "concentrating" all of these cases on a core team seems like a good way to build up that experience/benefit from having people with experience deal with things.

**Comment by choldgraf** [comment]
> if there is something missing we should try and get it included "upstream"

I agree with this in principle, though also think there could be value in trying out CoC language and procedures in the hub community with the goal of contributing upstream in the future, similar to how one might do the same for soft-forks of a project. I can say from experience that getting anything in the CoC changed (even trivial things) is a _loooooooooong_ process that takes a fair amount of work at the Jupyter-wide level

**Comment by sgibson91** [comment]
Yeah, I also think it can be quite intimidating to take a CoC report to the overall CoC committee straight off the bat. It can feel really "official".

**Comment by choldgraf** [comment]
the CoC is now in our meeting notes: https://hackmd.io/@sgibson91/hubs-team-meeting so perhaps we can close this?
