### ISSUE TITLE
Sign agreement to publish our GitHub actions to the GitHub marketplace?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#366]
We have developed three github actions:
- [jupyterhub/action-k3s-helm](https://github.com/jupyterhub/action-k3s-helm)
- [jupyterhub/action-k8s-namespace-report](https://github.com/jupyterhub/action-k8s-namespace-report)
- [jupyterhub/repo2docker-action](https://github.com/jupyterhub/repo2docker-action) (Already published)

I'd like to publish them, but it requires signing an agreement on behalf of the JupyterHub org, I think. Sounds okay? I have not read it...

Technically, we run into the need to sign the agreement from this view in the GitHub UI: https://github.com/jupyterhub/action-k3s-helm/releases/new

It is available [here](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-marketplace-developer-agreement) as well I believe.

Any thoughts about this?

**Comment by manics** [comment]
FYI the action-k3s-helm was already [published on the marketplace](https://github.com/marketplace/actions/k3s-with-calico-and-helm) when it was under my account, but following the transfer to the org it's now out of sync with the [action-k3s-helm releases](https://github.com/jupyterhub/action-k3s-helm/releases)

**Comment by manics** [comment]
There's a third action owned by the JupyterHub org: https://github.com/jupyterhub/repo2docker-action

**Comment by consideRatio** [comment]
@manics it is also published already it seems: https://github.com/marketplace/actions/repo2docker-action

**Comment by consideRatio** [comment]
I skimmed through it and didn't feel alarm bells go off. I updated the github releases to publish our actions also.

- https://github.com/marketplace/actions/k3s-with-calico-and-helm
- https://github.com/marketplace/actions/kubernetes-namespace-report

Woop woop!
