### ISSUE TITLE
April team meeting

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#37]
We should schedule the "April" meeting (even if it ends up taking place in early May).

I'd start the bidding with April 26th at 6pm Zurich (the usual time slot) ([in your timezone](http://arewemeetingyet.com/Zurich/2018-04-26/18:00/JupyterHub%20team)).

* video link: https://calpoly.zoom.us/my/jupyter
* agenda link: https://hackmd.io/0TPWM_qdTdmI_0y-3dIbhQ#
* [x] announce on: gitter, jupyter@googlegroups.com, jupyter-education@googlegroups.com, binderhub-dev@googlegroups.com

**Comment by jzf2101** [comment]
I'm ok with that time

**Comment by choldgraf** [comment]
+1 from me too
--

**Comment by consideRatio** [comment]
Works fine for me!

**Comment by minrk** [comment]
Works for me

**Comment by minrk** [comment]
We met!

**Comment by jzf2101** [comment]
FYI I submitted to the conference in Montreal.  Thanks @choldgraf !

**Comment by choldgraf** [comment]
woohoooo!
