### ISSUE TITLE
Hubs Team Meeting: February 2021

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#370]
Hello everyone!

Reminder that our next meeting is Thursday, February 18th, 2021 at 9AM GMT (or [your timezone](https://arewemeetingyet.com/London/2021-02-18/09:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Google Meet: https://meet.google.com/kxq-hycx-bvt

These calls are open to anyone, so please join us! We love seeing new members on the call 😄

**Comment by betatim** [comment]
Should we attach this meeting to the new timezone (#371) already?

**Comment by sgibson91** [comment]
I am +1 on changing the meeting time for this meeting if we have consensus.

Also, heads up that I won't be chairing this meeting as I've taken the week off to celebrate my birthday (mostly by watching more-than-usual amounts of Netflix in my pyjamas 😂 )

**Comment by minrk** [comment]
We have six votes for the change and zero other input, so I think we can call it consensus

**Comment by sgibson91** [comment]
Note that I have updated all the timings and links in this issue and the hackmd, so 🤞🏻 for this month's meeting!
