### ISSUE TITLE
Hub team meeting timezone

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#371]
Hub team meetings are currently scheduled in UTC, I think because we are computer people and UTC is easy to reason about, and DST is a crime against reason. A consequence of this is that due to UTC not observing Daylight Saving Time unlike most (not all) timezones where our humans work, meetings are an hour earlier in the winter for most folks than in the summer. I'm not sure this is an intentional difference, and I think I have heard that the summer time is working better for folks. In particular I think I have heard that 8AM is uncomfortably early in the UK, especially in the darker time of the year. Do note, though, that part of the reason we have these schedules is that not everyone is expected to make every meeting. Every other meeting is supposed to be an okay time in a given timezone.

**Question: Should we pin to a DST-observing timezone, then, and if so, which one?** There shouldn't be a long-term difference, but our March meetings can fall between DST transitions because e.g. the US changes on the second Sunday of March and the first of November, while the EU changes on the last Sunday of March and the last of October, meaning our March meetings will always be the odd one out - if we pin to the US, the March meeting will be one hour early in Europe; if we pin to Europe, it will be one hour later in the US. Because of that, I think Europe perhaps makes the most sense as a timezone to follow (moving from 10 to 11 in the US seems preferable to moving 9 to 8 in the UK for the odd one out). I believe EU DST transition is standardized, but we can pick Geneva as [a good place](https://en.wikipedia.org/wiki/Watch_Valley) to center our clocks if this makes sense.

Southern hemispheres change in the opposite direction and tend to change in September/April, so there would be two hours difference between Winter/Summer there instead of one (and instead of zero for US/Europe), and at least two meetings per year with off times. So this is ultimately a change that prioritizes the northern hemisphere and specifically US/Europe, which we may not want to do. Though it is where most of our team currently works.

Barring overlapping DST transitions, these are our meeting times. Winter times differing from summer highlighted in **bold**:

Current meeting calendar (UTC AM/PM meetings):

| season | UTC | US/Pacific | UK | CE[S]T | India | Singapore | Sydney |
| -- | -- | -- | -- | -- | -- | -- | -- |
| Winter | 08:00 / 17:00 | **00:00 / 09:00** | **08:00 / 17:00** | **09:00 / 18:00** | 22:30 / 13:30 | 01:00 / 16:00 | **19:00 / 04:00** |
| Summer | 08:00 / 17:00 | 01:00 / 10:00 | 09:00 / 18:00 | 10:00 / 19:00 | 22:30 / 13:30 | 01:00 / 16:00 | 18:00 / 03:00 |

Proposed meeting calendar (one hour later in winter):

| season | UTC | US/Pacific | UK | CE[S]T | India | Singapore | Sydney |
| -- | -- | -- | -- | -- | -- | -- | -- |
| Winter | **09:00 / 18:00** | 01:00 / 10:00 | 09:00 / 18:00 | 10:00 / 19:00 | **23:30 / 14:30** | **02:00 / 17:00** | **20:00 / 05:00** |
| Summer (unchanged) | 08:00 / 17:00 | 01:00 / 10:00  | 09:00 / 18:00  | 10:00 / 19:00 | 22:30 / 13:30 | 01:00 / 16:00 | 18:00 / 03:00 |

Maybe we can vote with 👍 for the proposed change (change winter to match summer), 👎 (change summer to match winter), ❤️  for keeping the current UTC scheme, or comment to propose something else or specifying a timezone.

**Comment by betatim** [comment]
Based on https://github.com/jupyterhub/team-compass/issues/370#issuecomment-771582110 and responses here I am closing this issue as "time change accepted". Make sure to update your calendars and watches :)

**Comment by sgibson91** [comment]
Sorry, just before we close this: does anyone know how to implement such a shifting schedule in the [Google calendar](https://calendar.google.com/calendar/u/0?cid=YXFwa3VpNXE3b2kzMnBrOXRjcDUzaG5zc2NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)?

**Comment by betatim** [comment]
I think if you set the timezone of the meeting to "Europe/Paris" (or such) then you get the summer/winter time switch for free.

**Comment by sgibson91** [comment]
OK, I will try that. I think timezones are confusing 😅

**Comment by sgibson91** [comment]
Ok, done that - we'll see what happens in March!

**Comment by betatim** [comment]
> I think timezones are confusing

Timezones and video conferencing software, both right up there :D
