### ISSUE TITLE
Moving jupyter-desktop-server into jupyterhub org

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#372]
I've had a brief chat with @yuvipanda, and we'd like to move the ` jupyter-desktop-server` repo into the jupyterhub org (though it could plausibly go to a different jupyter* org since it's not strictly related to jupyterhub).

We've got two options
1. Move https://github.com/yuvipanda/jupyter-desktop-server/ into jupyterhub
2. Rename https://github.com/manics/jupyter-omeroanalysis-desktop to `jupyter-desktop-server` and move that into `jupyterhub`. The reason to consider this is that I originally created this repo, @yuvipanda forked it and to create `jupyter-desktop-server`. From our perspective it doesn't make a difference which one we move, but if we move my repo it means jupyterhub will contain the parent/head fork which is a bit [nicer for external contributors](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile).

**Comment by choldgraf** [comment]
yeeeesssss

Assuming there are no technical differences between them, I vote for the rename and move to make it easier for external contributors.

**Comment by consideRatio** [comment]
I'm in favor and think its fine to be in jupyterhub and/or other org.

I'd like to contribute to a push associated with its transfer to improve any org members ability to onboard as maintainers and help increase its pony factor - i'm happy to help with what i can!

- some word's about what could be in scope and what probably isn't for the project
- what release artifacts are managed, and how? PyPI pacakage only, and/or docker image also?
- what is and isn't tested, test that we should develop, and what to consider to merge something etc?
- local development setup notes etc

**Comment by choldgraf** [comment]
@consideRatio FWIW I think that this work would definitely be covered under the scope of the jupyter meets the earth grant!

**Comment by betatim** [comment]
I'm happy with the move and no opinion on which repo to move.

Naming feedback: when I read "jupyter desktop server" I thought "why is something that runs jupyter on my desktop in the jupyterhub org? seems unrelated?". After looking at the repo I realised it is about running a X11 desktop on a remove machine. I don't have a good suggestion right now (maybe "jupyter graphical desktop (server)"?) but maybe 10min of collecting ideas could find a name that tells unsuspecting users more about what it is.

**Comment by minrk** [comment]
Definitely go ahead with whatever move seems to work best

**Comment by manics** [comment]
Naming is a good point, I like your suggestion of `jupyter-graphical-desktop`. @yuvipanda If you're happy with this new name I'll do the work to move my repo here, then I'll open a PR to discuss the code changes and PyPI deployment.

**Comment by consideRatio** [comment]
What about `jupyter-remote-desktop`? To me, `desktop` implies graphical, but the remote part is not obvious right? Is it correct that this is only useful to run if you don't run it on your own machine?

My current understanding: you run `jupyter-desktop-server`, and that allows you to connect to it as a remote desktop from other locations. Is that right? I think the name as it is with desktop server is quite good but that the readme could communicate its function via a basic image.

Perhaps `jupyter-remote-desktop-server` even? Hmm... I'm in brainstorming phase still. Any input summarizing the scope of the python package and other parts of the repo would be useful for brainstorming!

**Comment by yuvipanda** [comment]
I like `jupyter-remote-desktop-proxy`, to go with the naming scheme of other jupyter-server-proxy based apps.

**Comment by manics** [comment]
I think `server` and `remote` are both redundant, it's Jupyter so isn't it always remote? 😄 And as a user `server` doesn't mean anything. But I don't really mind- once it's clear there's agreement on a name I'll go ahead.

Regarding scope: how about:
> Provide a Linux desktop environment inside Jupyter

I've deliberately omitted any mention of the desktop implementation because that doesn't matter, the relevant part of this repo is the proxying of VNC into a browser rather than the actual desktop environment. The `Dockerfile` is there as a starting point but it's not the core output, In future we might even want this to proxy externally hosted vnc servers. Also I've just discovered https://guacamole.apache.org/ which might be relevant in future.

**Comment by yuvipanda** [comment]
> it's Jupyter so isn't it always remote?

For most people, I think it is run locally. There was even a desktop app! https://github.com/jupyterlab/jupyterlab_app

**Comment by consideRatio** [comment]
> Provide a Linux desktop environment inside Jupyter

This is a bit too vague for me yet as i lack understanding of it still?

One confusion for me regarding the project is what is done on the server end and what is done on the client end. Between what points do the video feed go for example?

Server need and requires what? Does the video feed source know about jupyter, or does a jupyter server facilitate exposing the video feed to some remote location?

Client is what and requires what? My confusion regards if the client a jupyter server as well that surface a video feed to the browser through it, or if the jupyter server is providing the browser for a visitor with the JS and credentials to acces the remote desktop feed? Or ...


Hmmmm! No clear question but perhaps some insights into what i dont understand yet.

**Comment by manics** [comment]
> For most people, I think it is run locally

For me network == remote, even if it's localhost.

> Hmmmm! No clear question but perhaps some insights into what i dont understand yet.

How about we start from what you're aware of so far? e.g. what are your first impressions from running it on mybinder?

**Comment by choldgraf** [comment]
Speaking as somebody without knowledge of the technical pieces behind this, `jupyter-remote-desktop` is the one that gives me the best intuition for what the tool does. `proxy` is fine to add but IMO is an implementation detail and not inherently important to a person like me (but, maybe I am not the kind of person that this tool is designed for!)

**Comment by manics** [comment]
Shall we go with `jupyter-remote-desktop-proxy` since https://github.com/jupyterhub/team-compass/issues/372#issuecomment-773306829 has 3 upvotes, and make any refinements after the repo is migrated but before it's released to pypi?

**Comment by manics** [comment]
I've transferred the repo https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/2
