### ISSUE TITLE
Reduced availability @betatim

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#374]
I'll be away till 15. February. Snow time.

See you on the other side.

**Comment by choldgraf** [comment]
`#jealous`

**Comment by betatim** [comment]
Lots of powder and no avalanches. Slowly digging myself through my emails and github notifications now.

**Comment by choldgraf** [comment]
Better to dig out of email than out of snow?

**Comment by betatim** [comment]
The good thing is that since I switched to hey.com, my inbox is now a source of calm and quiet contemplation :D

**Comment by choldgraf** [comment]
Is that because of hey or because you didn't tell a bunch of people that your email had switched 😅

**Comment by betatim** [comment]
I forward all my emails there but I have https://hey.com/features/the-screener/. It is fantastic. Basically one click to remove people/services/companies who don't make a good first impression from my inbox for forever.

**Comment by choldgraf** [comment]
wow that is so cool!
