### ISSUE TITLE
Reduced availability @sgibson91

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#375]
I'll be offline 15-19th Feb (and probably the bookending weekends too) to celebrate my birthday!

**Comment by sgibson91** [comment]
I'm technically back from leave, but my calendar is so packed this week that I'm still going to be pretty unavailable 😅

**Comment by sgibson91** [comment]
Ok, fingers crossed I can resume normal service now!

**Comment by consideRatio** [comment]
:heart: welcome back and congratulations on a day following your birthday @sgibson91!! :tada:
