### ISSUE TITLE
Hubs Team Meeting: March 2021

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#378]
Hello everyone!

Reminder that our next meeting is **Thursday, March 18th, 2021 at 5PM UTC** (or [your timezone](https://arewemeetingyet.com/UTC/2021-03-18/17:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Google Meet: https://meet.google.com/uor-hgcz-emy

These calls are open to anyone, so please join us! We love seeing new members on the call 😄

**Comment by consideRatio** [comment]
@sgibson91 thank you for your work to ensure there is a topic for the upcoming meeting open, it is very helpful! :heart:
