### ISSUE TITLE
Force 2018 proposal

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#38]
I'm drafting a Force 2018 proposal, which is due today. There isn't a time, but I'm going to assume late May 1, Montreal time. My plan is to submit immediately after the Jupyter meeting in the (US) morning, since that's the end of the day for me.

Who's interested? @jzf2101 expressed interest at the meeting.

Draft: https://hackmd.io/7tidoGBvRd2ZmNKESySwNQ
CFP: https://docs.google.com/forms/d/e/1FAIpQLScmcNJs2dx361_YZmekXNn7k8YtMKoFI1G1Rx1Ske6HVrDhGA/viewform
conference site: https://www.force11.org/meetings/force2018

**Comment by minrk** [comment]
@jzf2101 that's fine! Is the proposal somewhere?

**Comment by jzf2101** [comment]
I took edits from my CERN abstract that @betatim suggested and submitted.  Where should I post it?

**Comment by minrk** [comment]
Here is fine.
