### ISSUE TITLE
Our list of previous meetings is broken

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#387]
The list of our previous meetings is not rendering on our gh-pages https://jupyterhub-team-compass.readthedocs.io/en/latest/monthly-meeting/monthly_report_index.html I'm not well-versed enough in rst to understand what's going on here unfortunately 😕

**Comment by manics** [comment]
Running `make html` in the docs directory results in 3571 WARNINGs, log attached:
[log.txt](https://github.com/jupyterhub/team-compass/files/6173136/log.txt)

The relevant one seems to be `/jupyter/team-compass/docs/monthly-meeting/monthly_report_index.rst:12: WARNING: toctree contains reference to document 'monthly-meeting/2021-03-18' that doesn't have a title: no link will be generated`
So maybe there's a problem in the markdown->RST conversion? I guess we could try switching to MyST which is used for some of the other Jupyterhub docs?

**Comment by betatim** [comment]
Re-opened because I am not sure if #389 fixes the problem the warnings are warning us about or just doesn't generate a warning (the old "absence of evidence is not evidence of absence" chestnut).
