### ISSUE TITLE
Hubs Team Meeting - April 2021

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#388]
Hello everyone!

Reminder that our next meeting is **Thursday, 15th April, 2021 at 9AM Europe/London** (or [your timezone](https://arewemeetingyet.com/London/2021-04-15/09:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Google Meet: https://meet.google.com/kxq-hycx-bvt

These calls are open to **anyone**, so please join us! We love seeing new members on the call 😄

**Comment by manics** [comment]
I've editted the post to say April instead of March 😀

**Comment by minrk** [comment]
I have a meeting conflict this week, so can't make it.

**Comment by choldgraf** [comment]
Have a good meeting y'all :-) I will be hopefully fast asleep at 1am haha

**Comment by betatim** [comment]
I'll be there!
