### ISSUE TITLE
May team meeting

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#39]
This issue is to schedule and coordinate the May team meeting.

I'd start the bidding with May 29th at 6pm Zurich ([in your timezone](http://arewemeetingyet.com/Zurich/2018-05-29/18:00/JupyterHub%20team)). This is Tuesday not Thursday as usual. However it will be at the start of the in person meeting at Berkeley instead of at the end. That seems worth moving it. How does this work for those not in Berkeley?

* video link: https://calpoly.zoom.us/my/jupyter
* agenda link: https://hackmd.io/tozT_3BDQPCDBayobJKFtQ#
* [ ] announce on: gitter, jupyter@googlegroups.com, jupyter-education@googlegroups.com, binderhub-dev@googlegroups.com

Extra agenda items:
* https://github.com/jupyterhub/mybinder.org-deploy/issues/611
* https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/691#issuecomment-390799994

**Comment by betatim** [comment]
I've started adding things I come across on the issue tracker/gitter as "extra agenda items". This is at least 50% a selfish way to keep track of things we might want to discuss next week in general/during the phone meeting

**Comment by choldgraf** [comment]
(note that there is also the Jupyter full team agenda doc, which I won't post here since I don't know if @ellisonbg wants this public or not)

**Comment by betatim** [comment]
Is there a schedule yet for the team meeting? We should try and schedule this team meeting with a few days notice for those who aren't in Berkeley. If we have too much uncertainty about the agenda of the in-person meeting we should maybe re-schedule our team meeting to the week after?

**Comment by choldgraf** [comment]
that's a good point - I believe @willingc has more experience with Jupyter dev meetings than I. Carol, do you think it's a better idea to post-pone the JupyterHub meeting, or do you think we could have it during the in-person Jupyter meeting?

**Comment by betatim** [comment]
Super late but: this meeting is happening!
