### ISSUE TITLE
A co-ordinated welcome effort on first merged PR in our org

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#391]
> __TL;DR__
> To let automation help us identify when a person is new to the JupyterHub org and provide a explicit warm and human welcome, perhaps for example by having a bot tag a welcome team the first time a person gets merged PR or similar?

@jupyterhub/jupyterhubteam sometimes a person gets their first PR merged within our organisation. I think that is worth some extra celebration, so what do you think about having a bot that mentions either the @jupyterhub/jupyterhubteam or a dedicated JupyterHub org team for welcoming and congratulating that person?

I have never seen that before, but wouldn't it be quite nice? To gather everyone in order to welcome someone actively for their first contribution in our org? Perhaps the team could also be Jupyter wide rather than JupyterHub wide? I think it could make sense to do this Jupyter wide now that I think of it, across a collection of organizations that opt-in to it.

### Today I learned
I have used the word _love bombing_ without understanding its connotations. I assumed it was the act of putting in some additional effort to show love/appreciation/etc for someone, but I think the term love bombing can mean to do so with a bad intent.

**Comment by minrk** [comment]
I think our current welcome bot does this on a per-repo basis, and this seems pretty nice to me. I'm not sure doing more based on org-level information would be better or not.

**Comment by consideRatio** [comment]
@minrk I'd like to retain the per-repo system but to augment it with a per-org first time ever non-automated welcome effort, perhaps for a merged PR as opened issue/opened PR would lead to too much noise I think.

**Comment by betatim** [comment]
What is the thing/problem that would be fixed by doing this?

**Comment by consideRatio** [comment]
@betatim thanks for the question, it enabled me to think a bit more explicitly about it!

The goal of having a "human welcome party" happen the first time a "new contributor" (gets a PR merged within our org?), is for example to:

- Give the new contributor a positive experience about contributing to our org
- Provide the voluntary welcoming team with a good reason to be happy together
- Help the new contributor establish some connection with more active people in the org
  - This could help the new contributor dare to reach out to other contributors and not only the ones involved in reviewing/merging that specific first PR merged

**Comment by manics** [comment]
I don't think we need a per-repo _and_ a per-org post- if they are too many friendly bot replies it devalues them.

I see the value in encouraging new contributors to Jupyter*, and I like the suggestion from @consideRatio of _"Perhaps the team could also be Jupyter wide rather than JupyterHub wide?"_. With this in mind perhaps we should discuss this more openly on Discourse, especially as submitting a PR is only one form of contribution, but if we only "welcome" PR contributors that elevates them above the rest.

My gut feeling from observing the JupyterHub repos is that although there are outstanding unimplemented features and unfixed bugs (and always will be!) we're not really lacking in PRs. We're more lacking in the time to review them, or to investigate potential bugs, or to take charge of a discussion and encourage people to come to a consensus. If we were to focus on onboarding new contributors I'd think we'd get more benefit from encouraging the latter than focussing on code submissions.

**Comment by consideRatio** [comment]
@manics the per-org response that I suggest wouldn't need to have any bot involvement visible for the user that is welcomed. It could simply be a hidden notification to other users that the contributor is a new contributor in a separate communication channel for example.

Discourse is developed to help community grow and foster a good culture, and have these "this is the first post for this user" notices that show for those that are more experienced in the forum. I guess what I'm looking for is something like this in practice, some way to help us provide some human encouragement.

**Comment by yuvipanda** [comment]
FWIW, @rgbkrk did this for me when I first contributed, and it really really really really helped me stick around :)

**Comment by rkdarst** [comment]
same - someone personally commented on my first contribution, which
probably had some positive effects.  I may be old/cynical, but having
a automatic bot doesn't have the same effect.  Even replying a simple
"thanks!"  anytime a person you don't know makes a contribution has
more effect to me.

**Comment by consideRatio** [comment]
This was also my experience, that the positive encouragement early on had a significant impact on me. I guess it also modelled a behavior that I could adopt.

I recall research that acts of kindness and friendly gestures etc can propagate, just like a friendly smile and eye contact can make you smile when you meet a person short thereafter etc because the positive feeling lingered.

**Comment by choldgraf** [comment]
Perhaps this kind of thing could be either carried out, or at least use some thinking and planning, by a "community advocate" role as described in #380 ?

**Comment by consideRatio** [comment]
I think we concluded that having a personal thanks is a big deal compared to having a bot.

We have a bot as well now, and that in turn has helped at least me realize who is a new contributor etc. Let's go for a close!
