### ISSUE TITLE
Reduced availability @minrk

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#395]
Due to holidays in Norway this week and a huge construction project in our borettslag and pandemic-related closures, I'll have reduced availability from now until at least April 15.

**Comment by minrk** [comment]
Another update here: due to some funding changes, I'll be shifting much of my jobby-job time to IPython Parallel for much of the Summer and Fall (starting 1. June), so I'll have a bit less time for JupyterHub.

The construction madness that makes the still-mandatory-here working from home a loud bangy mess also continues at least through the end of June.

**Comment by sgibson91** [comment]
Let us know if there are specific things we can take off your plate, and hang in there!

**Comment by manics** [comment]
Closing!
