### ISSUE TITLE
Submit an application for the CZI EOSS grant around the "Community Developer" role

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#402]
# Background

I just got word that we were invited to submit a full application for the Community Developer role! (see #380 for more context).

[**Draft of proposal**](https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.palfui4hnsdp)

# Informant information

- We have until **May 19th, 2021** to submit.
- [Here are the application instructions](https://apply.chanzuckerberg.com/protected/resource/eyJoZnJlIjogOTQ1OTM2NzAsICJ2cSI6IDE2ODc4M30/)

**Comment by choldgraf** [comment]
**update:** I've created a draft of the proposal and have also updated its structure for the new submission forms we'll need to fill out.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/coordinating-czi-eoss-applications-across-the-community/8472/12

**Comment by choldgraf** [comment]
A few notes from a recent meeting with @sgibson91:

- Things that the role would do
  - Managing the cohort of learners
  - Mentoring the JupyterHub maintainers to help them

- Create structure to help team dynamics
  - Model after Mozilla Open Leaders / Open Life Sciences programs
    - Adapt for the JupyterHub community
  - Things to improve
    - Structure for team information flow and sharing
      - Templates for Mentoring check-ins
    - Pairing newcomers with mentors (either within JupyterHub or with adjacent communities like Pangeo)
      - Might make it easier to deal w/ timezones etc
    - Planning / coordinating team events for focused work (e.g., dugnads, mentorship sessions, team training sessions, etc)
- Broader impact
  - Design in a way that other parts of Jupyter could adopt (or other communities outside of Jupyter)
  - The nature of the work itself is not Jupyter-specific. People are learning and sharing general skills

- Workload balance
  - Is this a realistic amount of work for a 50% load?
  - This role could focus on coordinating that work rather than *doing* that work.
  - Community "shepherd" rather than community "developer"? "Community Champion"?

**Comment by choldgraf** [comment]
**update**:

**Content updates**
I've taken a pass at adding some outlines and content to the [Work Plan, Milestones and Deliverables, and Expected Outcomes](https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.6xl5ernp7921). It is still in a bulleted format - I mostly want to make sure we have the right pieces of information there, and then plan to convert it into narrative text as needed.

**Budget + Justification**
I've added a [budget and a justification](https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.1lg0zkpsfq98). Would love feedback as to whether this seems reasonable.

**Previously-funded Jupyter grants**
We need a list of support that Jupyter has previously received. Here is [a Google Sheet with a list of previous grants and support](https://docs.google.com/spreadsheets/d/1kP1ggTmBji7eGlXYakBfRXKS_I7hjFxKR-gfkh-vO50/edit?usp=sharing). Please add or edit as you like!

**Comment by choldgraf** [comment]
**update**:

I've taken another pass and fleshed out most of the remaining "content sections". Here are the major new areas that could use some 👀 

- [Milestones and deliverables](https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.sfv52t6nkp84)
- [Expected Outcomes](https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.9g7cpbb6zsqo)
- [Evaluation and learning goals](https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit#heading=h.v2i6bzfvxgh2)

Let me know what folks think! I'll plan to fill in most of the application **tomorrow** (Tues) and then submit on Wednesday.

**Comment by choldgraf** [comment]
We've now submitted this proposal! Here's a link to a tweet w/ some background and a link to the PDF

https://twitter.com/choldgraf/status/1395454558357184512

fingers crossed everybody!

**Comment by choldgraf** [comment]
Hey all - I don't know if this is supposed to be super public yet, so don't share widely, but I got word that our application will be funded! I will update with more information as I get it :-)
