### ISSUE TITLE
Submit an application for the CZI EOSS grant around deployment infrastructure collaboration

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#403]
Like #402, got word that the deployment collaboration LOI was accepted, so time to write the application!

# Background

- Related discussion: #382
- [Letter of Intent (LOI)](https://docs.google.com/document/d/1s2Rt9B4BzJIvg1WwoywNMalPorXhHgGNu8HD842_sDg/edit?usp=sharing)

# Important information

- We have until **May 19th, 2021** to submit.
- [draft](https://docs.google.com/document/d/1xU13FImPkudwmlRlKGSrbGgmfKlU6yp5nkOpdwjN77Y/edit?usp=sharing)
- [Here are the application instructions](https://apply.chanzuckerberg.com/protected/resource/eyJoZnJlIjogOTQ1OTM2NzAsICJ2cSI6IDE2ODc4M30/)

**Comment by choldgraf** [comment]
@minrk how would you like to move forward on this one? Should we draw inspiration from some of the ideas in #382 ? Would you like to take a first stab at language and then others can provide suggestions/edits/etc?

**Comment by choldgraf** [comment]
In case it's helpful, here's a draft of the Google Doc I'm using to put together the other JupyterHub application. It's roughly got the structure that we'll need to fill out online (+ a few extra sections that are specific to that application which you can ignore): https://docs.google.com/document/d/12iVNKkxlNfUy0ldcxcy04imbhSHZVr_vGkbJHQ2bEH8/edit?usp=sharing

**Comment by minrk** [comment]
I'd like to have a reasonably complete draft in the next couple of days, then ask for feedback. I'm struggling a bit on the metrics/milestones part, though. How to express these in a reasonably objective measurable form.

**Comment by minrk** [comment]
I can never do anything like this as early as I mean to, but the draft is relatively complete now and ready for feedback, especially on my budget sketch and descriptions of workshops.

**Comment by minrk** [comment]
Submitted! 🚀 

Extra thanks to @consideRatio and especially @choldgraf for lots of wonderful feedback and revisions. ❤️
