### ISSUE TITLE
Introducing Callum Mole as new Turing cluster admin

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#407]
Hey all! 👋🏻 

I'd like to introduce you all to Callum (@callummole) who will begin helping me maintain the Turing cluster. Callum is a fellow member of the Research Engineering team at the Turing Institute. I'll add an item to this month's meeting agenda (#400) for a further introduction 🚀

**Comment by choldgraf** [comment]
Welcome @callummole !

**Comment by callummole** [comment]
Hello all! Very pleased to be a part of this. Looking forward to meeting you all.

**Comment by betatim** [comment]
Hey!! Welcome 👋
