### ISSUE TITLE
Video conferencing platform for meetings

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#411]
Hey folks!

In May's team meeting (#400; that just happened as I am writing), people were looking for a "raise hand" function in order to politely bring themselves into the conversation which seems to be a feature currently missing from Google Meet. (Our switch from Zoom to Google Meet is documented here: #282) We handled this by folks popping a hand emoji (✋🏻) in the chat which I managed as chair. I wanted to check that this worked well for everyone and, if not, what are the alternatives?

Some options:

- Add a "Speaking List" section to the hackmd. Folks who'd like to talk add themselves to the bottom, the meeting chair brings people in from the top and checks them off when they've spoken, then clears the full list when moving on to the next agenda item.
- We investigate whether the paid tier of Google Meet has a hand raise feature
- We switch back to Zoom which we know has these features
- We switch to another video conferencing software
- Something else? Add your suggestion below!

**Comment by choldgraf** [comment]
Ah i like the idea of a speaking list in the hackmd - even if we use ✋ we could still add names to that list to keep track

**Comment by betatim** [comment]
2cecnts: As a user with access to the paid version of Meet: it has a "raise hand" feature. I can make a meeting URL that we can keep using, but I think I can't make others "owners" of the meeting so that you can do admin'y things :-/

As an alternative to switching to a commercial tool or pay a commercial provider: can we use (or pay) someone like jitsi?

**Comment by choldgraf** [comment]
I'm +1 on jitsi in theory but don't have much experience with it, so will defer to others to discuss whether it has the right features etc

**Comment by isabela-pf** [comment]
To answer @choldgraf's question, I use Jitsi in the weekly nteract community meetings and I know it has a "raise hand" option. I don't know what other features you want to make sure it has.

**Comment by sgibson91** [comment]
I'm looking into jitsi now for next month's meeting, but there doesn't seem to be a way to 'schedule' a call, or have a link link set ahead of time. @betatim @isabela-pf do you have any insight how this is handled?

(I'll go ahead and setup the hackmd/issue with the google meet link as normal but happy to change it when I'm more familiar with jitsi :) )

**Comment by isabela-pf** [comment]
I'll ask the person who set up the jitsi meetings! I couldn't figure it out either, but the nteract team definitely shares the link before anyone is in the call.

**Comment by betatim** [comment]
AFAIK you can just make up a link and once you visit it, it exists as a meeting. So there is no need to "schedule" it

**Comment by manics** [comment]
I had to leave today's meeting early so didn't see how well the screen-sharing performed, but the video and chat before that seemed fine to me.

**Comment by betatim** [comment]
For me as viewer (not sharer) the screen share worked well.

**Comment by callummole** [comment]
Yep, same as @betatim. Jitsi seemed like a good replacement from my side.

**Comment by sgibson91** [comment]
It was a lot easier to moderate with the raise hand function too. I propose using Jitsi again for the next meeting so that folks in US time zones can also weigh in, and then make a decision.

**Comment by consideRatio** [comment]
I've been happy with Jitsi so far - +1 for continued usage

**Comment by sgibson91** [comment]
It seemed to be a bit unstable for me today - it looked like _everyone_ had turned their video off (which I'm not sure was the case?). Probably not enough of an issue for me to explicitly downvote it though.

**Comment by rcthomas** [comment]
It was fine for me.  I saw plenty of people on video, but there were some with their cameras off.

**Comment by choldgraf** [comment]
I enjoyed it as well, although the emoji sounds are ridiculous in a "love/hate" kind of way haha

**Comment by minrk** [comment]
Had my first Jitsi meeting. No objections.

**Comment by choldgraf** [comment]
What's the act that closes this issue? Should we set a time box (eg, 2 more team meetings) and then just adopt jitsi after this time if there are still no objections ?

**Comment by sgibson91** [comment]
I'm happy to say we've settled on Jitsi and close the issue now if there's no pushback

**Comment by betatim** [comment]
I'm happy with jitsi as well and would switch to it.

**Comment by sgibson91** [comment]
I declare Jitsi our new platform and this issue closed! 🧙🏻‍♀️

**Comment by choldgraf** [comment]
_clapping emoji sound_
