### ISSUE TITLE
Onboarding Callum: Permissions and Access

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#421]
Hey, I'm just thinking as the new Turing cluster admin what Binder-related access @callummole needs?

- [x] Adding to jupyterhub/mybinder-org-operators and jupyterhub/binder-team github teams
- [x] Write access to mybinder.org-deploy (might be granted with membership to the above)
- [x] mybinder.org-deploy git-crypt key
  - I've already shared this with him via keybase, PR documenting this is here: https://github.com/jupyterhub/mybinder.org-deploy/pull/1912
- [ ] Anything else?

**Comment by minrk** [comment]
Invited to the team, which does grant access to the deploy repo
