### ISSUE TITLE
Transfer ownership of mybinder.org away from Chris's account?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#424]
We currently use BlueHost for the DNS registration at mybinder.org, running off of my personal account. I think that this is not great for a number of reasons, most notably that I am personally a strong bus-factor for mybinder.org's long-term existence 😅

The mybinder.org registration is expiring in a month or so, and perhaps this is a good moment to **transfer ownership** to a multi-person account. Does anybody know if the Jupyter project has guidelines for this? Perhaps @minrk has experienced this with nbviewer?

I am happy to take whatever path is best for the team (including just renewing registration under my account, if that's what others want). Let me know what folks think

**Comment by minrk** [comment]
We should definitely do that. I think jupyter.org *registration* is still on @fperez personal account. The DNS and all operations are on CloudFlare, on the same account as mybinder.org. We should probably consolidate all those on a registrar account that supports multi-user access, if one exists (or a single projectjupyter account, if necessary).

**Comment by choldgraf** [comment]
Can CloudFlare be used to own the mybinder.org domain? If so, it feels like that'd make the most sense since we already use it for the other services you describe.

If we need to use a different service, I've generally used NameCheap with good results, and [I believe it supports multi-user access](https://www.namecheap.com/support/knowledgebase/article.aspx/192/46/how-do-i-share-access-to-my-domain-with-other-users/) (though requires one account to be the "owner" account).

If we need an "owner" account, perhaps the easiest thing to do would be:

1. Transfer to **my** NameCheap account
2. I provide full access rights to anybody else on the Red Team.
3. At this point, we'll have the domain in a more accessible state than it is now, and less bottlenecked on me (we'll also have it renewed for another year)
4. We ask the Steering Council to provide an account that could be person-agnostic.
5. When we find that account, we transfer ownership to them.

What do you think?

**Comment by choldgraf** [comment]
I think as a first step I'd like to take **Option 1** above. If we move to NameCheap I will still technically be the "owner" of the account, but I can give everybody else full privileges. It even sounds like we could pass the account to another person as "owner" if something happened to me (https://twitter.com/Namecheap/status/1411768877546094596).

It also seems like transferring an account between NameCheap users is pretty straightforward, so that would leave this option open for the future.

I believe I can do the transfer myself, but **does anybody think that this transfer would affect mybinder.org uptime**? CloudFlare is doing our DNS, but perhaps there is something I'd need to do upon transferring to NameCheap to ensure continuation of service?

**Comment by yuvipanda** [comment]
I'd suggest moving it to Google Domains, so it unifies access control in the Google Cloud binder project (https://cloud.google.com/blog/products/networking/introducing-cloud-domains)

**Comment by fperez** [comment]
On Sun, Aug 8, 2021 at 11:58 PM Yuvi Panda ***@***.***> wrote:

> I'd suggest moving it to Google Domains, so it unifies access control in
> the Google Cloud binder project (
> https://cloud.google.com/blog/products/networking/introducing-cloud-domains
> )
>

Sorry, I'm finally getting more up to speed on my github notifications...

Just to record publicly that I'm 100% on board with moving all resources
that have historically been held by me personally to team orgs and shared
accounts.  A lot of that was a natural process stemming from IPython's
beginnings, but today it makes no sense for domains, credentials, etc, to
be tied to me personally. It will take us a bit of time to disentangle all
this, but I want to clarify that other than logistics/slowness on my part
out of being busy, I have absolutely no objection here, and I think this is
what we should do!

**Comment by choldgraf** [comment]
I'm happy to do whatever including paying for a renewal, but i have minimal time to do anything so I'll prefer the path of least resistance

**Comment by rpwagner** [comment]
Hi,

I'm going to work with the others on the Security Subproject to come up with a suggestion during our meeting next Tuesday.

--Rick

**Comment by choldgraf** [comment]
Yesss I am very excited to get this one completed. Thanks @afshin for reaching out.

**Comment by afshin** [comment]
I can confirm that `mybinder.org` has successfully transferred to the Project Jupyter domain registrar account that is stored in our password manager. Thanks again @choldgraf and everyone for their patience!

**Comment by manics** [comment]
Are there any JupyterHub docs we need to update, or can we close this?

**Comment by afshin** [comment]
I don’t think there’s any meaningful thing that changed so we can probably
close the issue.
