### ISSUE TITLE
SciPy 2021 plenarry session update

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/team-compass#429]
Apologies for the slightly off-topic issue, 

I'm gathering all project updates from Jupyter to prepare a 5 minutes updates for the SciPy plenary session. 

The discourse thread is here but has not seen many updates.:

https://discourse.jupyter.org/t/scipy-tools-plenary-session-at-scipy-2021/9567/3

We only have 5 minutes for all of Jupyter, so if one of you could post a minimal list of what the jupyterhub team would like to say/announce that would be fantastic.

I haven't followed JupyterHub amuch over the past year, but with the updates in the discourse I can setup the slides. 

Updates can be new community members, number of releases....

**Comment by manics** [comment]
@Carreau I've moved this to the team-compass

Wasn't sure whether to post here or on the Discourse thread.... here's a few potential items to choose from, let's see what everyone else comes up with.

Several Jupyter projects are supporting or will soon support ARM64:
- Supported in JupyterHub Docker and Z2JH Docker/Kubernetes
- Being added to docker-stacks https://github.com/jupyter/docker-stacks/pull/1368, https://github.com/jupyter/docker-stacks/issues/1019

A big upcoming feature in JupyterHub 2.0 will be RBAC.

Repo2Docker has two community additions in the past year, support for Mercurial and Software Heritage persistent identifiers.

**Comment by betatim** [comment]
@choldgraf you recently created a number for how many launches mybinder.org has served in total and how many it serves each week. That might be an interesting factoid that fits the "all of jupyter in 5minutes" constraints.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/scipy-tools-plenary-session-at-scipy-2021/9567/8

**Comment by Carreau** [comment]
Thanks for the updates. Feel free to post on the discourse site. And please try to describe what you believe is interesting in the simplest way possible, as the audience might even have no clue what this will mean, and the presenter might also not know what the features are – for example I had to google RBAC. 

I'd love number as well

In the discourse thread is also a link to the slides (in progress), on which you can also directly comment.
