### ISSUE TITLE
Add people to quay.io JupyterHub org

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#439]
### Proposed change
In [today's team meeting](https://github.com/jupyterhub/team-compass/issues/435) we agreed to publish repo2docker containers on quay.io due to the problems with Docker Hub (see https://github.com/jupyterhub/repo2docker/pull/1071 and comments)

We already have a [jupyterhub quay.io org](https://quay.io/organization/jupyterhub) that @yuvipanda has access to. If you want to be added put your quay.io username in a comment below.

**Comment by manics** [comment]
My quay.io username is [manics](https://quay.io/user/manics)

**Comment by yuvipanda** [comment]
I added @minrk @manics @sgibson91 @consideRatio as owners!

**Comment by manics** [comment]
Thanks @yuvipanda !

**Comment by betatim** [comment]
I'm @betatim on quay.io (after a bit of trouble trying to create an account :-/)

**Comment by yuvipanda** [comment]
@betatim invited!
