### ISSUE TITLE
Require 2FA for all in the JupyterHub GitHub organization

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#443]
To protect the JupyterHub GitHub organization from accidental password leaks, I suggested that we enable a requirement of having 2FA enabled for all members of the org which was considered acceptable in the latest JupyterHub team meeting.

But, before we do that, we need all members to have it enabled to not kick them out of the organization when enabling it. @callummole, @GladysNalvarte, @mbmilligan, @Ruv7, @tgeorgeux - could you enable 2FA by visiting https://github.com/settings/security ?

I recommend the application _Authy_ if you need a 2FA application on your mobile.

### Related
- [Members with 2FA disabled in the JupyterHub org](https://github.com/orgs/jupyterhub/people?query=two-factor%3Adisabled)
- [Where we toggle 2FA to be required among members in the JupyterHub org](https://github.com/organizations/jupyterhub/settings/security)

**Comment by mbmilligan** [comment]
Thanks for the reminder, have done.

**Comment by consideRatio** [comment]
Hello again! It has been a month, @callummole @GladysNalvarte @Ruv7 @tgeorgeux have you been able to see this? Are you okay with enabling 2FA?

**Comment by Ruv7** [comment]
Hi there - thanks for the ping and for checking in. I'm not sure why I would be a part of this org as I don't contribute code. Feel free to move ahead without taking my participation into account.

**Comment by tgeorgeux** [comment]
I have no idea, I don't work within the JupyterHub org at all (=

**Comment by IvanaH8** [comment]
Done, thank you for the ping!

**Comment by bitnik** [comment]
Thanks for the reminder, done :)

**Comment by manics** [comment]
It's past the 19th June now. Who's left?

Also note 2FA is now an official Jupyter policy
https://blog.jupyter.org/requiring-2fa-for-jupyter-github-organizations-ad15507da9b1
so if we can sort this out now we'll make the Jupyter security teams lives slightly easier 😃.

**Comment by consideRatio** [comment]
Thank you @manics, the following users were removed. The policy is now enforced in the jupyterhub organization, for members and "outside collaborators" (those with access to individual projects).

cam72cam
cpascual
jgwerner - ltiauthenticator, i opened https://github.com/jupyterhub/ltiauthenticator/issues/108 about this as jgwernes is still somewhat active in the project.
jlooney
lsammut
magoulac
rnetro
SaladRaider
scottgs
shreddd
