### ISSUE TITLE
@consideRatio AFK: 4th Sept - 11th Sep

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#445]
I'll be on a climbing trip to Fontainebleau, probably just checking in a bit now and then to do unblocking actions.

Here a clip from a previous trip of me climbing there :)
https://www.youtube.com/watch?v=NdSoCPQIUQA

**Comment by choldgraf** [comment]
closing this since you're back :-)

**Comment by consideRatio** [comment]
Thanks @choldgraf!

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/134516217-31a03a1a-ee0b-4e8e-838d-ed846838bc48.png)

![image](https://user-images.githubusercontent.com/3837114/134516278-56fc5dd6-3dc8-4151-a2d3-c090068d9efb.png)


Me just after crashing from falling on the rock climbed above. I made it in the end though!
![image](https://user-images.githubusercontent.com/3837114/134515962-9e956edf-05b1-4240-822a-51ff46159de3.png)

![image](https://user-images.githubusercontent.com/3837114/134516590-c9e93e79-95b8-4c03-b1f1-24012b1dec84.png)

A place where there is very fine sand dunes in the middle of the forest, where there are a lot of nice boulders also. In this picture there is a famous stone that one isn't allowed to climb on. This is in Cul de chien.

![image](https://user-images.githubusercontent.com/3837114/134516940-541909c6-ffa9-4d84-90aa-5113f1fdc67d.png)

The hardest boulder i did this trip, a 6a according to the fontainebleau scale, called "roxane" I think.

![image](https://user-images.githubusercontent.com/3837114/134517204-5ca27d6a-b228-441f-8f76-4355e86358aa.png)

**Comment by choldgraf** [comment]
Thanks for sharing 🙂
