### ISSUE TITLE
Add a binder template repo for voila

### ISSUE THREAD

**Issue by fcollonval** [jupyterhub/team-compass#446]
### Proposed change

We would like to add a new example of user interface for voila on binder by:
- Adding a section in the [User interfaces](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#user-interfaces) documentation
- Adding a template repo based on [voila demo](https://github.com/voila-gallery/voila-gallery-country-indicators/) in [binder-examples](https://github.com/binder-examples).

### Alternative options

N/A

### Who would use this feature?

User interested in deploying voila dashboard on Binder

### (Optional): Suggest a solution

If you agree adding that example, what is the process for doing so.

cc @jtpio

**Comment by manics** [comment]
Sounds like a good idea. Are you happy to maintain it once it's added?

I think the easiest way is for you to create the repo in your own account, then when everyone's happy with the content transfer it to one of the owners of the binder-example GitHub org who can then transfer it to the org.

**Comment by jtpio** [comment]
Maybe we could just move this repo as-is?

https://github.com/voila-gallery/voila-gallery-country-indicators/

Then we update the Voila Gallery to point to the new location.

**Comment by sgibson91** [comment]
> Maybe we could just move this repo as-is?

I would agree if the README could be updated to discuss how to construct the Binder URL in order to point to the Voila dashboard, as that's the important thing here. It's not clear that that's what needs to happen just by looking at the files in the repo.

**Comment by choldgraf** [comment]
+1 to @sgibson91's idea!

**Comment by jtpio** [comment]
Thanks @sgibson91 and @choldgraf.

The README has been updated: https://github.com/voila-gallery/voila-gallery-country-indicators

**Comment by choldgraf** [comment]
sounds good - +1 from me

**Comment by minrk** [comment]
let's do it!

**Comment by jtpio** [comment]
Nice, thanks!

Let me do how we can proceed with the transfer. We can then rename the repo to just `voila`, and the URL of the repo will be https://github.com/binder-examples/voila

**Comment by minrk** [comment]
@jtpio if you grant me admin permissions on the repo, I think I can do the transfer, then you'll be admin on the new repo

**Comment by jtpio** [comment]
@minrk you should have Admin access now.

**Comment by minrk** [comment]
Thanks @jtpio! Migrated and updated the links in README. I believe you should have access to the new repo, let us know if anything's amiss.

**Comment by jtpio** [comment]
Nice, thanks @minrk!
