### ISSUE TITLE
Default to adopt pyugprade in our repos

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#453]
I've grown fond of the pyupgrade to the extent that I'd like to suggest we default to use it unless someone objects for our repos.

PyUpgrade is like an autoformatter that adjusts code, but pyupgrade does it to upgrade old Python code patterns to newer python code patterns. One can pass `--py36-plus` for example to make the code be compatible with py36 and above.

PyUpgrade typically doesn't change so many lines of code. For example, running it in jupyterhub/kubespawner made no difference at all, but in jupyterhub/jupyterhub it changes 68 lines of code as can be seen in https://github.com/jupyterhub/jupyterhub/pull/3584/files.

PyUpgrades [documentation](https://github.com/asottile/pyupgrade#readme) outlines all of its transformations it scans the code for code.

**Comment by consideRatio** [comment]
In https://github.com/jupyterhub/binderhub/pull/1381#issuecomment-925147219 @choldgraf suggests that we let the decision to adopt a standard across our repos be formalized by merging documentation into team-compass.

I'm not sure what or where I'd write something within our team-compass. I consider it could be a "list of decisions" voted on, or it could be a dedicated page on various practices to adopt across our github repos, etc. Any ideas?

**Comment by choldgraf** [comment]
What if we added a page like `Standards that we follow` to [our team guide](https://jupyterhub-team-compass.readthedocs.io/en/latest/index-team_guides.html). This could have a list of practices that we've agreed to at the team level. The implication would be that if a practice isn't followed in a repository, but listed here, then the team is +1 on implementing the changes needed to adopt that practice without requiring subsequent votes and discussion.

**Comment by betatim** [comment]
Do we need to run pyupgrade on every PR or would it make sense (no decision needed, no infrastructure to maintain, no tooling to explain) to run it once and then maybe again in a few months or so? Basically someone who cares/spots old Python patterns/when we want to deprecate an older version runs it locally and makes a PR to contribute the upgrades?

**Comment by consideRatio** [comment]
My suggestion is to run pyupgrade as a pre-commit hook just like black - I failed to clarify it is a available as a pre-commit hook! There is no strict need to run either black or pyupgrade automatically, but it serves the same kind of purpose of doing it automatically.

pyupgrade is developed by the author of pre-commit btw.

**Comment by manics** [comment]
I think it makes sense to include it in pre-commit, since it can only fail on new or modified code that doesn't comply.

pyupgrade should only change existing code if pyupgrade is itself upgraded (same with all other pre-commit hooks), and since that's done in a seperate PR we have full control over when it happens and what changes are required.

**Comment by minrk** [comment]
Yeah, and it may also make broader changes when we periodically bump the minimum Python for a given package, but that's something we only do once every year or two, and probably won't produce many diffs in the next few years, since our baseline (3.6 most places) already includes the most significant language features from the last several years.

Happy to give it a go.

**Comment by minrk** [comment]
Yup, I like it

**Comment by consideRatio** [comment]
Its [part of the jupyterhub/jupyterhub-python-repo-template project](https://github.com/jupyterhub/jupyterhub-python-repo-template/blob/d4bc77bea8a6066182d23f7cd86ee44ed1297e8c/.pre-commit-config.yaml#L12-L18), so I consider this resolved without further action points to make!
