### ISSUE TITLE
Write a blog post about our `/test-this-pr` infrastructure

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#456]
### Proposed change

@sgibson91 recently did a lot of cool work to improve our automated testing infrastructure for Binder deploys. She mentioned that she would like to write up a blog post about the implementation and the things that she learned along the way. This is an issue to track and hopefully help get it done :-)

I think that this would be of interest for the jupyter blog, as it might also help other BinderHub / JupyterHub deployers learn about how to accomplish similar things for their infrastructure.

**Comment by sgibson91** [comment]
I am drafting this here: https://hackmd.io/@sgibson91/rJrc5aKEt

**Comment by minrk** [comment]
btw, I've been using this quite a bit this week to test the consequences of some PRs, and it is absolutely wonderful.

**Comment by sgibson91** [comment]
I submitted the hackmd contents to blog.jupyter.org to be reviewed! 🚀

**Comment by sgibson91** [comment]
Does anyone have admin rights to the medium account to review and publish this?

**Comment by choldgraf** [comment]
I have the ability to post there. Unless anybody suggests we should do otherwise, I'll plan to do the following:

- Today, give it a quick review and make sure there isn't anything major to change
- If we're good to go, publish on Monday morning

**Comment by choldgraf** [comment]
Just a note that I took another look at the draft and I think that it is good to go! In case anybody else would like to look, you can find it here:

https://blog.jupyter.org/how-i-automated-authorised-cloud-deployments-from-pull-requests-with-github-actions-13f890538e32

**Comment by sgibson91** [comment]
I like the image you added @choldgraf, though this one actually shows the complete workflow (from https://github.com/jupyterhub/mybinder.org-deploy/pull/2044)

<img width="659" alt="Screenshot 2021-11-22 at 11 55 44" src="https://user-images.githubusercontent.com/44771837/142857688-e2d23b26-f8d7-4140-bdc5-318fe3d2e4a0.png">

**Comment by choldgraf** [comment]
ah perfect @sgibson91 - thanks very much :-) I will update the image and post today

**Comment by choldgraf** [comment]
### Update: post is published!

- Link to blog post: https://blog.jupyter.org/how-i-automated-authorised-cloud-deployments-from-pull-requests-with-github-actions-13f890538e32
- Link to tweet about it: https://twitter.com/mybinderteam/status/1462852107787251712

Thanks so much @sgibson91 for your work on this, and for the follow-up post!
