### ISSUE TITLE
August team meeting

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#46]
This issue is to schedule and coordinate the August team meeting.

There will be absences during August because of holiday and there is JupyterCon. This probably means we will not find a date that everyone can make :-/ Below I optimistically propose next week Thursday because of the absences I know of. The last meeting wasn't long ago which might be a good thing (this meeting will be shorter!).

We meet 9th August at 6pm Zurich ([in your timezone](http://arewemeetingyet.com/Zurich/2018-08-09/18:00/JupyterHub%20team)). Thursdays as usual. 

* video link: https://calpoly.zoom.us/my/jupyter
* [ ] agenda link: https://hackmd.io/2-_aFfk-RtCOBvjKDCWT0g
* [ ] announce on: gitter, jupyter@googlegroups.com, jupyter-education@googlegroups.com, binderhub-dev@googlegroups.com

**Comment by choldgraf** [comment]
I can meet tomorrow if need be, but am also +1 on postponing until after JupyterCon since I imagine folks will be chatting with one another quite a bit in the days leading up to the conference anyway.

**Comment by betatim** [comment]
There are three people who said "yes" (including Chris) so I'd suggest we meet, even if it is only a short one. It would be a good opportunity to coordinate what ever needs coordinating for JupyterCon. Maybe we want to have some standard answer/comment on some questions that might come up or some such?

**Comment by consideRatio** [comment]
I'd happily meet with you today at 6pm Zurich time (also Swedish time)!

---

I'm attempting to break apart https://github.com/jupyterhub/kubespawner/pull/205 into smaller pieces to make it easier to overview and review changes. I'd be very happy to get your eyes on them!

#### I :heart: reviews
- [ ] Part 1: https://github.com/jupyterhub/kubespawner/pull/230
- [ ] Part 2: https://github.com/jupyterhub/kubespawner/pull/231

**Comment by jzf2101** [comment]
Can we close this?
