### ISSUE TITLE
The littlest jupyterhub day - a maintenance sprint Friday 22th October?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#460]
I've not helped out with maintenance of https://github.com/jupyterhub/the-littlest-jupyterhub, but I'd like that to change as I've now setup a hub myself for the first time and learned how cool the project is!

I think maintenance work to requires momentum, and that such momentum is gained by working together with others. As an example, I see some PRs opened by other JupyterHub team members, but they have gone stale by a lack of review input. Perhaps if we make a common push, we can make progress enough to make the maintenance process easier going onwards?

I propose a day next week where we sprint together to triage issues and review PRs! Would someone like to join me in such effort? I suggest __Friday 22th October, next week__, that is one day after our [team meeting on Thursday](https://github.com/jupyterhub/team-compass/issues/449) where this can be announced as well.

Practically, I think of that day as people coming and going when they have time - focusing work towards the maintenance of this repo, with some Gitter `jupyterhub/random` chat channel interactions, and spontaneous video calls.

- [x] PR review and triage
  There are currently 20 open PRs
- [x] Issue triaging
  There are currently 177 open issues

**Comment by minrk** [comment]
I've been home with a sick toddler for almost two weeks, so my time's been limited, but I'm hoping he can go back to barnehage tomorrow, in which case I'll be happy to join this effort.
