### ISSUE TITLE
The future of the classic notebook interface

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#461]
Hey y'all, I'm opening this issue here to (hopefully) increase visibility on the discussion about the future of the classic notebook. 

"The future of the classic notebook": https://github.com/jupyter/notebook/issues/6210

### If you have thoughts on this topic, please visit the above issue and leave comments

Let's try to centralize conversation there and avoid commenting here.

**Comment by choldgraf** [comment]
thanks @Zsailer for opening this! I edited your top comment to make that point a bit easier to notice :-)

**Comment by tonyfast** [comment]
hey y'all, we're starting to converge on some concrete steps to get through this transition. the weekly notebook meetings are going to be repurposed to manage the release of notebook 7. we're going to manage these steps using a github project that we'll fill out over the next few weeks. https://github.com/orgs/jupyterlab/projects/2/

i've started new hackmd to keep track of our meetings https://hackmd.io/gl6x_SL0S_aYVn0Y0lSBpQ

**Comment by choldgraf** [comment]
Thanks for this update Tony! I also opened up this in the repo2docker repo in case we want to follow-suit with mybinder https://github.com/jupyterhub/repo2docker/issues/1095

**Comment by tonyfast** [comment]
we discussed moving notebook classic to the jupyterlab organization to make managing the sunrise process a little smoother. 

@Zsailer do we need to open a new issue entirely?

**Comment by tonyfast** [comment]
is there an existing place for notebook classic meeting notes on the team compass or should i start a new thread?

**Comment by jtpio** [comment]
> is there an existing place for notebook classic meeting notes on the team compass or should i start a new thread?

Yes the meeting notes are now being added to this issue: https://github.com/jupyter/notebook-team-compass/issues/5

Looks like this issue can now be closed, since the JEP has been accepted and the fist 7.0 pre-release is out?

- https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html
- https://github.com/jupyter/notebook/releases/tag/v7.0.0a1

**Comment by choldgraf** [comment]
Hey all - since that conversation has now completed and we have several other links and threads for more discussion, I'll close this one. Thanks @zsailer for being inclusive and bringing the JupyterHub team's attention to these important conversations!
