### ISSUE TITLE
Guidelines regarding self-merging PRs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#466]
We typically avoid to self merge PRs, but I do it from time to time for various reasons. It would be great to have some guidelines or rules of thumbs, and perhaps some indication on we think about this made explicit rather than implicit.

I wanted to create this PR now that #465 is opened regarding pushing commits vs opening PRs, as the act of self-merging a PR or not is a bit of a separate discussion in my mind but still quite relevant to discuss next to #465.

### EDIT: list of self-merged PRs, please feel free to update this with PRs you self-merge
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2480
- https://github.com/jupyterhub/binder/pull/250
- https://github.com/jupyterhub/action-major-minor-tag-calculator/pull/149
- https://github.com/jupyterhub/jupyterhub/pull/3708
- https://github.com/jupyterhub/jupyterhub/pull/3705
- https://github.com/jupyterhub/jupyterhub/pull/3720

**Comment by lambdaTotoro** [comment]
My point in favour of at least occasionally self-merging PRs is the same as my point. Insisting on at least four eyes on every line of code and every moved comma sacrifices time and fun for bureaucracy and procedure (and spurious security concerns). Again, I do agree that within a serious organisation, procedure is sometimes necessary. But keep in mind that procedure is here to make things easier for us and not the other way around.

**Comment by consideRatio** [comment]
To me, self-merging some kinds of PRs are essential for the maintenance of some projects. Maintenance is done by humans, and we are limited in capacity and are influenced by things such as context switching. I'm clearly and strongly against defining a strict no-self-merge policy, at the same time I think it's crucial we don't end up feeling shame or similar for self-merging because its against an abstract ideal of never self-merging.

I deliberated on outlining ideas I have about when and why to self-merge, but perhaps instead of doing that, we could instead start linking to PRs that we self merge to this issue? If we make this issue collect a set of situations where we have self-merged a PR, we can then have a more concrete discussion about the practice.

The more concrete we can make this discussion, the less complicated it will become I think! I'll go ahead and write a comment in this issue whenever I self-merge a PR to build up some examples to discuss in the future!

**Comment by choldgraf** [comment]
I agree with this:

> So I would actually like to see self-merging become more normalised, and the question then becomes “when is self-merging without review appropriate?” and I think that broadly overlaps with what you’ve already highlighted: typos, broken links, etc.

Can we adopt a policy like:

- Most PRs need at least one approving review from a team member before merging
- Some kinds of PRs (relatively minor documentation changes, for example) do not require an approving review
- As soon as there's an approving review anybody can merge it and the author is encouraged to self-merge
- In general, PRs that are self-merged without review should first be open for at least 2 working days

With a big helping of: **use your best judgment** - the goal of our processes should be to encourage transparency and collaboration, and reviews are a great way to ensure that we share context and knowledge with one another, and improve the codebase. In general, take actions that you think are inclusive of other team members, and reasonable given the nature of the PR and how impactful/complex it is.
