### ISSUE TITLE
Hubs Team Meeting - December 2021

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#472]
Hello everyone!

Reminder that our next meeting is **Thursday, 16th December, 2021 at 9 AM Europe/London** (or [your timezone](https://arewemeetingyet.com/London/2021-12-16/09:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

Please think of things to make this meeting extra festive! 🎄 🎁 🎊

**Comment by betatim** [comment]
I'll be there (and unlike previous times I said that I have made myself several big fat reminders so I don't forget :D)

**Comment by minrk** [comment]
I'll miss this one, as I'll be in a US timezone.

**Comment by choldgraf** [comment]
I'm in the same boat as @minrk but hope that the meeting is joyful and full of holiday spirit :-)

**Comment by sgibson91** [comment]
Friendly reminder that this meeting is happening tomorrow.

I'm getting my Covid booster shot later today, so there's a small chance that I won't make the meeting due to feeling terrible and deciding to stay in bed 🙂
