### ISSUE TITLE
Reduced availability 12/7-31

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#475]
I'll be traveling from 12/7-23, then back just in time for holidays, so will have reduced capacity. I'll be in US East, timezone-wise.

**Comment by minrk** [comment]
Forgot to update: trip was cancelled, so I'm still working in Oslo timezone this week and some of next.

**Comment by choldgraf** [comment]
Sorry to hear that min 😔 I hope you are enjoying your holiday as best you can
