### ISSUE TITLE
Collaborate on Binder User Workshop?

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#476]
As some of you may remember, I was successful in applying for an SSI Fellowship with a focus on expanding the Binder contributor community, particularly with members from the Julia and R communities https://github.com/jupyterhub/team-compass/issues/208

Since the pandemic hit very early on in my Fellowship, I haven't really acted on a lot of my plans beyond the three talks I had committed myself to giving: EuroPython 2020, eRum 2020 and JuliaCon 2020. As a result, I still have most of the £3k award remaining. The SSI have also extended the 2020 cohort up to December 2022 so I have another year to implement some plans.

Given the extension and the upcoming JupyterHub Community Strategic Lead role, @choldgraf and I had a chat about how we could align these two strategies, which is laid out in this issue https://github.com/sgibson91/ssi-fellowship/issues/32

Also, the call for mini-workshop proposals at [Collaborations Workshop 2022](https://software.ac.uk/cw22) is now open and I thought such an event would be a great test bed for the first draft of a survey/focus group mentioned in the new direction. I intend to plan a submission in this issue https://github.com/sgibson91/ssi-fellowship/issues/33

Would anybody be interested in collaborating with me on this workshop, in any capacity? :)

cc/ @choldgraf @willingc

**Comment by minrk** [comment]
What sort of collaboration would you find useful? I'd be happy to help out, if I can.

**Comment by sgibson91** [comment]
I think there's definitely tasks pre- and post-workshop that will lend themselves to distributed/async collaboration.

Pre-workshop: drafting the survey questions/discussion points so that we get information we're interested in. I'm particularly interested in thinking about _what things about Binder are difficult in Julia and R because we're a Python-based team? What community practices do we miss and lack representation for?_ But there may be other questions we'd like to use this opportunity to gather information for too.

Post-workshop: data collation, analysis and dissemination, probably a blog post.

**Comment by minrk** [comment]
I can help with those!

**Comment by sgibson91** [comment]
Thanks so much! I pinged you on the issue and gave you access to the repo too. We can convene over there :)

**Comment by sgibson91** [comment]
I'll close this now, but folk should still feel free to join in at https://github.com/sgibson91/ssi-fellowship !
