### ISSUE TITLE
Hubs Team Meeting - January 2022

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#480]
Hello everyone!

Reminder that our next meeting is **Thursday, 20th January, 2022 at 5 PM UTC** (or [your timezone](https://arewemeetingyet.com/UTC/2022-01-20/17:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-amalthea/12208/4

**Comment by manics** [comment]
There'll be a demo of Amalthea!
https://discourse.jupyter.org/t/jupyterhub-amalthea/12208/7

**Comment by sgibson91** [comment]
Reminder that this meeting is tomorrow!

**Comment by ableuler** [comment]
> There'll be a demo of Amalthea! https://discourse.jupyter.org/t/jupyterhub-amalthea/12208/7

I have a few slides that I can show too. How much time can the presentation/demo/discussion on Amalthea cover in total?

**Comment by consideRatio** [comment]
> I have a few slides that I can show too. How much time can the presentation/demo/discussion on Amalthea cover in total?

I'm thinking 10 minutes would be a reasonable to aim for and perhaps a hard limit on 20 minutes. I'm just ballparking what seems reasonable though, in practice there is no strict time schedule and in my mind what's important is that we get to cover the agenda items and allow people to raise some discussion point on the fly. Currently, the agenda is very sparse but i believe Yuvi Panda will add a demo as well.
