### ISSUE TITLE
JupyterCon Talk - Learn by Doing (Erik, Jessica, Carol)

### ISSUE THREAD

**Issue by willingc** [jupyterhub/team-compass#49]
@consideRatio @jzf2101 I've taken a first pass at outlining and blocking timing for our JupyterCon talk. [Outline](https://hackmd.io/WW8524KMTJum8jKUsn15IQ) using our [original submission](https://hackmd.io/cqbDJFHSR7yKEuHRetO9Lg) as a starting point.
I've put some names to sections, but feel free to change/add yourself to sections as interested. In sections III, IV, V, I was thinking we could each take one and talk about the item and our personal use in the classroom.

Last year the audio was a bit of a challenge with multiple speakers. Passing of handheld mic IIRC. Let's try to minimize the transitions.

Let's create a Google presentation using the Jupyter template for the slidedeck.

**Comment by consideRatio** [comment]
Thank you @willingc for writing this up!

**Comment by jzf2101** [comment]
I'll start wt littlest jupyterhub and hopefully that'll get the \ball rolling with shared slides

**Comment by willingc** [comment]
@consideRatio @jzf2101 Here's a shared Google Presentation with the Jupyter theme that we can use for the talk: https://docs.google.com/presentation/d/11Xm6raWcF7uGzpqmJHLhMM812UN2ES8sKmo-Nek9_Lw/edit?usp=sharing

I've added the subsection dividers and put a slide of all the hackpad in this as well.

**Comment by consideRatio** [comment]
Thank you @willingc!

**Comment by willingc** [comment]
Great job @consideRatio @jzf2101.

**Comment by choldgraf** [comment]
yay!!! way to go everybody!
