### ISSUE TITLE
EU Binder proposal 2022

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#490]
I'm working on an EU proposal in collaboration with Hans Fangohr at Max Planck

[The call](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/horizon-widera-2022-era-01-41).

Key points:

Deadline: 20 April, 2022
Scope: 2M Euro over 3 years (probably just a few partners)

The gist of the call: improving reproducible scientific results in Europe by any means (technical, social, policy)

Proposed approach:

- Study reproducibility with repo2docker, so we can measure how we are doing 'improving' it
- Explore 'verification' step in repo2docker to help check if an environment was correctly produced beyond 'did it build'
- Expand best practice coverage in repo2docker (support more buildpacks, etc. In practice: dedicate time to reviewing/merging all those existing PRs!)
- Improve repo2docker reproducibility in general (e.g. taking last modified time into account to select default runtime version, package mirrors, selecting past r2d versions, etc.)
- Education - workshops, docs, demonstrations of best practices, pitfalls
- Help with current effort to use BinderHub outside Kubernetes
- authenticated BinderHub for on-site data access
- Specific demonstration applications from science & HPC
- General support of BinderHub/repo2docker/JupyterHub maintenance

A key angle I want to take is that I think our "automating existing best practices" approach is valuable in this context because it improves reproducibility and practice _whether folks use repo2docker/binder or not_. Binder is a motivator/tool to make these things more attractive/valuable, but the practices themselves are beneficial on their own. This is unlike many reproducibility tools that require total buy-in to be useful. We try to meet folks where they are. The phrase "best practice" is even in the call!

Taking notes [here](https://docs.google.com/document/d/1B5tQxdsaP4j_7uhp7BXH9MQzI5gTM2A-pIBz2Xwzh9w) will start drafting on a repo soon, and will post a link here when that starts.

**Comment by choldgraf** [comment]
I'm happy to do whatever I can to support this, let me know if I can be helpful

**Comment by sgibson91** [comment]
Just want to explicitly say that I think there is tie-in with what we're trying to achieve over in https://github.com/sgibson91/ssi-fellowship/issues/32 and https://github.com/sgibson91/ssi-fellowship/issues/33 and give my permission/consent/blessing upfront to reuse whatever useful results we find over there in this proposal.

**Comment by minrk** [comment]
Submitted!

**Comment by choldgraf** [comment]
I wish you innumerable success in this grant @minrk !
