### ISSUE TITLE
Hubs Team Meeting - March 2022

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#493]
Hello everyone!

Reminder that our next meeting is **Thursday, 17th March, 2022 at 5 PM UTC** (or [your timezone](https://arewemeetingyet.com/UTC/2022-03-17/17:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

**Comment by sgibson91** [comment]
A reminder that this meeting is tomorrow!

**Comment by manics** [comment]
<a title="Whoisjohngalt, CC BY-SA 4.0 &lt;https://creativecommons.org/licenses/by-sa/4.0&gt;, via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:Balloon_leprechaun_at_Boston%27s_St_Patrick%27s_Day_Parade_in_2018.jpg"><img width="256" alt="Balloon leprechaun at Boston&#039;s St Patrick&#039;s Day Parade in 2018" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Balloon_leprechaun_at_Boston%27s_St_Patrick%27s_Day_Parade_in_2018.jpg/256px-Balloon_leprechaun_at_Boston%27s_St_Patrick%27s_Day_Parade_in_2018.jpg"></a>

**Comment by betatim** [comment]
As I just (re)learnt: the US has moved timezones, but Europe hasn't so make sure to double check "in your timezone"
