### ISSUE TITLE
Temporarily scale back the Turing cluster.

### ISSUE THREAD

**Issue by callummole** [jupyterhub/team-compass#495]
### Proposed change
The Turing cluster current has £230 left on the subscription. It will currently run out of credits towards the end of the week.

There is a credit request pending for £28k (described [here](https://github.com/callummole/the-turing-way/blob/binder_credit_reqs/project_management/credit_requests/turing_mybinder_azure_credit_request_2022-03.md)) that I am hopeful to hear from soon (I have nudged this morning and the team is aware of the urgency).

Is it possible to roll the pod quota back to something small (40 or 80?) for rest of the week while the pending request gets approved? The quota is currently 200.

**Comment by sgibson91** [comment]
@callummole See this PR for an example of how to remove the Turing from the federation https://github.com/jupyterhub/mybinder.org-deploy/pull/1800 (To reinstate, simply revert

**Comment by sgibson91** [comment]
That's totally fine! Do whatever you feel is best. I'm happy to review a PR too.

**Comment by choldgraf** [comment]
I'm +1 on just removing it for now. We don't want to create a stressful credit crunch situation for @callummole !

**Comment by minrk** [comment]
Removing in https://github.com/jupyterhub/team-compass/issues/495

**Comment by callummole** [comment]
Sorry - I took time off sick yesterday. Thanks @minrk for being so efficient.

**Comment by callummole** [comment]
Funding approved and cluster restarted. Reinstated in https://github.com/jupyterhub/mybinder.org-deploy/pull/2161

**Comment by minrk** [comment]
Turing's back online and accepting users. Thanks @callummole!
