### ISSUE TITLE
State of JupyterHub talk

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/team-compass#50]
I started an outline here: https://hackmd.io/jdO1Cl8MQVCZlDUHGE74Dw#

/cc @minrk

**Comment by minrk** [comment]
Yeah, definitely! Feel free to add A few bullets and notes to the outline and we'll work them in. I don't think we're short on time at all.

**Comment by jzf2101** [comment]
I'm assuming we can close? Feel free to reopen.

**Comment by choldgraf** [comment]
congrats all on giving the talk!
