### ISSUE TITLE
Hubs Team Meeting - April 2022

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#500]
Hello everyone!

Reminder that our next meeting is **Thursday, 21st April, 2022 at 9 AM Europe/London** (or [your timezone](https://arewemeetingyet.com/London/2022-04-21/09:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

**Comment by minrk** [comment]
I'll miss this week because I have a work event at the same time. Our work schedule has changed with returning to the office such that I'm going to have a conflict with the Thursday EU AM time slot relatively often. I don't relish proposing a rescheduling, though.

**Comment by minrk** [comment]
Tuesday, Wednesday, Friday all ~always work for me.

**Comment by minrk** [comment]
I'll also mention: not all Thursdays won't work for me, if change is too disruptive. But probably about half and hard to predict. Shifting by an hour on Thursday either direction will work more often, but with partial work-from-home, Thursday is our "everybody in the office" day and tends to accumulate meetings and events, some of which have to take precedence.

**Comment by betatim** [comment]
I think Tuesday would be a good new day to propose for the "Asia/EU" meeting. At least from those present at the meeting yesterday no one hated that idea/sounded like it was equally good as Thursday.

**Comment by choldgraf** [comment]
Tuesday at the same time CET is also not a problem for me either!

Is this moving both of the meetings, or just the CET one? The Americas-friendly meeting time might occasionally overlap with 2i2c team meetings, though we might be able to stagger ours by a week or something if need be.

**Comment by minrk** [comment]
I think we were only talking about EU AM, but I'm okay either way.
