### ISSUE TITLE
Deploy a Binder federation member on AWS?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#501]
### Context

In recent meetings around Binder sustainability (e.g. #430) a few times @manics has mentioned interest in running an AWS-based BinderHub. I believe that we could also get access to AWS credits for running a BinderHub federation member on AWS.

### Proposal

If @manics is willing to lead deployment and operations efforts, I'd like to set up an AWS-based federation member for mybinder.org. This could distribute the load towards more cloud providers, which gives us more options for accepting credits that can power the service.

### Questions to answer

- [ ] Is @manics willing to give this a shot?
- [ ] How can we share knowledge and responsibilities with other team members so that this load doesn't fall on him alone?
- [ ] Where can we get AWS credits from? (I have a few ideas)

**Comment by MridulS** [comment]
btw I can help around too with the AWS backed binderhub :)

**Comment by minrk** [comment]
We have terraform setup for GKE (it's not run on CI, but at least the deployment is recorded and automated so it's easier to teardown/redeploy). It may make sense to do the same for AWS. I _suspect_ all we need is the terraform for an AKS cluster, and the rest should be a standard federation member.

**Comment by manics** [comment]
I'm happy to take the lead. Most of the work will be deciding between the different options (e.g. EKS EC2 vs Fargate, ECR vs self hosted container registry). I'd probably approach this by starting with some manual deploys, then ripping down everything and rebuilding with Terraform a few times till we're happy.

**Comment by sgibson91** [comment]
In the September Team Meeting (#554 ) we discussed that Pangeo would like to contribute their AWS Binder to the federation as providing a separate, unauthenticated Binder didn't seem to have much value add. This Binder would be operated by 2i2c and would not have Dask Gateway available, as the current instantiation does. Notes from the discussion are in https://github.com/jupyterhub/team-compass/pull/567

**Comment by betatim** [comment]
That would be super cool! As to "what is the value of a standalone binderhub?" - I had hoped the pangeo people knew the answer to that when they set it up :D

**Comment by sgibson91** [comment]
I think it was specifically "what is the value of _another unauthenticated, globally accessible_ binderhub?". There's two things you can do there: offer something fundamentally different to what mybinder.org does (which was dask gateway, in the past. There is usually a cost associated with this though), or join the federation and increase the resources of mybinder.org (I also don't think the federation existed or was very new when Pangeo Binder was first setup). I agree that the answers to that question look very different if you have a more specific audience in mind though.

**Comment by sgibson91** [comment]
FYI, as of today I got access to an AWS account being managed by @scottyhq and will start providing config to deploy a cluster and hub to that account in the mybinder.org-deploy repo soon.

**Comment by choldgraf** [comment]
closing this as superceded by:

- https://github.com/jupyterhub/mybinder.org-deploy/issues/2556
