### ISSUE TITLE
Hubs Team Meeting - May 2022

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#510]
Hello everyone!

Reminder that our next meeting is **Thursday, 19th May, 2022 at 5 PM UTC** (or [your timezone](https://arewemeetingyet.com/UTC/2022-05-19/17:00/Hubs%20Team%20Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

**Comment by sgibson91** [comment]
A reminder that this meeting is tomorrow!

**Comment by minrk** [comment]
The event on Google Calendar has this happening at 16:00 UTC, not 17:00 UTC. IIRC the resolution of #371 correctly, the event should be at 19:00 central-europe year-round. Is that right? Which are we doing tomorrow?

**Comment by sgibson91** [comment]
Oh god, I am so confused right now. I thought it was happening at 5pm UTC+1 but I'm going off just the Google calendar, because it's the only one in my calendar and that is indeed not the info I have put in this issue or the hackmd

![Screenshot 2022-05-18 at 14 01 38](https://user-images.githubusercontent.com/44771837/169045073-85cec64e-055e-46a8-9a38-68d8194b7354.png)

I think this should be at 5pm UTC/6pm BST (UTC+1)

**Comment by sgibson91** [comment]
I just updated the calendar, does this look like it's resolved itself now?

**Comment by sgibson91** [comment]
Thank you for being patient with me - calendars are hard 🙂
