### ISSUE TITLE
Help making releases: nativeauthenticator, oauthenticator, kubespawner

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#518]
Now is a good time as ever to cut some releases. Looking at the [list of dependencies for the hub image in z2jh](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/images/hub/requirements.in), I see the following projects and consider if we should cut a release of them.

- [x] [jupyterhub](https://github.com/jupyterhub/jupyterhub)
  2.3.0 was recently released.
- [x] [jupyterhub-firstuseauthenticator](https://github.com/jupyterhub/firstuseauthenticator)
  No release needed.
- [x] [jupyterhub-hmacauthenticator](https://github.com/yuvipanda/hmacauthenticator)
  No release needed.
- [x] [jupyterhub-ldapauthenticator](https://github.com/jupyterhub/ldapauthenticator)
  No release needed, only three PRs merged, related to CI and docs about study participation.
- [x] [jupyterhub-ltiauthenticator](https://github.com/jupyterhub/ldapauthenticator)
  No release needed, only one PR merged, related to CI.
- [x] [jupyterhub-nativeauthenticator](https://github.com/jupyterhub/nativeauthenticator)
  There are a few maintenance PRs and quite a few docs PRs that we could cut a release with it seems, since the last release 1.0.5 made 19th october.
  @lambdatotoro do you want to help out with this?
  See https://github.com/jupyterhub/nativeauthenticator/blob/main/RELEASE.md for details. EDIT: oops this isn't defined yet, but should be similar to for example https://github.com/jupyterhub/oauthenticator/blob/main/RELEASE.md.
- [x] [jupyterhub-tmpauthenticator](https://github.com/jupyterhub/tmpauthenticator)
  Nothing new.
- [x] [nullauthenticator](https://github.com/jupyterhub/nullauthenticator)
  Now officially deprecated with https://github.com/jupyterhub/nullauthenticator/pull/5, I'll remove it from the z2jh image.
- [x] [oauthenticator](https://github.com/jupyterhub/oauthenticator)
  A release is relevant, new features has been added I know.
  @2i2c-org/tech-team do you want to help out with this?
  See https://github.com/jupyterhub/oauthenticator/blob/main/RELEASE.md for details.
- [x] [jupyterhub-kubespawner](https://github.com/jupyterhub/kubespawner)
  Releases has been made recently already, but the feature https://github.com/jupyterhub/kubespawner/pull/607 isn't part of a release yet. Anyone feeling like making 4.1.0 are most welcome to go for it.
  See https://github.com/jupyterhub/kubespawner/blob/main/RELEASE.md for details.
  This was done by @GeorgianaElena, thank you!!!
- [x] [jupyterhub-idle-culler](https://github.com/jupyterhub/jupyterhub-idle-culler)
  A doc and ci PR has been merged, no release needed.

**Comment by consideRatio** [comment]
> Nativeauthenticator is not far from a new release, I think we can have that sometime soon. Are we on a specific timeline?

Wieee thanks for your work @lambdaTotoro!!! No deadline exist!

I'm just going through things across the JupyterHub org as part of a general maintenance push. I find myself doing that when about to cut a major z2jh release as it imports many other dependencies from the JupyterHub org. We can always bump a version of oauthenticator and nativeauthenticator after as well - especially if they aren't breaking changes.

**Comment by manics** [comment]
https://github.com/jupyterhub/nativeauthenticator/issues/214
