### ISSUE TITLE
** Now on Tuesdays! ** Hubs Team Meeting - June 2022

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#523]
🚨 **Note:** As agreed upon in our last one, our team meetings will now happen on the third _Tuesday_ of each month, still alternating timezones. 🚨 

Hello everyone!

Reminder that our next meeting is **Tuesday, 21st June, 2022 at 9AM Europe/London** (or [your timezone](https://arewemeetingyet.com/London/2022-06-21/09:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

**Comment by minrk** [comment]
I am traveling tomorrow, so I'm not sure if I'll be able to make it in the morning. I'll try, though!

**Comment by sgibson91** [comment]
We didn't have many people join today and not a lot on the agenda, so we reviewed some PRs that are listed in the Quick Updates section of the HackMD. I won't put up a PR for notes for this month, as there aren't any!
