### ISSUE TITLE
Bug in the documentations TOC, unsure where to report

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#525]
I'm not sure where this makes sense to report, perhaps @choldgraf has a guess?

The bug is that when I press an entry in the TOC, i arrive at the correct anchor and such, but the wrong part of the TOC is expanded. This can be seen in https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html now.

![doc-bug-in-toc-the-one-above-is-selected](https://user-images.githubusercontent.com/3837114/172252847-142375f1-4766-47cf-add3-babadd7d7d22.gif)

**Comment by choldgraf** [comment]
This is already fixed in the theme! Just not released yet 🙂

**Comment by consideRatio** [comment]
Thanks Chris!
