### ISSUE TITLE
Redeploy Turing cluster to UK south

### ISSUE THREAD

**Issue by callummole** [jupyterhub/team-compass#529]
To reduce costs I have been asked to redeploy the Turing cluster from West Europe Azure region to UK South, where Turing has reserved instances. 

Turing is currently unhealthy (https://github.com/jupyterhub/mybinder.org-deploy/issues/2252). Redeployment may help if [this hub23 ingress PR](https://github.com/alan-turing-institute/hub23-deploy/pull/445) doesn't help.

As a timescale for this, I will have time Friday 24th June to do this (yeah right).

Since Turing is not part of the federation redirect this shouldn't affect mybinder.org's current levels. I suggest we keep Turing out of fed redirect for another week (even if [#445](https://github.com/alan-turing-institute/hub23-deploy/pull/445) helps with our DNS issues - will upgrade the hub23 helm chart later today).

Thoughts welcome.

**Comment by minrk** [comment]
That sounds great. We can take the current cluster out of our CD since it's failing anyway.

It should (hopefully) be a small update in this repo to load the credentials for the new cluster once it's up.

**Comment by callummole** [comment]
Just quickly to say that I'm very sorry that this isn't closed yet, and am now on holiday for two weeks. I finished up a project this week, which means I will have time to do this in the week commencing July 18th. Then hopefully usual service will resume.

**Comment by sgibson91** [comment]
I think this is closed now, save for some CI issues? Reopen if in disagreement!
