### ISSUE TITLE
Jupyter Community Call - June 2022

### ISSUE THREAD

**Issue by isabela-pf** [jupyterhub/team-compass#534]
June's Jupyter community call is coming soon! Join us on Tuesday, June 28 at 3pm Pacific ([in your timezone](https://arewemeetingyet.com/Los%20Angeles/2022-06-28/15:00/Jupyter%20Community%20Call)) for another adventure in community.

-   If you’d like to share, you can sign up by adding yourself to [the agenda ](https://hackmd.io/V24b_NCCQRy-UT4EyvbrUw) before the call begins.
-   To attend, you can [join on Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09) at the time of the call.

Hope to see you at the call!

**Note:** We’ve had two different times in a row,  and June will be at a different time while we experiment with a new schedule.

**Comment by sgibson91** [comment]
Closing as this has passed :)

**Comment by isabela-pf** [comment]
Thank you! Here are the [notes](https://github.com/jupyter/jupyter/issues/618) and [recording](https://youtu.be/pyEE4tjsj3U) as well!
