### ISSUE TITLE
Slides from JupyterCon?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#54]
Hey all - I'm giving a talk about JupyterHub at the West Big Data Hub meeting next week. It's a 2-hour talk about JupyterHub in education and will hopefully be given to some folks with $$$ to pay for things like shared compute infrastructure for universities. It'll be part "motivate why we need things like JupyterHub", part "what is JupyterHub and how do you use it" and part "what new people/tech infrastructure is needed for universities to make the most of it?".

I am hoping to recycle previously-existing JupyterHub talk material as much as possible, since I'm going to be in honeymoon mode until 2 days before I have to give this talk (I know, this sounds crazy to me too). Would folks be willing to share links to their JupyterHub material from JupyterCon? I think I remember @willingc @minrk @yuvipanda @betatim and @consideRatio gave talks...maybe others as well?

**Comment by betatim** [comment]
[Tim's slides on Binder](https://rawgit.com/wildtreetech/jupyterhub-talk/d196b3eb55b5683812c3d40380ebd01a891b30ac/index.html?p=talk-binder-jupytercon18.md#1)

**Comment by consideRatio** [comment]
[2018-08-jupytercon -  a shared Google Drive folder](https://drive.google.com/drive/u/0/folders/1ck-OaqKvlvOUkuJmMRw5pCdh0F67YmJh)
At the time of writing, it contains:
- Learn by doing: Using data-driven stories and visualizations in the (high school and college) classroom
- Deploying a cloud-based JupyterHub for students and researchers
- Portable Research and Learning Environments with Jupyter

**Comment by willingc** [comment]
All of my talks on Jupyter and education, given prior to JupyterHub, can be found on [SpeakerDeck](https://speakerdeck.com/willingc).

**Comment by minrk** [comment]
My slides are [on speakerdeck](https://speakerdeck.com/minrk/the-current-state-of-jupyterhub)

**Comment by yuvipanda** [comment]
Slides from my Mybinder.org talk: https://docs.google.com/presentation/d/1nb-baeB-XHZiPrPlBoDVLMa2Dr9nPkV3XdQ3kFL7OhE/edit?usp=sharing

slides from my half of the JupyterHub talk: https://docs.google.com/presentation/d/1_SDeizA6GxbKzDHq23dKzshE52F012QxxKVxO537hpU/edit

**Comment by choldgraf** [comment]
yay, thanks everybody :-)  I really appreciate it! It means I can spend more time looking at old Roman stuff and less time preparing slides <3

**Comment by choldgraf** [comment]
also, speakerdeck is cool! I never heard of it before. That's way easier than me sending google slides links to people!

**Comment by jzf2101** [comment]
Great I'm assuming we can close
