### ISSUE TITLE
Migrate pamela, escapism to jupyterhub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#540]
I noticed in the PyPI critical package updates that these two are on my github and only have me as a maintainer. They don't really require any maintenance, given that they are single-purpose packages, but they dependencies of jupyterhub and kubespawner, at least. Should we bring them into the jupyterhub org and add more folks on PyPI?

**Comment by choldgraf** [comment]
IMO if they:

- are related to the mission of jupyterhub (which I'd define like "enabling multi-user experiences on shared infrastructure with jupyter")
- require similar skills and knowledge as our other repositories
- are tools we regularly use or depend on

Then they are good candidates for being in our org. (But I must admit I don't know the answers to these questions except the last one, so I'd defer to others)

**Comment by manics** [comment]
I think we should move them to the JupyterHub GitHub or some other org. They're definitely core dependencies of JupyterHub even if they're not directly visible.

Alternatively we could find a new organisation to own them, either an existing one or https://github.com/jupyterhub/team-compass/issues/519 ?

**Comment by minrk** [comment]
These packages provide core features of jupyterhub and kubespawner (and BinderHub, I think). They require ~no maintenance because their scope is extremely small and has no reason to grow. While they are generic, they really only exist to solve jupyterhub problems, and are comfortably directed by the needs of jupyterhub. They are tiny pure-Python packages, so the skills should match most of everything.

**Comment by choldgraf** [comment]
+1 from me!

**Comment by yuvipanda** [comment]
Yeah, I think they should be moved for same reason https://github.com/jupyterhub/simpervisor/ is here.

**Comment by minrk** [comment]
Only took me a year, but just did this:

- https://github.com/jupyterhub/escapism
- https://github.com/jupyterhub/pamela

and added them to the Jupyter org on PyPI

**Comment by minrk** [comment]
*make that 2.5 years. Sheesh.
