### ISSUE TITLE
JupyterHub updates at SciPy

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#541]
There's going to be a short update on Jupyter projects.

Any Jupyter/Binder-related updates in the last year that folks want to highlight? Maybe the imminent z2jh 2.0 and the RTC-related granular permissions in jupyterhub main?

**Comment by choldgraf** [comment]
Maybe steps towards donation infrastructure for binder? We are not quite there yet but have taken some important steps forward. How much time do we have?

**Comment by manics** [comment]
The new community role? https://github.com/jupyterhub/team-compass/issues/536
It's nice to highlight the non-technical aspects of the project.

**Comment by manics** [comment]
This ran from 11-17 July https://www.scipy2022.scipy.org/
