### ISSUE TITLE
Transition to using the Jupyter central calendar ?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#543]
@afshin raised a topic in todays JupyterHub team meeting about adding entries about JupyterHub team meetings in the Jupyter calendar, which for example is featured at https://jupyter.org/community#calendar.

I consider the following separate options:
1. Should we stop using the JupyterHub calendar, and rely on JupyterHub calendar entries in the Jupyter calendar?
2. Should we put meetings entries in two calendars?
3. Should we stay with the JupyterHub calendar only?

Maybe there are more options as well?

I nominate option 1 to avoid the risk of getting calendars out of sync, and ensuring that our meetings are featured in the centralized calendar. If there is a technical option to let a calendar have sub-calendar, that would be optimal though - but I don't think it can have that even though users can be subscribed to multiple calendars.

What are your thoughts?

---

Practically, @afshin can provide admin access to this calendar for us.

**Comment by choldgraf** [comment]
What is the main benefit of using a central jupyter calendar instead of a jupyterhub-specific one? Put another way, what is the problem we are trying to solve here?

I think it's also important to know where the jupyter calendar is documented, and what processes are needed to change entries there.

**Comment by choldgraf** [comment]
I opened a PR to try and clarify this a little bit, maybe it would help: https://github.com/jupyterhub/team-compass/issues/543

**Comment by afshin** [comment]
The PR is linked automatically above your comment, but I think you meant to link to: https://github.com/jupyterhub/team-compass/pull/546

**Comment by choldgraf** [comment]
yep - updated
