### ISSUE TITLE
mybinder.org meets kaggle

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#55]
At JupyterCon I had lunch with Rachel Tatman from kaggle and she mentioned we should have a chat about the cloud bill of mybinder.org.

We exchanged an email now and decided it would be good to have a skype. I proposed [Zurich 9pm next Monday](http://arewemeetingyet.com/Zurich/2018-09-17/21:00/binder%3C%3Ekaggle).

This is just the start of a conversation to get to know each other better, at least that is how I see it. It would be good to have at least one other person join (but maybe not everyone so we can keep it short?) so we have two brains and four ears.

**Comment by consideRatio** [comment]
I'd be happy to join, we have spoke during ICML and JupyterCon so she knows me already.

**Comment by choldgraf** [comment]
I'm traveling back to the States that day, so probably can't join in, but I trust y'all to represent Binder well :-)

**Comment by betatim** [comment]
Call went well. They will see what they can do in terms of telling GCP people that mybinder.org should remain on GCP and not move elsewhere. More details on Thursday's call.
