### ISSUE TITLE
Do we have capacity for Outreachy for the next cohort?

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#550]
### Context

As part of the Community Strategic Lead grant (#536), we have budget to hire Outreachy interns over a few cohorts as a way of setting up a mentorship program. The timeline for the upcoming Outreachy cohort is here (end of year internships): https://www.outreachy.org/communities/cfp/ If we were to participate in this upcoming cohort, we would need to have our mentored projects scoped and submitted by the **end of October**.

I have also been in talks with @yochannah about partnering with [Open Life Science](https://openlifesci.org/) to provide training for mentors. We would split the cost of three training slots (provided by [360 training](https://360training.co.uk/)) between us (exact splitting is up for negotiation) and any mentors from JupyterHub would be welcome to attend any of the slots, given maximum timezone flex. This training would happen in **late August or early September** (exact dates TBD). I highly recommend this training, I've been through it twice myself as an OLS mentor. Even if you are an experienced mentor, it is a great refresher course.

### Alternative

If we decide we don't have the capacity for this right now, that's fine! We can push instead for the mid-year internships and we still may be able to collaborate with OLS regarding mentor training depending on when the OLS-7 cohort kicks off.

### Questions that need answering

- [ ] Who has capacity to mentor an Outreachy intern this cohort?
- [ ] If we have capacity for this cohort, who of the mentors would like to participate in the training?

### Related

- https://github.com/jupyterhub/outreachy

**Comment by minrk** [comment]
I can be available, though I'd love to have a partner. We need to get to work on tasks, though. Both the mini tasks for the interview stage, and the larger mentor tasks.

**Comment by sgibson91** [comment]
Yes, I was thinking I'd take a mentee for this first round so I have some hands-on experience. But in future rounds I expect to be on the coordinating side of things

> I can be available, though I'd love to have a partner.

I would love for @GeorgianaElena to be involved with mentoring. 1) because I think she would be great, and 2) it's a great impact story when folks who were mentored by the community become mentors themselves. Maybe you two could mentor together? (Georgiana's on holiday right now so I expect she'll respond next week!)

> We need to get to work on tasks, though. Both the mini tasks for the interview stage, and the larger mentor tasks.

Yes, shall we have a call about this next week?

**Comment by damianavila** [comment]
> it's a great impact story when folks who were mentored by the community become mentors themselves

That would be an awesome story to tell everyone about, IMHO.

**Comment by sgibson91** [comment]
Thanks Chris! Some targeted ways to help me out would be to:

- Help identify and shape the mentored projects to go on the Outreachy site
- Help identify and shape some good first issues for the contribution period

I know we have the https://github.com/jupyterhub/outreachy repo, but I have no idea how up-to-date it is (I'm guessing, not at all). I'm also not sure if we have a 'laundry list' of things we'd like to do and if any of those would be good mentored projects?

**Comment by minrk** [comment]
I don't think we have a good list right now. I'm thinking something around accessibility and/or localization of JupyterHub pages would be a good project.

**Comment by sgibson91** [comment]
With these Outreachy rounds, I'd like to do cohort-based learning (bringing the interns together, talking to one another and learning together). We just just follow Yo's templates from when she did a similar thing at Intermine: http://intermine.org/internships/call-templates/ They are excellent and we can tweak as we need

**Comment by sgibson91** [comment]
@minrk @GeorgianaElena and I just had a planning meeting about this, the notes for which are here: https://hackmd.io/@sgibson91/HyaL9l6Ac

I will come back with more details/new issues when I have the time to write them up (somehow managed to fill my Friday with lots of chatting with different people! 🚀 )

**Comment by sgibson91** [comment]
I'm back with more info!

### Who will mentor?

Min, Georgiana and myself will mentor in this first round. We aim to have a small cohort for the first round (2, max. 3 interns) so that I have the time to be hands-on with the intern as well as trialling this cohort-based approach. We will scale up from the next cohort where I won't mentor and will instead take on an organising/coordinating role.

All three of us will also participate in the mentor training offered 

### Project ideas

We talked through a few potential projects, details of which are in the hackmd and I will synthesise elsewhere for posterity.
Projects we will flesh out are:

- Documentation refactoring, try to apply the diataxis framework to a repository (@sgibson91)
- Testing fixtures, provide infrastructure for various JupyterHub components to be able to test as if there was a running hub available (@minrk and @GeorgianaElena)
- Accessibility for JupyterHub pages, can hopefully connect with the Accessibility folks on this one (@minrk and @GeorgianaElena)

We will also link the documentation and testing projects together, e.g, we have a lot of docs on how to write a custom OAuthenticator but not many developer-focussed docs on how one works. To write and implement useful tests, you need both these parts 😉 

As we write up these project abstracts to submit to Outreachy, we will try to identify small, starter tasks that can function as the contribution issues. Ideally, they will be tasks that many people can do so we don't have to keep coming up with new ones as people claim them (e.g., "given this section of documentation, how would you place the sub-pages on the diataxis quadrant framework? please provide a sketch"), and if they are related to the main projects, even in a small way, this can help us judge which interns would fit well with which projects.

*N.B.:* It was noted that the 2i2c folk probably have a better overview of intern-friendly low hanging fruit (compared to tasks the JupyterHub team haven't got to yet because they're difficult) and I invite the 2i2c team to propose projects/be mentors when they have capacity to. We should be mindful to not create "2i2c cohorts" though.

### Strategy

We discussed a little bit about the tension between projects that are contained (maybe in a new or specific repo) and integration with the rest of the team or code that is touched more frequently. If our goal of participating in Outreachy is to develop a path into the community outside of the "burnt out PhD", then integration with the team and wider codebase is important to build confidence and a sense of belonging for the intern, i.e., that great quote "came for the language, stayed for the community".

While we don't want to necessarily block our community members from doing important maintenance/feature development work, coordinating with other people to land a PR that may affect other work is an important skill to build. This is one reason we thought a documentation project would be beneficial since it will touch a whole repo and cause interactions with others beyond the mentors, but probably not block someone doing technical work. It will also help us teach "atomic" PRs (making small changes, little and often).

### Action points

I will open new issues to track these (probably next week)

**All mentors:**

- [ ] Write up project proposals to submit to Outreachy
   - These can be in a collaborative docs for now. I will try and find a template for what uploading them to Outreachy will look like.
- [ ] Identify small tasks that can be issues during the contribution phase
   - Again, can be in a collaborative document for now and we can open the issues closer to the contribution period

**Sarah:**

- [ ] Register the community as participating on Outreachy
- [ ] Coordinate with Yo @ OLS regarding mentor training and @choldgraf regarding paying for it
- [ ] Prepare information for wider-community regarding what will happen during the contribution phase and what guidelines they should follow if they are interacting with an Outreachy issue (I will create labels to make this obvious)
- [ ] Disseminate above info in an issue and at September team meeting

**Comment by sgibson91** [comment]
Just an update for anyone who has heard me talk about "4 interns for 4 rounds": Chris and I just revisited the budget and it is 4 interns per year, over 2 years. Outreachy has two rounds per year, so this is actually two interns per round. Apologies for any confusion!

**Comment by sgibson91** [comment]
I have opened new issues for the tasks that were outlined [here](https://github.com/jupyterhub/team-compass/issues/550#issuecomment-1220923644) so I will close this issue now. Thanks everyone!
