### ISSUE TITLE
Request another year of credits with Google for gke.mybinder.org

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#555]
### Context

Our current credits with Google Cloud don't run out until May 2023, but I was told that Google makes decisions about credits on an annual cycle (Jan -> Dec), and it takes several months to go through the whole process.

So, I think that we should start the process of asking for more credits with Binder in the next few weeks.

Historically, this has looked something like the following:

- Send an email to folks at Google asking what the process is
- Put together a 1-2 pager that explains the impact of Binder. Usually pulling from our Matomo instance.
- Do a few rounds of emailing and some light paperwork
- Remember to ping folks after a few months in case they haven't responded.

### Is anybody willing to give this a try?

Historically I have done this, but I don't want to bottleneck myself on our connection to Google, and I also don't have a ton of time to do this. Maybe this time around, somebody can shadow me and we can write up the process that we follow so that others on the team can help in the future?

Who would be willing to help with this?

- Chris and Min are going to do this together.

### Checkpoints

- [x] **2022-11-07**: Sent an e-mail asking about potential for more credits
- [x] **2022-11-29**: Asked us to ping them again in January
- [ ] **2023-01-09**: Pinged them again to see if they have more budget clarity

**Comment by minrk** [comment]
I'd be happy to help this time around

**Comment by choldgraf** [comment]
I've just sent an email to Amanda and Mary @ Google restarting this process, and have also cc'ed Min.

Just a quick note, looking at our cloud credits we are almost directly on-track to spend all of the credits we've been given, which is great! We have about 50% of the time remaining to use the credits, and about 54% of the credits themselves remaining.

**Comment by minrk** [comment]
Thanks, Chris! It's about to get a lot less overwhelming for me now that the outreachy application period is done.

**Comment by choldgraf** [comment]
### Update: they asked us to ping them again in January

They mentioned that they're finalizing budget stuff for this year and will have a better idea of what their budget is in the next year. I'll plan to ping them again in early January.

**Comment by choldgraf** [comment]
I've pinged them again since they said they'd have more budget clarity by now, will let folks know what they say.

**Comment by minrk** [comment]
Yes, I can do that. I will also work on #512 to allow us to turn off the GKE cluster with minimal disruption if we need to.

**Comment by manics** [comment]
Thanks for trying!
