### ISSUE TITLE
Write up project proposals for Outreachy Dec 22 

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#556]
### Context

In https://github.com/jupyterhub/team-compass/issues/550#issuecomment-1220923644, Min, Georgiana and I decided to submit three mentored projects to the Dec 22 cohort of Outreachy. This is issue is to track the write up of those projects and submission to the Outreachy platform.

We agreed to flesh out the following three project ideas:

- Documentation refactoring, try to apply the [diataxis framework](https://diataxis.fr/) to a repository (Sarah)
- Testing fixtures, provide infrastructure for various JupyterHub components to be able to test as if there was a running hub available (Min and Georgiana)
- Accessibility for JupyterHub pages, can hopefully connect with the Accessibility folks on this one (Min and Georgiana)

### Action points

- [x] Write up the project proposals in any collaborative note-taking platform that suits you and share a link in this issue (Template here: https://hackmd.io/@sgibson91/outreachy-project-proposal-template)
  - While writing these proposals, please try to identify small, isolated tasks that could be a fit for the contribution phase. Ideally think of tasks that multiple people could work on at the same time. Note these somewhere in the document as it will help in setting up the contribution issues later.
- [x] Submit the projects to the Outreachy platform

**Comment by sgibson91** [comment]
I created a test project so that I could establish what information we would need to provide in this template: https://hackmd.io/@sgibson91/outreachy-project-proposal-template Please feel free to use it (or not) as you see fit.

I think we should separately enter our projects into the Outreachy platform as that will be the easiest way to register us as mentors. Once the project has been submitted, we can then add a co-mentor (e.g. Georgiana, or Georgiana adds Min).

I don't expect you to share everything openly, e.g., the section 2 mentor profile doesn't need to be radically open I don't think.

We should also provide the same answers to some of the questions, e.g., the section 4 project communications channels should be consistent between the projects. I also think we should add a note to the long description of the project about our cohort-based plans and how we expect the interns to work together as well as with the broader team, so there aren't any surprises.

**Comment by GeorgianaElena** [comment]
Thanks for creating the template @sgibson91 ✨! I've copied it into [new separate hackmd](https://hackmd.io/qcUPJWvWRYCz_d10p6dHsA?view) and tried to sketch out a first iteration for the project description for the pytest plugin project and also proposed a couple of possible titles for it.

I will continue to work on that in the following days, but any early feedback is very appreciated <3

**Comment by minrk** [comment]
@GeorgianaElena I don't think I can see your HackMD. Maybe check the permissions?

**Comment by GeorgianaElena** [comment]
Permissions weren't right indeed. Try again?

**Comment by sgibson91** [comment]
Georgiana, it works for me now!

I just want to clarify that I got my maths a little bit wrong, we have money for 4 interns _per year_ for 2 years, so that's _2 interns per Outreachy round_. Yo also confirmed for me that it's very normal to advertise more projects than you have intern spaces (e.g. 3 project, but 2 spots) and then decide which two projects will happen when reviewing applications.

**Comment by sgibson91** [comment]
Hey @minrk @GeorgianaElena! I propose we have a quick meeting about the project proposals towards the end of next week. This is because I will be in San Francisco during the week of the submission deadline and I want you both to feel empowered to submit without sign-off from me if I'm not reachable for any questions, etc. I think it would also be good to:

1. Unify on the "contact" style information we will provide in each proposal, and;
2. Strategise on where to open the contribution issues, e.g., outreachy repo, across multiple repos? I'll then create labels to tag the issues with in the decided upon repo(s) and we can include that link in the project proposal too.

Roughly, when would be good for you both?

**Comment by minrk** [comment]
Sounds like a great plan!

Can we do Wednesday? I have an event all of Thursday and Friday. I don't have anything on the day, so free any time 9-15.30 CEST (same on Tuesday)

**Comment by sgibson91** [comment]
Calendar invite sent out for [2022-09-14 13:00 BST](https://arewemeetingyet.com/London/2022-09-14/13:00)

**Comment by minrk** [comment]
Realized I never shared my link: https://hackmd.io/RefMPNM_Qomb5S8rCh2esw

**Comment by sgibson91** [comment]
I have submitted the documentation and invited you both to co-mentor :)

**Comment by GeorgianaElena** [comment]
I have also just submitted the project proposal and invited both of you as mentors 🚀

**Comment by minrk** [comment]
Mine is submitted as well, with invitations to both of you. Task closed, on to preparing for the application period?

**Comment by GeorgianaElena** [comment]
Yay! yes, let's close it as completed 🚀
