### ISSUE TITLE
Write-up and disseminate information/guidelines on Outreachy contribution period to wider JupyterHub community

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#557]
### Context

Outreachy has a "contribution period" where applicants work on some small tasks in order to learn more about the community and decide whether to apply for one of our projects, and to demonstrate interest/competency related to the project. This will result in a lot of activity across the JupyterHub org and so we should provide information/guidelines to the broader community. This should include:

- a reminder to be their wonderful, welcoming selves
- a link to the projects and issues so they can familiarise themselves with the content
- information on who the mentors and organiser are in order to raise issues/signal boost/hand over responsibilities if needed

### Action points

- [x] Write a short blurb on what to expect and what to do during this period: https://hackmd.io/@sgibson91/r1rR3vmxj
- [x] Disseminate info in a new issue and at the September team meeting

**Comment by sgibson91** [comment]
Related info: https://www.outreachy.org/docs/community/#avoiding-mentor-burnout-during-contribution-period

**Comment by sgibson91** [comment]
@GeorgianaElena @minrk what do you think? ☝🏻

**Comment by minrk** [comment]
Looks great!

**Comment by sgibson91** [comment]
Created a new issue with the text from the HackMD and added it to the Quick Updates section of Tuesday's meeting!
