### ISSUE TITLE
JupyterHub and Jupyter got into the open-source program for dockerhub!

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#559]
@mathbunnyru advocated for a submission into DockerHub's _Open Source program_. An application [was submitted]( https://github.com/jupyter/docker-stacks/issues/1650#issuecomment-1173072582) and has now been accepted!

I received this email:

>Congratulations! The Jupyter and Jupyterhub projects have been approved for the Docker-Sponsored Open Source program. A Docker Team subscription will be allocated to your Docker Hub organization within 14 days. In addition to a Team subscription, you now have:
>
>- free autobuilds
>- rate-limit removal for all users pulling public images from your project namespace
>- special badging on Docker Hub (this will be visible within two weeks)
>
>If you haven’t already, please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub.
>
>Membership in the Docker-Sponsored Open Source (DSOS) program is valid for one year. You will receive a reminder email from us when it is time to renew your membership.
>
>We are thrilled to have you as an open-source partner. If you have any questions regarding the open source program please contact [opensource@docker.com](mailto:opensource@docker.com) and include the name of your project in the subject line. If you have questions regarding technical support please contact [support@docker.com](mailto:support@docker.com).
>
>Thank you!

**Comment by mathbunnyru** [comment]
Great news, Erik, thank you!

When (and if) it becomes possible, please add me to the DockerHub team as well :)
https://github.com/jupyter/docker-stacks/issues/1309

**Comment by choldgraf** [comment]
hooray! thanks @mathbunnyru for making an application for the team!

**Comment by consideRatio** [comment]
The application was easy to write, but to even find the form to apply etc we had to speak with dockerhub - the button to apply was missing from the website ;D Thank you @mathbunnyru for making this happen!

### Adding Ayaz to hub.docker.com's Jupyter organization

> When (and if) it becomes possible, please add me to the DockerHub team as well :)

So far I can't invite members to the JupyterHub organization where I have _owner_ permissions, but I assume we are enabled doing that soon.

![image](https://user-images.githubusercontent.com/3837114/187426319-59af6683-d7b7-487f-a1f0-39184b8295ae.png)

When such permissions is granted for the jupyter and jupyterhub organization I hope we can add members. @minrk are you an owner in the [jupyter organization on hub.docker.com](https://hub.docker.com/orgs/jupyter/members)?

### Adding image repository descriptions

As described in the email, they want us to add descriptions to the image repositories linking out to the source code etc. That makes perfect sense to me and I'm happy to work on getting that done.

But I'd like to clear out a few image repositories that I don't think are used any more.

@jupyterhub/jupyterhubteam do you agree its okay to delete the image repositories aged more than 4+ years old as seen in the screenshots below?

JupyterHub organization on hub.docker.com:
![image](https://user-images.githubusercontent.com/3837114/187425987-df1b531c-22b3-42bc-a269-657ab4218ffa.png)

Jupyter organization on hub.docker.com:
![image](https://user-images.githubusercontent.com/3837114/187427747-be26d993-15da-4f38-866b-c809a48ca883.png)

**Comment by mathbunnyru** [comment]
Everything seems to work 👍 

![Снимок экрана 2022-09-01 в 09 38 12](https://user-images.githubusercontent.com/12270691/187839540-43a7c46c-2922-4977-98de-8c52d4f3b44d.png)
![Снимок экрана 2022-09-01 в 09 38 20](https://user-images.githubusercontent.com/12270691/187839545-f63c680d-4650-4640-85a3-0a1ccfce5246.png)

**Comment by manics** [comment]
Can you get any stats on when images were last pulled? e.g. for the images with 100K+ pulls, how many pulls were in the past year?

**Comment by consideRatio** [comment]
Yepp, for the jupyterhub organization's images I can see that because I'm an admin there, but not in the jupyter part.

A|B
-|-
![image](https://user-images.githubusercontent.com/3837114/191323767-2dbb0860-9ccb-4c23-96b1-0eae3ee0ce3d.png)|![image](https://user-images.githubusercontent.com/3837114/191323960-ce8d02e1-cb92-4ed7-8c94-94ec13ef2432.png)
![image](https://user-images.githubusercontent.com/3837114/191324016-5d43fcd7-43f1-4d49-9be4-9933ab5c559b.png)|![image](https://user-images.githubusercontent.com/3837114/191324073-a06cc41a-ba53-4b03-975c-39c63ee458cc.png)
![image](https://user-images.githubusercontent.com/3837114/191324234-cd02a570-3ebc-4fd5-9753-6e79ffec1dfc.png)|![image](https://user-images.githubusercontent.com/3837114/191324277-dd09ffd8-58c8-4a0d-93f1-4d2aaa8a01c8.png)

**Comment by manics** [comment]
Can you get pulls/month? If an image is pulled once a month by some automated external security scanning company we don't care, but if it's 100/week we should probably keep them.

**Comment by manics** [comment]
How about a cutoff of 1000 total pulls? Delete if there are fewer, document if there are more?

**Comment by minrk** [comment]
- All the `k8s-` images are built from zero-to-jupyterhub, and no longer built because they've been removed from the chart.
  - [k8s-pod-culler](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/0.7.0/images/pod-culler)
  - [k8s-pre-puller](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/v0.6/images/pre-puller)
  - k8s-image-puller - I can't find this one! It's not [where it should be](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/2b02899/images/), and only has one hash pushed and no tags. Safe to delete.
  - k8s-rateproxy is actually the [nginx image](https://hub.docker.com/layers/jupyterhub/k8s-rateproxy/v0.5a/images/sha256-596cc3687363a8d846d82a0f743a07fafa0e49935055b319859bdc96ee575668?context=explore)! It's not used in any version of the chart and can be removed.

- systemuser was built from [dockerspawner](https://github.com/jupyterhub/dockerspawner/tree/0.8.0/systemuser). SystemUserSpawner used to rely on some bootstrapping steps in the image itself, but that requirement was removed, so it can work with any image.

**Comment by minrk** [comment]
tljh-circleci-base-image was used in tljh CI, but not anymore. That's clearly for internal use only, and safe to remove since we aren't using it.

**Comment by minrk** [comment]
Is there a benefit to deleting it? I don't really understand proactively deleting published artifacts from the internet.

**Comment by minrk** [comment]
To be clear - I think we should leave it alone because it was part of a [published release](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/v0.6/images/pre-puller), and already has a readme, Dockerfile, etc. If it were only an interim image, deleting makes sense to me.

**Comment by consideRatio** [comment]
Since its part of a published release, let's retain it. I can document whats needed in the jupyterhub org on dockerhub now given your findings!

I find cleaning up unused things etc is relevant overall though. An accumulation of historic parts can be problematic, but not always. For example when its clear something is outdated its far better when its not clear. It can be quite clear that code only found in git history or a pypi release superseeded by a newer version is outdated, but its less clear if we have stopped pushing new versions of a docker image in favor of another name or similar.

I remember how finding the tljh-circleci image made me think tljh was tested like that still even though it wasn't - and that made me onboard myself to tljh's CI system a bit slower. Not a big deal, but I really appreciate complexity reduction whenever possible for reasons like that.

**Comment by minrk** [comment]
Thanks, I appreciate that perspective and all your efforts on reducing complexity and helping people contribute!

**Comment by consideRatio** [comment]
I see that we have now got 10 members in the jupyterhub organization on hub.docker.com, maybe also for the jupyter organization then?

**Comment by consideRatio** [comment]
> @minrk are you an owner in the [jupyter organization on hub.docker.com](https://hub.docker.com/orgs/jupyter/members)?

If so, could you confirm if we got 10 members allowed in the jupyter dockerhub organization at this point? I think we have! I'd like to help get @mathbunnyru access to help with jupyter/docker-stacks maintenance, for example to define the new proposed image repository in https://github.com/jupyter/docker-stacks/issues/1809.

**Comment by parente** [comment]
@mathbunnyru Is your Docker ID the same as your GitHub ID? If so, I can invite you.

**Comment by mathbunnyru** [comment]
> @mathbunnyru Is your Docker ID the same as your GitHub ID? If so, I can invite you.

@parente yes! 👍

**Comment by parente** [comment]
@mathbunnyru Invite sent.

**Comment by mathbunnyru** [comment]
I accepted the invite, thank you! I guess you should also add me to the `owner` team, so I can create repositories.

<img width="1470" alt="Screenshot 2022-11-05 at 23 10 35" src="https://user-images.githubusercontent.com/12270691/200137019-1df85aed-b3c0-44bc-a178-6d608a9ac2cf.png">

**Comment by mathbunnyru** [comment]
@parente could you take a look, please?

**Comment by mathbunnyru** [comment]
@minrk @parente @rgbkrk could you please add me to the `owner` team?

**Comment by minrk** [comment]
@mathbunnyru added!

**Comment by consideRatio** [comment]
I'll go for a close on this issue, its too large and we have resolved a lot of things already! Thanks everyone!!!

**Comment by mathbunnyru** [comment]
Thank you everyone for your help! I hope I will be able to help the community even better now.

**Comment by minrk** [comment]
Thanks @mathbunnyru for your extraordinary patience through this process!
