### ISSUE TITLE
Do we control the jupyterhub npm organization?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#562]
A user in control of the npm orgnization should be able to visit https://www.npmjs.com/settings/jupyterhub/packages.

I'm asking because jupyter-server-proxy is part of the jupyterlab organization now and it was considered if we could relocate it. If we do, it should be under @jupyterhub I figure.

See https://github.com/jupyterhub/jupyter-server-proxy/pull/323#issuecomment-1166275368:

> This repo has a npm package in the jupyterlab org, but we dont need it for
>
> > jupyterlab 3+ so should we reference it here now?
>
> Yes, by convention it should keep publishing under an npm name, ideally the
same one. What org it is under isn't very important, but having it be
_something_ consistent is important for downstream packages.

**Comment by manics** [comment]
Isn't it a JupyterLab specific extension/package though? IIUC it's not _needed_ because the files in the npm package are included in the pip installable package. Or are there other files that are useful outside JupyterLab?

**Comment by consideRatio** [comment]
Hmm but anyone can argue that its a jupyterlab specific package - its for that software, but we are the publishers and not the jupyterlab team.

We should focus such discussions towards the linked issue, but independently on that - do we even have an option to use @jupyterhub in npm? I'm not in control of that organization at least.

**Comment by minrk** [comment]
I don't have access to [the org](https://www.npmjs.com/org/jupyterhub). It has no packages. There's a [form](https://support.github.com/contact/npm-name-disputes) for trying to claim org names. I can submit that if nobody knows who owns the name.

**Comment by consideRatio** [comment]
Wieee i think that would be good to do!

**Comment by consideRatio** [comment]
@minrk have you received a response?

**Comment by minrk** [comment]
Nope, no response. Ticket still open.

**Comment by yuvipanda** [comment]
turns out I'm an owner! I've invited @minrk and @consideRatio. I've no idea how that happened.

**Comment by choldgraf** [comment]
LOL
