### ISSUE TITLE
Have a post-mortem on the contribution period

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#574]
Once the Contribution Period is over, we should have a retrospective/post-mortem to assess what strategies worked well, what didn't, and what alternatives to try in the next round.

We should document methods of tracking contributions in the Outreachy documentation thread:

* https://github.com/jupyterhub/outreachy/issues/45

**Comment by sgibson91** [comment]
I'm going to propose we schedule this meeting for the w/c 14th Nov. I want us all to have a couple of days where we don't have to think about Outreachy, but not leave it so long we forget details!

**Comment by sgibson91** [comment]
I created a when2meet for this here: https://www.when2meet.com/?17653110-Q6Ipi

**Comment by sgibson91** [comment]
Between a hub outage yesterday, and writing a keynote I am giving on Monday, I forgot to schedule this meeting! Will do it now

**Comment by GeorgianaElena** [comment]
@sgibson91, no, there's no need to. I will be away in the afternoon, starting 3~4 P.M. my time.
The meeting is scheduled for 12-1PM, so I should be able to participate. Thanks for offering to reschedule and sorry for not filling in my availability in when2meet (I totally forgot to do it :( )

**Comment by sgibson91** [comment]
That's great to know, thanks!

**Comment by sgibson91** [comment]
This has happened! The notes are in https://hackmd.io/@sgibson91/S1RyCF5ro And they will be written up and added to https://jupyterhub-outreachy.readthedocs.io/en/latest/
