### ISSUE TITLE
Hubs Team Meeting - January 2023

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#582]
Hello everyone! And Happy New Year from the past!

Reminder that our next meeting is **Tuesday, 17th January, 2022 at 6PM Europe/London** (or [your timezone](https://arewemeetingyet.com/London/2023-01-17/18:00/Hubs-Team-Meeting)).

Agenda - HackMD: https://hackmd.io/@sgibson91/hubs-team-meeting
Video - Jitsi: https://meet.jit.si/HubsTeamMeeting

- 💁🏻‍♀️ anyone can attend
- 🧑🏼‍💻 anyone can present - add yourself to the HackMD above!
- 👀 anyone can sit in on the call

**Comment by alwasega** [comment]
Thanks, @sgibson91. Booked the date!

**Comment by sgibson91** [comment]
A reminder for folks that this meeting is tomorrow :)
