### ISSUE TITLE
Jupyter Community Call - November 2022

### ISSUE THREAD

**Issue by isabela-pf** [jupyterhub/team-compass#583]
The next Jupyter community call will be November 29, 2022 at 7am Pacific ([in your timezone](https://arewemeetingyet.com/Los%20Angeles/2022-11-29/07:00/Jupyter%20Community%20Call)). Bring your favorite agenda items or come prepared to cheer on the presenters!

- If you’d like to share, you can sign up by adding yourself to [the agenda ](https://hackmd.io/@isabela-pf/HyVaWtkWs)before the call begins.
- To attend, you can [join on Zoom ](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)at the time of the call.

Please don't hesitate to ask questions here or on the [Jupyter Discourse topic](https://discourse.jupyter.org/t/jupyter-community-calls/668). Hope to see you in two weeks!

**Comment by isabela-pf** [comment]
Thanks for attending! You can find the [YouTube recording](https://youtu.be/GsOjIvV7ymY) and [Meeting notes](https://github.com/jupyter/jupyter/issues/670) if you'd like to catch up on what happened. 🌻

**Comment by choldgraf** [comment]
Thanks for keeping the jupyterhub team in the loop @isabela-pf !
