### ISSUE TITLE
Blog outputs from Round 1 of the CZI CSL-funded Outreachy rounds

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#586]
This is an issue to track some blog outputs that would be nice to have from the first round of Outreachy funded by #536 

- [x] Introduce the new interns and their projects!
  - https://github.com/jupyterhub/outreachy/issues/138#issuecomment-1326131713
- [x] @GeorgianaElena's journey from Outreachy intern to mentor https://medium.com/p/6055df406999
- [ ] What the did the JupyterHub team learn from this round?
  - Introduce our processes in https://jupyterhub-outreachy.readthedocs.io/, invite feedback and participation in future rounds (as mentors)

**Comment by sgibson91** [comment]
I am drafting blog number 1 here: https://hackmd.io/@sgibson91/SJRB_uR8o

On Monday, I will send round an introductory email to the three interns and ask them for a few sentences about themselves to include in the blog post.

If you are interested, you can see a template of the email I will send here: https://github.com/jupyterhub/outreachy/pull/145

**Comment by sgibson91** [comment]
I have a draft blog post announcing the interns here: https://blog.jupyter.org/introducing-jupyterhubs-outreachy-interns-december-2022-cohort-23aaf4613556

cc @minrk and @GeorgianaElena as co-mentors
cc @choldgraf as a blog person
cc @trallard RE: the connection to the accessibility team

**Comment by minrk** [comment]
I've looked over the blog and it looks great!

**Comment by sgibson91** [comment]
Thanks Min! I submitted it but don't think I have to power to fully publish.

**Comment by minrk** [comment]
I tried to add you as an editor so you can hit publish yourself, but I don't seem to be able to.

**Comment by sgibson91** [comment]
Sorry, I was out of office today. I am happy for anyone who has the power to hit publish :)

**Comment by minrk** [comment]
Published!

**Comment by GeorgianaElena** [comment]
I have a draft of the intern->mentor post available at https://medium.com/@georgiana.dolocan/6055df406999. Feedback is very much appreciated.
I plan to submit it as a draft to the Jupyter Blog on Monday.

**Comment by trallard** [comment]
I did a quick read, and it is excellent @GeorgianaElena  - I love the full circle approach to the whole blogpost and the honesty/openness about how mentoring others is also a continuous learning and iterative process 💜

**Comment by GeorgianaElena** [comment]
Thank you very much @trallard ❤️

I've submitted the post to the Jupyter Blog publication today, but I don't think I can publish it myself.

**Comment by minrk** [comment]
I can hit publish if you say it's ready. Looks great to me!

**Comment by minrk** [comment]
Published!

**Comment by sgibson91** [comment]
I don't have the capacity for my blog post, but I think the talk at JupyterCon captured a lot of learning and can be viewed here: https://www.youtube.com/watch?v=vMm5rkiMbGU
