### ISSUE TITLE
October team meeting

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#60]
We should schedule the next team meeting with a bit more notice so that people have a chance to attend.

I propose 18 October 2018 at 6pm Zurich ([your timezone](http://arewemeetingyet.com/Zurich/2018-10-18/18:00/Binder%20team)).

https://calpoly.zoom.us/my/jupyter zoom link for video conferencing

Agenda: https://hackmd.io/GO0wG17yQz-iRqslH8K5Xg?edit

**Comment by jzf2101** [comment]
I may be giving a talk at that time- let me confirm that I can attend.

**Comment by consideRatio** [comment]
I'm occupied from early morning to late night the 18th of October =/

**Comment by choldgraf** [comment]
The team report is up on the archive, so I'll close this! https://jupyterhub-team-compass.readthedocs.io/en/latest/monthly-meeting/2018-10-18.html
