### ISSUE TITLE
Create a `jupyterhub-python-repo` GitHub template repository

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/team-compass#601]
### Proposed change

In the context of https://github.com/jupyterhub/team-compass/issues/590 and https://github.com/jupyterhub/team-compass/issues/588,
I believe another thing that would be beneficial apart from only documenting the standards we are (sometimes only inplicitly) following across jupyterhub repositories,
is to have a template repository as the source of truth of the current "shape" we want **new** repositories to have.

This repo could hold configs about:
- ci/cd
- docs
- packaging
- etc

### Alternative options

Right now, when we're creating new repositories, there's a lot of copy-pasting involved from other repositories.

But copying config files from other repos is not sustainable and it's hard to know which of the repositories is "the most up to date" with current standards.
Some of them are up-to-date on the packaging side, some on the ci/cd workflows it is using and some on the docs side.

### Who would use this feature?

One use-case I thought of and the one that actually sparked this idea is this Outreachy internship round.
When I thought about how to best guide a new contributor through the process of creating a new Python repository inside the JupyterHub GitHub organization, I realized that I don't have a clear answer and there's a lot of confusion around which are the most up to date practices we're using.

### (Optional): Suggest a solution

I've actually started this work by creating a repository inside my account that I'm happy to move to the `jupyterhub` org for polishing it further with all of your help if you consider this proposal to be valuable.

The repo it's lacking a lot of stuff, especially docs, but I believe it helps make this case 

https://github.com/GeorgianaElena/jupyterhub-python-repo-template

**Comment by consideRatio** [comment]
Ohhh I greatly appreciate this idea, I'm leaning very positive towards it right away!!

## Narrowing scope

I'd like to see us try to specify the scope of whats done in the repo as tightly as we can at this point. For example, one may want to put things in the docs of actual relevance, but then we start to enter undefined realms of what should go where. I'd suggest we draw a clear line and declare that we should keep it the scope simple and just provide demonstrative examples of technical stuff like sphinx/myst in the project's docs.

I think a good starting point to clarify the scope of this repository is that nothing in the repo should be by itself useful for something, but solely exist to provide solid and highly reduced examples to capture good practices for a project's repository content.

Another scope limitation could be to narrow it to be python specific - as already suggested by Georgiana. But then what about helm charts, nodejs applications, github actions, etc? I suggest the README.md suggests other repositories to look at for a good reference for such kinds of projects. helm chart project could be zero-to-jupyterhub-k8s, nodejs project could be configurable-http-proxy, github actions project could be actions-k3s-helm for a composite bash action etc.

Another scope limitation would be to declare that it should not transform into a cookiecutter project or similar, in my mind it should be a repo directly comparable to real use repositories - allowing you to copy paste pieces from its directory structure directly and not understand how a cookiecutter template project works first etc.

**Comment by minrk** [comment]
I agree, a simple Python template repo seems super useful. We don't need to go too far, but there are lots of files to start with. Does it make sense to add skeleton release and test workflow files, too?

If it's not a cookie cutter, we should make it super easy to find the fields that _need_ to be replaced (package name, repo, etc.). A simple string like TODO ought to be enough.

**Comment by GeorgianaElena** [comment]
Thanks all for the feedback and for endorsing the overall idea. I just moved the repository I was sketching this in, under the `jupyterhub` organization for better visibility.  It stills needs a looot of polishing however, especially around the documentation side and how to build easy to follow instructions

**Comment by GeorgianaElena** [comment]
https://github.com/jupyterhub/jupyterhub-python-repo-template now exists, so I believe this issue can be closed.
Thank you all!
