### ISSUE TITLE
Share JupyterHub Demo video

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#603]
### Context

Yesterday, Min, Georgiana and myself held a demo session for the Outreachy interns where Min described the architecture of JupyterHub, it's main job, the layout of the repository, and how to get setup for development in terms of installation, testing, documentation, etc. I recorded the demo and would like to share this video on the [Jupyter YouTube channel](https://www.youtube.com/@ipython) if possible, because it was really useful (even to me who has been in the project a few years now!)

### Actions

- [x] @minrk do you consent to me making the recording public? (I'll edit around the parts where the interns spoke about their OS)
- [ ] Can someone help me get the video onto the channel? @isabela-pf, I know you upload the community calls there, could you help me with access please?

**Comment by minrk** [comment]
Yes, absolutely!

**Comment by consideRatio** [comment]
Super!!! I love these kinds of overviews, its quite a big deal for any open source project i think. Having seen something like it is like getting the borders in a puzzle, it makes putting down further pieces quite a bit easier.

**Comment by choldgraf** [comment]
I think this is a great idea!

**Comment by sgibson91** [comment]
@isabela-pf can you help me out with access to the YouTube channel please?

**Comment by isabela-pf** [comment]
Yes! Thanks for the re-@; this got lost in my inbox!

Would you prefer to
- a) Be added to the youtube account
- b) Have me upload the video myself

Either works for me, I just need to know for which next step to take.

**Comment by sgibson91** [comment]
Shall we go with option (a) so I don't have to keep bothering you? I promise to use the power wisely :) I 
believe I can be added via my Gmail account drsarahlgibson@gmail.com. Thank you!

**Comment by sgibson91** [comment]
Demo is published! https://youtu.be/IhMHMuwphc0

**Comment by alwasega** [comment]
> Demo is published! https://youtu.be/IhMHMuwphc0

Thank you!
