### ISSUE TITLE
pre-commit update monthly?

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#604]
I just [learned](https://pre-commit.ci/#configuration-autoupdate_schedule) you can add

```yaml
ci:
  autoupdate_schedule: monthly
```

to pre-commit-config.yaml to slow down the autoupdate PRs to monthly instead of weekly. I don't love spending a big fraction of  every Monday/Tuesday merging inconsequential PRs.

Any objection to doing this? I don't see much value in these autoupdate PRs being a constant flood, and they do cost a nontrivial amount when they are across all our repos.

**Comment by choldgraf** [comment]
I think it's a great idea 👍

**Comment by consideRatio** [comment]
Big thumbs up!

**Comment by consideRatio** [comment]
I like if they cause lett clutter in lists of opened PRs as well

**Comment by mathbunnyru** [comment]
Definitely 👍 from me, having to do this once a month seems reasonable.

**Comment by consideRatio** [comment]
As part of getting the weekly flood of pre-commit.ci update PRs, I added a commit to them before merging. See for example https://github.com/jupyterhub/mybinder.org-deploy/pull/2466/commits/ccfc68759cd370560eba77c0f8c88d5d50fd8006.

In practice, the following was appended to .pre-commit-config.yaml files. Note that the configuration reference for .pre-commit-config.yaml does not include the `ci` section, so another note about a configuration reference for that was added.

```yaml

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
```
