### ISSUE TITLE
Decide on "regular" team meetings

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#61]
What do folks say to us just deciding on a "regular" team meeting time (say, the 3rd Thursday of every month at 9AM PST). That way it will be easier for others in the community to plan ahead, and there will be less variability in deciding if/when to hold meetings.

**Comment by minrk** [comment]
I think that's a good plan. With conferences/travel/holidays we might move them once in a while, but starting with that as "assumed, unless it doesn't work for some reason" makes sense to me. With that in mind, having that "does the usual time work?" decision immediately after the previous meeting probably makes sense.

BTW, that would make the next three:

18. October (already proposed in #60)
15. November
20. December

**Comment by betatim** [comment]
I added this issue to the agenda for #60.

---

Close this after we update it with feedback from #60.

**Comment by choldgraf** [comment]
sounds good! let's discuss @ the next community meeting :-)

**Comment by jzf2101** [comment]
@Zsailer will you come? We'd like to include you if possible

**Comment by choldgraf** [comment]
As this is now codified in the [team compass website](https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings.html), I'll close this!

**Comment by consideRatio** [comment]
Haha im smiling very wide on a train now :D - jhubctl, pronounced 'hub-cuddle'

Things are out of controleleven

**Comment by consideRatio** [comment]
(i read about the WIP cli for jhub in meeting logs of october, and eleven is 11, and 11 is !!)

**Comment by choldgraf** [comment]
Haha thank you for the translationeleven

**Comment by minrk** [comment]
The above list got misformatted by markdown as an ordered list, when it was actually 3 dates. The third Thursday of November is the 15th (today!).

I'll be around if folks want to meet (agenda [here](https://hackmd.io/gu0YVVrXR3WG0fJOgyBNLg)), or we can try again in two weeks (29. Nov), or hold until December.

**Comment by choldgraf** [comment]
ahhh I totally mistook that for the 18th even though that is obviously not a Thursday :-(

I could meet briefly now, though if the goal is for us to be inclusive, I'm worried that this won't be a very inclusive meeting (even to others in the team). WDYT?

**Comment by minrk** [comment]
I'm okay either way. It's a miscommunication, though folks have shown up.

**Comment by jzf2101** [comment]
Oh wait are we talking now?!

**Comment by choldgraf** [comment]
ok, I will jump on the call...
