### ISSUE TITLE
Blog post announcing daily, weekly & monthly active user counting in JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/team-compass#622]
Heya! I've written up a very quick blog post announcing the daily, weekly and monthly active user counting feature of JupyterHub 3.1. The draft is here: https://hackmd.io/hpKlQHnYSICaZmvy-E2vOg

I think this will be well liked and very well used, and hence deserves wider announcement than just the release notes.

If this draft looks ok, I'll post it to the medium interface and work on getting it published.

Thanks

**Comment by minrk** [comment]
Awesome! Made some tiny tweaks and put in a couple of questions that might be worth answering.

**Comment by choldgraf** [comment]
This inspired me to add a little blog post list to our jupyterhub home page :-)

- https://github.com/jupyterhub/jupyterhub.github.io/pull/1

**Comment by yuvipanda** [comment]
Ok, it's a draft here: https://blog.jupyter.org/accurately-counting-daily-weekly-monthly-active-users-on-jupyterhub-6fbec6c6ce2f.

I've also added a sentence addressing @minrk's comments about this not being useful for binderhub.

Anyone wanna hit publish? :)

**Comment by yuvipanda** [comment]
yay, thank you @minrk!
