### ISSUE TITLE
Jupyter Community Call - February 2023

### ISSUE THREAD

**Issue by marthacryan** [jupyterhub/team-compass#627]
Join us on February 28, 2023 at 8am Pacific ([in your timezone](https://arewemeetingyet.com/Los%20Angeles/2023-02-28/8:00/Jupyter%20Community%20Call)) to celebrate another year gone by and a new one to come.

If you’d like to share, you can sign up by adding yourself to [the agenda ](https://hackmd.io/@isabela-pf/r1S83fv3j)before the call begins.
To attend, you can [join on Zoom ](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09)at the time of the call.
Happy new year! Let me know if you have any questions.

**Comment by yuvipanda** [comment]
Going to close this one as completed.
