### ISSUE TITLE
Blog post announcing/explaining new Collab Café format

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#628]
ref #617 

I have drafted a blog post announcing the change in format of the team meeting to a collaboration cafe and trying to explain a little bit what to expect. I'd like to publish it before the next meeting happens.

https://hackmd.io/@sgibson91/S1MJUGf0i

Are there any questions left unanswered that should be included in this post?

**Comment by minrk** [comment]
That looks very nice, and answers my questions, thank you!

**Comment by sgibson91** [comment]
Thanks! I submitted it to medium. Draft is here: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15 I had to change some of the formatting because apparently tables and nested bullets aren't available in medium 🤯

**Comment by minrk** [comment]
LGTM, ok with you to publish?

**Comment by sgibson91** [comment]
Yes, let's go!

**Comment by minrk** [comment]
[published!](https://blog.jupyter.org/online-collaboration-café-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15)
