### ISSUE TITLE
Blog post announcing mybinder.org updates

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#632]
We have some major updates coming to mybinder.org, waiting to deploy in https://github.com/jupyterhub/mybinder.org-deploy/pull/2517

In https://github.com/jupyterhub/binderhub/pull/1635, it was suggested that we should announce the changes with a blog post, which I drafted and linked from the Issue, but today realized I should have started with an Issue here for review of the post to make sure folks have a chance to look it over. It's probably more of a wall of text than it should be, but it's what I could come up with.

@manics has already given it a review and I've applied his suggestions.

[Draft for review](https://blog.jupyter.org/updating-defaults-on-mybinder-org-4df41d601955)

**Comment by sgibson91** [comment]
LGTM! 👍🏻

**Comment by minrk** [comment]
Thanks! published.
