### ISSUE TITLE
Write a blog post about an expected drop in mybinder.org capacity

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#643]
Our credits on the GKE deployment of mybinder.org are going to run out in April, and Google has decided not to renew them. We need to write a blog post that lets the community know what to expect. I think these are the main points:

- Our funds on `gke.mybinder.org`, by far the biggest part of the federation, will run out in April. Google has decided not to provide more credits.
- We will re-distribute traffic to the `ovh` federation member. We may also deploy an `aws` federation member.
- Service reductions to expect
    - This may come with changes in performance level (e.g. https://github.com/jupyterhub/mybinder.org-deploy/issues/2514 and the fact that we haven't deployed on AWS much)
	- We will also intend on reducing the total capacity of Binder by **XX%** so you may get rate limit warnings.
	- We will start more aggressively deleting older built images because Google's cloud storage became more expensive in 2022.
- We are searching for funds to continue funding a Google Cloud version of Binder (or an AWS version), if you have any support to offer please reach out to **contact here**

**Comment by minrk** [comment]
I started drafting here: https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f Probably good to post today, if we can

**Comment by minrk** [comment]
Published, thanks!
