### ISSUE TITLE
Emeritus'ing myself

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#645]
I'd like to move myself to emeritus status (even though I am not yet a 70 year old professor).

I haven't been very active for some time, so I think it is worth making it official/doing the admin 😀

The project has been expertly managed and pushed forward by all those of you who are active. It is super cool to watch and see where the project goes next. I hardly manage to keep up with watching from the outside, so I think it is time to retire. Over time other hobbies and tasks have taken over my life. There is no big bang/moment in time or even real reason. Maybe that is how life works. No drama, just subtle change over time.

The whole idea of (in particular) mybinder.org is so outrageous that even after all these years and all the hard evidence of it being possible, I mostly can't believe it actually works 😀. This is due to the many people who've gone beyond what many think is a reasonable amount of effort to help make it happen. Thank you.

I read somewhere that one of the techniques for magic tricks is to go far beyond what people think is reasonable in terms of effort ("No way did they memorise the whole phone book!"). If this means all this is a magic trick, it is one of the best ones I've ever seen!

ps. I don't really know what edit to make to https://github.com/jupyterhub/team-compass/blob/main/docs/_data/contributors/contributors-jupyterhub.yaml - remove the team?

**Comment by minrk** [comment]
Thanks for all your contributions, @betatim!

**Comment by sgibson91** [comment]
Thank you for all your work Tim, and especially for being one of my first points of contact in Binder land :)

**Comment by consideRatio** [comment]
Thank you for all your contributions Tim and for helping me onboard into the world of open-source and Python, you have impacted my life very positively!! :heart:

**Comment by GeorgianaElena** [comment]
Thank you for all your guidance and work Tim 🧡
