### ISSUE TITLE
Whole Tale video chat on October 24th

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#65]
Hey all - it sounds like the folks from Whole Tale and eLife are organizing a video chat with a bunch of the people the space of reproducibility/cloud/etc. They asked folks in the Binder project if we'd like to participate.

https://github.com/whole-tale/whole-tale/issues/43

From the issue:

> Tentative time: Wednesday October 24, 2018, 1pm PDT/4pm EST and 9am NZDT (via Google Meet)

Just keeping you all in the loop in case you wanna join! It'd be good for us to interface more with the broader community.

**Comment by choldgraf** [comment]
cc @betatim and @minrk who I think have already met with eLife folks on some of this stuff

**Comment by betatim** [comment]
I'll be at PyconDE on that date so won't be able to attend.

Should we suggest to make the second agenda item more specific and send some written input in case none of us can attend?

**Comment by choldgraf** [comment]
Hey all - we had this video chat today. There were a lot of projects represented! A lot of folks were interested in using something repo2docker (or binderhub) under the hood as parts of more usecase-specific tools. Also some interest in federated Binderhubs. Meeting notes are here:

https://docs.google.com/document/d/1bOVWBfhOiKGU2dYoHN_Pkpv5zPI6y819UISfkTqYpoQ/edit#

Gonna close this issue, unless folks wanna discuss further in which case feel free to re-open!
