### ISSUE TITLE
May 2023 Collaboration Café - Facilitator Required!

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#652]
Hello, here are the details for our next Collaboration Cafe:

- Date: Tuesday 16th May, 2023
- Time: 17:00 - 19:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2023-05-16/17:00/JupyterHub%20Collaboration%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

---

### Facilitator Required!

I am unable to attend this month due to moving house (🎉 !). I have updated the hackmd with some guidelines in the [Breakout Room Topics](https://hackmd.io/@sgibson91/jupyterhub-collab-cafe#Breakout-Room-Topics) section, and a video describing how to use breakout rooms in Jitsi can be viewed [here](https://www.youtube.com/watch?v=ubYYZ0daw10). I would appreciate it if someone would volunteer to facilitate this month's cafe. Thank you in advance!

**Comment by minrk** [comment]
It's Tuesday the 16th, right (Tomorrow)? Not the 26th? I'll definitely be there, so I will try facilitate. Help from others who were there for the first hour last time would be great.

**Comment by rgaiacs** [comment]
I will be attending today (16th May). I can help.

**Comment by sgibson91** [comment]
Sorry, typo
