### ISSUE TITLE
Min on vacation in July

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#658]
I'll be on vacation for most of July (5-29), during which I'll officially not be working. I'll still be contactable, and in US/Pacific time zone, but (hopefully) not actively checking GitHub.

**Comment by yuvipanda** [comment]
I hope you had a good vacation, @minrk :)

**Comment by minrk** [comment]
Sorry for leaving this open (yes, it was nice). Thanks for cleaning things up, @yuvipanda!
