### ISSUE TITLE
Create a "jupyterhub-cdn" repository for shared CSS/JS?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#66]
Hey all - I just realized that we pushed some CSS to clean up the docs on the Binder user documentation, but now we need to re-apply this to BinderHub / repo2docker / z2jh etc.

This got me thinking: what if we had a repository that was shared with all of the JupyterHub repositories that use the Sphinx Alabaster theme. Then in the `conf.py` we'd pull this CSS file and load it. That way we could have a single set of Alabaster CSS rules that we could update and automatically apply to all of our Sphinx sites.

Thoughts?

**Comment by willingc** [comment]
This is essentially creating a lightweight Sphinx theme for JupyterHub. The old Jupyter Sphinx theme was complicated since it was designed to integrate with the website's navbar and look and feel. Creating a JupyterHub org custom theme would be pretty straightforward.

**Comment by willingc** [comment]
Pretty much create a `theme.conf` that derives from alabaster and include any JupyterHub css/js/templates and that would be the JupyterHub org sphinx theme.

**Comment by choldgraf** [comment]
I'd be +1 on that, I mostly just haven't created a sphinx theme before, which is why I was looking into this method :-)

If I have a moment I will give it a stab! I agree that would be a cleaner solution

**Comment by willingc** [comment]
We can pair if needed. Thanks @choldgraf.

**Comment by choldgraf** [comment]
I gave a shot at this here:

https://github.com/jupyterhub/alabaster-jupyterhub

it's a super lightweight extension of alabaster. However, I think I'm doing something wrong as I keep getting a `missing theme.conf` error. I'll try to debug more when I have more time, but PRs or tips are certainly welcome!

**Comment by choldgraf** [comment]
this is now in the shared theme!
