### ISSUE TITLE
July Collaboration Cafe

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#661]
Hello, here are the details for our next Collaboration Cafe:

- Date: Tuesday 18th July, 2023
- Time: 17:00 - 19:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2023-07-18/17:00/JupyterHub%20Collab%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
I know a lot of folk are away during July. Please feel free to give me a pulse on whether we should proceed or cancel this month.

**Comment by rgaiacs** [comment]
I can join on the 18th.

**Comment by minrk** [comment]
I almost certainly won't make it

**Comment by sgibson91** [comment]
Unfortunately, I hate to go collect my car from the garage and won't be back in time to start the Café. I think lots of folk are away anyway, so if you need the space, please do join, but also no pressure to either

**Comment by manics** [comment]
A few of us met!
