### ISSUE TITLE
Cleanup JupyterHub DockerHub

### ISSUE THREAD

**Issue by mathbunnyru** [jupyterhub/team-compass#664]
### Proposed change

I would like to make a few proposals to JupyterHub DockerHub:
1. Add the logo. I added a `mathbunnyru+jupyterhub@gmail.com` gravatar, so you can use it if you want to. You can take a look at the logo [here](https://en.gravatar.com/site/check/).
2. Rename `Jupyter` -> `JupyterHub`, it just seems a natural thing to do.
3. Update the link to <https://jupyterhub.readthedocs.io/en/stable/>.

### Alternative options

To do nothing 😃 

### Who would use this feature?

The DockerHub will look better and people won't be confused between Jupyter and JupyterHub projects.

**Comment by mathbunnyru** [comment]
I do not have any access to the jupyterhub DockerHub, so I need someone with access to do all this :)
Or give me an access 😄

**Comment by consideRatio** [comment]
@mathbunnyru I think this is done, what do you think?

In https://hub.docker.com/orgs/jupyterhub/settings/general, it now looks like...

![image](https://github.com/jupyterhub/team-compass/assets/3837114/f973f309-1349-44bc-9f81-7fb32ae3cb5d)

Where I've updated three fields representing your three proposals!

**Comment by consideRatio** [comment]
Ah, I think I now understand that you meant to update the "Company" from Jupyter to JupyterHub, where I just populated the empty field "Organization Name" to JupyterHub, which only infleunced capitalization.

**Comment by consideRatio** [comment]
Quck poll:
- Should the dockerhub "Company" be JupyterHub (vote :tada:) or Jupyter (vote :rocket:)?

**Comment by mathbunnyru** [comment]
> @mathbunnyru I think this is done, what do you think?
> 
> 
> 
> In https://hub.docker.com/orgs/jupyterhub/settings/general, it now looks like...
> 
> 
> 
> ![image](https://github.com/jupyterhub/team-compass/assets/3837114/f973f309-1349-44bc-9f81-7fb32ae3cb5d)
> 
> 
> 
> Where I've updated three fields representing your three proposals!

Thank you @consideRatio!
Looks nice 😊

**Comment by mathbunnyru** [comment]
I think it is already nice enough, and I don't mind having `Jupyter` in the company name, so let's close this issue.
