### ISSUE TITLE
ReadTheDocs build is broken

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#667]
<img width="841" alt="Screenshot 2023-07-24 at 15 35 58" src="https://github.com/jupyterhub/team-compass/assets/44771837/4826c66e-419c-4018-959b-db7afbcbf885">

- https://readthedocs.org/projects/jupyterhub-team-compass/builds/21390329/
- https://docs.readthedocs.io/en/stable/config-file/v2.html
- PR where I noticed the error: https://github.com/jupyterhub/team-compass/pull/666

**Comment by sgibson91** [comment]
This may be fixed by renaming our config file to `.readthedocs.yaml`

**Comment by sgibson91** [comment]
I think this is still broken despite #668

**Comment by manics** [comment]
Based on https://docs.readthedocs.io/en/stable/config-file/v2.html
it looks like
https://github.com/jupyterhub/team-compass/blob/04db7217548fff176b7e33b1f4784c36c5290ecb/.readthedocs.yaml#L1-L5
is using an old schema, it'll need to be updated to v2.

**Comment by sgibson91** [comment]
Thanks, opened https://github.com/jupyterhub/team-compass/pull/669
