### ISSUE TITLE
Celebration image/drawing for the "2M binders served" milestone

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#67]
We are nearing the magic and totally arbitrary mark of over two million binder's having been launched on mybinder.org since 1 January 2018.

I think we should make a bit of a fuss around this when we do cross the line.

Maybe we write a short post for the Jupyter blog?

It would also be very cool to use this as an excuse to create some "2million binders served" picture/drawing we can use for talks and/or twitter. Something like the image you see when you [first join GitHub](https://assets-cdn.github.com/images/modules/profile/profile-joined-github.png) or some such? Fireworks?

We are currently at about 1785637 - 140000 ~ 1660000 launches (the 140000 is number of people visiting just the front page), growing at around 80-90k per week. These are lower limits as there are a lot of launches that don't trigger our Google Analytics counter. So we have some time to get prepared.

cc @blairhudson and @agahkarakuzu and @tgeorgeux who have been helpful with good looking visuals in the past :)

**Comment by agahkarakuzu** [comment]
Wow! This is amazing, so happy to see these numbers. Here is the first sketch :) 

![image](https://user-images.githubusercontent.com/9632322/47099045-82248880-d202-11e8-9052-d46096a7402c.png)

**Comment by agahkarakuzu** [comment]
Something more plain would be better. Especially removing the arm holding the platter. 
Can put confetti etc. back if you think it is better that way. 
![image](https://user-images.githubusercontent.com/9632322/47101448-16451e80-d208-11e8-847b-b23681c89ee0.png)

**Comment by betatim** [comment]
Should we spell out 2M as 2million? When I looked at the cool(!) picture I had to think for a second: 2M? I thought the company is 3M .. ah no 2 million!

How about taking just the left half and putting some text under/with it to say thanks to all those who helped out. My other question: "served 2million" doesn't flow well in English "2 million served" would be better IMO. Is there some rule/guidance on making things like this that says we should put it in the order it currently is in?

After thinking about it while writing this: I think I'd prefer just the left half with a sentence underneath "2 million binders served by mybinder.org. Thanks for all the help!" and the Binder logo in a corner maybe.

**Comment by choldgraf** [comment]
what about 2e6 ? ;-)

**Comment by agahkarakuzu** [comment]
Here is a new one, following @betatim's suggestions (I guess) :) 

![image](https://user-images.githubusercontent.com/9632322/47125994-5f22c480-d254-11e8-8725-9bc80c93f36b.png)

**Comment by choldgraf** [comment]
Getting design contributions from the open source community is a very satisfying process :-)

**Comment by choldgraf** [comment]
@betatim how are you counting cumulative sessions, btw? I can't find a cumulative plot in google analytics

**Comment by betatim** [comment]
I visit https://analytics.google.com/analytics/web/?authuser=1#/report/content-overview/a101904940w149250546p154152886/_u.date00=20180101&_u.date01=20181017/ (Behaviour -> Overview with date range set from 1 Jan 2018 to today)

**Comment by choldgraf** [comment]
Note that we are now at 1,900,000 users :-)

**Comment by betatim** [comment]
I subtract 147849 from the number of sessions/unique page views. That is the current number of visits to `/`. Maybe not all of them should be subtracted but it seems like a lower bound to assume that none of those launched a binder.

**Comment by choldgraf** [comment]
but then the number is lower @betatim!!!! I choose a different preprocessing step ;-)

**Comment by betatim** [comment]
<img width="190" alt="screen shot 2018-11-09 at 22 45 47" src="https://user-images.githubusercontent.com/1448859/48289872-3c5d8780-e471-11e8-8a78-ddbb53e35513.png">

(minus 158,606 who visit the front page plus all the ones we don't count, basically have a slice of cake to celebrate you lot :) )

Options:
* just tweet about it
* short blog post saying not much beyond "Wow-eee!"
* slightly longer blog post with "2million!11!", "new badges!" and "daily analytics data!!"

My preference would be the last option. One paragraph on each point with an intro and an outro.

We should get this done at the start of next week (otherwise we will have too many launches ;) )

cc @minrk @willingc @yuvipanda

**Comment by agahkarakuzu** [comment]
Now that time has come here is the highres version of the design :) 

![binder_2m](https://user-images.githubusercontent.com/9632322/48290627-8b8bc400-e441-11e8-89a6-9dc9eacedc20.png)

**Comment by choldgraf** [comment]
@yuvipanda do you think the "analytics stream" is ready to "tell the world about" next week?

**Comment by choldgraf** [comment]
hey all - I've got a hackmd here where I've put a few early thoughts on how we can talk about this in a blog post:

https://hackmd.io/nA4V6f5oT8SDwRL9tPrjTw?both

**Please feel free to edit, add comments, add media, and discuss here!** That's just a starting point. We can plan to release something and post it this week!

**Comment by choldgraf** [comment]
cc @betatim in case he'd like to help w/ the post launch!

**Comment by willingc** [comment]
@choldgraf I made some edits and updated some of the outline flow to tell a story:
- Hooray for milestone
- We're global and check out the analytics
- What's new
  - all the technical items
- What's next
   - Direction
   - Discuss on discourse
- Thanks

So happy about this :smile: and the beautiful graphic too.

**Comment by betatim** [comment]
Ha! Just put together a draft post on the Jupyter blog after dinner and only now checked back on GitHub ...

Draft post link: https://blog.jupyter.org/thanks-a-million-or-two-actually-7543ae498a2a (I think if your medium account is somehow connected to the Jupyter blog you should be able to see it as a draft and able to edit it?? This is my first time writing on medium :-/)

I will try and merge my work into the hackmd that Chris posted above.

**Comment by minrk** [comment]
Post looks really nice. Well done, folks!

**Comment by betatim** [comment]
Too early, we still need to merge the hackmd and the post on medium :-/

I am waiting for Chris to wake up again. I quite like the medium draft (that I wrote, what a surprise...) because it is short(ish) (could be shorter with some word smithing and more linking out to other resources). I think talking about the thinking that went into each draft and then resolving the differences will be most productive if done in real time.

In the outro section I'd add a bit more on what project binder is, how mybinder.org relates to binderhub and repo2docker etc. That they are all open-source software and open infrastructure operated by people from around the world with no plans of turning it into a service that requires a credit card. Basically "you are still reading, you really must want more details".

**Comment by choldgraf** [comment]
ok I took at @betatim 's post - I think it was actually quite close to what @willingc suggested in her outline. I made a few edits, so let's see what folks think about that. Tim, can you post a link to the post here so that others can see?

**Comment by willingc** [comment]
I don't have a strong feeling. One thing that I did think about before I saw @betatim's post was possibly splitting the original draft by @choldgraf into a higher level celebration(like Tim's) and another that focuses on all the technical bits.

**Comment by choldgraf** [comment]
@willingc I think that's a great idea - perhaps we could plan to roll out some specific technical drafts in the coming weeks. Even the technical stuff we do mention here (like the public data archive) is still treated at a very high level...perhaps we can add in language like "more to come on this" and post about it later

**Comment by betatim** [comment]
I think we are getting there. There is now just one version of the post!

I'd be happy to press publish now. The post has grown (they always do :-)) so I am wondering (related to the comments above) if we should cut everything after the map of the world and instead make each of those sections into a separate new post. We'd keep the "Open infrastructure in the cloud" section as a kind of "what is this, how is it different, details" section.

@yuvipanda check out the section on the event stream (A public data stream from mybinder.org). My vote right now would be to make a new post about it if the feeling is that being this short isn't worth it.

Same about the new badge section, we could easily make a longer post about it, how we got the new badge, how to use it, plug discourse more, etc.

Right now we are jumping from "party time!" to "oh and here some data" to "also shiny new badge" without much of a flow to the whole thing. Which would also suggest to split things.

**Comment by betatim** [comment]
@yuvipanda @willingc @choldgraf if each of you could somehow signal "i am happy to press publish" here that would be great. I am happy with the post as it is now. So if everyone else is happy feel free to publish it. Otherwise I will do it tomorrow morning or if there is something to edit/change will do that.

**Comment by choldgraf** [comment]
I'm +1 on posting it

**Comment by minrk** [comment]
looks great!

**Comment by betatim** [comment]
Thanks everyone! The post is public at: https://blog.jupyter.org/mybinder-org-serves-two-million-launches-7543ae498a2a I scheduled a tweet from the team account at about 15:30h Zurich time (about 90minutes after this post).

Thanks for the help writing the post and even more thanks for being such awesome people to work with. Who'd have thought that a ragtag group of people from the internet would put together such an awesome service 😀
