### ISSUE TITLE
Blog Post: Climate science workshop with Linux Desktop (and qgis) on a JupyterHub!

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/team-compass#671]
There was a recent amazing climate science related workshop that used JupyterHub with a Linux Desktop (via https://github.com/jupyterhub/jupyter-remote-desktop-proxy) to do stuff that would've been hard without Linux Desktop in JupyterHub, and it went pretty great! 

Given this is a newish use case, and that this went great (with some caveats), I have asked the team to help write a blog post for the Jupyter Blog!

Opening this issue to track this.

**Comment by yuvipanda** [comment]
@mattf-nsidc has written a draft that I've helped edit in https://medium.com/@mafi5546/ddced297019a, and after a bunch of tweaking, I think this is good to go. They'd like to get it in before AGU's submission deadline of Aug 2 (Wednesday), so I'd love to publish this by Aug 1 European time.

**Comment by MattF-NSIDC** [comment]
Thank you all for the opportunity for the QGreenland team to publish to the Jupyter Blog :) I'm new to using Medium, so please bear with me. I'm happy to continue making any edits, and also ready to "Add to publication" whenever appropriate!

**Comment by yuvipanda** [comment]
https://blog.jupyter.org/desktop-gis-software-in-the-cloud-with-jupyterhub-ddced297019a is now the draft link!
