### ISSUE TITLE
[URGENT] Schedule a meeting with Sumana to discuss maintenance strategies for the org

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#680]
### Context

In September's Collab Cafe, we discussed the opaqueness of our current maintenance strategy for repos with the organisation.

- What does it mean if we're "supporting" a repo?
- What is the minimal level of support for these repos?
- Three levels:
  - `jupyterhub-contrib` org: not fully supported, JupyterHub associated
  - `jupyterhub` org: Fully fledged JupyterHub repos
  - Repos that are part of z2jh and tljh distributions: highest level of support
- Bar for accepting a project has been low to encourage new maintainers/contributors
  - This may have backfired and instead created more maintainer load

I believe this would be a good topic to discuss with my leadership coach [Sumana](https://www.changeset.nyc/about-us/), and she has agreed to spend  up to 2 hours with us on a call so she can share some strategies she has tried in the past for similar situations, what has worked, and what hasn't, and we can ask questions and decide if want to try out any of the strategies she suggests.

### Action Point

Sumana's calendar is a little bit tight and so is hoping to have something on the books between now and EOD Eastern Time on Tuesday Oct 3rd.

**Please fill in the doodle poll with availability ASAP so I can book something in her calendar!** 🙏🏻 https://doodle.com/meeting/participate/id/e09qgGLa

**Comment by yuvipanda** [comment]
Sumana is absolutely amazing and I'm excited to have this opportunity! I've signed up.

**Comment by minrk** [comment]
Filled it out. This is awesome. My availability is quite limited, so if it doesn't fit with my times, don't worry about it and I'll try to drop in while I can, if that's okay.

**Comment by sgibson91** [comment]
Thank you everyone for the quick response and for being flexible on such short notice.

I have provisionally booked a slot in Sumana's calendar for [**Friday 29th, 19:00 BST**](https://arewemeetingyet.com/London/2023-09-29/19:00). I will provide more info and add this to the team calendar when I have confirmed with Sumana.

I realise that our availability as a team was quite limited so I will commit to taking notes to share with those who cannot attend afterwards.

**Comment by sgibson91** [comment]
Notes and next steps from this meeting are here: https://hackmd.io/@sgibson91/HJitFKNga

Thank you to those that attended!
