### ISSUE TITLE
Add Raniere to binder operators team

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#692]
While debugging some cryptomining on GESIS mybinder with Yuvi, it came to light that @rgaiacs doesn't have merge permissions to https://github.com/jupyterhub/mybinder.org-deploy and indeed is not a member of @jupyterhub/binder-team. I believe we should add him and give him merge rights.

**Comment by minrk** [comment]
added!

**Comment by rgaiacs** [comment]
Thanks. Invitation accepted.
