### ISSUE TITLE
Help jupyter org on dockerhub retain open source status

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/team-compass#694]
I'm not alligable to re-apply for the open-source status because I'm not an owner of the `jupyter` (not `jupyterhub`!) organization on dockerhub.

https://www.docker.com/community/open-source/application/

@mathbunnyru I think you are, could you apply just to be safe that we don't loose that status and run into a lot of trouble that could be avoided while migrating to quay?

I know @choldgraf re-applied for `jupyterhub` successfully, and our initial application wasn't made using this form and covered both `jupyterhub` and `jupyter` - so maybe they re-approved the `jupyter` org alongside this, maybe not.

**Comment by mathbunnyru** [comment]
Done.

<img width="462" alt="Screenshot 2023-11-04 at 11 08 42" src="https://github.com/jupyterhub/team-compass/assets/12270691/40c177a5-9a89-44c5-ab46-a83fe0c9e37c">

**Comment by consideRatio** [comment]
Thank you @mathbunnyru!!!
