### ISSUE TITLE
Collab Cafe - February 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#707]
Here are the details for our next Collaboration Cafe!

- Date: Tuesday 20th February, 2024
- Time: 09:00 - 11:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-02-20/09:00/JupyterHub%20Collaboration%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by KirstieJane** [comment]
Hi @sgibson91! Please can I have a slot in the agenda to talk about a proposed revamp of the CZI EOSS Diversity Equity and Inclusion funded project?

I can add to the hackmd, is that the right plan?

**Comment by manics** [comment]
@KirstieJane yes, just add it to the Hackmd!
