### ISSUE TITLE
Moving Directory  of Team Members back to Readme?

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/team-compass#71]
I think we've found having this listing on the readme to be useful for visibilty?

**Comment by betatim** [comment]
Maybe we can have them in both places? I think there are people who look at webpages first and people who look at GitHub repos first depending on what kind of person you are. Not sure but it could be that READMEs aren't indexed by google? MY vote would be have them in both places, even though it duplicates info.

Do you want to make a PR?

**Comment by choldgraf** [comment]
I'm happy with having them in both, though it's another thing for somebody to remember to update. My assumption in the last PR was that a website is more visible to a broader part of the community than a github README file, but we also then need to do a better job of linking to, promoting, etc the website.

What if in the README we had sections that linked out to the website? (https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html)

**Comment by jzf2101** [comment]
I know that @ellisonbg looks first to the readme to find the team https://github.com/jupyterlab/jupyterlab/issues/4297 for org level communication
