### ISSUE TITLE
Collab Cafe - March 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#712]
Here are the details for our next Collaboration Cafe!

- Date: Tuesday 19th March, 2024
- Time: 17:00 - 19:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-03-19/17:00
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by manics** [comment]
I won't be able to make this
