### ISSUE TITLE
Add Security team

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#716]
It would be valuable to give folks working on [security across Jupyter](https://github.com/jupyter/security) access to advisories on the JupyterHub org, to not rely on maintainers for creating the drafts in the first place, and ensure security folks are available in the advisory discussions without needing to add collaborators one-by-one.

Proposal:

add a 'security' team, and grant them 'Security Manager' permissions.

Tasks:

- [x] document security team's permissions, membership, and how membership is managed
- [x] create security team
- [x] grant security manager role to the team
- [x] add some members (who? Perhaps the whole jupyter/security Council, plus some members of the working group, as selected by the Council)

More info:

- [security manager documentation](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/managing-security-managers-in-your-organization)
- security manager role is assigned [here](https://github.com/organizations/jupyterhub/settings/security_analysis)

cc @rpwagner @dlqqq

**Comment by manics** [comment]
Sounds fine to me.

**Comment by dlqqq** [comment]
Awesome, thanks for opening the issue! Subscribed.

**Comment by minrk** [comment]
docs and member list started in #721
