### ISSUE TITLE
Collab Cafe | May 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#718]
Here are the details for our next Collaboration Cafe!

- Date: Tuesday 21st May, 2024
- Time: 17:00 - 19:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-05-21/17:00/JupyterHub%20and%20Binder%20Collaboration%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
A reminder that this is next week!

**Comment by sgibson91** [comment]
A reminder that this meeting is tomorrow!

**Comment by minrk** [comment]
I'll be there! I can only make the first hour.
