### ISSUE TITLE
Adding JupyterHub to the "Project Jupyter" GitHub Enterprise

### ISSUE THREAD

**Issue by manics** [jupyterhub/team-compass#719]
The JupyterHub organisation has received an invite to join the Project Jupyter Enterprise on GitHub.

The only discussion I'm seen so far is in https://github.com/jupyter/enhancement-proposals/issues/122#issuecomment-2099501888
It sounds fine to me, and follows on from the discussion in https://github.com/jupyterhub/team-compass/issues/716
Does anyone have concerns about this?

**Comment by minrk** [comment]
No concerns other than the lack of a central governance issue about what the Enterprise means. I don't really know what that is, but I think it's like an 'org of orgs' which lets us do some things "jupyter-wide" like security and teams, which have been really hard across many orgs.

So 👍 from me to joining.

**Comment by choldgraf** [comment]
+1 from me

**Comment by manics** [comment]
There's a new issue on the Governance repo with an explanation: https://github.com/jupyter/governance/issues/219
Summary: more or less what @minrk said above

**Comment by jasongrout** [comment]
We've now moved the discussion to the draft governance PR: https://github.com/jupyter/governance/pull/221

Sorry again about the confusion.

**Comment by minrk** [comment]
I've accepted the invitation for JupyterHub
