### ISSUE TITLE
Collab Cafe - June 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#724]
Here are the details for our next Collaboration Cafe!

- Date: Tuesday 18th June, 2024
- Time: 09:00 - 11:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-06-18/09:00/JupyterHub%2FBinder%20Collab%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
Hey folks - a reminder that this is happening next week

**Comment by minrk** [comment]
I have a conflict so can't make this one.

**Comment by manics** [comment]
I can't make it either.

**Comment by sgibson91** [comment]
Given that our attendance rate for the Euro AM meetings tend to be lower, and two key team members are not available, it may be worth considering cancelling this one?

**Comment by consideRatio** [comment]
I'm vacationing and wouldn't mind it being cancelled - uncertain if i would find time to attend

**Comment by minrk** [comment]
Thanks, @sgibson91!
