### ISSUE TITLE
Merging community issue templates from .github repo with repo-specific issue templates

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#727]
### Context

I wanted to add an issue template for the Collab Cafe issues to save myself some copy-pasting when I do this task. However, because we have community issue templates setup in the `.github` repo, creating any issue templates in the team-compass repo will overwrite what we inherit from there.

From the [documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file):

> If a repository has any files in its own `.github/ISSUE_TEMPLATE` folder, including issue templates or a _config.yml_ file, none of the contents of the default `.github/ISSUE_TEMPLATE` folder will be used.

### Proposal

In 2i2c, we get around this by using a `sync-issue-templates` workflow in the `.github` repo. There is a `sync` definition file which defines which issue templates to sync into which repos, and opens PRs to the listed repos when the issue templates in `.github` change.

- [workflow file](https://github.com/2i2c-org/.github/blob/main/.github/workflows/sync-issue-templates.yaml)
- [definition file](https://github.com/2i2c-org/.github/blob/main/.github/sync.yml)

Does this sound like an acceptable approach to take for JupyterHub?

**Comment by minrk** [comment]
Yeah, that sounds reasonable. I think it would also be appropriate for this repo to not shareissue templates with the rest, since it doesn't make sense to have bug reports here, etc., if that would be simpler.
