### ISSUE TITLE
Raniere will be on annual leave in October

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/team-compass#730]
I will be on annual leave from 2nd October 2024 (included) until 3rd November 2024 (included).

@juliandehne works at GESIS and he will cover the mybinder.org GESIS server operation during my annual leave.

In August and September, I will work together with @juliandehne for @juliandehne to be familiar with issues like https://github.com/jupyterhub/mybinder.org-deploy/issues/3026.

cc @arnim

**Comment by arnim** [comment]
Thank you @juliandehne for taking care of this while @rgaiacs is on vacation :)

**Comment by rgaiacs** [comment]
I'm back from holiday.
