### ISSUE TITLE
JupyterHub and Binder Collaboration Cafe | September 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#740]
Here are the details for our next Collaboration Cafe!

- Date: Tuesday 17th September, 2024
- Time: 17:00 - 19:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-09-17/17:00/JupyterHub%20and%20Binder%20Collab%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
As per #737, if anyone would like to facilitate this meeting I would be very happy to have a chat through what I do.

**Comment by minrk** [comment]
With no volunteers in #737, I can facilitate this one tomorrow. I'll make sure #737 is on the agenda.

**Comment by consideRatio** [comment]
> I can facilitate this one tomorrow

@minrk note that this is scheduled Tuesday 17th September!

**Comment by minrk** [comment]
Blarg, thank you! I'm bad at calendars.

It would still be good to get a facilitator volunteer for this one, but I can fill in if necessary.

**Comment by sgibson91** [comment]
As Erik correctly pointed out, this meeting is scheduled for next week 😄 (Just posting my regular reminder)

**Comment by sgibson91** [comment]
A reminder that this is happening tomorrow! If anyone will like to volunteer to facilitate, please let us know :)

**Comment by minrk** [comment]
I'll be there and plan to facilitate if we don't have another volunteer.

**Comment by manics** [comment]
I can't make tomorrow's meeting

**Comment by arnim** [comment]
@rgaiacs asked me to join the discussion on jupyterhub/mybinder.org-deploy#3083 and jupyterhub/mybinder.org-deploy#3087. I'll try to attend. Perhaps we could have a short Pomodoro session for some brainstorming?

**Comment by minrk** [comment]
@arnim sounds great!
