### ISSUE TITLE
The Donate link on the MyBinder homepage is broken

### ISSUE THREAD

**Issue by rgaiacs** [jupyterhub/team-compass#742]
This was first reported by [anjackson](https://discourse.jupyter.org/u/anjackson) at [Jupyter Community Forum](https://discourse.jupyter.org/t/the-donate-link-on-the-mybinder-homepage-is-broken/27841),

> The link in https://mybinder.org/ is https://numfocus.salsalabs.org/donate-to-binder.
> 
> I believe that https://salsalabs.org is now redirecting to https://bonterratech.com/ and this redirect is not properly configured.

Who is the contact person with NumFOCUS to get the new link?

### Todo

- [ ] Update the link to https://numfocus.org/donate-to-jupyter

**Comment by choldgraf** [comment]
Hmmm good question - I'm not really sure. I've asked in the NumFOCUS slack and will let you know if there's any update

**Comment by manics** [comment]
@choldgraf is that a typo? https://numfocus.salsalabs.org/donate-to-binder is the same as the broken link that redirects to https://www.bonterratech.com/

**Comment by choldgraf** [comment]
Yep - good catch, was a wrong copypaste. I've updated it now

**Comment by manics** [comment]
PR: https://github.com/jupyterhub/mybinder.org-deploy/pull/3076

**Comment by CommanderStorm** [comment]
> They told me that they recommendation is to use the following Jupyter donate link for now:
> 
> https://numfocus.org/donate-to-jupyter

@rgaiacs Could we reopen this issue, as the previous fix was apparently not as final as thought:

![image](https://github.com/user-attachments/assets/75e9c5fd-e963-4ecc-8a94-c4b94376084b)

**Comment by krassowski** [comment]
Ah, this is the link endorsed by EC: https://jupyter.org/about#donate

**Comment by minrk** [comment]
https://github.com/jupyterhub/mybinder.org-deploy/pull/3139 updates the link
