### ISSUE TITLE
JupyterHub and Binder Collab Cafe | November 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#747]
Here are the details for our next Collaboration Cafe!

- Date: Tuesday 19th November 2024
- Time: 17:00 - 19:00 Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-11-19/17:00/JupyterHub%20and%20Binder%20Collab%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs, including a facilitator checklist: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
Hello. A reminder that this is happening next week. And if anyone would like to host, per #737, please feel free to ping me.

**Comment by sgibson91** [comment]
Hey folks, this is happening tomorrow!

**Comment by minrk** [comment]
Thanks! I'll be there, but can only stay for the first hour.
