### ISSUE TITLE
[TENTATIVE] JupyterHub and Binder Collab Cafe | December 2024

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/team-compass#749]
> We usually cancel the December meeting as a lot of folk take breaks at this time of year. However, we can run this meeting if there is quorum.
> Please emoji-react to provide a pulse check on attendance of this meeting:
> - 😄: I can definitely attend
> - 👍🏻: I can attend if it's running
> - 👎🏻: I can definitely not attend

Here are the details for our next Collaboration Cafe!

- Date: Tuesday 17th December 2024
- Time: 9AM - 11AM Europe/London
  - Your timezone: https://arewemeetingyet.com/London/2024-12-17/09:00/JupyterHub%20and%20Binder%20Collab%20Cafe
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs, including a facilitator checklist: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
There's not much activity here, so I think I will cancel this meeting. See you in the new year everyone!

**Comment by minrk** [comment]
Makes sense, thanks @sgibson91!
