### ISSUE TITLE
Reproducible Research workshop planning call 10/30 (Whole Tale/Code Ocean)

### ISSUE THREAD

**Issue by craig-willis** [jupyterhub/team-compass#75]
Per @choldgraf's suggestion, I'm opening this issue in case anyone is interested in joining a call next week planning a Reproducible Research workshop at UIUC/NCSA.

From https://github.com/whole-tale/whole-tale/blob/master/working_groups/education/README.md

> We will be having a call on Tuesday 10/30 at 2pm CT (via Meet/Hangouts) to continue planning a spring workshop at UIUC.
> https://meet.google.com/czh-fknp-jmm
> ‎(‪US‬) ‪+1 724-260-6039‬
> PIN: ‪337 776 853#‬

One outcome from [yesterday's Whole Tale call](https://github.com/whole-tale/whole-tale/issues/43) was an interest in potentially collaborating on education/training materials in the reproducible research space.  

Working with @aprilcs, the current plan is to host a 2-day workshop at UIUC/NCSA based on the existing Data Carpentry material [workshop-RR-Jupyter](https://reproducible-science-curriculum.github.io/workshop-RR-Jupyter) forked to adapt to our goals, incorporating some of her existing material.  Feel free to contact me with questions.

**Comment by choldgraf** [comment]
I won't be able to make this since I'm outta town, but if anybody else can make it that'd be awesome!

**Comment by choldgraf** [comment]
(also @jbpoline is interested and working on building open tools for scientific publishing, which also seems relevant :-) )

**Comment by craig-willis** [comment]
Notes from this call have been posted:
https://github.com/whole-tale/whole-tale/blob/master/working_groups/education/meeting_notes.md

We will have a follow-up call on 11/7 from 1-2pm CT with the same call-in information.  This issue can be closed.

**Comment by choldgraf** [comment]
great - thanks for the notes!
