### ISSUE TITLE
JupyterHub and Binder Collab Cafe | [Month, Year]

### ISSUE THREAD

**Issue by jonana701** [jupyterhub/team-compass#750]
Here are the details for our next Collaboration Cafe!

- Date: 
- Time: 
  - Your timezone: 
- HackMD link: https://hackmd.io/@sgibson91/jupyterhub-collab-cafe
- Video link: https://meet.jit.si/jupyterhub-collab-cafe
- More info:
  - Docs, including a facilitator checklist: https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings/collab-cafe/index.html
  - Blog: https://blog.jupyter.org/online-collaboration-caf%C3%A9-launch-jupyterhub-team-meetings-to-become-more-collaborative-spaces-b713edadf15

A reminder that this is a large block of time, so arriving late or dropping early if required is normal and to be expected.

**Comment by sgibson91** [comment]
Hey @jonana701 ! If you're looking for details of our next meeting, you can find them here https://github.com/jupyterhub/team-compass/issues/749 Though given that it's near the end of the year it may not happen, and instead we'll reconvene in the new year. I'll close this issue for now :)
