### ISSUE TITLE
Clarify JupyterHub communication strategy

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#77]
Right now there are many different channels of communication in the JupyterHub world. Recently we set up a Discourse (discourse.jupyter.org) for another style of communication. This brings up the question of how we can use all of these channels in an effective manner.

@willingc along with comments from @betatim and @ellisonbg recently laid out a nice list for ideas for which kinds of communication fits where. I'm pasting the full text below.

I've also set up a thread to discuss this in the Discourse, link here:

https://discourse.jupyter.org/t/discuss-the-jupyterhub-communications-strategy/27

---

### Gitter

- general chat (quick questions between devs)
- quick (one conversation) technical support issues (posting to Discourse the outcome if it will take > 1 conversation) *May make sense to encourage users to migrate their questions to Discourse; answering quick questions synchronously has the benefit of building rapport with users*
- time sensitive devops
- coordination (are you around to review my PR today, can I help with
that?)
- informal team building/trust

### Discourse 

- Technical support requiring more than one discussion (moved from Gitter to Discourse)
- Opinion polls
- Discussions of controversial issues (process, workflow, project direction)
- Discussion of GitHub issues that are broad in scope or where next actions are not well defined (*Cross linking with the [discourse-github plugin](https://github.com/discourse/discourse-github#github-linkback)*)
- Discussions of topics not related to a GitHub item
- How to contribute discussions
- Events
- summarization for a broader audience (GitHub is a firehose),
- discussion of larger work efforts that span multiple issues or repos but
are still within an area of the project
- requests for feedback
- other organizational and non-code matters.

### GitHub

- Enhancements, bugs, and triaged support questions that need development to resolve
- Brief responses on well-scoped (actionable) GitHub issues
- Review comments and suggestions for open PRs
- Release milestones

**Comment by jzf2101** [comment]
Can we put this in a website somewhere or markdown when we're ready?
