### ISSUE TITLE
PyCon US 2019

### ISSUE THREAD

**Issue by betatim** [jupyterhub/team-compass#79]
Should we submit a tutorial? (https://us.pycon.org/2019/speaking/tutorials/, deadline November 25)

Should we submit a talk? (https://us.pycon.org/2019/speaking/talks/, deadline January 3)

Do those who are going planning on coordinating?

---

Tim isn't sure if he will/can/wants to go. Mostly because it is in the US (travel time and politics :-/), I am thinking to prioritise JupyterCon over PyCon. However I would like to meet up with other Binder people so if everyone is doing PyCon this year ... let me know.

**Comment by choldgraf** [comment]
Hmmm, I don't know pycon that well (I have never been, in fact). I think it'd be cool to submit something. I know a lot of our work overlaps with the "non data sciencey" part of the Python ecosystem, so maybe folks there would be interested.

**Comment by minrk** [comment]
I won't be available for travel in May, but as always am happy to help put together materials.

**Comment by jzf2101** [comment]
I'm not going to PyCon this year but can help

**Comment by choldgraf** [comment]
This deadline has passed, so closing this issue 🙃
