### ISSUE TITLE
December 2018 meeting

### ISSUE THREAD

**Issue by minrk** [jupyterhub/team-compass#86]
Now that we're on a regular third-Thursday schedule, the December meeting will be held on Thursday 20. December, 2018 at 6pm European time ([your timezone](http://arewemeetingyet.com/Zurich/2018-12-20/18:00/Binder%20team)).

https://calpoly.zoom.us/my/jupyter zoom link for video conferencing

Agenda: https://hackmd.io/KS4Tw2__RVWJgiZ_5aeanA?edit

First question: is this too close to holidays for folks? Should we try a week earlier on 13 December?

**Comment by Zsailer** [comment]
Either date works for me.

**Comment by minrk** [comment]
Let's assume the regular 3rd Thursday schedule unless we find too many conflicts. Folks with conflicts: post here!

**Comment by choldgraf** [comment]
either should work for me!

**Comment by Zsailer** [comment]
Great! 

As I said on the call, I'd be happy to manage the logistics for these calls. I'm imagining this involves:

1. Add monthly call details to Google calendar at least a month in advance.
1. Open an issue on Github at least a month in advance.
1. Comment on the issue the day before the call (with hackpad links).
1. Post on the jupyterhub and binder gitter channels the day before the call (with hackpad links).
1. Start a fresh HackPad template for the meeting.
1. Comment on gitter right before the call.
1. Close the Github issue for that current month *after* the call. 

Anything I'm missing?

**Comment by minrk** [comment]
That looks great, thanks @Zsailer! I'd add a comment here a week before the call, or at the beginning of the week, rather than just 24 hours in advance.

**Comment by choldgraf** [comment]
hey @Zsailer , add yourself to the https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html#jupyterhub-team page :-)

**Comment by Zsailer** [comment]
Thanks @choldgraf! I added myself in #91 :)

**Comment by jzf2101** [comment]
Later is better for me

**Comment by betatim** [comment]
Updated the top comment

**Comment by Zsailer** [comment]
Hello everybody!

This is your friendly reminder that we have a Jupyterhub (video) team meeting *next week*!

That's **Thursday, December 20th, 2018** at **6pm European time** (or [your timezone](http://arewemeetingyet.com/Zurich/2018-12-20/18:00/Binder%20team)).

* You can find the agenda [here](https://hackmd.io/KS4Tw2__RVWJgiZ_5aeanA?edit).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter).

I look forward to seeing you all next Thursday! 

Until then, have a wonderful week+weekend and keep up the awesome work!

 😃

**Comment by consideRatio** [comment]
@Zsailer thanks for the reminder =D

**Comment by Zsailer** [comment]
Closing this issue now! I'll submit the hackmd notes for the meeting soon!

Thanks to everyone who appeared in the meeting!
