### ISSUE TITLE
Equipment+posters/banners @ NeurIPS?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#93]
I just realized that we'll probably have some kind of a "booth-like" setup at NeurIPS. To that extent, we may need equipment. Can we use this issue to make sure we're OK on this front? If you've already got a plan for this @jzf2101 then apologies for the noise! Just wanna make sure we have the details nailed down.

From the NIPS email about this, they recommended these things for presentations:

* Prepare a poster with
  * The title and authors of your demo
  * One sentence explaining the "what?" and the "what for?" in big letters
  * Supporting material to explain your technology and answer people's questions
* If you are demonstrating tools and your material consists of a laptop
  * Consider renting a large monitor or bringing a projector to enlarge your screen. We *do not* provide monitors or projectors. 1/2 of your poster board can be used for projection. Note that you will also need to bring a white poster or linen to cover the poster board, to use it for projection.
  * Prepare a slide show so there is something going on while you are not demonstrating.
  * If possible bring 2 laptops, one for the slide show or demo and one for people to try things on their own.

@jzf2101 do we have any of these things (in particular, hand-outs, a poster, etc) ready to go? I have an older Binder poster that I will bring with me just in case.

## Some questions we should figure out:

* How many monitors do we need, and where should we get them? The email had a suggested person to coordinate about monitors, have we emailed them?
* Should we make a new poster, or use the one that I made about a year ago? If we need to make a new poster, we should really get on this...
* Has anybody got a demo-reel of Binder repositories? Something that we can put on a screen as a slideshow while nobody is there?
* Is it worth putting together a handout of some kind?

I'm traveling to Montreal tomorrow, so I'll be out until about 5pm or so.

**Comment by choldgraf** [comment]
Also I think I have an old Binder poster somewhere at BIDS, should I bring it?

**Comment by choldgraf** [comment]
cc people who are on the registered author list for the demo, or who (I think) will be there.

@jzf2101 @betatim @mpacer @cmd-ntrf @fperez

**Comment by choldgraf** [comment]
@jzf2101 I'm gonna defer to you on all of these points, those were just my general suggestions :-)  I think that when I first made this post, I was under the impression that we had a "booth" kind of setup, but this feels more like it's "poster session ++" which doesn't have as much need for handouts etc. I think a good poster + at least 2 monitors would be a good base.

**Comment by jzf2101** [comment]
Great job everyone!
