### ISSUE TITLE
NeurIPS plan for Tuesday

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#94]
Hey all - just wanted to send out (what I think is) the plan for tomorrow so that we are roughly on the same page. 

* 8:45am - Felix and I will meet with Elizabeth at MNI to pick up two monitors. We also need to get a power strip.
* 9am (or so) - I'm available to pick something up at the printers if need be
* 10:30am (or so) - Jessica+Felix+Chris should be ready to go @ the booth
* 1pm - Poutine and or smoked meat break
* 10:45am - 12:45pm - Our first demo session is live
* 4:45pm - Jessica+Felix+Chris should be ready to go @ the booth
* 5:00pm - 7:30pm - Our second demo session is live

also see @consideRatio's deployment plan for the hub: https://github.com/jupyterhub/team-compass/issues/92#issuecomment-443906937

cc @jzf2101 @cmd-ntrf @consideRatio @fperez @minrk @betatim

**Comment by betatim** [comment]
Not urgent: does the demo session continue on Wednesday?

**Comment by choldgraf** [comment]
nope, it's done now. @jzf2101 is giving a presentation about it on Saturday, not sure if she's planning on a live demo or not (I'll be back in Cali by then)

**Comment by jzf2101** [comment]
Yay team 💪 !
