### ISSUE TITLE
TLJH blog post?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#95]
Have we written a blog post about the littlest jupyterhub? @yuvipanda do you know? If not, we should once we're happy enough with the tech to tell people to use it widely!

**Comment by minrk** [comment]
Yuvi wrote [this one](http://words.yuvi.in/post/the-littlest-jupyterhub/)

**Comment by yuvipanda** [comment]
I'd like to land culling in TLJH before making this post, but +1 for making a post!

**Comment by choldgraf** [comment]
Cool - I'm also thinking of this as a way for us to release the "non-alpha" version of the tool. We should definitely link back to Yuvi's post too!

**Comment by yuvipanda** [comment]
@GeorgianaElena did a great job in https://blog.jupyter.org/the-superheros-and-the-magic-wand-596acaab722a \o/
