### ISSUE TITLE
Blog post for Binder @ NeurIPS

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/team-compass#96]
Hey all - we recently had a thread where somebody started a hackmd to write a blog post summarizing our NeurIPS deployment. I don't remember where that was (maybe gitter?) but either way I wanted to start an issue so we keep track of it. 

On the plane ride, I did a little bit of re-organizing and building off of @betatim 's original outline. Is this a good starting point to start fleshing it out w/ content?

https://hackmd.io/ZEVbmiWHQiOuRUQzRmjnNg?edit

cc @jzf2101 @consideRatio @cmd-ntrf @fperez and @minrk who were also involved heavily the last couple days

**Comment by choldgraf** [comment]
Heya folks - I fleshed out the outline a little bit, and there are two specific places that we can add in information

@jzf2101 can you provide a list of repositories that we reproduced w/ the BinderHub@NeurIPS deployment, and just note briefly what you needed to add to them to make this possible?

@consideRatio or @minrk or @betatim could you provide a link to information about the BinderHub deployment that we used (e.g., information that somebody else might find useful for reproducing the deployment)

**Comment by consideRatio** [comment]
@choldgraf here goes!

- The deployment source code: https://github.com/consideratio/neurips.mybinder.org-deploy
- These are [3-4 images that were made extra accessible](https://github.com/consideRatio/neurips.mybinder.org-deploy/blob/5aad94a99afed0f13fce35c9524ea5d5c57d3084/values.yaml#L78-L89) selected, forked and prepared for GPU launch by @jzf2101 in the following repositories under a branch called binder-gpu or gpu-binder.
  - https://github.com/jzf2101/shap
  - https://github.com/jzf2101/tutorial
  - https://github.com/jzf2101/gan_tutorial
  - https://github.com/jzf2101/mxnet-the-straight-dope

- What was done [can be seen in this commit by @jzf2101](https://github.com/jzf2101/mxnet-the-straight-dope/commit/338f3365b17487e50e090ec24bd58d0b9c32d721)

---

For additional details, this is a relevant post: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/994

**Comment by choldgraf** [comment]
this is great! thanks for the info - one thing I noticed is that you mention in your guide that you're basing off of a Docker image that you personally created, but I thought @betatim mentioned that in the end we got it working using a barebones Docker image and got GPU support working the "regular" way w/ repo2docker. Could you clarify?

I'm updating the post with all of this great info! Also one thought, **we should definitely publish your post about GPU-enabled JupyterHub** when you think it's ready (if you want to). Let me know once you're happy with it and we can help you get it on the jupyter blog

**Comment by consideRatio** [comment]
You sure know how to fill someone with energy and warm feelings @choldgraf =D I love it!

I did not grasp what you are asking in the first paragraph though :p

I think the key to getting the GPU working is:
1. Install cudatoolkit=9.0 for NVIDIA Tesla K80, P100, V100 and the 384 driver that is installed by the nvidia-driver-installer daemonset
2. Configure the path variables LD_LIBRARY_PATH and PATH to include the binary folders installed by the nvidia-driver-installer daemonset

- repo2docker can accomplish part 1 in `environment.yaml` and part 2 in the file `start`
- If you manually build an image, you can accomplish both steps in the Dockerfile

**Comment by choldgraf** [comment]
ah ok cool - that actually confirms what I was asking :-)  I just noticed that in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/994#issue-373992464 you say "you should use a Dockerfile and source this custom image", but in the end we accomplished the same thing without needing people to use a custom docker image built just for GPUs, and by utilizing the standard repo2docker config file approach.

**Comment by betatim** [comment]
> in the end we accomplished the same thing without needing people to use a custom docker image built just for GPUs, and by utilizing the standard repo2docker config file approach.

This is correct.

**Comment by betatim** [comment]
I made some edits to the beginning of the article: https://hackmd.io/ZEVbmiWHQiOuRUQzRmjnNg?edit#

What do people think about moving the section on the repositories and how little work it was to modify them up before the deployment config section?

**Comment by choldgraf** [comment]
@betatim I think the article is still in a very rough state, so from my perspective, feel free to move around anything you like

**Comment by choldgraf** [comment]
hey all - I'd like to get this post out there sometime soon so that it doesn't go stale. Does anybody think that it needs major changes? If not, I can make some small refinements and then post to the jupyter blog.

@jzf2101 I believe you said you were planning to work on the post - have you made any progress?

**Comment by minrk** [comment]
@choldgraf please go ahead

**Comment by consideRatio** [comment]
@choldgraf I did a read through, it seems great to me. I like especially how you explain "The problem we wanted to solve" and how that can relate to others' needs.

**Comment by choldgraf** [comment]
hey all - it seems like we dropped this one...shall I close this because too much time has passed since the event? Or do y'all think we could still make a post about this? I'm happy to put in the work to get the post out the door if people think it's still valuable.

**Comment by consideRatio** [comment]
@choldgraf it has some value to me as reference, but ill not the one to put in the additional work with this post so for my sake please do not feel obliged to pick up the ball - it is easy to work too much, best not to!

**Comment by betatim** [comment]
I'd close the issue now. Trying to recall the details that would make a good post would be too much work IMHO.

**Comment by choldgraf** [comment]
alright, kind of a bummer that we've already got all that content there but I agree I don't have the cycles anymore to push this over the finish line. If somebody else would like to pick it up and make it post-ready, I support the idea! Otherwise I'll close this issue for now 😕

**Comment by leportella** [comment]
IMHO if we have information and all the trouble happened, I would post it either way. I can volunteer for reading it and check as a new-comer if there is something missing, if you feel like :)

**Comment by choldgraf** [comment]
yessss @leportella go for it! I'm happy to help you push it over the finish line (see threads above for some context, and the hackmd at the top for the text)
