### ISSUE TITLE
January 2019 Meeting

### ISSUE THREAD

**Issue by Zsailer** [jupyterhub/team-compass#97]
Hello everyone, 

The January meeting will be held on the third Thursday of the month. 

That's **Thursday, January 17th, 2019** at 6pm European time (or your [timezone](http://arewemeetingyet.com/Zurich/2019-01-17/18:00/Jupyterhub%2FBinder%20team)).

* You can find the agenda [here](https://hackmd.io/FOMStPqfRFS5-Bf7pQyWBw).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter).

I look forward to seeing you then!

**Comment by Zsailer** [comment]
Hello again, Zach here. You all know what that means 😃 ...

🎉 Next week is our monthly Jupyterhub/Binder team meeting! 🎉 

I can't wait to see you all there! The details are above. Until then, have a fantastic week.

**Comment by betatim** [comment]
After the last meeting where we had a lot to talk about, a lot of participants and as a result kind of readjusted the agenda on the fly: please submit things you want to talk about **at least 24h before the meeting starts** so we can create a (somewhat) coherent agenda before the meeting starts.

If there are items that are added after the cut off they will be dealt with after all those that did get in there before the cut off and if the meeting time isn't up.

Hopefully this will lead to a better meeting.

**Comment by Zsailer** [comment]
I'll send out a reminder next Wednesday to add you agenda items 24 hours ahead.

**Comment by Zsailer** [comment]
Great meeting everyone! Thank you for showing up. See you next month!
